syntax = "proto3";

package ai.traceable.fraud.datamodel.config.service.v1;

import "ai/traceable/fraud/datamodel/config/service/v1/fraud_datamodel.proto";

option java_multiple_files = true;
option java_package = "ai.traceable.fraud.datamodel.config.service.v1.internal";

enum ObjectKind {
  OBJECT_KIND_UNSPECIFIED = 0;
  OBJECT_KIND_ENTITY = 1;
  OBJECT_KIND_RELATIONSHIP = 2;
  OBJECT_KIND_EVENT = 3;
  OBJECT_KIND_METRIC = 4;
  OBJECT_KIND_BASELINE = 5;
}

message ObjectTypeReference {
  // buf:lint:ignore FIELD_LOWER_SNAKE_CASE
  ObjectKind objectKind = 1;
  string id = 2;
}

// this is primarily used for storing the doc in the store.
message ObjectType {
  oneof object {
    EntityType entity_type = 1;
    RelationshipType relationship_type = 2;
    EventType event_type = 3;
    MetricType metric_type = 4;
    BaselineType baseline_type = 5;
  }
}

message ObjectTypeColumnMappings {
  map<string, InternalFieldMetadata> fields_meta = 1;
  ColumnMappingMeta column_mapping_meta = 2;
}

// a union of EntityFieldMetadata and FieldMetadata from the external api
message InternalFieldMetadata {
  FieldType field_type = 1;
  bool versioned = 2;
  bool disabled = 3;
  oneof pointer {
    string entity_type = 5;
    string relationship_type = 6;
  }
}
