syntax = "proto3";
package ai.traceable.genai.config.service.v1;

import "ai/traceable/genai/config/service/v1/gen_ai_config.proto";

option java_multiple_files = true;

message GetGenAiConfigRequest {
  GenAiScope scope = 1;
}

message UpdateGenAiConfigRequest {
  GenAiScope scope = 1;
  oneof config_update {
    GlobalConfigUpdate global_config_update = 3;
    FeatureLevelConfigUpdate feature_level_config_update = 4;
  }
  GenAiFeatureConfigUpdate update = 2 [deprecated = true];
}

message GlobalConfigUpdate {
  bool enabled = 1;
}

message FeatureLevelConfigUpdate {
  IssuesSummaryFeatureConfig issues_summary_feature_config_update = 1;
  ThreatActivitySummaryFeatureConfig threat_activity_summary_feature_config_update = 2;
  ChatbotFeatureConfig chatbot_feature_config_update = 3;
  AstAuthHookGeneratorAgentFeatureConfig ast_auth_hook_generator_agent_feature_config_update = 4;
}

message GenAiFeatureConfigUpdate {
  IssuesSummaryFeatureConfig issues_summary_feature_config = 1;
  ThreatActivitySummaryFeatureConfig threat_activity_summary_feature_config = 2;
}
