syntax = "proto3";

package ai.traceable.ast.hooks.config.service.v1;

option java_multiple_files = true;

message AstHook {
  string id = 1;
  AstHookDetails hook_details = 2;
  string created_by = 3;
  optional string ast_hook_test_id = 4;
}

message AstHookDetails {
  string name = 1;
  string description = 2;
  oneof ast_hook_type {
    HookConfig hook_config = 7;
    AdvancedMode advanced_mode = 9;
  }
  string code_snippet = 4 [deprecated = true];
  AuthMechanism auth_mechanism = 5 [deprecated = true];
  Role role = 8;
  HookCategory hook_category = 10;
  bool is_draft = 11;
}

enum HookCategory {
  HOOK_CATEGORY_UNSPECIFIED = 0;
  HOOK_CATEGORY_PRE_HOOK = 1;
  HOOK_CATEGORY_POST_HOOK = 2;
  HOOK_CATEGORY_POST_MUTATION_PRE_HOOK = 3;
}

message AdvancedMode {
  string code_snippet = 1;
  AuthMechanism auth_mechanism = 2 [deprecated = true];
  AdvancedModeMechanism advanced_mode_mechanism = 3;
}

message RequestTokenInfo {
  TokenPlacement token_placement = 1;
  string token_key = 2;
  optional string token_value_template = 3;
}

enum TokenPlacement {
  TOKEN_PLACEMENT_UNSPECIFIED = 0;
  TOKEN_PLACEMENT_HEADER = 1;
  TOKEN_PLACEMENT_QUERY = 2;
  TOKEN_PLACEMENT_COOKIE = 3;
}

enum AstHookType {
  AST_HOOK_TYPE_UNSPECIFIED = 0;
  AST_HOOK_TYPE_AUTHENTICATION = 1;
}

enum AuthMechanism {
  AUTH_MECHANISM_UNSPECIFIED = 0;
  AUTH_MECHANISM_BEARER_TOKEN = 1;
  AUTH_MECHANISM_FORM_BASED_ENTRY = 2;
  AUTH_MECHANISM_AUTH_CUSTOM_JSON_PAYLOAD = 3;
  AUTH_MECHANISM_AUTH0_CLIENT_CREDENTIALS = 4;
  AUTH_MECHANISM_AUTH0_RESOURCE_OWNER_PASSWORD = 5;
  AUTH_MECHANISM_OKTA_CLIENT_CREDENTIALS = 6;
  AUTH_MECHANISM_OKTA_RESOURCE_OWNER_PASSWORD = 7;
  AUTH_MECHANISM_KEYCLOAK_CLIENT_CREDENTIALS = 8;
  AUTH_MECHANISM_OAUTH_CLEINT_CREDENTIALS = 9;
  AUTH_MECHANISM_COGNITO_USER_PASSWORD = 10;
  AUTH_MECHANISM_CUSTOM = 11;
}

enum AdvancedModeMechanism {
  ADVANCED_MODE_MECHANISM_UNSPECIFIED = 0;
  ADVANCED_MODE_MECHANISM_API_KEY = 1;
  ADVANCED_MODE_MECHANISM_BASIC_AUTH = 2;
  ADVANCED_MODE_MECHANISM_JWT = 3;
  ADVANCED_MODE_MECHANISM_CONTENT_SIGNATURE = 4;
  ADVANCED_MODE_MECHANISM_HMAC = 5;
  ADVANCED_MODE_MECHANISM_OAUTH = 6;
  ADVANCED_MODE_MECHANISM_POSTMAN = 7;
  ADVANCED_MODE_MECHANISM_BEARER = 8;
  ADVANCED_MODE_MECHANISM_MTLS = 9;
  ADVANCED_MODE_MECHANISM_AWS_SIGNATURE_V4 = 10;
  ADVANCED_MODE_MECHANISM_POP_SIGNATURE = 11;
}

message HookConfig {
  string auth_endpoint = 1 [deprecated = true];
  oneof hook_config {
    PostmanHookConfig postman_hook_config = 2;
    BasicAuthConfig basic_auth_config = 3;
    JwtConfig jwt_config = 4;
    Hmac hmac = 5;
    Oauth2 oauth2 = 6;
    ContentSignature content_signature = 7;
    Bearer bearer = 8;
    MutualTls mutual_tls = 9;
    AwsSignatureV4 aws_signature_v4 = 10;
    PopTokenSignature pop_token_signature = 11;
    ApiKey api_key = 12;
  }
}

message PopTokenSignature {
  EncryptedText pop_private_key = 1;
  repeated string external_headers_to_sign = 2;
  string pop_header_key = 3;
  string pop_header_prefix = 4;
}

message AwsSignatureV4 {
  EncryptedText access_id_key = 1;
  EncryptedText secret_access_key = 2;
  string aws_region = 3;
  string service_name = 4;
}

message MutualTls {
  message MutualTlsAdvanced {
    string cert_authority_cert = 1;
    EncryptedText client_key_passphrase = 2;
    string sni = 3;
    optional string host = 4;
  }

  string client_cert = 1;
  EncryptedText client_key = 2;
  MutualTlsAdvanced advanced_options = 3;
}

message Bearer {
  oneof generation_info {
    EncryptedText bearer_token = 1;
    DynamicBearer dynamic_bearer = 2;
  }
  optional RequestTokenInfo token_info = 3; // applicable for explicit bearer token
}

message DynamicBearer {
  oneof bearer_auth_type {
    BasicAuthConfig basic_auth = 1;
    Oauth2 oauth2 = 2;
  }
}

message ContentSignature {
  string header_key = 1;
  EncryptedText private_key = 2;
}

message BasicAuthConfig {
  string username = 1;
  EncryptedText password = 2;
}

message Hmac {
  HmacHash hmac_hash_algo = 1;
  string signature_header = 2;
  HmacAdvanced hmac_advanced = 3;
  EncryptedText access_key = 4;
  EncryptedText secret_key = 5;
}

message HmacAdvanced {
  string timestamp_header = 1;
  string canonical_request_format = 2;
  int64 allowed_time_skew = 3;
  optional string canonical_mac_header_format = 4;
}

message Oauth2 {
  // TODO: OauthTokenGenInfo : if we need to show the token gen info back in UI.
  EncryptedText token = 1;
  RequestTokenInfo token_info = 2;
  EncryptedText client_id = 3 [deprecated=true];
  string access_token_url = 4;
  string client_id_plain_text = 10;
  oneof flow_type {
    OauthAuthorizationCodeFlow authorization_code_flow = 5;
    OauthPkceFlow pkce_flow = 6;
    OauthImplicitFlow implicit_flow = 7;
    OauthClientCredentialsFlow client_credentials_flow = 8;
    OauthPasswordFlow password_flow = 9;
  }
  string auth_endpoint = 11;
}

message OauthAuthorizationCodeFlow {
  string state = 1;
  OauthClientAuthenticationType client_authentication_type = 2;
  EncryptedText client_secret = 3;
}

message OauthImplicitFlow {
  string state = 1;
}

message OauthPkceFlow {
  string state = 1;
  string code_verifier = 2;
  EncryptedText client_secret = 3;
}

message OauthClientCredentialsFlow {
  EncryptedText client_secret = 1;
}

message OauthPasswordFlow {
  string username = 1;
  string password = 2;
  EncryptedText client_secret = 3;
}

message JwtConfig {
  oneof jwt_info {
    EncryptedText jwt_token = 1;
    DynamicJwt dynamic_jwt = 2;
  }
  RequestTokenInfo token_info = 3;
}

message DynamicJwt {
  EncryptedText secret_key = 1;
  KeyGenAlgo key_gen_algo = 2;
  map<string, string> claims = 3;
  int64 token_expiry_mins = 4;
}

message PostmanHookConfig {
  string collection_url = 1;
}

enum OauthClientAuthenticationType {
  OAUTH_CLIENT_AUTHENTICATION_TYPE_UNSPECIFIED = 0;
  OAUTH_CLIENT_AUTHENTICATION_TYPE_REQUEST_BODY = 1;
  OAUTH_CLIENT_AUTHENTICATION_TYPE_BASIC_AUTH_HEADER = 2;
}

enum HookMode {
  HOOK_MODE_UNSPECIFIED = 0;
  HOOK_MODE_NORMAL = 1;
  HOOK_MODE_ADVANCED = 2;
}

enum Role {
  ROLE_UNSPECIFIED = 0;
  ROLE_STANDARD = 1;
  ROLE_ADMIN = 2;
  ROLE_READER = 3;
  ROLE_WRITER = 4;
}

enum KeyGenAlgo {
  KEY_GEN_ALGO_UNSPECIFIED = 0;
  KEY_GEN_ALGO_SHA256 = 1;
  KEY_GEN_ALGO_SHA1 = 2;
}

enum HmacHash {
  HMAC_HASH_UNSPECIFIED = 0;
  HMAC_HASH_HMAC_SHA1 = 1;
  HMAC_HASH_HMAC_SHA256 = 2;
  HMAC_HASH_HMAC_SHA512 = 3;
}

message EncryptedText {
  string key_id = 1;
  string value = 2;
  string symmetric_key = 3;
}

message ApiKey {
  EncryptedText api_key_value = 1;
  RequestTokenInfo token_info = 2;
}
