syntax = "proto3";

package ai.traceable.ast.hooks.config.service.v1;

option java_multiple_files = true;

message AstHook {
  string id = 1;
  AstHookDetails hook_details = 2;
}

message AstHookDetails {
  string name = 1;
  string description = 2;
  AstHookType hook_type = 3;
  string code_snippet = 4;
  AuthMechanism auth_mechanism = 5;
}

enum AstHookType {
  AST_HOOK_TYPE_UNSPECIFIED = 0;
  AST_HOOK_TYPE_AUTHENTICATION = 1;
}

enum AuthMechanism {
  AUTH_MECHANISM_UNSPECIFIED = 0;
  AUTH_MECHANISM_BEARER_TOKEN = 1;
  AUTH_MECHANISM_FORM_BASED_ENTRY = 2;
  AUTH_MECHANISM_AUTH_CUSTOM_JSON_PAYLOAD = 3;
  AUTH_MECHANISM_AUTH0_CLIENT_CREDENTIALS = 4;
  AUTH_MECHANISM_AUTH0_RESOURCE_OWNER_PASSWORD = 5;
  AUTH_MECHANISM_OKTA_CLIENT_CREDENTIALS = 6;
  AUTH_MECHANISM_OKTA_RESOURCE_OWNER_PASSWORD = 7;
  AUTH_MECHANISM_KEYCLOAK_CLIENT_CREDENTIALS = 8;
  AUTH_MECHANISM_OAUTH_CLEINT_CREDENTIALS = 9;
  AUTH_MECHANISM_COGNITO_USER_PASSWORD = 10;
}
