syntax = "proto3";

package ai.traceable.ast.hooks.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/ast/hooks/config/service/v1/ast_hook.proto";
import "ai/traceable/ast/hooks/config/service/v1/ast_hook_test.proto";

service AstHooksConfigService {
  rpc CreateAstHook(CreateAstHookRequest) returns (CreateAstHookResponse);
  rpc UpdateAstHook(UpdateAstHookRequest) returns (UpdateAstHookResponse);
  rpc DeleteAstHook(DeleteAstHookRequest) returns (DeleteAstHookResponse);
  rpc GetAllAstHooks(GetAllAstHooksRequest) returns (GetAllAstHooksResponse);
  rpc GetAstHook(GetAstHookRequest) returns (GetAstHookResponse);
  rpc CreateAstHookTest(CreateAstHookTestRequest) returns (CreateAstHookTestResponse);
  rpc UpdateAstHookTest(UpdateAstHookTestRequest) returns (UpdateAstHookTestResponse);
  rpc DeleteAstHookTests(DeleteAstHookTestsRequest) returns (DeleteAstHookTestsResponse);
  rpc GetAstHookTestResult(GetAstHookTestResultRequest) returns (GetAstHookTestResultResponse);
  rpc GetAstHookTests(GetAstHookTestsRequest) returns (GetAstHookTestsResponse);
}

message UpdateAstHookRequest {
  string id = 1;
  optional string name = 2 [deprecated = true];
  optional string description = 3 [deprecated = true];
  optional AstHookType hook_type = 4 [deprecated = true];
  optional string code_snippet = 5 [deprecated = true];
  AstHookDetails ast_hook_details = 6;
}

message UpdateAstHookResponse {
  AstHook ast_hook = 1;
}

message CreateAstHookRequest {
  AstHookDetails hook_details = 1;
}

message CreateAstHookResponse {
  AstHook ast_hook = 1;
}

message DeleteAstHookRequest {
  string id = 1;
}

message DeleteAstHookResponse {

}

message GetAllAstHooksRequest {

}

message GetAllAstHooksResponse {
  repeated AstHook ast_hooks = 1;
}

message GetAstHookRequest {
  string id = 1;
}

message GetAstHookResponse {
  AstHook ast_hook = 1;
}

message CreateAstHookTestRequest {
  AstHookTestDetails hook_test_details = 1;
  AllowedRunners allowed_runners = 2;
}

message CreateAstHookTestResponse {
  AstHookTest ast_hook_test = 1;
}

message GetAstHookTestResultRequest {
  string id = 1;
}

message GetAstHookTestResultResponse {
  AstHookTestResult hook_test_result = 1;
}

message GetAstHookTestsRequest {
  repeated AstHookTestFilter ast_hook_test_filters = 1;
}

message GetAstHookTestsResponse {
  repeated AstHookTest ast_hook_tests = 1;
}

message DeleteAstHookTestsRequest {
  repeated string ids = 1;
}

message DeleteAstHookTestsResponse {}

message UpdateAstHookTestRequest {
  string id = 1;
  optional TestStatus test_status = 2;
  optional string logs = 3;
}

message UpdateAstHookTestResponse {
  AstHookTest ast_hook_test = 1;
}
