syntax = "proto3";

package ai.traceable.ast.hooks.config.service.v1;

import "ai/traceable/ast/hooks/config/service/v1/ast_hook.proto";

option java_multiple_files = true;

message AstHookTest {
  string id = 1;
  AstHookTestDetails ast_hook_test_details = 2;
  TestStatus test_status = 3;
  AllowedRunners allowed_runners = 4;
  repeated string logs = 5;
}

message AstHookTestDetails {
  oneof ast_hook_type {
    HookConfig hook_config = 1;
    AdvancedMode advanced_mode = 2;
  }
  Role role = 3;
  HookScope scope = 4;
}

message AstHookTestResult {
  string id = 1;
  TestStatus test_status = 2;
  repeated string logs = 3;
}

message AllowedRunners {
  oneof allowed_runners {
    AllowedRunnersInfo runners_info = 1;
    bool any_runner = 2;
  }
}

message AllowedRunnersInfo {
  repeated RunnerInfo runners_info = 1;
}

message RunnerInfo {
  string id = 1;
  repeated string labels = 2;
}

message AstHookTestFilter {
  oneof filter {
    TestStatusFilter test_status_filter = 1;
    TestIdFilter test_id_filter = 2;
  }
}

message TestIdFilter {
  repeated string ids = 1;
}

message TestStatusFilter {
  repeated TestStatus statuses = 1;
}
