syntax = "proto3";
package ai.traceable.github.integration.config.service.v1;

option java_multiple_files = true;

service GithubIntegrationConfigService {
  rpc GetGithubIntegrations(GetGithubIntegrationsRequest) returns (GetGithubIntegrationsResponse) {}
  rpc CreateGithubIntegration(CreateGithubIntegrationRequest) returns (CreateGithubIntegrationResponse) {}
  rpc UpdateGithubIntegration(UpdateGithubIntegrationRequest) returns (UpdateGithubIntegrationResponse) {}
  rpc DeleteGithubIntegration(DeleteGithubIntegrationRequest) returns (DeleteGithubIntegrationResponse) {}
}

message GetGithubIntegrationsRequest {
  GithubIntegrationFilter filter = 1;
}

message GithubIntegrationFilter {
  optional string github_installation_target_name = 1;
  optional string config_id = 2;
  optional string request_user_email = 3;
  optional int64 installation_id = 4;
  optional string internal_app_id = 5;
}

message GetGithubIntegrationsResponse {
  repeated GithubIntegration integrations = 1;
}

message CreateGithubIntegrationRequest {
  optional string internal_app_id = 1;
}

message CreateGithubIntegrationResponse {
  GithubIntegration created_integration = 1;
}

message UpdateGithubIntegrationRequest {
  string id = 1;
  IntegrationStatus status = 2;
}

message UpdateGithubIntegrationResponse {
  GithubIntegration updated_integration = 1;
}

message DeleteGithubIntegrationRequest {
  string id = 1;
}

message DeleteGithubIntegrationResponse {}

message IntegrationStatus {
  oneof status {
    AwaitingRequest awaiting_request = 1;
    AwaitingApproval awaiting_approval = 2;
    Completed completed = 3;
    Suspended suspended = 4;
  }
  message AwaitingRequest {
    string request_user_email = 1;
  }
  message AwaitingApproval {
    string github_installation_target_name = 1;
  }
  message Completed {
    int64 installation_id = 1;
    string github_installation_target_name = 2;
    string github_installation_url = 3;
  }

  message Suspended {
    int64 installation_id = 1;
    string github_installation_target_name = 2;
    string github_installation_url = 3;
  }
}

message GithubIntegration {
  string id = 1;
  IntegrationStatus status = 2;
  optional string internal_app_id = 3;
}
