plugins {
  `java-library`
}

dependencies {
  api(commonLibs.hypertrace.framework.grpc)

  implementation(localLibs.hypertrace.configservice.factory)
  implementation(localLibs.hypertrace.configservice.impl)
  implementation(localLibs.hypertrace.configservice.changeeventgenerator)
  implementation(commonLibs.typesafe.config)
  implementation(localLibs.hypertrace.configservice.partitioner.config.impl)

  implementation(projects.activityEventProducer)
  implementation(projects.sensitiveDataConfigServiceImpl)
  implementation(projects.localProcessingConfigServiceImpl)
  implementation(projects.blockingConfigServiceImpl)
  implementation(projects.externalUserAttributionConfigServiceImpl)
  implementation(projects.externalAgentAttributeConfigServiceImpl)
  implementation(projects.externalDataClassificationConfigServiceImpl)

  implementation(projects.licenseStatusConfigServiceImpl)
  implementation(projects.localProcessingConfigServiceImpl)
  implementation(projects.regionConfigServiceImpl)
  implementation(projects.iprangeConfigServiceImpl)
  implementation(projects.customSignatureConfigServiceImpl)
  implementation(projects.userAttributionConfigServiceImpl)
  implementation(projects.sessionIdentificationConfigServiceImpl)
  implementation(projects.threatManagementConfigServiceImpl)
  implementation(projects.riskConfigServiceImpl)
  implementation(projects.riskConfigServiceV2Impl)
  implementation(projects.dataClassificationConfigServiceImpl)
  implementation(projects.dataExfiltrationConfigServiceImpl)
  implementation(projects.wafProviderIntegrationServiceImpl)
  implementation(projects.rateLimitingConfigServiceImpl)
  implementation(projects.traceableSpanProcessingConfigServiceImpl)
  implementation(projects.anomalyConfigServiceImpl)
  implementation(projects.apiAttributeOverrideServiceImpl)
  implementation(projects.traceableAlertingConfigServiceImpl)
  implementation(projects.reportingConfigServiceImpl)
  implementation(projects.apiSpecConfigServiceImpl)
  implementation(projects.maliciousSourcesConfigServiceImpl)
  implementation(projects.dataProtectionConfigServiceImpl)
  implementation(projects.authDetectionConfigServiceImpl)
  implementation(projects.jwtExtractionConfigServiceImpl)
  implementation(projects.astScanProfileConfigServiceImpl)
  implementation(projects.integrationConfigServiceImpl)
  implementation(projects.detectionExclusionConfigServiceImpl)
  implementation(projects.astConfigServiceImpl)
  implementation(projects.apiGatewayConfigServiceImpl)
  implementation(projects.splunkIntegrationConfigServiceImpl)
  implementation(projects.syslogIntegrationConfigServiceImpl)
  implementation(projects.astHooksConfigServiceImpl)
  implementation(projects.savedFilterConfigServiceImpl)
  implementation(projects.anomalyScoringConfigServiceImpl)
  implementation(projects.savedQueryConfigServiceImpl)
  implementation(projects.dashboardConfigServiceImpl)
  implementation(projects.jiraIntegrationConfigServiceImpl)
  implementation(projects.runnerLogsConfigServiceImpl)
  implementation(projects.fraudDatamodelDerivationConfigServiceImpl)
  implementation(projects.fraudDatamodelConfigServiceImpl)
  implementation(projects.fraudPolicyConfigServiceImpl)

  annotationProcessor(commonLibs.lombok)
  compileOnly(commonLibs.lombok)
}
