syntax = "proto3";


package ai.traceable.detection.inclusion.rules.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/detection/inclusion/rules/config/service/v1/detection_inclusion_rules_config.proto";

service DetectionInclusionRulesConfigService {

  rpc GetDetectionInclusionRules (GetDetectionInclusionRulesRequest) returns (GetDetectionInclusionRulesResponse) {
  }

  rpc CreateDetectionInclusionRule (CreateDetectionInclusionRuleRequest) returns (CreateDetectionInclusionRuleResponse) {
  }

  rpc UpdateDetectionInclusionRule (UpdateDetectionInclusionRuleRequest) returns (UpdateDetectionInclusionRuleResponse) {
  }

  rpc DeleteDetectionInclusionRule (DeleteDetectionInclusionRuleRequest) returns (DeleteDetectionInclusionRuleResponse) {
  }
}
