syntax = "proto3";

package ai.traceable.detection.inclusion.rules.config.service.v1;
import "ai/traceable/detection/inclusion/rules/config/service/v1/dataset/data_exfiltration_inclusion_rule.proto";

option java_multiple_files = true;

message GetDetectionInclusionRulesRequest {
   GetDetectionInclusionRuleFilter filter = 1;
}

message GetDetectionInclusionRulesResponse {
  repeated DetectionInclusionRuleConfig configs = 1;
}

message CreateDetectionInclusionRuleRequest {
  DetectionInclusionRuleData rule_data = 1;
}

message CreateDetectionInclusionRuleResponse {
  DetectionInclusionRuleConfig config = 1;
}

message UpdateDetectionInclusionRuleRequest {
  DetectionInclusionRuleConfig rule_config = 1;
}

message UpdateDetectionInclusionRuleResponse {
  DetectionInclusionRuleConfig config = 1;
}

message DeleteDetectionInclusionRuleRequest {
  string rule_id = 1;
}


message DeleteDetectionInclusionRuleResponse {

}

message GetDetectionInclusionRuleFilter {
  repeated DetectionInclusionRuleType rule_types = 1;
}

message DetectionInclusionRuleConfig {
  string id = 1;
  DetectionInclusionRuleData rule_data = 2;
  InclusionConfigStatus config_status = 3;

}
message DetectionInclusionRuleData {
  string name = 1;
  repeated EnvironmentScope environment_scopes = 2;
  repeated string label_ids = 3; // TODO
  oneof inclusion_rule_type {
    ai.traceable.detection.inclusion.rules.config.service.v1.dataset.DataExfiltrationInclusionRule data_exfiltration_rule = 4;
  }
}

message InclusionConfigStatus {
  bool disabled = 1;
}

message EnvironmentScope {
  bool enabled = 1; // true means all services
  repeated ServiceScope service_scopes = 2;
  string id = 3;
}

message ServiceScope {
  bool enabled = 1; // true means all apis
  repeated ApiScope api_scopes = 2;
  string id = 3;
}

message ApiScope {
  string id = 1;
}

enum DetectionInclusionRuleType {
  DETECTION_INCLUSION_RULE_TYPE_UNSPECIFIED = 0;
  DETECTION_INCLUSION_RULE_TYPE_DATA_EXFILTRATION = 1;
}
