syntax = "proto3";

package ai.traceable.userattribution.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/userattribution/config/service/v1/user_attribution_rule.proto";

service UserAttributionConfigService {
  rpc GetUserAttributionRules (GetUserAttributionRulesRequest) returns (GetUserAttributionRulesResponse) {
  }

  rpc CreateUserAttributionRule (CreateUserAttributionRuleRequest) returns (CreateUserAttributionRuleResponse) {
  }

  rpc UpdateUserAttributionRule (UpdateUserAttributionRuleRequest) returns (UpdateUserAttributionRuleResponse) {
  }

  rpc DeleteUserAttributionRule (DeleteUserAttributionRuleRequest) returns (DeleteUserAttributionRuleResponse) {
  }

  rpc RankUserAttributionRule (RankUserAttributionRuleRequest) returns (RankUserAttributionRuleResponse) {
  }
}

message GetUserAttributionRulesRequest {
}

message GetUserAttributionRulesResponse {
  repeated UserAttributionRule rules = 1;
}

message CreateUserAttributionRuleRequest {
  string name = 1;
  UserAttributionRuleData data = 2;
}

message CreateUserAttributionRuleResponse {
  // rule deprecated as a new rule may change the ranks of existing rules
  UserAttributionRule rule = 1 [deprecated = true];
  repeated UserAttributionRule rules = 2;
}

message UpdateUserAttributionRuleRequest {
  UserAttributionRule rule = 1;
}

message UpdateUserAttributionRuleResponse {
  UserAttributionRule rule = 1;
}

message DeleteUserAttributionRuleRequest {
  string rule_id = 1;
}

message DeleteUserAttributionRuleResponse {
  repeated UserAttributionRule rules = 2;
}

message RankUserAttributionRuleRequest {
  string id_to_update = 1;
  // The id of the rule that should immediately precede the target id. Omit if we're updating to highest rank.
  optional string preceding_rule_id = 2;
}

message RankUserAttributionRuleResponse {
  repeated UserAttributionRule rules = 1;
}
