syntax = "proto3";

package ai.traceable.customsignature.config.service.v1;

option java_multiple_files = true;

message CreateCustomSignatureRuleRequest {
  string name = 1;
  string description = 2;
  RuleDefinition definition = 3;
  RuleEffect effect = 4;
  ExpiryDetails blocking_expiry_details = 5;
  RuleScope rule_scope = 6;
}

message CreateCustomSignatureRuleResponse {
  CustomSignatureRule rule = 1;
}

message UpdateCustomSignatureRuleRequest {
  CustomSignatureRule rule = 1;
}

message UpdateCustomSignatureRuleResponse {
  CustomSignatureRule rule = 1;
}

message DeleteCustomSignatureRuleRequest {
  string id = 1;
}

message DeleteCustomSignatureRuleResponse {
}

message GetCustomSignatureRulesRequest {
  GetRulesFilter filter = 1;
}

message GetCustomSignatureRulesResponse {
  repeated CustomSignatureRule rules = 1;
}

message GetCustomSignatureModsecRulesRequest {
  GetRulesFilter filter = 1;
}

message GetCustomSignatureModsecRulesResponse {
  string modsec_rules_blob = 1;
  repeated CustomSignatureRuleDetails rules = 2;
}

message GetRulesFilter {
  repeated string rule_ids = 1;
  repeated EventType event_types = 2;
  optional bool disabled = 3;
  optional bool internal = 4;
  RuleScope rule_scope = 5;
}

message CustomSignatureRule {
  string id = 1;
  string name = 2;
  string description = 3;
  RuleDefinition definition = 4;
  RuleEffect effect = 5;
  bool disabled = 6;
  bool internal = 7;
  ExpiryDetails blocking_expiry_details = 8;
  RuleScope rule_scope = 9;
}

message CustomSignatureRuleDetails {
  string id = 1;
  string name = 2;
  RuleEffect effect = 3;
  bool disabled = 6;
  bool internal = 7;
  ExpiryDetails blocking_expiry_details = 8;
  RuleScope rule_scope = 9;
}

message RuleScope {
  oneof scope { // if no option selected, default is customer scope (all environments)
    EnvironmentScope environment_scope = 1;
  }
}

message EnvironmentScope {
  repeated string environment_ids = 1;
}

message RuleDefinition {
  ClauseGroup clause_group = 1;
  CustomSignatureScopeConfig scope_config = 2;
}

message RuleEffect {
  EventType event_type = 1;
  EventSeverity event_severity = 2;
}

message CustomSignatureScopeConfig {
   repeated CustomSignatureScope scopes = 1;
}

message CustomSignatureScope {
  oneof scope {
    CustomSignatureEntityScope api_scope = 1;
    CustomSignatureEntityScope service_scope = 2;
  }
}

message CustomSignatureEntityScope {
  oneof ids {
    StringList entity_ids = 1;
    StringList label_ids = 2;
  }
}

message StringList {
  repeated string values = 1;
}

message ClauseGroup {
  ClauseOperator clause_operator = 1;
  repeated Clause clauses = 2;
}

message Clause {
  oneof clause {
    MatchExpression match_expression = 1;
    KeyValueExpression key_value_expression = 2;
  }
}

message MatchExpression {
  MatchKey match_key = 1;
  MatchOperator match_operator = 2;
  string match_value = 3;
  MatchCategory match_category  = 4;
}


message KeyValueExpression {
  KeyValueTag tag = 1;
  MatchOperator key_match_operator = 2;
  string match_key = 3;
  MatchOperator value_match_operator = 4;
  string match_value = 5;
  MatchCategory match_category  = 6;
}

message ExpiryDetails {
  // Expiry duration represented in ISO 8601 duration format.
  // If expiry_duration is not set and expiry_timestamp_millis is set, the value gets derived from the expiry_timestamp_millis field
  optional string expiry_duration = 1;
  // Timestamp at which the blocking expires.
  // If expiry_timestamp_millis is not set and expiry_duration is set, the value gets derived from the expiry_duration field
  optional int64 expiry_timestamp_millis = 2;
}

enum EventSeverity {
  EVENT_SEVERITY_UNSPECIFIED = 0;
  EVENT_SEVERITY_LOW = 1;
  EVENT_SEVERITY_MEDIUM = 2;
  EVENT_SEVERITY_HIGH = 3;
  EVENT_SEVERITY_CRITICAL = 4;
}

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;
  EVENT_TYPE_TESTING_DETECTION = 1;
  EVENT_TYPE_NORMAL_DETECTION = 2;
  EVENT_TYPE_DETECTION_AND_BLOCKING = 3;
  EVENT_TYPE_ALLOW = 4;
}

enum ClauseOperator {
  CLAUSE_OPERATOR_UNSPECIFIED = 0;
  CLAUSE_OPERATOR_AND = 1;
  CLAUSE_OPERATOR_OR = 2;
}

enum MatchKey {
  MATCH_KEY_UNSPECIFIED = 0;
  MATCH_KEY_URL = 1;
  MATCH_KEY_HOST = 2;
  MATCH_KEY_HTTP_METHOD = 3;
  MATCH_KEY_USER_AGENT = 4;
  MATCH_KEY_HEADER_NAME = 5;
  MATCH_KEY_HEADER_VALUE = 6;
  MATCH_KEY_PARAMETER_NAME = 7;
  MATCH_KEY_PARAMETER_VALUE = 8;
  MATCH_KEY_STATUS_CODE = 9;
  MATCH_KEY_BODY = 10;
}

enum MatchOperator {
  MATCH_OPERATOR_UNSPECIFIED = 0;
  MATCH_OPERATOR_EQUALS = 1;
  MATCH_OPERATOR_NOT_EQUAL = 2;
  MATCH_OPERATOR_MATCHES_REGEX = 3;
  MATCH_OPERATOR_NOT_MATCH_REGEX = 4;
  MATCH_OPERATOR_GREATER_THAN = 5;
  MATCH_OPERATOR_LESS_THAN = 6;
  MATCH_OPERATOR_CONTAINS = 7;
  MATCH_OPERATOR_NOT_CONTAIN = 8;
}

enum KeyValueTag {
  KEY_VALUE_TAG_UNSPECIFIED = 0;
  KEY_VALUE_TAG_HEADER = 1;
  KEY_VALUE_TAG_PARAMETER = 2;
}

enum MatchCategory {
  MATCH_CATEGORY_UNSPECIFIED = 0;
  MATCH_CATEGORY_REQUEST = 1;
  MATCH_CATEGORY_RESPONSE = 2;
}
