syntax = "proto3";

package ai.traceable.customsignature.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/customsignature/config/service/v1/custom_signature_config.proto";


service CustomSignatureConfigService {

  rpc GetCustomSignatureRules (GetCustomSignatureRulesRequest) returns (GetCustomSignatureRulesResponse) {
  }

  rpc CreateCustomSignatureRule (CreateCustomSignatureRuleRequest) returns (CreateCustomSignatureRuleResponse) {
  }

  rpc UpdateCustomSignatureRule (UpdateCustomSignatureRuleRequest) returns (UpdateCustomSignatureRuleResponse) {
  }

  rpc DeleteCustomSignatureRule (DeleteCustomSignatureRuleRequest) returns (DeleteCustomSignatureRuleResponse) {
  }

  rpc GetEnabledCustomSignatureModsecRules (GetEnabledCustomSignatureModsecRulesRequest) returns (GetEnabledCustomSignatureModsecRulesResponse) {
  }
}
