syntax = "proto3";

package ai.traceable.customsignature.config.service.v1;

import "ai/traceable/edge/decision/config/service/v1/edge_decision_config.proto";

option java_multiple_files = true;

message CreateCustomSignatureRuleRequest {
  string name = 1;
  string description = 2;
  RuleDefinition definition = 3;
  RuleEffect effect = 4;
  ExpiryDetails blocking_expiry_details = 5;
  RuleScope rule_scope = 6;
  bool internal = 7;
  RuleSource rule_source = 8;
  bool hidden = 9;
}

message CreateCustomSignatureRuleResponse {
  CustomSignatureRule rule = 1;
}

message UpdateCustomSignatureRuleRequest {
  CustomSignatureRule rule = 1;
}

message UpdateCustomSignatureRuleResponse {
  CustomSignatureRule rule = 1;
}

message DeleteCustomSignatureRuleRequest {
  string id = 1;
}

message DeleteCustomSignatureRuleResponse {}

message GetCustomSignatureRulesRequest {
  GetRulesFilter filter = 1;
}

message GetCustomSignatureRulesResponse {
  repeated CustomSignatureRule rules = 1;
}

message GetCustomSignatureModsecRulesRequest {
  GetRulesFilter filter = 1;
  CustomModsecRuleVersion rule_version = 2;
}

message GetCustomSignatureModsecRulesResponse {
  string modsec_rules_blob = 1;
  repeated CustomSignatureRuleDetails rules = 2 [deprecated = true];
  repeated CustomSignatureInlineRule inline_rules = 3;
}

message GetCustomSignatureEdgeDecisionRulesRequest {
  GetRulesFilter rules_filter = 1;
}

message GetCustomSignatureEdgeDecisionRulesResponse {
  ai.traceable.edge.decision.config.service.v1.EdgeDecisionEngineConfig edge_decision_engine_config = 1;
}

message GetRulesFilter {
  repeated string rule_ids = 1;
  repeated EventType event_types = 2;
  optional bool disabled = 3;
  optional bool internal = 4;
  RuleScope rule_scope = 5;
  optional bool contains_sec_rule_clause = 6;
  repeated RuleSource rule_sources = 7;
  // rules having all these label keys will pass the filter
  repeated string label_keys = 8;
  optional bool filter_edge_decision_rules = 9;
}

message CustomSignatureRule {
  string id = 1;
  string name = 2;
  string description = 3;
  RuleDefinition definition = 4;
  RuleEffect effect = 5;
  bool disabled = 6;
  bool internal = 7;
  ExpiryDetails blocking_expiry_details = 8;
  RuleScope rule_scope = 9;
  RuleSource rule_source = 10;
  bool hidden = 11;
}

message CustomSignatureRuleDetails {
  // entire message is deprecated
  option deprecated = true;

  string id = 1;
  string name = 2;
  RuleEffect effect = 3;
  bool disabled = 6;
  bool internal = 7;
  ExpiryDetails blocking_expiry_details = 8;
  RuleScope rule_scope = 9;
  map<string, string> labels = 10;
}

message CustomSignatureInlineRule {
  CustomSignatureRule rule = 1;
}

message RuleScope {
  oneof scope { // if no option selected, default is customer scope (all environments)
    EnvironmentScope environment_scope = 1;
  }
}

message EnvironmentScope {
  repeated string environment_ids = 1;
}

message RuleDefinition {
  ClauseGroup clause_group = 1;
  CustomSignatureScopeConfig scope_config = 2;
  map<string, string> labels = 3;
}

message RuleEffect {
  EventType event_type = 1;
  EventSeverity event_severity = 2;
  repeated RuleEffectWithModifications effects = 3;
  repeated RuleEvaluationPoint rule_evaluation_points = 4;
}

message RuleEffectWithModifications {
  oneof effect {
    AgentRuleEffect agent_rule_effect = 1;
  }
}

enum RuleEvaluationPoint {
  RULE_EVALUATION_POINT_UNSPECIFIED = 0;
  RULE_EVALUATION_POINT_INLINE_TRACING_AGENT = 1;
  RULE_EVALUATION_POINT_EDGE = 2;
  RULE_EVALUATION_POINT_PLATFORM = 3;
}

message AgentRuleEffect {
  repeated AgentModification agent_modifications = 1;
}

message AgentModification {
  oneof modification {
    HeaderInjection header_injection = 1;
    StatusCodeModification status_code_modification = 2;
    BodyModification body_modification = 3;
  }
}

message HeaderInjection {
  MatchCategory header_category = 1;
  string header_name = 2;
  FieldValue value = 3;
}

message StatusCodeModification {
  int32 status_code = 1;
}

message BodyModification {
  MatchCategory location_category = 1;
  FieldValue body_value = 2;
}

message FieldValue {
  oneof value {
    string static_value = 1;
  }
}

message CustomSignatureScopeConfig {
  repeated CustomSignatureScope scopes = 1;
}

message CustomSignatureScope {
  oneof scope {
    CustomSignatureEntityScope api_scope = 1;
    CustomSignatureEntityScope service_scope = 2;
  }
}

message CustomSignatureEntityScope {
  oneof ids {
    StringList entity_ids = 1;
    StringList label_ids = 2;
  }
}

message StringList {
  repeated string values = 1;
}

message ClauseGroup {
  ClauseOperator clause_operator = 1;
  repeated Clause clauses = 2;
}

message Clause {
  oneof clause {
    MatchExpression match_expression = 1;
    KeyValueExpression key_value_expression = 2;
    AttributeKeyValueExpression attribute_key_value_expression = 3;
    CustomSecRule custom_sec_rule = 4;
    IpAddressExpression ip_address_expression = 5;
    IpTypeExpression ip_type_expression = 6;
    IpReputationExpression ip_reputation_expression = 7;
    IpConnectionTypeExpression ip_connection_type_expression = 8;
    IpOrganisationExpression ip_organisation_expression = 9;
    IpAsnExpression ip_asn_expression = 10;
    IpAbuseVelocityExpression ip_abuse_velocity_expression = 11;
    RegionExpression region_expression = 12;
    UserIdExpression user_id_expression = 13;
    EmailDomainExpression email_domain_expression = 14;
    UserAgentExpression user_agent_expression = 15;
    RequestScannerTypeExpression request_scanner_type_expression = 16;
    ClauseGroup clause_group = 17;
  }
}

message CustomSecRule {
  string input_sec_rule = 1;
  string sanitised_sec_rule = 2;
}

message MatchExpression {
  MatchKey match_key = 1;
  MatchOperator match_operator = 2;
  string match_value = 3;
  MatchCategory match_category = 4;
}

message KeyValueExpression {
  KeyValueTag tag = 1;
  MatchOperator key_match_operator = 2;
  string match_key = 3;
  MatchOperator value_match_operator = 4;
  string match_value = 5;
  MatchCategory match_category = 6;
}

message AttributeKeyValueExpression {
  MatchOperator key_match_operator = 1 [deprecated = true];
  string match_key = 2 [deprecated = true];
  MatchOperator value_match_operator = 3 [deprecated = true];
  string match_value = 4 [deprecated = true];
  StringCondition key_condition = 5;
  StringCondition value_condition = 6;
}

message IpAddressExpression {
  repeated string cidr_ip_ranges = 1;
  repeated string ip_addresses = 2;
  repeated string raw_input_ip_data = 3;
  IpAddressExpressionType ip_address_expression_type = 4;
  bool exclude = 5;
}

message IpTypeExpression {
  repeated IpType ip_types = 1;
  bool exclude = 2;
}

message IpReputationExpression {
  IpReputationSeverity min_ip_reputation_severity = 1;
}

message IpConnectionTypeExpression {
  repeated IpConnectionType ip_connection_types = 1;
  bool exclude = 2;
}

message IpOrganisationExpression {
  repeated string ip_organisation_regexes = 1;
  bool exclude = 2;
}

message IpAsnExpression {
  repeated string ip_asn_regexes = 1;
  bool exclude = 2;
}

message IpAbuseVelocityExpression {
  IpAbuseVelocity min_ip_abuse_velocity = 1;
}

message UserIdExpression {
  repeated string user_id_regexes = 1;
  repeated string user_ids = 2;
  bool exclude = 3;
}

message EmailDomainExpression {
  repeated string email_domains = 1;
  repeated string email_regexes = 2;
  bool exclude = 3;
}

message RegionExpression {
  repeated Region region_identifiers = 1;
  bool exclude = 2;

  message Region {
    oneof region {
      string country_iso_code = 1;
    }
  }
}

message UserAgentExpression {
  repeated string user_agents = 1;
  repeated string user_agent_regexes = 2;
  bool exclude = 3;
}

message RequestScannerTypeExpression {
  repeated string scanner_types = 1;
  bool exclude = 2;
}

message StringCondition {
  MatchOperator operator = 1;
  string value = 2;
}

message ExpiryDetails {
  // Expiry duration represented in ISO 8601 duration format.
  // If expiry_duration is not set and expiry_timestamp_millis is set, the value gets derived from the expiry_timestamp_millis field
  optional string expiry_duration = 1;
  // Timestamp at which the blocking expires.
  // If expiry_timestamp_millis is not set and expiry_duration is set, the value gets derived from the expiry_duration field
  optional int64 expiry_timestamp_millis = 2;
}

enum EventSeverity {
  EVENT_SEVERITY_UNSPECIFIED = 0;
  EVENT_SEVERITY_LOW = 1;
  EVENT_SEVERITY_MEDIUM = 2;
  EVENT_SEVERITY_HIGH = 3;
  EVENT_SEVERITY_CRITICAL = 4;
}

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;
  EVENT_TYPE_TESTING_DETECTION = 1;
  EVENT_TYPE_NORMAL_DETECTION = 2;
  EVENT_TYPE_DETECTION_AND_BLOCKING = 3;
  EVENT_TYPE_ALLOW = 4;
}

enum ClauseOperator {
  CLAUSE_OPERATOR_UNSPECIFIED = 0;
  CLAUSE_OPERATOR_AND = 1;
  CLAUSE_OPERATOR_OR = 2;
}

enum MatchKey {
  MATCH_KEY_UNSPECIFIED = 0;
  MATCH_KEY_URL = 1;
  MATCH_KEY_HOST = 2;
  MATCH_KEY_HTTP_METHOD = 3;
  MATCH_KEY_USER_AGENT = 4;
  MATCH_KEY_HEADER_NAME = 5;
  MATCH_KEY_HEADER_VALUE = 6;
  MATCH_KEY_PARAMETER_NAME = 7;
  MATCH_KEY_PARAMETER_VALUE = 8;
  MATCH_KEY_STATUS_CODE = 9;
  MATCH_KEY_BODY = 10;
  MATCH_KEY_QUERY_PARAMETER_NAME = 11;
  MATCH_KEY_QUERY_PARAMETER_VALUE = 12;
  MATCH_KEY_BODY_PARAMETER_NAME = 13;
  MATCH_KEY_BODY_PARAMETER_VALUE = 14;
  MATCH_KEY_COOKIE_NAME = 15;
  MATCH_KEY_COOKIE_VALUE = 16;
  MATCH_KEY_BODY_SIZE = 17;
  MATCH_KEY_QUERY_PARAMS_COUNT = 18;
  MATCH_KEY_HEADERS_COUNT = 19;
  MATCH_KEY_COOKIES_COUNT = 20;
}

enum MatchOperator {
  MATCH_OPERATOR_UNSPECIFIED = 0;
  MATCH_OPERATOR_EQUALS = 1;
  MATCH_OPERATOR_NOT_EQUAL = 2;
  MATCH_OPERATOR_MATCHES_REGEX = 3;
  MATCH_OPERATOR_NOT_MATCH_REGEX = 4;
  MATCH_OPERATOR_GREATER_THAN = 5;
  MATCH_OPERATOR_LESS_THAN = 6;
  MATCH_OPERATOR_CONTAINS = 7;
  MATCH_OPERATOR_NOT_CONTAIN = 8;
}

enum KeyValueTag {
  KEY_VALUE_TAG_UNSPECIFIED = 0;
  KEY_VALUE_TAG_HEADER = 1;
  KEY_VALUE_TAG_PARAMETER = 2;
  KEY_VALUE_TAG_QUERY_PARAMETER = 3;
  KEY_VALUE_TAG_BODY_PARAMETER = 4;
  KEY_VALUE_TAG_COOKIE = 5;
}

enum MatchCategory {
  MATCH_CATEGORY_UNSPECIFIED = 0;
  MATCH_CATEGORY_REQUEST = 1;
  MATCH_CATEGORY_RESPONSE = 2;
}

enum CustomModsecRuleVersion {
  CUSTOM_MODSEC_RULE_VERSION_UNSPECIFIED = 0;
  CUSTOM_MODSEC_RULE_VERSION_V3 = 1;
  CUSTOM_MODSEC_RULE_VERSION_V3_SECARG_LIMITS = 2;
  CUSTOM_MODSEC_RULE_VERSION_CORAZA_V3 = 3;
  CUSTOM_MODSEC_RULE_VERSION_V3_SECARG_LIMITS_DETECTION_ONLY_MODE = 4;
  CUSTOM_MODSEC_RULE_VERSION_CORAZA_V3_DETECTION_ONLY_MODE = 5;
}

enum RuleSource {
  RULE_SOURCE_UNSPECIFIED = 0;
  RULE_SOURCE_CUSTOMER = 1;
  RULE_SOURCE_TRACEABLE = 2;
  RULE_SOURCE_SYSTEM = 3;
}

enum IpAddressExpressionType {
  IP_ADDRESS_EXPRESSION_TYPE_UNSPECIFIED = 0;
  IP_ADDRESS_EXPRESSION_TYPE_ALL_INTERNAL = 1;
  IP_ADDRESS_EXPRESSION_TYPE_ALL_EXTERNAL = 2;
}

enum IpType {
  IP_TYPE_UNSPECIFIED = 0;
  IP_TYPE_ANONYMOUS_VPN = 1;
  IP_TYPE_HOSTING_PROVIDER = 2;
  IP_TYPE_PUBLIC_PROXY = 3;
  IP_TYPE_TOR_EXIT_NODE = 4;
  IP_TYPE_BOT = 5;
  IP_TYPE_SCANNER = 6;
}

enum IpReputationSeverity {
  IP_REPUTATION_SEVERITY_UNSPECIFIED = 0;
  IP_REPUTATION_SEVERITY_LOW = 1;
  IP_REPUTATION_SEVERITY_MEDIUM = 2;
  IP_REPUTATION_SEVERITY_HIGH = 3;
  IP_REPUTATION_SEVERITY_CRITICAL = 4;
}

enum IpConnectionType {
  IP_CONNECTION_TYPE_UNSPECIFIED = 0;
  IP_CONNECTION_TYPE_RESIDENTIAL = 1;
  IP_CONNECTION_TYPE_MOBILE = 2;
  IP_CONNECTION_TYPE_CORPORATE = 3;
  IP_CONNECTION_TYPE_DATA_CENTER = 4;
  IP_CONNECTION_TYPE_EDUCATION = 5;
}

enum IpAbuseVelocity {
  IP_ABUSE_VELOCITY_UNSPECIFIED = 0;
  IP_ABUSE_VELOCITY_LOW = 1;
  IP_ABUSE_VELOCITY_MEDIUM = 2;
  IP_ABUSE_VELOCITY_HIGH = 3;
}
