syntax = "proto3";

package ai.traceable.malicioussources.config.service.v1;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

option java_multiple_files = true;

message MaliciousSourcesRule {
  string id = 1;
  MaliciousSourcesRuleScope rule_scope = 2;
  MaliciousSourcesRuleStatus rule_status = 3;
  MaliciousSourcesRuleInfo rule_info = 4;
}

message MaliciousSourcesRuleScope {
  oneof scope { // if no option selected, default is customer scope (all environments)
    EnvironmentScope environment_scope = 1;
  }
}

message EnvironmentScope {
  repeated string environment_ids = 1;
}

message MaliciousSourcesRuleStatus {
  bool disabled = 1;
  bool internal = 2;
}

message MaliciousSourcesRuleInfo {
  string name = 1;
  string description = 2;
  MaliciousSourcesRuleAction rule_action = 3;
  repeated MaliciousSourcesRuleCondition conditions = 4;
}

message MaliciousSourcesRuleAction {
  RuleActionType action_type = 1;
  ExpirationDetails expiration_details = 2;
  EventSeverity event_severity = 3;
  repeated RuleEffectWithModifications effects = 4;
}

message RuleEffectWithModifications {
  oneof effect {
    AgentRuleEffect agent_rule_effect = 1;
  }
}

message AgentRuleEffect {
  repeated AgentModification agent_modifications = 1;
}

message AgentModification {
  oneof modification {
    HeaderInjection header_injection = 1;
  }
}

message HeaderInjection {
  PredicateLocation header_location = 1;
  string header_name = 2;
  FieldValue value = 3;
}

message FieldValue {
  oneof value {
    string static_value = 1;
  }
}

enum PredicateLocation {
  PREDICATE_LOCATION_UNSPECIFIED = 0;
  PREDICATE_LOCATION_REQUEST = 1;
  PREDICATE_LOCATION_RESPONSE = 2;
}

message MaliciousSourcesRuleCondition {
  oneof condition {
    IpAddressCondition ip_range_condition = 1;
    RegionCondition region_condition = 2;
    IpLocationTypeCondition ip_location_type_condition = 3;
    IpReputationCondition ip_reputation_condition = 4;
    EmailDomainCondition email_domain_condition = 5;
  }
}

enum RuleActionType {
  RULE_ACTION_TYPE_UNSPECIFIED = 0;
  RULE_ACTION_TYPE_BLOCK = 1;
  RULE_ACTION_TYPE_ALLOW = 2;
  RULE_ACTION_TYPE_BLOCK_ALL_EXCEPT = 3;
  RULE_ACTION_TYPE_ALERT = 4;
}

message ExpirationDetails {
  // Expiration duration represented in ISO 8601 duration format.
  // If expiration_duration is not set and expiration_timestamp is set, the value gets derived from the expiration_timestamp field
  optional google.protobuf.Duration expiration_duration = 1;
  // Timestamp at which the blocking expires.
  // If expiration_timestamp is not set and expiration_duration is set, the value gets derived from the expiration_duration field
  optional google.protobuf.Timestamp expiration_timestamp = 2;
}

enum EventSeverity {
  EVENT_SEVERITY_UNSPECIFIED = 0;
  EVENT_SEVERITY_LOW = 1;
  EVENT_SEVERITY_MEDIUM = 2;
  EVENT_SEVERITY_HIGH = 3;
  EVENT_SEVERITY_CRITICAL = 4;
}

message IpAddressCondition {
  repeated string cidr_ip_ranges = 1;
  repeated string ip_addresses = 2;
}
message RegionCondition {
  repeated Region regions = 1;
}

message Region {
  oneof region {
    string country_iso_code = 1;
  }
}

message IpLocationTypeCondition {
  repeated IpLocationType ip_location_types = 1;
}

enum IpLocationType {
  IP_LOCATION_TYPE_UNSPECIFIED = 0;
  IP_LOCATION_TYPE_ANONYMOUS_VPN = 1;
  IP_LOCATION_TYPE_HOSTING_PROVIDER = 2;
  IP_LOCATION_TYPE_PUBLIC_PROXY = 3;
  IP_LOCATION_TYPE_TOR_EXIT_NODE = 4;
  IP_LOCATION_TYPE_BOT = 7;
}

message IpReputationCondition {
  oneof reputation {
    IpReputationSeverity min_ip_reputation_severity = 1;
    int32 min_ip_reputation_score = 2;
  }
}

enum IpReputationSeverity {
  IP_REPUTATION_SEVERITY_UNSPECIFIED = 0;
  IP_REPUTATION_SEVERITY_LOW = 1;
  IP_REPUTATION_SEVERITY_MEDIUM = 2;
  IP_REPUTATION_SEVERITY_HIGH = 3;
  IP_REPUTATION_SEVERITY_CRITICAL = 4;
}
message EmailDomainCondition {
  optional bool disposable_email_domain = 1;
  optional bool data_leaked_email = 2;
  repeated string email_domains = 3;
  repeated string email_regexes = 4;
  EmailFraudScore email_fraud_score = 5;
}

message EmailFraudScore {
  oneof fraud_score {
    EmailFraudScoreLevel min_email_fraud_score_level = 1;
    int32 min_email_fraud_score = 2;
  }
}

enum EmailFraudScoreLevel {
  EMAIL_FRAUD_SCORE_LEVEL_UNSPECIFIED = 0;
  EMAIL_FRAUD_SCORE_LEVEL_HIGH = 1;
  EMAIL_FRAUD_SCORE_LEVEL_CRITICAL = 2;
}
