syntax = "proto3";

package ai.traceable.malicioussources.config.service.v1;

import "ai/traceable/malicioussources/config/service/v1/malicious_sources_request_response.proto";

option java_multiple_files = true;

service MaliciousSourcesConfigService {
  rpc GetMaliciousSourcesRules(GetMaliciousSourcesRulesRequest) returns (GetMaliciousSourcesRulesResponse) {}

  rpc CreateMaliciousSourcesRule(CreateMaliciousSourcesRuleRequest) returns (CreateMaliciousSourcesRuleResponse) {}

  rpc UpdateMaliciousSourcesRule(UpdateMaliciousSourcesRuleRequest) returns (UpdateMaliciousSourcesRuleResponse) {}

  rpc DeleteMaliciousSourcesRule(DeleteMaliciousSourcesRuleRequest) returns (DeleteMaliciousSourcesRuleResponse) {}
}
