riskScoringGridCells = [
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_LOW
    impactScoreCategory = RISK_SCORE_CATEGORY_LOW
    score = 1
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_LOW
    impactScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
    score = 2
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_LOW
    impactScoreCategory = RISK_SCORE_CATEGORY_HIGH
    score = 3
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_LOW
    impactScoreCategory = RISK_SCORE_CATEGORY_CRITICAL
    score = 4
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
    impactScoreCategory = RISK_SCORE_CATEGORY_LOW
    score = 2
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
    impactScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
    score = 5
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
    impactScoreCategory = RISK_SCORE_CATEGORY_HIGH
    score = 6
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
    impactScoreCategory = RISK_SCORE_CATEGORY_CRITICAL
    score = 7
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_HIGH
    impactScoreCategory = RISK_SCORE_CATEGORY_LOW
    score = 3
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_HIGH
    impactScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
    score = 6
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_HIGH
    impactScoreCategory = RISK_SCORE_CATEGORY_HIGH
    score = 8
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_HIGH
    impactScoreCategory = RISK_SCORE_CATEGORY_CRITICAL
    score = 9
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_CRITICAL
    impactScoreCategory = RISK_SCORE_CATEGORY_LOW
    score = 4
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_CRITICAL
    impactScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
    score = 7
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_CRITICAL
    impactScoreCategory = RISK_SCORE_CATEGORY_HIGH
    score = 9
  },
  {
    likelihoodScoreCategory = RISK_SCORE_CATEGORY_CRITICAL
    impactScoreCategory = RISK_SCORE_CATEGORY_CRITICAL
    score = 10
  }
]
