syntax = "proto3";

package ai.traceable.data.exfiltration.config.service.v1;

import "ai/traceable/data/exfiltration/config/service/v1/data_exfiltration_detection_rule_config.proto";

option java_multiple_files = true;

service DataExfiltrationDetectionRuleConfigService {
  rpc GetDataExfiltrationDetectionRules(GetDataExfiltrationDetectionRulesRequest) returns (GetDataExfiltrationDetectionRulesResponse) {}

  rpc CreateDataExfiltrationDetectionRule(CreateDataExfiltrationDetectionRuleRequest) returns (CreateDataExfiltrationDetectionRuleResponse) {}

  rpc UpdateDataExfiltrationDetectionRule(UpdateDataExfiltrationDetectionRuleRequest) returns (UpdateDataExfiltrationDetectionRuleResponse) {}

  rpc DeleteDataExfiltrationDetectionRule(DeleteDataExfiltrationDetectionRuleRequest) returns (DeleteDataExfiltrationDetectionRuleResponse) {}
}
