syntax = "proto3";

package ai.traceable.blocking.config.service.v1;

option java_multiple_files = true;

message GetBlockingRulesRequest {
    string omit_if_matches_hash = 1;
}

message GetBlockingRulesResponse {
    BlockingRules blocking_rules = 1;
    string hash = 2;
}

message BlockingRules {
    RegionBlockingRules region_blocking_rules = 1;
    CustomModsecBlockingRules custom_modsec_blocking_rules = 2;
}

message RegionBlockingRules {
    repeated RegionIpBlockingDetails region_ip_blocking_details = 1;
}

message RegionIpBlockingDetails {
    repeated IpRange ip_ranges = 1;
    string region_id = 2;
}

message IpRange {
    oneof value {
        IpV4Range ipv4_range = 1;
    }
}

message IpV4Range {
    int64 start_ip = 1;
    int64 end_ip = 2;
}

message CustomModsecBlockingRules {
    string custom_modsec_rules_blob = 1;
}
