import org.hypertrace.gradle.dependency.DependencyPluginSettingExtension

pluginManagement {
  repositories {
    mavenLocal()
    maven((extra.properties["artifactory_contextUrl"] as String) + "/gradle") {
      credentials {
        username = extra.properties["artifactory_user"] as String
        password = extra.properties["artifactory_password"] as String
      }
    }
  }
}

plugins {
  id("org.hypertrace.version-settings") version "0.2.1"
  id("ai.traceable.dependency-settings") version "1.6.3"
}

rootProject.name = "traceable-config-service-root"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

configure<DependencyPluginSettingExtension> {
  catalogVersion.set("0.3.1408")
}

includeBuild("./hypertrace-config-service")

include(":traceable-config-service")
include(":sensitive-data-config-service-api")
include(":sensitive-data-config-service-impl")
include(":rate-limiting-config-service-api")
include(":rate-limiting-config-service-impl")
include(":license-status-config-service-api")
include(":license-status-config-service-impl")
include(":local-processing-config-service-api")
include(":local-processing-config-service-impl")
include(":blocking-config-service-api")
include(":blocking-config-service-impl")
include(":region-config-service-api")
include(":region-config-service-impl")
include(":custom-signature-config-service-api")
include(":custom-signature-config-service-impl")
include(":user-attribution-config-service-api")
include(":user-attribution-config-service-impl")
include(":auth-detection-config-service-api")
include(":auth-detection-config-service-impl")
include(":threat-management-config-service-api")
include(":threat-management-config-service-impl")
include(":external-user-attribution-config-service-api")
include(":external-user-attribution-config-service-impl")
include(":external-agent-attribute-config-service-api")
include(":external-agent-attribute-config-service-impl")
include(":external-wasm-config-service-api")
include(":anomaly-config-service-api")
include(":anomaly-config-service-impl")
include(":anomaly-config-service-registry")
include(":anomaly-config-service-utils")
include(":detection-exclusion-config-service-api")
include(":detection-exclusion-config-service-impl")
include(":iprange-config-service-api")
include(":iprange-config-service-impl")
include(":ip-resolution-config-service-api")
include(":jwt-extraction-config-service-api")
include(":jwt-extraction-config-service-impl")
include(":malicious-sources-config-service-api")
include(":malicious-sources-config-service-impl")
include(":activity-event-producer")
include(":risk-config-service-api")
include(":risk-config-service-impl")
include(":risk-config-service-v2-impl")
include(":config-utils")
include(":data-config-service-api")
include(":data-config-service-impl")
include(":traceable-alerting-config-service-api")
include(":traceable-alerting-config-service-impl")
include(":data-classification-config-service-api")
include(":data-classification-config-service-impl")
include(":reporting-config-service-api")
include(":reporting-config-service-impl")
include(":data-exfiltration-config-service-api")
include(":data-exfiltration-config-service-impl")
include(":external-data-classification-config-service-api")
include(":external-data-classification-config-service-impl")
include(":api-attribute-override-service-api")
include(":api-attribute-override-service-impl")
include(":waf-provider-integration-service-api")
include(":waf-provider-integration-service-impl")
include(":traceable-span-processing-config-service-api")
include(":traceable-span-processing-config-service-impl")
include(":api-spec-config-service-api")
include(":api-spec-config-service-impl")
include(":feature-caching-client")
include(":traceable-config-service-factory")
include(":api-gateway-config-service-api")
include(":api-gateway-config-service-cache")
include(":api-gateway-config-service-common")
include(":api-gateway-config-service-impl")
include(":anomaly-scoring-config-service-api")
include(":anomaly-scoring-config-service-impl")
include(":entity-fetcher-cache")

include(":mock-config-service")
include(":ast-scan-profile-config-service-api")
include(":ast-scan-profile-config-service-impl")
include(":integration-config-service-api")
include(":integration-config-service-impl")
include(":ast-config-service-api")
include(":ast-config-service-impl")
include(":splunk-integration-config-service-api")
include(":splunk-integration-config-service-impl")
include(":ast-hooks-config-service-api")
include(":ast-hooks-config-service-impl")
include(":saved-filter-config-service-api")
include(":saved-filter-config-service-impl")
include(":session-identification-config-service-api")
include(":session-identification-config-service-impl")
include(":saved-query-config-service-api")
include(":saved-query-config-service-impl")
include(":dashboard-config-service-api")
include(":dashboard-config-service-impl")
include(":modsecurity-utils")
include(":syslog-integration-config-service-api")
include(":syslog-integration-config-service-impl")
include(":jira-integration-config-service-api")
include(":jira-integration-config-service-impl")
include(":runner-logs-config-service-api")
include(":runner-logs-config-service-impl")
include(":data-classification-client")
include(":data-protection-config-service-api")
include(":data-protection-config-service-impl")
include(":fraud-datamodel-config-service-api")
include(":fraud-datamodel-config-service-impl")
include(":fraud-datamodel-derivation-config-service-api")
include(":fraud-datamodel-derivation-config-service-impl")
include(":fraud-policy-config-service-api")
include(":fraud-policy-config-service-impl")
include(":vulnerability-config-service-api")
include(":vulnerability-config-service-impl")
include(":servicenow-itsm-integration-config-service-api")
include(":servicenow-itsm-integration-config-service-impl")
include(":azure-devops-integration-config-service-api")
include(":azure-devops-integration-config-service-impl")
include(":traceable-config-service-rest")
include(":traceable-datamodel-config-service-api")
include(":traceable-policy-config-service-api")
include(":traceable-edge-config-service-api")