syntax = "proto3";

option java_multiple_files = true;

package ai.traceable.ratelimiting.config.service.v2;

import "ai/traceable/ratelimiting/config/service/v2/rate_limiting_rule.proto";

service RateLimitingConfigService {
  rpc GetRateLimitingRules (GetRateLimitingRulesRequest) returns (GetRateLimitingRulesResponse) {
  }
  rpc UpdateRateLimitingRule (UpdateRateLimitingRuleRequest) returns (UpdateRateLimitingRuleResponse) {
  }
  rpc DeleteRateLimitingRule (DeleteRateLimitingRuleRequest) returns (DeleteRateLimitingRuleResponse) {
  }
  rpc CreateRateLimitingRule (CreateRateLimitingRuleRequest) returns (CreateRateLimitingRuleResponse) {
  }
  rpc GetRateLimitingRuleModsecRules (GetRateLimitingRuleModsecRulesRequest) returns (GetRateLimitingRuleModsecRulesResponse) {
  }
}

message GetRateLimitingRulesRequest {
  GetRulesByCategoryFilter filter = 1 [deprecated = true];
  GetRateLimitingRulesFilter rules_filter = 2;
}

message GetRateLimitingRulesFilter {
  repeated Category categories = 1;
  RuleConfigScope scope = 2;
  optional bool disabled = 3;
  repeated RuleAction rule_actions = 4;

  enum RuleAction {
    RULE_ACTION_UNSPECIFIED = 0;
    RULE_ACTION_TRANSACTION_BLOCKED = 1;
    RULE_ACTION_TRANSACTION_ALLOWED = 2;
  }
}

message GetRulesByCategoryFilter {
  repeated Category categories = 1;
}

message GetRateLimitingRulesResponse {
  repeated RateLimitingRule rules = 1;
}

message UpdateRateLimitingRuleRequest {
  string rule_id = 1;
  RateLimitingRuleData data = 2;
}

message UpdateRateLimitingRuleResponse {
  RateLimitingRule rule = 1;
}

message DeleteRateLimitingRuleRequest {
  string rule_id = 1;
}

message DeleteRateLimitingRuleResponse {
}

message CreateRateLimitingRuleRequest {
  RateLimitingRuleData data = 1;
}

message CreateRateLimitingRuleResponse {
  RateLimitingRule rule = 1;
}

message GetRateLimitingRuleModsecRulesRequest{
  GetRateLimitingRulesFilter rules_filter = 1;
}

message GetRateLimitingRuleModsecRulesResponse {
  string modsec_directives_blob = 1;
  string modsec_rules_blob = 2;
  repeated RateLimitingModsecRule rules = 3;
}
