syntax = "proto3";

option java_multiple_files = true;

package ai.traceable.ratelimiting.config.service.v2;

import "ai/traceable/ratelimiting/config/service/v2/rate_limiting_rule.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_config.proto";

service RateLimitingConfigService {
  rpc GetRateLimitingRules (GetRateLimitingRulesRequest) returns (GetRateLimitingRulesResponse) {
  }
  rpc UpdateRateLimitingRule (UpdateRateLimitingRuleRequest) returns (UpdateRateLimitingRuleResponse) {
  }
  rpc DeleteRateLimitingRule (DeleteRateLimitingRuleRequest) returns (DeleteRateLimitingRuleResponse) {
  }
  rpc CreateRateLimitingRule (CreateRateLimitingRuleRequest) returns (CreateRateLimitingRuleResponse) {
  }
  rpc GetRateLimitingRuleModsecRules (GetRateLimitingRuleModsecRulesRequest) returns (GetRateLimitingRuleModsecRulesResponse) {
  }
  rpc GetRateLimitingEdgeDecisionRules (GetRateLimitingEdgeDecisionRulesRequest) returns (GetRateLimitingEdgeDecisionRulesResponse) {
  }
}

message GetRateLimitingRulesRequest {
  GetRulesByCategoryFilter filter = 1 [deprecated = true];
  GetRateLimitingRulesFilter rules_filter = 2;
}

message GetRateLimitingRulesFilter {
  repeated Category categories = 1;
  RuleConfigScope scope = 2;
  optional bool disabled = 3;
}

message GetRateLimitingModsecRulesFilter {
  GetRateLimitingRulesFilter rules_filter = 1;
  repeated RuleAction rule_actions = 2;
  repeated string service_names = 3;

  enum RuleAction {
    RULE_ACTION_UNSPECIFIED = 0;
    RULE_ACTION_TRANSACTION_BLOCKED = 1;
    RULE_ACTION_TRANSACTION_ALLOWED = 2;
  }
}

message GetRulesByCategoryFilter {
  repeated Category categories = 1;
}

message GetRateLimitingRulesResponse {
  repeated RateLimitingRule rules = 1;
}

message UpdateRateLimitingRuleRequest {
  string rule_id = 1;
  RateLimitingRuleData data = 2;
}

message UpdateRateLimitingRuleResponse {
  RateLimitingRule rule = 1;
}

message DeleteRateLimitingRuleRequest {
  string rule_id = 1;
}

message DeleteRateLimitingRuleResponse {
}

message CreateRateLimitingRuleRequest {
  RateLimitingRuleData data = 1;
}

message CreateRateLimitingRuleResponse {
  RateLimitingRule rule = 1;
}

message GetRateLimitingRuleModsecRulesRequest{
  GetRateLimitingModsecRulesFilter rules_filter = 1;
}

message GetRateLimitingRuleModsecRulesResponse {
  string modsec_directives_blob = 1;
  repeated ModsecBlobData modsec_blobs_data = 2;
  repeated RateLimitingModsecRule rules = 3;
}

message GetRateLimitingEdgeDecisionRulesRequest {
  GetRateLimitingRulesFilter rules_filter = 1;
}

message GetRateLimitingEdgeDecisionRulesResponse {
    ai.traceable.edge.decision.config.service.v1.EdgeDecisionEngineConfig edge_decision_engine_config = 1;
}

message ModsecBlobData {
  string modsec_blob = 1;
  repeated string service_names = 2;
  repeated string rule_ids = 3;
}
