apiDefRuleIdToConfigMap =
  [
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "missingParam"
        missingParam = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "enum"
        enum = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "integer"
        integer = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "type"
        type = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "device"
        device = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "httpStatus"
        httpStatus = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "contentType"
        contentType = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "contentSize"
        contentSize = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "specialCharacter"
        specialCharacter = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "contentExplosion"
        contentExplosion = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "ssrf"
        ssrf = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "unknownParam"
        unknownParam = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "bfla"
        bfla = {}
      }
    },
    {
      apiDefinitionMetadataAnomalyDetectionConfig = {
        anomalyRuleId = "jwt"
        jwt = {}
      }
    }
  ]
