apiDefRules = [
  {
    ruleId = "unknownParam"
    ruleName = "Unrecognized Field"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "enum"
    ruleName = "Invalid Enumerations"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "integer"
    ruleName = "Value Out of Range"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "type"
    ruleName = "Type Anomaly"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "device"
    ruleName = "Unexpected User Agent"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES
  },
  {
    ruleId = "httpStatus"
    ruleName = "Unexpected HTTP Response Code"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES
  },
  {
    ruleId = "contentType"
    ruleName = "Content Type Anomaly"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES
  },
  {
    ruleId = "contentSize"
    ruleName = "Content Size Anomaly"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES
  },
  {
    ruleId = "xxe"
    ruleName = "XML External Entity Injection"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_INJECTIONS
  },
  {
    ruleId = "ssrf"
    ruleName = "Server-Side Request Forgery (SSRF)"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_SSRF
  }
]