apiDefRules = [
  {
    ruleId = "unknownParam"
    ruleName = "Unrecognized Field"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "enum"
    ruleName = "Invalid Enumerations"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "integer"
    ruleName = "Value Out of Range"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "type"
    ruleName = "Type Anomaly"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "missingParam"
    ruleName = "Missing Field"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES
  },
  {
    ruleId = "device"
    ruleName = "Unexpected User Agent"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES
  },
  {
    ruleId = "httpStatus"
    ruleName = "Unexpected HTTP Response Code"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES
  },
  {
    ruleId = "contentType"
    ruleName = "Content Type Anomaly"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES
  },
  {
    ruleId = "contentSize"
    ruleName = "Content Size Anomaly"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES
  },
  {
    ruleId = "ssrf"
    ruleName = "Server-Side Request Forgery (SSRF)"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_SSRF
  },
  {
    ruleId = "bfla"
    ruleName = "Broken Function Level Authorization (BFLA)"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_AUTHORIZATION_VIOLATIONS
  },
  {
    ruleId = "jwt"
    ruleName = "JWT Anomaly"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_AUTHENTICATION_AND_TOKEN_VIOLATIONS
    subRuleInfos = [
      {
        ruleId = "jwt_exp"
        ruleName = "JWT Expired"
        subRuleTypes = [ANOMALY_SUB_RULE_TYPE_REGULAR]
      },
      {
        ruleId = "jwt_nbf"
        ruleName = "JWT Premature Usage"
        subRuleTypes = [ANOMALY_SUB_RULE_TYPE_REGULAR]
      },
      {
        ruleId = "jwt_iss"
        ruleName = "Unknown JWT Issuer"
        subRuleTypes = [ANOMALY_SUB_RULE_TYPE_REGULAR]
      },
      {
        ruleId = "jwt_aud"
        ruleName = "Unauthorised JWT audience"
        subRuleTypes = [ANOMALY_SUB_RULE_TYPE_REGULAR]
      },
      {
        ruleId = "jwt_alg"
        ruleName = "JWT Algorithm Confusion"
        subRuleTypes = [ANOMALY_SUB_RULE_TYPE_REGULAR]
      }
    ]
  }
]
