apiDefRules = [
  {
    ruleId = "unknownParam"
    ruleName = "Unrecognized Field"
    ruleCategory = "Parameter Anomalies"
  },
  {
    ruleId = "enum"
    ruleName = "Invalid Enumerations"
    ruleCategory = "Parameter Anomalies"
  },
  {
    ruleId = "integer"
    ruleName = "Value Out of Range"
    ruleCategory = "Parameter Anomalies"
  },
  {
    ruleId = "type"
    ruleName = "Type Anomaly"
    ruleCategory = "Parameter Anomalies"
  },
  {
    ruleId = "device"
    ruleName = "Unexpected User Agent"
    ruleCategory = "Request and Response Metadata Anomalies"
  },
  {
    ruleId = "httpStatus"
    ruleName = "Unexpected HTTP Response Code"
    ruleCategory = "Request and Response Metadata Anomalies"
  },
  {
    ruleId = "contentType"
    ruleName = "Content Type Anomaly"
    ruleCategory = "Request and Response Metadata Anomalies"
  },
  {
    ruleId = "contentSize"
    ruleName = "Content Size Anomaly"
    ruleCategory = "Request and Response Metadata Anomalies"
  },
  {
    ruleId = "xxe"
    ruleName = "XML External Entity Injection"
    ruleCategory = "Injections"
  },
  {
    ruleId = "ssrf"
    ruleName = "Server-Side Request Forgery"
  }
]