{{- if .Values.cleanupJob.enabled }}
{{- if $.Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: config-old-versions-cleanup
  labels:
    release: {{ .Release.Name }}
  {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.cleanupJob.schedule |  quote }}
  {{- if .Values.cleanupJob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ int .Values.cleanupJob.startingDeadlineSeconds }}
  {{- end }}
  {{- if .Values.cleanupJob.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.cleanupJob.concurrencyPolicy }}
  {{- end }}
  {{- if not .Values.cleanupJob.enabled }}
  suspend: true
  {{- end }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ int .Values.cleanupJob.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ int .Values.cleanupJob.ttlSecondsAfterFinished }}
      template:
        {{- if .Values.cleanupJob.podAnnotations }}
        metadata:
          annotations:
            {{- toYaml .Values.cleanupJob.podAnnotations | nindent 12 }}
        {{- end }}
        spec:
          containers:
            - name: config-old-versions-cleanup
              image: {{ .Values.cleanupJob.image.repository }}:{{ .Values.cleanupJob.image.tag }}
              imagePullPolicy: {{ .Values.cleanupJob.image.pullPolicy }}
              command: ["/bin/sh", "-c"]
              args:
                - |
                  finish() {
                    curl -sf -XPOST http://127.0.0.1:15020/quitquitquit || true
                  }
                  trap finish EXIT
                  cd /scripts
                  mongo "${MONGODB_URI}" config_old_versions_cleanup.js
              volumeMounts:
                - name: config-old-versions-cleanup
                  mountPath: /scripts
              env:
                - name: MONGODB_URI
                  value: {{ .Values.cleanupJob.mongodb.uri | quote }}
          restartPolicy: Never
          volumes:
            - name: config-old-versions-cleanup
              configMap:
                name: config-old-versions-cleanup
          {{- with .Values.cleanupJob.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanupJob.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanupJob.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanupJob.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanupJob.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
