{{- if eq .Values.chartType "application" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name }}
  {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.deploymentSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        {{- with merge .Values.podLabels .Values.commonPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/traceable-config-service-config.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.containerAdminPort }}"
        {{- with merge .Values.podAnnotations .Values.commonPodAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: service-config
          configMap:
            name: {{ .Values.traceableConfigServiceConfig.name }}
        - name: log4j-config
          configMap:
            name: {{ .Values.logConfig.name }}
        {{- if eq $.Values.deepStoreFsScheme "gs" }}
        - name: service-account-iam
          secret:
            secretName: {{ $.Values.iamServiceAccountSecret }}
        {{- end }}
        {{- if eq $.Values.deepStoreFsScheme "file" }}
        - name: traceable-nfs-deep-store
          persistentVolumeClaim:
            claimName: {{ $.Values.deepStoreClaimName }}
        {{- end }}
        - name: traceable-nfs-model-store
          persistentVolumeClaim:
            claimName: {{ $.Values.modelStoreNFSClaimName }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "traceable-config-service.inject-user-group.volumes" . | nindent 8 }}
    {{- with .Values.nodeLabels }}
      nodeSelector:
      {{- toYaml . | nindent 8}}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8}}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8}}
    {{- end }}
    {{- with .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    {{- end }}
    {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8}}
    {{- end }}
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.corazaWafService.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.corazaWafService.image.repository }}:{{ default .Values.corazaWafService.image.tag .Values.corazaWafService.image.tagOverride }}"
          imagePullPolicy: {{ .Values.corazaWafService.image.pullPolicy }}
          ports:
            - name: grpc-coraza
              containerPort: 9000
              protocol: TCP
            - name: http-cz-metrics
              containerPort: 8090
              protocol: TCP
            - name: http-cz-profile
              containerPort: 8050
              protocol: TCP
          resources:
            {{- toYaml .Values.corazaWafService.resources | nindent 12 }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if and .Values.podSecurityContext .Values.injectUserGroup.enabled }}
          volumeMounts:
            {{- include "traceable-config-service.inject-user-group.volume-mounts" . | nindent 12 }}
          {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ $.Values.image.registry }}/{{ .Values.image.repository }}:{{ default $.Chart.AppVersion $.Values.image.tagOverride }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.internalContainerPortName }}
              containerPort: {{ .Values.internalContainerPort }}
              protocol: TCP
            - name: {{ .Values.internalGlobalServiceContainerPortName }}
              containerPort: {{ .Values.internalGlobalServiceContainerPort }}
              protocol: TCP
            - name: {{ .Values.externalContainerPortName }}
              containerPort: {{ .Values.externalContainerPort }}
              protocol: TCP
            - name: {{ .Values.restContainerPortName }}
              containerPort: {{ .Values.restContainerPort }}
              protocol: TCP
            - name: admin-port
              containerPort: {{ .Values.containerAdminPort }}
              protocol: TCP
          env:
            - name: BOOTSTRAP_CONFIG_URI
              value: "file:///app/resources/configs"
            - name: LOG4J_CONFIGURATION_FILE
              value: "/var/{{ .Chart.Name }}/log/log4j2.properties"
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
            {{- if and .Values.database .Values.database.mongo.authEnabled }}
            {{- with .Values.database.mongo.credentials }}
            - name: MONGO_SERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretUsernameKey }}
            - name: MONGO_SERVICE_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.secretName }}
                  key: {{.secretPasswordKey }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: service-config
              mountPath: /app/resources/configs/{{ .Chart.Name }}/application.conf
              subPath: application.conf
            - name: service-config
              mountPath: /app/resources/configs/{{ .Chart.Name }}/anomaly.conf
              subPath: anomaly.conf
            - name: service-config
              mountPath: /app/resources/configs/{{ .Chart.Name }}/risk.conf
              subPath: risk.conf
            - name: service-config
              mountPath: /app/resources/configs/{{ .Chart.Name }}/traceable-edge.conf
              subPath: traceable-edge.conf
            - name: service-config
              mountPath: /app/resources/configs/{{ .Chart.Name }}/span-processing-rules.conf
              subPath: span-processing-rules.conf
            - name: log4j-config
              mountPath: /var/{{ .Chart.Name }}/log
            {{- if eq $.Values.deepStoreFsScheme "gs" }}
            - name: service-account-iam
              mountPath: "/accounts"
              readOnly: true
            {{- end }}
            {{- if eq $.Values.deepStoreFsScheme "file" }}
            - name: traceable-nfs-deep-store
              mountPath: {{ $.Values.deepStoreMountPath }}
            {{- end }}
            - name: traceable-nfs-model-store
              mountPath: {{ $.Values.modelStoreNFSMountPath }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- include "traceable-config-service.inject-user-group.volume-mounts" . | nindent 12 }}
          livenessProbe:
            periodSeconds: {{ int .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ int .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ int .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: /health
              port: {{ .Values.containerAdminPort }}
          startupProbe:
            periodSeconds: {{ int .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ int .Values.startupProbe.failureThreshold }}
            timeoutSeconds: {{ int .Values.startupProbe.timeoutSeconds }}
            httpGet:
              path: /health
              port: {{ .Values.containerAdminPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
