{{- if .Values.prometheusRule.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: traceable-config-service-prometheus-rule
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    monitoring: shared
    app: {{ .Values.service.name }}
spec:
  groups:
    - name: traceable-config-service
      rules:
        - alert: ThreatAutoBlockingConfigurationChange
          annotations:
            summary: 'Threat Auto Blocking Configuration Change'
            message: 'Threat Auto Blocking Configuration changed to {{`{{ $labels.operation}}`}} for customer:{{`{{ $labels.tenantId }}`}}'
          expr: sum(config_threat_autoblocking_action_timer_seconds_max) by (tenantId, operation) > 0
          for: 0m
          labels:
            severity: SEV3
            repository: config-service
            team: common
            {{- with .Values.prometheusRule.additionalRuleLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - alert: ScopedAnomalyGlobalConfigurationChange
          annotations:
            summary: 'Scoped Anomaly Global Configuration Change'
            message: 'Scoped Anomaly Global Configuration changed to {{`{{ $labels.action}}`}} for {{`{{ $labels.anomalyDetectionType}}`}} policies for customer:{{`{{ $labels.tenantId }}`}}'
          expr: sum(scoped_anomaly_global_config_action_timer_seconds_max) by (tenantId, action, anomalyDetectionType) > 0
          for: 0m
          labels:
            severity: SEV3
            repository: config-service
            team: protection
            {{- with .Values.prometheusRule.additionalRuleLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - alert: ApiNamingRulesLimitExceeded
          annotations:
            summary: 'The total number of API Naming Rules created is too high.'
            message: 'The number of API Naming Rules created for tenant {{`{{$labels.tenantId}}`}} exceeded the limit (10,000). Current value: {{`{{ $value }}`}} rules."'
          expr: sum by (tenantId) (max by (tenantId, disabled) (spec_based_api_naming_rules_count)) > 10000
          for: 0m
          labels:
            severity: warning
            repository: config-service
            team: catalog
            {{- with .Values.prometheusRule.additionalRuleLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - alert: CloudEdgeDeploymentConfigStatusChange
          annotations:
            summary: 'Cloud Edge Deployment Config Status Change'
            message: 'Cloud Edge Deployment Config status changed to {{`{{ $labels.deploymentStatus}}`}} for deployment id: {{`{{ $labels.deploymentId}}`}} for customer: {{`{{ $labels.tenantId }}`}}'
          expr: sum(cloud_edge_deployment_status_action_timer_seconds_max) by (tenantId, deploymentId, deploymentStatus) > 0
          for: 0m
          labels:
            severity: SEV1
            repository: config-service
            team: protection-waap
            {{- with .Values.prometheusRule.additionalRuleLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - alert: CloudEdgeDeploymentConfigurationStatusChange
          annotations:
            summary: 'Cloud Edge Deployment Config Status Change'
            message: 'Cloud Edge Deployment Config status changed to {{`{{ $labels.deploymentStatus}}`}} for deployment id: {{`{{ $labels.deploymentId}}`}} for customer: {{`{{ $labels.tenantId }}`}}'
          expr: sum(cloud_edge_deployment_status_action_timer_seconds_max) by (tenantId, deploymentId, deploymentStatus) > 0
          for: 0m
          labels:
            severity: SEV3
            repository: config-service
            team: protection-waap
            { { - with .Values.prometheusRule.additionalRuleLabels } }
            { { - toYaml . | nindent 12 } }
            { { - end } }
        - alert: CloudBotDeploymentConfigStatusChange
          annotations:
            summary: 'IGNORE: Cloud Bot Deployment Config Status Change'
            message: 'Cloud Bot Deployment Config status changed to {{`{{ $labels.deploymentStatus}}`}} for config id: {{`{{ $labels.configId}}`}} for customer: {{`{{ $labels.tenantId }}`}}'
            runbook_url: https://harness.atlassian.net/wiki/x/EQISTgU
          expr: sum(changes(cloud_bot_deployment_config_status_change_count_total{deploymentStatus=~"DEPLOYMENT_STATUS_REQUESTED|DEPLOYMENT_STATUS_CHANGE_REQUESTED|DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS"}[2m])) by (tenantId, configId, deploymentStatus) > bool 0
          for: 0m
          labels:
            severity: SEV2
            repository: config-service
            team: protection-bot
            {{- with .Values.prometheusRule.additionalRuleLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
  {{- end }}
{{- end }}
