apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.internalContainerPort }}
      name: {{ .Values.internalContainerPortName }}-{{ .Chart.Name }}
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.externalContainerPort }}
      name: {{ .Values.externalContainerPortName }}-{{ .Chart.Name }}
    - port: {{ .Values.service.internalGlobalPort }}
      targetPort: {{ .Values.internalGlobalServiceContainerPort }}
      name: {{ .Values.internalGlobalServiceContainerPortName }}-{{ .Chart.Name }}
  selector:
    {{- toYaml .Values.serviceSelectorLabels | nindent 4 }}
