apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.traceableConfigServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    service.port.internal = {{ .Values.internalContainerPort }}
    service.port.external = {{ .Values.externalContainerPort }}
    service.admin.port = {{ .Values.containerAdminPort }}
    generic.config.service {
      document.store {
        {{- $dst := .Values.traceableConfigServiceConfig.dataStoreType }}
        dataStoreType = {{ $dst }}
        {{ $dst }} {
          {{- range $key, $value := (index .Values "traceableConfigServiceConfig" (printf "%s" $dst)) }}
          {{- if $value }}
          {{ $key }} = {{ $value | quote }}
          {{- end }}
          {{- end }}
        }
      }
    }
    {{- if hasKey .Values.traceableConfigServiceConfig "defaultPiiFilterConfig" }}
    sensitive.data.config.service {
      default.pii.filter.config {
        {{- .Values.traceableConfigServiceConfig.defaultPiiFilterConfig | nindent 8 }}
      }
    }
    {{- end }}
    insights.service.config = {
      host = {{ .Values.traceableConfigServiceConfig.insightsServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.insightsServiceConfig.port }}
    }
    anomaly.config.service = {
      include "anomaly.conf"
    }
  anomaly.conf: |-
    global {
      disabled = {{ .Values.anomalyConfigServiceConfig.global.disabled }}
      internal = {{ .Values.anomalyConfigServiceConfig.global.internal }}
    }