apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.traceableConfigServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    service.port.internal = {{ .Values.internalContainerPort }}
    service.port.external = {{ .Values.externalContainerPort }}
    service.admin.port = {{ .Values.containerAdminPort }}
    generic.config.service {
      publish.change.events = {{ .Values.traceableConfigServiceConfig.publishChangeEvents }}
      document.store {
        {{- $dst := .Values.traceableConfigServiceConfig.dataStoreType }}
        dataStoreType = {{ $dst }}
        {{ $dst }} {
          {{- range $key, $value := (index .Values "traceableConfigServiceConfig" (printf "%s" $dst)) }}
          {{- if $value }}
          {{ $key }} = {{ $value | quote }}
          {{- end }}
          {{- end }}
        }
      }
    }
    event.store {
      type = kafka
      bootstrap.servers = "bootstrap:9092"
      activity.events.producer {
        bootstrap.servers = "bootstrap:9092"
        schema.registry.url = "http://schema-registry-service:8081"
      }
      config.change.events.producer {
        bootstrap.servers = "bootstrap:9092"
        schema.registry.url = "http://schema-registry-service:8081"
      }
    }
    {{- if hasKey .Values.traceableConfigServiceConfig "defaultPiiFilterConfig" }}
    sensitive.data.config.service {
      default.pii.filter.config {
        {{- .Values.traceableConfigServiceConfig.defaultPiiFilterConfig | nindent 8 }}
      }
    }
    {{- end }}
    actor.service.config = {
      host = {{ .Values.traceableConfigServiceConfig.actorServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.actorServiceConfig.port }}
      request.timeout = {{ .Values.traceableConfigServiceConfig.actorServiceConfig.request.timeout }}
      cache = {
        maxCacheSize = {{ .Values.traceableConfigServiceConfig.actorServiceConfig.cache.maxCacheSize }}
        refreshAfterWriteDuration = {{ .Values.traceableConfigServiceConfig.actorServiceConfig.cache.refreshAfterWriteDuration }}
        expireAfterWriteDuration = {{ .Values.traceableConfigServiceConfig.actorServiceConfig.cache.expireAfterWriteDuration }}
      }
    }
    insights.service.config = {
      host = {{ .Values.traceableConfigServiceConfig.insightsServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.insightsServiceConfig.port }}
      request.timeout = {{ .Values.traceableConfigServiceConfig.insightsServiceConfig.request.timeout }}
    }
    entity.service.config = {
      host = {{ .Values.traceableConfigServiceConfig.entityServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.entityServiceConfig.port }}
      cache = {
        maxCacheSize = {{ .Values.traceableConfigServiceConfig.entityServiceConfig.cache.maxCacheSize }}
        refreshAfterWriteDuration = {{ .Values.traceableConfigServiceConfig.entityServiceConfig.cache.refreshAfterWriteDuration }}
        expireAfterWriteDuration = {{ .Values.traceableConfigServiceConfig.entityServiceConfig.cache.expireAfterWriteDuration }}
      }
    }
    license.metering.service = {
      host = {{ .Values.traceableConfigServiceConfig.licenseMeteringServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.licenseMeteringServiceConfig.port }}
      cache.expiration.duration = {{ .Values.traceableConfigServiceConfig.licenseMeteringServiceConfig.cacheExpiryDuration }}
    }
    api.naming.config {
      trieModels = {
        {{- if $.Values.trieModels.modelStores }}
        model.stores = [
          {{- range $sk,$sv := $.Values.trieModels.modelStores }}
          {
            deep.store.fs.scheme = {{ $sv.deepStoreScheme }}
            read.enabled = {{ $sv.readEnabled }}
            read.priority = {{ $sv.readPriority }}
            write.disabled = {{ $sv.writeDisabled }}
            {{- if eq $sv.deepStoreScheme "file" }}
            directory = {{ printf "%s/%s/customers" $.Values.modelStoreNFSMountPath $.Values.global.env | quote }}
            {{- end }}
            {{- if eq $sv.deepStoreScheme "gs" }}
            gcs.bucket.name = {{ printf "%s-%s" $.Values.bucketPrefix $.Values.global.env | quote }}
            gcs.key.file = "/accounts/key.json"
            directory = {{ $.Values.deepStoreFilePath | quote }}
            {{- end }}
            {{- if eq $sv.deepStoreScheme "s3" }}
            directory = {{ $.Values.deepStoreFilePath | quote }}
            s3.bucket.name = {{ $.Values.s3BucketName | quote }}
            s3.config = {
              {{- range $k, $v := $.Values.s3Config }}
              {{ $k }} = {{ $v | quote }}
              {{- end }}
            }
            {{- end }}
          },
          {{- end}}
        ]
        {{- end}}
        cache = {
          refreshAfterWriteDuration = {{ .Values.trieModels.cache.refreshAfterWriteDuration }}
          expireAfterWriteDuration = {{ .Values.trieModels.cache.expireAfterWriteDuration }}
          maximumSize = {{ .Values.trieModels.cache.maximumSize }}
        }
      }
      trieDiffLog = {
        model.store = {
          deep.store.fs.schema = {{ .Values.trieDiffLog.modelStore.deepStoreScheme }}
          {{- if eq $.Values.trieDiffLog.modelStore.deepStoreScheme "file" }}
          directory = {{ printf "%s/%s/customers" $.Values.modelStoreNFSMountPath $.Values.global.env | quote }}
          {{- end }}
          {{- if eq $.Values.trieDiffLog.modelStore.deepStoreScheme "gs" }}
          gcs.bucket.name = {{ printf "%s-%s" $.Values.bucketPrefix $.Values.global.env | quote }}
          gcs.key.file = "/accounts/key.json"
          directory = {{ $.Values.deepStoreFilePath | quote }}
          {{- end }}
          {{- if eq $.Values.trieDiffLog.modelStore.deepStoreScheme "s3" }}
          directory = {{ $.Values.deepStoreFilePath | quote }}
          s3.bucket.name = {{ $.Values.s3BucketName | quote }}
          s3.config = {
            {{- range $k, $v := $.Values.s3Config }}
            {{ $k }} = {{ $v | quote }}
            {{- end }}
          }
          {{- end }}
        }
        diff.logs.retention.period = {{ .Values.trieDiffLog.trieDiffLogsRetentionPeriod }}
        cache = {
          refreshAfterWriteDuration = {{ .Values.trieDiffLog.cache.refreshAfterWriteDuration }}
          expireAfterWriteDuration = {{ .Values.trieDiffLog.cache.expireAfterWriteDuration }}
          maximumSize = {{ .Values.trieDiffLog.cache.maximumSize }}
        }
      }
      entity.fetcher = {
        cache = {
          refreshAfterWriteDuration = {{ .Values.entityFetcher.cache.refreshAfterWriteDuration }}
          expireAfterWriteDuration = {{ .Values.entityFetcher.cache.expireAfterWriteDuration }}
          maximumSize = {{ .Values.entityFetcher.cache.maximumSize }}
          delegate = {
            refreshAfterWriteDuration = {{ .Values.entityFetcher.cache.delegate.refreshAfterWriteDuration }}
            expireAfterWriteDuration = {{ .Values.entityFetcher.cache.delegate.expireAfterWriteDuration }}
            maximumSize = {{ .Values.entityFetcher.cache.delegate.maximumSize }}
          }
        }
      }
      customRules = {
        cache = {
          refreshAfterWriteDuration = {{ .Values.apiNamingCustomRules.cache.refreshAfterWriteDuration }}
          expireAfterWriteDuration = {{ .Values.apiNamingCustomRules.cache.expireAfterWriteDuration }}
          maximumSize = {{ .Values.apiNamingCustomRules.cache.maximumSize }}
        }
      }
      configs = {
        cache = {
          refreshAfterWriteDuration = {{ .Values.apiNamingConfigs.cache.refreshAfterWriteDuration }}
          expireAfterWriteDuration = {{ .Values.apiNamingConfigs.cache.expireAfterWriteDuration }}
          maximumSize = {{ .Values.apiNamingConfigs.cache.maximumSize }}
        }
      }
    }
    feature.flag.service.config = {
      host = {{ .Values.traceableConfigServiceConfig.featureFlagServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.featureFlagServiceConfig.port }}
      request.timeout = {{ .Values.traceableConfigServiceConfig.featureFlagServiceConfig.request.timeout }}
      cache {
        refresh.duration = {{ .Values.traceableConfigServiceConfig.featureFlagServiceConfig.cache.refresh.duration }}
        expiration.duration = {{ .Values.traceableConfigServiceConfig.featureFlagServiceConfig.cache.expiration.duration }}
        thread.pool.size = {{ .Values.traceableConfigServiceConfig.featureFlagServiceConfig.cache.thread.pool.size }}
      }
    }
    anomaly.config.service = {
      include "anomaly.conf"
    }
    risk.config.service = {
      include "risk.conf"
    }
    local.processing.config.service = {
      include "span-processing-rules.conf"
    }
    span.processing.config.service = {
      {{- if hasKey .Values.traceableConfigServiceConfig "spanProcessingConfigServiceConfig" }}
      sampling.config {
        rate.limit.config = {
          traceLimitPerEndpoint = {
            {{- if hasKey $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitPerEndpoint "fixedWindowLimit" }}
            fixedWindowLimit = {
              {{- if hasKey $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitPerEndpoint.fixedWindowLimit "quantityAllowed" }}
              quantityAllowed = {{ $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitPerEndpoint.fixedWindowLimit.quantityAllowed }}
              {{- end }}
              {{- if hasKey $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitPerEndpoint.fixedWindowLimit "windowDuration" }}
              windowDuration = {{ $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitPerEndpoint.fixedWindowLimit.windowDuration }}
              {{- end }}
            }
            {{- end }}
          }
          traceLimitGlobal = {
            {{- if hasKey $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitGlobal "fixedWindowLimit" }}
            fixedWindowLimit = {
              {{- if hasKey $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitGlobal.fixedWindowLimit "quantityAllowed" }}
              quantityAllowed = {{ $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitGlobal.fixedWindowLimit.quantityAllowed }}
              {{- end }}
              {{- if hasKey $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitGlobal.fixedWindowLimit "windowDuration" }}
              windowDuration = {{ $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.traceLimitGlobal.fixedWindowLimit.windowDuration }}
              {{- end }}
            }
            {{- end }}
          }
          apiEndpointCacheDuration = {{ $.Values.traceableConfigServiceConfig.spanProcessingConfigServiceConfig.samplingConfig.rateLimitConfig.apiEndpointCacheDuration }}
        }
      }
      {{- end }}
    }
    label.application.rule.config.service {
      max.dynamic.label.application.rules.per.tenant = {{ int .Values.traceableConfigServiceConfig.labelApplicationRuleConfigServiceConfig.maxDynamicLabelApplicationRulesPerTenant }}
    }
    local.api.naming.config = {
      {{- if hasKey $.Values.localApiNamingConfig "fullTrieReloadConfig" }}
      full.trie.reload.config = {
        {{- range $k,$v := $.Values.localApiNamingConfig.fullTrieReloadConfig }}
          {{- if eq $k "default" }}
          default = {
            disabled = {{ $.Values.localApiNamingConfig.fullTrieReloadConfig.default.disabled }}
            version = {{ $.Values.localApiNamingConfig.fullTrieReloadConfig.default.version | quote }}
          }
          {{- else }}
          {{ $k }} = {
            {{- range $sk,$sv := $v }}
              {{ $sk }} = {
                disabled = {{ $sv.disabled }}
                version = {{ $sv.version | quote}}
              }
            {{- end }}
          }
          {{- end }}
        {{- end }}
      }
      {{- end }}
    }
  anomaly.conf: |-
    global {
      disabled = {{ .Values.anomalyConfigServiceConfig.global.disabled }}
      internal = {{ .Values.anomalyConfigServiceConfig.global.internal }}
      licenseTiers = {{ .Values.anomalyConfigServiceConfig.global.licenseTiers | nindent 6 }}
    }
  risk.conf: |-
    {{- if hasKey .Values "riskConfigServiceConfig" }}
      {{- if hasKey .Values.riskConfigServiceConfig "riskLevelConfigValues" }}
        riskLevelConfigValues = {{ .Values.riskConfigServiceConfig.riskLevelConfigValues | nindent 2 }}
      {{- end }}
      {{- if hasKey .Values.riskConfigServiceConfig "riskFactorGridConfigValues" }}
        riskFactorGridConfigValues = {{ .Values.riskConfigServiceConfig.riskFactorGridConfigValues | nindent 2 }}
      {{- end }}
    {{- end }}