apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.traceableConfigServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    service.port.internal = {{ .Values.internalContainerPort }}
    service.port.external = {{ .Values.externalContainerPort }}
    service.admin.port = {{ .Values.containerAdminPort }}
    generic.config.service {
      publish.change.events = {{ .Values.traceableConfigServiceConfig.publishChangeEvents }}
      document.store {
        {{- $dst := .Values.traceableConfigServiceConfig.dataStoreType }}
        dataStoreType = {{ $dst }}
        {{ $dst }} {
          {{- range $key, $value := (index .Values "traceableConfigServiceConfig" (printf "%s" $dst)) }}
          {{- if $value }}
          {{ $key }} = {{ $value | quote }}
          {{- end }}
          {{- end }}
        }
      }
    }
    event.store {
      type = kafka
      bootstrap.servers = "bootstrap:9092"
      activity.events.producer {
        bootstrap.servers = "bootstrap:9092"
        schema.registry.url = "http://schema-registry-service:8081"
      }
      config.change.events.producer {
        bootstrap.servers = "bootstrap:9092"
        schema.registry.url = "http://schema-registry-service:8081"
      }
    }
    {{- if hasKey .Values.traceableConfigServiceConfig "defaultPiiFilterConfig" }}
    sensitive.data.config.service {
      default.pii.filter.config {
        {{- .Values.traceableConfigServiceConfig.defaultPiiFilterConfig | nindent 8 }}
      }
    }
    {{- end }}
    insights.service.config = {
      host = {{ .Values.traceableConfigServiceConfig.insightsServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.insightsServiceConfig.port }}
    }
    entity.service.config = {
      host = {{ .Values.traceableConfigServiceConfig.entityServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.entityServiceConfig.port }}
    }
    license.metering.service = {
      host = {{ .Values.traceableConfigServiceConfig.licenseMeteringServiceConfig.host }}
      port = {{ .Values.traceableConfigServiceConfig.licenseMeteringServiceConfig.port }}
      cache.expiry.duration = {{ .Values.traceableConfigServiceConfig.licenseMeteringServiceConfig.cacheExpiryDuration }}
    }
    anomaly.config.service = {
      include "anomaly.conf"
    }
    risk.config.service = {
      include "risk.conf"
    }
    label.application.rule.config.service {
      max.dynamic.label.application.rules.per.tenant = {{ int .Values.traceableConfigServiceConfig.labelApplicationRuleConfigServiceConfig.maxDynamicLabelApplicationRulesPerTenant }}
    }
  anomaly.conf: |-
    global {
      disabled = {{ .Values.anomalyConfigServiceConfig.global.disabled }}
      internal = {{ .Values.anomalyConfigServiceConfig.global.internal }}
      licenseTiers = {{ .Values.anomalyConfigServiceConfig.global.licenseTiers | nindent 6 }}
    }
    detector.config.service {
      modsecDetectionConfigs = {{ .Values.anomalyConfigServiceConfig.detectorConfigService.modsecDetectionConfigs | nindent 6 }}
      apiDefinitionDetectionConfigs = {{ .Values.anomalyConfigServiceConfig.detectorConfigService.apiDefinitionDetectionConfigs | nindent 6 }}
    }
  risk.conf: |-
    {{- if hasKey .Values "riskConfigServiceConfig" }}
      {{- if hasKey .Values.riskConfigServiceConfig "riskLevelConfigValues" }}
        riskLevelConfigValues = {{ .Values.riskConfigServiceConfig.riskLevelConfigValues | nindent 2 }}
      {{- end }}
      {{- if hasKey .Values.riskConfigServiceConfig "riskFactorGridConfigValues" }}
        riskFactorGridConfigValues = {{ .Values.riskConfigServiceConfig.riskFactorGridConfigValues | nindent 2 }}
      {{- end }}
    {{- end }}