traceableCategorizedBots = [
  {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "categorizedBotDetails": {
      "name": "Bing bot",
      "description": "Bingbot is Microsoft's web crawler responsible for indexing content for Bing Search.",
      "categorizedBotSignatureRule": {
        "matchCondition": {
            "logicalMatchCondition": {
              "operator": "LOGICAL_MATCH_OPERATOR_AND",
              "leftOperand": {
                "ipMetadataMatchCondition": {
                  "ipAddressCondition": {
                    "ipv4CidrIpRanges": [
                      "13.66.139.0/24",
                      "40.77.167.0/24"
                    ],
                    "ipv6CidrIpRanges": []
                  }
                }
              },
              "rightOperand": {
                "genericMatchCondition": {
                  "keyCondition": {
                    "keyType": "KEY_TYPE_HEADER",
                    "key_match_operator": {
                      "matchOperator": "MATCH_OPERATOR_EQUALS",
                      "matchValue": "User-Agent"
                    }
                  },
                  "valueMatchCondition": {
                    "matchOperator": "MATCH_OPERATOR_EQUALS",
                    "matchValue": "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
                  }
                }
              }
            }
          }
      },
      "botCategory": "CRAWLERS",
      "botSubCategory": "SEARCH_BOTS"
    }
  }
]