aiAppProtectionRules = [
  {
    id = "30e096e2-cb17-4a98-839e-0e0eda1852cc"
    data = {
      category = CATEGORY_AI_APP_PROTECTION
      name = "Default: Spike in AI Calls"
      description = "Spike in AI Calls"
      enabled = false
      labels = {
        "threatTypeId" : "llmRateLimiting"
      }
      ruleEvaluationPoints = [RULE_EVALUATION_POINT_PLATFORM]
      condition = {
        compositeCondition = {
          operator = LOGICAL_OPERATOR_AND
          children = [
            {
              leafCondition = {
                keyValueCondition = {
                  type = TYPE_TAG
                  keyCondition = {
                    operator = MATCH_OPERATOR_EQUALS
                    value = "GENAI_MODELS"
                  }
                }
              }
            },
            {
              leafCondition = {
                keyValueCondition = {
                  type = TYPE_TAG
                  keyCondition = {
                    operator = MATCH_OPERATOR_EQUALS
                    value = "GENAI_PROVIDERS"
                  }
                }
              }
            }
          ]
        }
      }
      thresholdActionConfigs = [
        {
          resourceAccessThresholdConfigs = [
            {
              userAggregateType = USER_AGGREGATE_TYPE_PER_USER
              apiAggregateType = API_AGGREGATE_TYPE_PER_ENDPOINT
              rollingWindowThresholdConfig = {
                countAllowed = 100
                durationIso = "PT1M"
              }
            }
          ]
          actions = [
            {
              alert = {
                eventSeverity = EVENT_SEVERITY_LOW
              }
            }
          ]
        }
      ]
      ruleStatus = {
        ruleCreationSource = RULE_SOURCE_DEFAULT
        internal = true
      }
    }
  },
  {
    id = "d1afe0dd-ba4b-4e81-854e-5bdc3fa466eb"
    data = {
      category = CATEGORY_AI_APP_PROTECTION
      name = "Default: PII Data in Prompt"
      description = "PII Data in Prompt"
      enabled = false
      labels = {
        "threatTypeId" : "piiDetectedInPrompt"
      }
      ruleEvaluationPoints = [RULE_EVALUATION_POINT_PLATFORM]
      transactionActionConfig = {
        action = {
          alert = {
            eventSeverity = EVENT_SEVERITY_LOW
          }
        }
      }
      condition = {
        compositeCondition = {
          operator = LOGICAL_OPERATOR_AND
          children = [
            {
              leafCondition = {
                datatypeCondition = {
                  dataLocation = DATA_LOCATION_REQUEST
                  # data-sets - PCI DSS (in scope), PCI DSS (open), PII USA, PII Canada, PII India, PII UK, PII International
                  datasetIds = [
                    "a1618a61-84ae-5afd-634c-bca2047f70f4",
                    "c51ba5e0-3f25-3517-ee0a-5b65c16eec9d",
                    "c1dce7a9-4dda-ebe6-fbd0-c6a57b0539e2",
                    "5c2433d7-9a2c-44db-8365-7a5e0da34e8d"
                    "f3baab5c-2994-d22c-4fa2-7119adb26371",
                    "1f1458ab-c59b-a4be-8091-e80362de24a9",
                    "85d6fbc0-ee36-4b5b-93c8-56dfc5ab40a7",
                  ]
                }
              }
            }
          ]
        }
      }
      ruleStatus = {
        ruleCreationSource = RULE_SOURCE_DEFAULT
        internal = true
      }
    }
  }
]