rateLimitingRules = [
  {
    id = "8b6542e3-e776-4430-8578-818bd59357c3"
    data = {
      category = CATEGORY_RATE_LIMITING
      name = "Default: Potential Access Rate Violation due to High Error Rate"
      description = "High Error Rate detected which may mean potential Access Rate Violation"
      enabled = false
      labels = {
        "OWASP_API_2023" : "API4"
        "CWE" : "285"
      }
      condition = {
        compositeCondition = {
          operator = LOGICAL_OPERATOR_AND
          children = [
            {
              leafCondition = {
                keyValueCondition = {
                  type = TYPE_STATUS_CODE
                  valueCondition = {
                    operator = MATCH_OPERATOR_MATCHES_REGEX
                    value = "^(4|5)"
                  }
                }
              }
            },
            {
              leafCondition = {
                keyValueCondition = {
                  type = TYPE_TAG
                  keyCondition = {
                    operator = MATCH_OPERATOR_EQUALS
                    value = "span.kind"
                  }
                  valueCondition = {
                    operator = MATCH_OPERATOR_EQUALS
                    value = "server"
                  }
                }
              }
            }
          ]
        }
      }
      thresholdActionConfigs = [
        {
          resourceAccessThresholdConfigs = [
            {
              userAggregateType = USER_AGGREGATE_TYPE_PER_USER
              apiAggregateType = API_AGGREGATE_TYPE_PER_ENDPOINT
              rollingWindowThresholdConfig = {
                countAllowed = 25
                durationIso = "PT300S"
              }
            }
          ]
          actions = [
            {
              alert = {
                eventSeverity = EVENT_SEVERITY_MEDIUM
              }
            }
          ]
        }
      ]
      ruleStatus = {
        ruleCreationSource = RULE_SOURCE_DEFAULT
      }
    }
  },
  {
    id = "468a6645-2438-4268-89b3-d0ed93438d28"
    data = {
      category = CATEGORY_RATE_LIMITING
      name = "Default: DDoS Rate Limit Violation"
      description = "High access rate detected which may result in denial of service"
      enabled = false
      condition = {
        compositeCondition = {
          operator = LOGICAL_OPERATOR_AND
          children = [
            {
              leafCondition = {
                ipAddressCondition = {
                  ipAddressConditionType = IP_ADDRESS_CONDITION_TYPE_ALL_EXTERNAL
                }
              }
            }
          ]
        }
      }
      thresholdActionConfigs = [
        {
          resourceAccessThresholdConfigs = [
            {
              userAggregateType = USER_AGGREGATE_TYPE_ACROSS_USERS
              apiAggregateType = API_AGGREGATE_TYPE_ACROSS_ENDPOINTS
              rollingWindowThresholdConfig = {
                countAllowed = 60000
                durationIso = "PT60S"
              }
            }
          ]
          actions = [
            {
              block = {
                eventSeverity = EVENT_SEVERITY_MEDIUM
                useThresholdDuration = true
              }
            }
          ]
        }
      ]
      ruleStatus = {
        ruleCreationSource = RULE_SOURCE_DEFAULT
      }
    }
  }
]