syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.global;

option java_multiple_files = true;

import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";

message UpdateAnomalyGlobalConfigStatusRequest  {
  option deprecated = true;
  AnomalyConfigScope config_scope = 1;
  AnomalyConfigStatusChange config_status = 2;
}

message UpdateAnomalyGlobalConfigStatusResponse {
  option deprecated = true;
  AnomalyConfigStatusChange config_status = 1;
}

message GetAnomalyGlobalConfigStatusRequest {
  option deprecated = true;
  AnomalyConfigScope config_scope = 1;
}

message GetAnomalyGlobalConfigStatusResponse {
  option deprecated = true;
  AnomalyConfigStatus config_status = 1;
}

message UpdateScopedAnomalyGlobalConfigStatusRequest {
  ScopedAnomalyConfigStatusChange scoped_config = 1;
}

message UpdateScopedAnomalyGlobalConfigStatusResponse {
  ScopedAnomalyConfigStatusChange scoped_config = 1;
}

message GetScopedAnomalyGlobalConfigStatusRequest {
  AnomalyConfigScope config_scope = 1;
}

message GetScopedAnomalyGlobalConfigStatusResponse {
  ScopedAnomalyConfigStatus scoped_config = 1;
}

message GetAllScopedAnomalyGlobalConfigStatusRequest {
}

message GetAllScopedAnomalyGlobalConfigStatusResponse {
  repeated ScopedAnomalyConfigStatus scoped_configs = 1;
}

message GetAnomalyRuleInfosRequest {
  repeated AnomalyEventFamily event_families = 1;
}

message GetAnomalyRuleInfosResponse {
  repeated AnomalyRuleInfo rule_infos = 1;
}

message ScopedAnomalyConfigStatus {
  AnomalyConfigScope config_scope = 1;
  AnomalyConfigStatus config_status = 2;
  ExcludedEventsGenerationConfig excluded_events_config = 3;
  AnomalyConfidenceLevel min_confidence_level = 4;
}

// any addition here requires update in ScopedGlobalConfigStatusChangeConverter logic
message ScopedAnomalyConfigStatusChange {
  AnomalyConfigScope config_scope = 1;
  AnomalyConfigStatusChange config_status = 2;
  ExcludedEventsGenerationConfig excluded_events_config = 3;
  optional AnomalyConfidenceLevel min_confidence_level = 4;
}

message ExcludedEventsGenerationConfig {
  oneof config {
    bool enabled_for_all = 1;
    StringList exclusion_rule_ids = 2;
  }
}
