syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.global;

import "ai/traceable/anomaly/config/service/v1/global/anomaly_global_config.proto";

option java_multiple_files = true;

service AnomalyGlobalConfigService {
  rpc GetScopedAnomalyGlobalConfigStatus(GetScopedAnomalyGlobalConfigStatusRequest) returns (GetScopedAnomalyGlobalConfigStatusResponse) {}

  rpc GetAllScopedAnomalyGlobalConfigStatus(GetAllScopedAnomalyGlobalConfigStatusRequest) returns (GetAllScopedAnomalyGlobalConfigStatusResponse) {}

  rpc GetUnresolvedScopedAnomalyGlobalConfigStatus(GetUnresolvedScopedAnomalyGlobalConfigStatusRequest) returns (GetUnresolvedScopedAnomalyGlobalConfigStatusResponse) {}

  rpc GetAllUnresolvedScopedAnomalyGlobalConfigStatus(GetAllUnresolvedScopedAnomalyGlobalConfigStatusRequest) returns (GetAllUnresolvedScopedAnomalyGlobalConfigStatusResponse) {}

  rpc UpdateScopedAnomalyGlobalConfigStatus(UpdateScopedAnomalyGlobalConfigStatusRequest) returns (UpdateScopedAnomalyGlobalConfigStatusResponse) {}

  // tenant-agnostic
  rpc GetAnomalyRuleInfos(GetAnomalyRuleInfosRequest) returns (GetAnomalyRuleInfosResponse) {}

  rpc GetAvailableRuleVersions(GetAvailableRuleVersionsRequest) returns (GetAvailableRuleVersionsResponse) {}

  rpc GetRulesChangeLog(GetRulesChangeLogRequest) returns (GetRulesChangeLogResponse) {}

  rpc GetChangeLogDoc(GetChangeLogDocRequest) returns (GetChangeLogDocResponse) {}

  rpc DeleteScopedAnomalyGlobalConfigStatus(DeleteScopedAnomalyGlobalConfigStatusRequest) returns (DeleteScopedAnomalyGlobalConfigStatusResponse) {}

  rpc DeleteRuleVersionConfigType(DeleteRuleVersionConfigTypeRequest) returns (DeleteRuleVersionConfigTypeResponse) {}
}
