syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.global;

import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";
import "ai/traceable/anomaly/config/service/v1/enum_extension.proto";
import "ai/traceable/anomaly/config/service/v1/modsec/anomaly_modsec_config.proto";

option java_multiple_files = true;

message UpdateScopedAnomalyGlobalConfigStatusRequest {
  ScopedAnomalyConfigStatusChange scoped_config = 1;
}

message UpdateScopedAnomalyGlobalConfigStatusResponse {
  ScopedAnomalyConfigStatusChange scoped_config = 1;
}

message GetScopedAnomalyGlobalConfigStatusRequest {
  AnomalyConfigScope config_scope = 1;
}

message GetScopedAnomalyGlobalConfigStatusResponse {
  ScopedAnomalyConfigStatus scoped_config = 1;
}

message GetUnresolvedScopedAnomalyGlobalConfigStatusRequest {
  AnomalyConfigScope config_scope = 1;
}

message GetUnresolvedScopedAnomalyGlobalConfigStatusResponse {
  ScopedAnomalyConfigStatusChange scoped_config = 1;
}

message GetAllScopedAnomalyGlobalConfigStatusRequest {
  GetAllAnomalyGlobalConfigStatusFilter filter = 1;
}

message GetAllScopedAnomalyGlobalConfigStatusResponse {
  repeated ScopedAnomalyConfigStatus scoped_configs = 1;
}

message GetAllUnresolvedScopedAnomalyGlobalConfigStatusRequest {
  GetAllAnomalyGlobalConfigStatusFilter filter = 1;
}

message GetAllUnresolvedScopedAnomalyGlobalConfigStatusResponse {
  repeated ScopedAnomalyConfigStatusChange scoped_configs = 1;
}

message GetAnomalyRuleInfosRequest {
  repeated AnomalyEventFamily event_families = 1;
  optional ai.traceable.anomaly.config.service.v1.modsec.ModsecRuleVersion modsec_rule_version = 2;
  bool use_test_modsec_rules = 3;
  RuleVersion version = 4;
}

message GetAnomalyRuleInfosResponse {
  repeated AnomalyRuleInfo rule_infos = 1;
}

message GetAvailableRuleVersionsRequest {
  RuleType rule_type = 1;
  AvailableRuleVersionsFilter filter = 2;
}

message GetAvailableRuleVersionsResponse {
  AvailableRuleVersions supported_versions = 1;
}

message GetRulesChangeLogRequest {
  RuleType rule_type = 1;
  RuleVersion current_version = 2;
  RuleVersion previous_version = 3;
}

message GetRulesChangeLogResponse {
  RulesChangeLog rules_change_log = 1;
}

message GetAllAnomalyGlobalConfigStatusFilter {
  repeated AnomalyConfigScope applicable_scopes = 1;
}

message ScopedAnomalyConfigStatus {
  AnomalyConfigScope config_scope = 1;
  AnomalyConfigStatus config_status = 2 [deprecated = true];
  ExcludedEventsGenerationConfig excluded_events_config = 3 [deprecated = true];
  AnomalyConfidenceLevel min_confidence_level = 4 [deprecated = true];
  bool enabled_for_exit_spans = 5 [deprecated = true];
  ModsecGlobalConfig modsec_global_config = 6 [deprecated = true];
  ApiGlobalConfig api_global_config = 7 [deprecated = true];
  GlobalModsecConfig global_modsec_config = 8;
  GlobalApiConfig global_api_config = 9;
}

// any addition here requires update in ScopedGlobalConfigStatusChangeConverter logic
message ScopedAnomalyConfigStatusChange {
  AnomalyConfigScope config_scope = 1;
  AnomalyConfigStatusChange config_status = 2 [deprecated = true];
  ExcludedEventsGenerationConfig excluded_events_config = 3 [deprecated = true];
  optional AnomalyConfidenceLevel min_confidence_level = 4 [deprecated = true];
  optional bool enabled_for_exit_spans = 5 [deprecated = true];
  ModsecGlobalConfig modsec_global_config = 6 [deprecated = true];
  ApiGlobalConfig api_global_config = 7 [deprecated = true];
  GlobalModsecConfigChange global_modsec_config_change = 8;
  GlobalApiConfigChange global_api_config_change = 9;
}

message GlobalModsecConfigChange {
  optional bool blocking_available_for_regular_rules = 1;
  optional bool use_test_rules = 2;
  optional bool disabled = 3;
  ModsecDefaultConfigsType default_configs_type = 4;
  AnomalyConfidenceLevel min_confidence_level = 5;
  optional bool enabled_for_exit_spans = 6;
  ModsecEvaluationEngineConfig modsec_evaluation_engine_config = 7;
  RuleVersion stable_version = 8;
  RuleVersion override_version = 9;
}

message GlobalModsecConfig {
  bool blocking_available_for_regular_rules = 1;
  bool use_test_rules = 2;
  bool disabled = 3;
  ModsecDefaultConfigsType default_configs_type = 4;
  AnomalyConfidenceLevel min_confidence_level = 5;
  bool enabled_for_exit_spans = 6;
  ModsecEvaluationEngineConfig modsec_evaluation_engine_config = 7;
  RuleVersionData rule_version_data = 8;
}

message GlobalApiConfigChange {
  optional bool disabled = 1;
  ApiDefaultConfigsType default_configs_type = 2;
  optional bool enabled_for_exit_spans = 3;
  RuleVersion stable_version = 4;
  RuleVersion override_version = 5;
}

message GlobalApiConfig {
  bool disabled = 1;
  ApiDefaultConfigsType default_configs_type = 2;
  bool enabled_for_exit_spans = 3;
  RuleVersionData rule_version_data = 4;
}

enum CorazaEngineVersion {
  CORAZA_ENGINE_VERSION_UNSPECIFIED = 0;
  CORAZA_ENGINE_VERSION_LATEST_STABLE = 1;
  CORAZA_ENGINE_VERSION_LATEST_TEST = 2;
}

message ModsecEvaluationEngineConfig {
  CorazaEngineVersion coraza_engine_version = 1;
}

message RulesChangeLog {
  RuleType rule_type = 1;
  RuleVersionUpdateDetails version_updated = 2;
  repeated ThreatTypeChange threat_type_changes = 3;
  repeated ThreatRuleChange rule_changes = 4;
}

message RuleVersionUpdateDetails {
  RuleVersion old_version = 1;
  RuleVersion new_version = 2;
}

message ThreatTypeChange {
  oneof change {
    StringList threat_type_ids_removed = 1;
    StringList threat_type_ids_added = 2;
    ThreatTypeUpdateDetails threat_type_updated = 3;
  }
}

message ThreatRuleChange {
  oneof change {
    StringList rule_ids_removed = 1;
    StringList rule_ids_added = 2;
    ThreatRuleUpdateDetails rule_updated = 3;
  }
}

message ThreatTypeUpdateDetails {
  string threat_type_id = 1;
  repeated ThreatTypeUpdate updates = 2;
  message ThreatTypeUpdate {
    oneof update {
      StringValueUpdate name_updated = 1;
    }
  }
}

message ThreatRuleUpdateDetails {
  string rule_id = 1;
  repeated ThreatRuleUpdate updates = 2;
  message ThreatRuleUpdate {
    oneof update {
      StringValueUpdate name_updated = 1;
      StringValueUpdate threat_type_id_updated = 2;
      bool signature_updated = 3;
      StringValueUpdate rule_type_updated = 4;
      StringValueUpdate severity_updated = 5;
      StringKeyValueUpdate threat_label_updated = 6;
    }
  }
}

message StringValueUpdate {
  string old_value = 1;
  string new_value = 2;
}

message StringKeyValueUpdate {
  string key = 1;
  oneof update {
    bool key_removed = 2;
    string value_added = 3;
    StringValueUpdate value_updated = 4;
  }
}

// deprecated
message ModsecGlobalConfig {
  option deprecated = true;
  optional bool blocking_available_for_regular_rules = 1;
  optional bool use_test_rules = 2;
  optional bool disabled = 3;
  ModsecDefaultConfigsType default_configs_type = 4;
  AnomalyConfidenceLevel min_confidence_level = 5;
  optional bool enabled_for_exit_spans = 6;
  ModsecEvaluationEngineConfig modsec_evaluation_engine_config = 7;
}

enum ModsecDefaultConfigsType {
  MODSEC_DEFAULT_CONFIGS_TYPE_UNSPECIFIED = 0;
  MODSEC_DEFAULT_CONFIGS_TYPE_DEFAULT_ENABLED = 1 [deprecated = true];
  MODSEC_DEFAULT_CONFIGS_TYPE_AGGRESSIVE_DISABLED = 2 [deprecated = true];
  MODSEC_DEFAULT_CONFIGS_TYPE_RECOMMENDED = 3 [deprecated = true]; // Aggressive disabled, rest blocking
  MODSEC_DEFAULT_CONFIGS_TYPE_STRICT = 4 [deprecated = true]; // Aggressive monitor, rest blocking
  MODSEC_DEFAULT_CONFIGS_TYPE_STANDARD = 5 [deprecated = true]; // Aggressive disabled, rest monitor
  MODSEC_DEFAULT_CONFIGS_TYPE_ALL_MONITOR = 6 [deprecated = true];
  MODSEC_DEFAULT_CONFIGS_TYPE_STANDARD_MONITORING = 7 [(string_value) = "Standard Profile - Monitoring Mode"]; // Aggressive disabled, rest monitor
  MODSEC_DEFAULT_CONFIGS_TYPE_STANDARD_BLOCKING = 8 [(string_value) = "Standard Profile - Blocking Mode"]; // Aggressive disabled, rest blocking
  MODSEC_DEFAULT_CONFIGS_TYPE_STRICT_MONITORING = 9 [(string_value) = "Strict Profile - Monitoring Mode"]; // Aggressive monitor, rest monitor
  MODSEC_DEFAULT_CONFIGS_TYPE_STRICT_BLOCKING = 10 [(string_value) = "Strict Profile - Blocking Mode"]; // Aggressive monitor, rest blocking
  MODSEC_DEFAULT_CONFIGS_TYPE_ALL_ENVIRONMENT = 11 [(string_value) = "Inherit Policy from All Environments"];
}

message AvailableRuleVersionsFilter {
  repeated RuleVersionType version_types = 1;
}

message AvailableRuleVersions {
  RuleType rule_type = 1;
  repeated RuleVersion versions = 2;
}

// deprecated
message ApiGlobalConfig {
  option deprecated = true;
  optional bool disabled = 1;
  ApiDefaultConfigsType default_configs_type = 2;
  optional bool enabled_for_exit_spans = 3;
}

enum ApiDefaultConfigsType {
  API_DEFAULT_CONFIGS_TYPE_UNSPECIFIED = 0;
  API_DEFAULT_CONFIGS_TYPE_ONLY_API_DEF_ENABLED = 1;
}

message ExcludedEventsGenerationConfig {
  oneof config {
    bool enabled_for_all = 1;
    StringList exclusion_rule_ids = 2;
  }
}

message DeleteScopedAnomalyGlobalConfigStatusRequest {
  AnomalyConfigScope config_scope = 1;
}

message DeleteScopedAnomalyGlobalConfigStatusResponse {}
