syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.global;

option java_multiple_files = true;

import "ai/traceable/anomaly/config/service/v1/global/anomaly_global_config.proto";


service AnomalyGlobalConfigService {

  rpc GetAnomalyGlobalConfigStatus (GetAnomalyGlobalConfigStatusRequest) returns (GetAnomalyGlobalConfigStatusResponse) {
  }

  rpc UpdateAnomalyGlobalConfigStatus (UpdateAnomalyGlobalConfigStatusRequest) returns (UpdateAnomalyGlobalConfigStatusResponse) {
  }

  rpc GetAnomalyRuleInfos (GetAnomalyRuleInfosRequest) returns (GetAnomalyRuleInfosResponse) {
  }
}
