package ai.traceable.customsignature.config.service.modsec.registry;

public enum ModsecVariables {
  REQUEST_URI_RAW,
  REQUEST_METHOD,
  REQUEST_HEADERS_NAMES,
  REQUEST_HEADERS,
  ARGS_NAMES,
  ARGS,
  ARGS_GET_NAMES,
  ARGS_GET,
  ARGS_POST_NAMES,
  ARGS_POST,
  REQUEST_BODY,
  RESPONSE_STATUS,
  RESPONSE_HEADERS,
  RESPONSE_HEADERS_NAMES,
  RESPONSE_BODY,
  REQUEST_COOKIES,
  REQUEST_COOKIES_NAMES
}
