syntax = "proto3";

package ai.traceable.edge.bot.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/edge/bot/config/service/v1/captcha_site_key_config.proto";
import "ai/traceable/policy/config/service/v1/client_bot_fingerprint_policy.proto";

service CaptchaSiteKeyConfigService {
  rpc Upsert(UpsertRequest) returns (UpsertResponse) {}
  rpc Get(GetRequest) returns (GetResponse) {}
  rpc GetAll(GetAllRequest) returns (GetAllResponse) {}
  rpc Delete(DeleteRequest) returns (DeleteResponse) {}
}

message UpsertRequest {
  ai.traceable.edge.bot.config.service.v1.CaptchaSiteKeyConfig config = 1;
}

message UpsertResponse {
  ai.traceable.edge.bot.config.service.v1.CaptchaSiteKeyConfig config = 1;
}

message GetRequest {
  string id = 1;
}

message GetResponse {
  ai.traceable.edge.bot.config.service.v1.CaptchaSiteKeyConfig config = 1;
}

message GetAllRequest {}

message GetAllResponse {
  repeated ai.traceable.edge.bot.config.service.v1.CaptchaSiteKeyConfig configs = 1;
}

message DeleteRequest {
  string id = 1;
}

message DeleteResponse {
  ai.traceable.edge.bot.config.service.v1.CaptchaSiteKeyConfig deleted_config = 1;
}
