syntax = "proto3";

package ai.traceable.integration.config.service.wiz.v1;

option java_multiple_files = true;

message WizIntegration {
  string id = 1;
  EncryptedText client_secret = 2;
  WizIntegrationInfo info = 3;
}

message WizIntegrationSummary {
  string id = 1;
  WizIntegrationInfo info = 2;
}

message EncryptedText {
  string key_id = 1;
  string value = 2;
}

message WizIntegrationInfo {
  string name = 1;
  string description = 2;
  string client_id = 3;
  string token_url = 4;
  string api_endpoint_url = 5;
  WizIntegrationPreferences wiz_integration_preferences = 6;
}

message WizIntegrationPreferences {
  WizIssuePullConfiguration wiz_issue_pull_configuration = 1;
  WizEventPushConfiguration wiz_event_push_configuration = 2;
}

message WizIssuePullConfiguration {
  bool enabled = 1;
}

message WizEventPushConfiguration {
  bool enabled = 1;
  string wiz_integration_id = 2 [deprecated = true];
}
