syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.exclusion;

import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";

option java_multiple_files = true;

message CreateAnomalyExclusionRuleRequest {
  AnomalyExclusionRuleData rule_data = 1;
}

message CreateAnomalyExclusionRuleResponse {
  AnomalyExclusionRuleConfig config = 1;
}

message GetAnomalyExclusionRulesRequest {
  GetRulesFilter filter = 1;
}

message GetRulesFilter {
  repeated string rule_ids = 1;
  repeated string event_type_ids = 2;
  repeated AnomalyEventFamily event_families = 3;
  repeated string anomaly_actor_ids = 4;
  AnomalyConfigScope anomaly_config_scope = 5;
}

message GetAnomalyExclusionRulesResponse {
  repeated AnomalyExclusionRuleConfig configs = 1;
}

message UpdateAnomalyExclusionRuleRequest {
  string rule_id = 1;
  string name = 2;
  string description = 3;
  AnomalyConfigStatus config_status = 4;
}

message UpdateAnomalyExclusionRuleResponse {
  AnomalyExclusionRuleConfig config = 1;
}

message DeleteAnomalyExclusionRuleRequest {
  string rule_id = 1;
}

message DeleteAnomalyExclusionRuleResponse {}

message AnomalyExclusionRuleConfig {
  string id = 1;
  AnomalyExclusionRuleData rule_data = 2;
  AnomalyConfigStatus config_status = 3;
}

message AnomalyExclusionRuleData {
  string name = 1;
  string description = 2;
  EventExclusionInfo event_exclusion_info = 3;
  AnomalyActorExclusionInfo anomaly_actor_exclusion_info = 4;
  AnomalyConfigScope anomaly_config_scope = 5;
  AnomalyConfigScope source_config_scope = 6;
}

message EventExclusionInfo {
  optional string event_type_id = 1;
  AnomalyEventFamily anomaly_event_family = 2;
  EventExclusionType event_exclusion_type = 3;
  optional string event_type_name = 4;
}

message AnomalyActorExclusionInfo {
  oneof anomaly_actor_exclusion {
    AnomalyActor anomaly_actor = 1;
  }
}

message AnomalyActor {
  string id = 1;
}

enum EventExclusionType {
  EVENT_EXCLUSION_TYPE_UNSPECIFIED = 0;
  EVENT_EXCLUSION_TYPE_ALL_EVENTS = 1;
  EVENT_EXCLUSION_TYPE_EVENT_TYPE = 2;
  EVENT_EXCLUSION_TYPE_EVENT_SUBTYPE = 3;
}
