syntax = "proto3";

package ai.traceable.span.processing.config.service.v1;

option java_multiple_files = true;

import "org/hypertrace/span/processing/config/service/v1/sampling_configs.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

service SpanProcessingConfigService {
  rpc GetAllResolvedSamplingConfigs(GetAllResolvedSamplingConfigsRequest) returns (GetAllResolvedSamplingConfigsResponse) {}
}

message GetAllResolvedSamplingConfigsRequest {}

message GetAllResolvedSamplingConfigsResponse {
  repeated org.hypertrace.span.processing.config.service.v1.SamplingConfig sampling_configs = 1;
}
