/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.traceable.example.impl;

import ai.traceable.example.api.MyService;

public class MyServiceImplementation implements MyService {
    public String getText() {
        return "implementation";
    }
}
