states:
- currentState: DEPLOYMENT_STATUS_UNSPECIFIED
  transitions:
  - ACTION_CREATE:
     nextState: DEPLOYMENT_STATUS_REQUESTED
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_REQUESTED
  transitions:
  - ACTION_EDIT_BREAKING:
     nextState: DEPLOYMENT_STATUS_REQUESTED
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_UPDATE_STATUS:
     nextState: DEPLOYMENT_STATUS_IN_PROGRESS
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DELETE:
     nextState: DEPLOYMENT_STATUS_DEPLOYMENT_DELETED
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER]

- currentState: DEPLOYMENT_STATUS_IN_PROGRESS
  transitions:
  - ACTION_UPDATE_STATUS:
     nextState: DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_BLOCK:
     nextState: DEPLOYMENT_STATUS_BLOCKED
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DELETE:
     nextState: DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_BLOCKED
  transitions:
  - ACTION_EDIT_BREAKING:
     nextState: DEPLOYMENT_STATUS_REQUESTED
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER]
  - ACTION_DELETE:
     nextState: DEPLOYMENT_STATUS_DEPLOYMENT_DELETED
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER]

- currentState: DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY
  transitions:
  - ACTION_EDIT_BREAKING:
     nextState: DEPLOYMENT_STATUS_CHANGE_REQUESTED
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DELETE:
     nextState: DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER]

- currentState: DEPLOYMENT_STATUS_CHANGE_REQUESTED
  transitions:
  - ACTION_EDIT_BREAKING:
     nextState: DEPLOYMENT_STATUS_CHANGE_REQUESTED
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER]
  - ACTION_UPDATE_STATUS:
     nextState: DEPLOYMENT_STATUS_CHANGE_IN_PROGRESS
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DELETE:
     nextState: DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_CHANGE_IN_PROGRESS
  transitions:
  - ACTION_UPDATE_STATUS:
     nextState: DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_BLOCK:
     nextState: DEPLOYMENT_STATUS_CHANGE_BLOCKED
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DELETE:
     nextState: DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_CHANGE_BLOCKED
  transitions:
  - ACTION_EDIT_BREAKING:
     nextState: DEPLOYMENT_STATUS_CHANGE_IN_PROGRESS
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DELETE:
     nextState: DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS
     accessTypes: [CONFIG_ACCESS_TYPE_CUSTOMER, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS
  transitions:
  - ACTION_UPDATE_STATUS:
     nextState: DEPLOYMENT_STATUS_DEPLOYMENT_DELETED
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS]
