syntax = "proto3";

package ai.traceable.region.config.service.v1;

import "ai/traceable/config/commons/v1/audit.proto";

option java_multiple_files = true;

message GetRegionsRequest {
  RegionsFilter filter = 1;
}

message RegionsFilter {
  repeated string id = 1;
  repeated RegionIdentifier region_identifier = 2;
}

message GetRegionsResponse {
  repeated Region region = 1;
}

message GetRegionRequest {
  string id = 1;
  RegionIdentifier region_identifier = 2;
}

message GetRegionResponse {
  Region region = 1;
}

message GetDetailedRegionsRequest {
  RegionsFilter filter = 1;
}

message GetDetailedRegionsResponse {
  repeated DetailedRegion region = 1;
}

message Region {
  string id = 1;
  string name = 2 [deprecated = true];
  oneof region {
    Country country = 3;
  }
}

message DetailedRegion {
  string id = 1;
  string name = 2;
  repeated IpRange ip_range = 3;
  Region region = 4;
}

message RegionIdentifier {
  oneof identifier {
    string country_iso_code = 1;
  }
}

message Country {
  string name = 1;
  string iso_code = 2;
}

message IpRange {
  oneof range {
    IpV4Range ipv4_range = 1;
  }
}

message IpV4Range {
  int64 start_ip = 1;
  int64 end_ip = 2;
}

message GetRegionRulesFilter {
  RuleScope rule_scope = 1;
  repeated RegionRuleActionType rule_action_types = 2;
  optional bool disabled = 8;
  optional bool internal = 9;
  optional bool hidden = 10;
  ai.traceable.config.commons.v1.AuditFilter audit_filter = 11;
}

message GetAllRegionRulesRequest {
  GetRegionRulesFilter filter = 1;
}

message GetAllRegionRulesResponse {
  repeated RegionRule rule = 1 [deprecated = true];
  repeated RegionRuleRecord rule_records = 2;
}

message RegionRuleRecord {
  RegionRule rule = 1;
  ai.traceable.config.commons.v1.AuditDetails audit_details = 2;
}

message CreateRegionRuleRequest {
  repeated string region_id = 1;
  string name = 2;
  RegionRuleActionType action_type = 3;
  ExpirationDetails expiration_details = 4;
  RuleScope rule_scope = 5;
  EventSeverity event_severity = 6;
  RegionRuleConditions conditions = 7 [deprecated = true]; //unused
  string description = 8;
  repeated RuleEffectWithModifications effects = 9;
}

message CreateRegionRuleResponse {
  RegionRule rule = 1;
}

message UpdateRegionRuleRequest {
  string id = 1;
  repeated string region_id = 2;
  string name = 3;
  RegionRuleActionType action_type = 4;
  ExpirationDetails expiration_details = 5;
  RuleScope rule_scope = 6;
  EventSeverity event_severity = 7;
  RegionRuleConditions conditions = 8;
  bool disabled = 9;
  bool internal = 10;
  string description = 11;
  repeated RuleEffectWithModifications effects = 12;
  bool hidden = 13;
}

message UpdateRegionRuleResponse {
  RegionRule rule = 1;
}

message DeleteRegionRuleRequest {
  string id = 1;
}

message DeleteRegionRuleResponse {}

message BulkDeleteRegionRulesRequest {
  repeated string ids = 1;
}

message BulkDeleteRegionRulesResponse {}

message ExpirationDetails {
  oneof expiration {
    // Duration represented in ISO 8601 duration format.
    string duration = 1;
  }
}

message RegionRule {
  string id = 1;
  repeated string region_id = 2;
  string name = 3;
  RegionRuleActionType action_type = 4;
  ExpirationDetails expiration_details = 5;
  RuleScope rule_scope = 6;
  EventSeverity event_severity = 7;
  RegionRuleConditions conditions = 8;
  bool disabled = 9;
  bool internal = 10;
  string description = 11;
  map<string, string> region_id_to_name_map = 12 [deprecated = true];
  map<string, Country> region_id_to_country_map = 13;
  repeated RuleEffectWithModifications effects = 14;
  bool hidden = 15;

  message ExpirationDetails {
    // Duration represented in ISO 8601 duration format.
    string duration = 1;
    int64 timestamp_millis = 2;
  }
}

message RuleEffectWithModifications {
  oneof effect {
    AgentRuleEffect agent_rule_effect = 1;
  }
}

message AgentRuleEffect {
  repeated AgentModification agent_modifications = 1;
}

message AgentModification {
  oneof modification {
    HeaderInjection header_injection = 1;
  }
}

message HeaderInjection {
  PredicateLocation header_location = 1;
  string header_name = 2;
  FieldValue value = 3;
}

message FieldValue {
  oneof value {
    string static_value = 1;
  }
}

enum PredicateLocation {
  PREDICATE_LOCATION_UNSPECIFIED = 0;
  PREDICATE_LOCATION_REQUEST = 1;
  PREDICATE_LOCATION_RESPONSE = 2;
}

message RegionRuleConditions {
  CustomRegionScopeCondition scope = 1;
  IpReputationCondition ip_reputation = 2;
  StatusCodeMatchCondition status_code_match_condition = 3;
}

message RuleScope {
  oneof scope { // if no option selected, default is customer scope (all environments)
    EnvironmentScope environment_scope = 1;
  }
}

message EnvironmentScope {
  repeated string environment_ids = 1;
}

enum RegionRuleActionType {
  REGION_RULE_ACTION_TYPE_UNSPECIFIED = 0;
  REGION_RULE_ACTION_TYPE_BLOCK = 1;
  REGION_RULE_ACTION_TYPE_ALLOW = 2;
  REGION_RULE_ACTION_TYPE_BLOCK_ALL_EXCEPT = 3;
  REGION_RULE_ACTION_TYPE_ALERT = 4;
}

enum EventSeverity {
  EVENT_SEVERITY_UNSPECIFIED = 0;
  EVENT_SEVERITY_LOW = 1;
  EVENT_SEVERITY_MEDIUM = 2;
  EVENT_SEVERITY_HIGH = 3;
  EVENT_SEVERITY_CRITICAL = 4;
}

message CustomRegionScopeCondition {
  repeated CustomRegionScope scopes = 1;
}

message CustomRegionScope {
  oneof scope {
    CustomRegionEntityScope api_scope = 1;
    CustomRegionEntityScope service_scope = 2;
  }
}

message CustomRegionEntityScope {
  oneof ids {
    StringList entity_ids = 1;
    StringList label_ids = 2;
  }
}

message StringList {
  repeated string values = 1;
}

message IpReputationCondition {
  IpReputationSeverity min_ip_reputation_severity = 1;
}

enum IpReputationSeverity {
  IP_REPUTATION_SEVERITY_UNSPECIFIED = 0;
  IP_REPUTATION_SEVERITY_LOW = 1;
  IP_REPUTATION_SEVERITY_MEDIUM = 2;
  IP_REPUTATION_SEVERITY_HIGH = 3;
  IP_REPUTATION_SEVERITY_CRITICAL = 4;
}

message StatusCodeMatchCondition {
  StatusCodeMatchType match_type = 1;
  string match_value = 2;
}

enum StatusCodeMatchType {
  STATUS_CODE_MATCH_TYPE_UNSPECIFIED = 0;
  STATUS_CODE_MATCH_TYPE_EQUALS = 1;
  STATUS_CODE_MATCH_TYPE_NOT_EQUAL = 2;
  STATUS_CODE_MATCH_TYPE_MATCHES_REGEX = 3;
  STATUS_CODE_MATCH_TYPE_NOT_MATCH_REGEX = 4;
}

message RegionRuleMigrationConfig {
  // marking existing internal rules as hidden
  bool change_log_1_migration_completed = 1;
}
