syntax = "proto3";
package ai.traceable.policy.config.service.v1;
option java_package = "ai.traceable.policy.config.service.v1";
option java_multiple_files = true;
import "google/protobuf/struct.proto";

message ClientBotFingerprintPolicy {
  bool use_default = 1;
  float bot_suspicion_threshold = 2;
  BotFingerprintScore default_scores = 4;
  repeated BotFingerprintEvalRule rules = 3;
  string site_key = 5;
}

message BotFingerprintEvalRule {
  bool enabled = 1;
  float weight = 2;
  google.protobuf.Value config = 3;
  string rule_type = 4;
  BotFingerprintScore scores = 5;
}

message BotFingerprintScore {
  float high_score = 1;
  float medium_score = 2;
  float low_score = 3;
}
