syntax = "proto3";

package ai.traceable.policy.config.service.v1;
option java_package = "ai.traceable.policy.config.service.v1";
option java_multiple_files = true;

import "google/protobuf/struct.proto";
import "ai/traceable/policy/config/service/v1/client_bot_fingerprint_policy.proto";

message TraceablePolicy {
  oneof kind {
    ClientBotFingerprintPolicy client_bot_fingerprint_policy = 1;
    // other policy kinds will be added here when we migrate existing "fraud policy" to this module
  }
}
