syntax = "proto3";

package ai.traceable.edge.decision.engine.config.v1;

option java_package = "ai.traceable.edge.decision.engine.config.v1";
option java_multiple_files = true;

import "ai/traceable/edge/decision/engine/config/v1/edge_decision_config.proto";
import "ai/traceable/edge/decision/engine/config/v1/edge_decision_spec_config.proto";

// this is the overall config for the edge decision engine.
// while there's only decision config currently, more may come later.
// for ex: additional metadata related to communication with other components at the edge
message EdgeDecisionEngineConfig {
  EdgeDecisionConfig edge_decision_config = 1;
}
