syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.override;

option java_multiple_files = true;

import "ai/traceable/anomaly/config/service/v1/override/exception_detection_override_configs.proto";
import "ai/traceable/anomaly/config/service/v1/override/exclusion_detection_override_configs.proto";


service DetectionOverrideConfigService {

  // detection exclusion rules

  rpc GetAllDetectionExclusionRules(GetAllDetectionExclusionRulesRequest) returns (GetAllDetectionExclusionRulesResponse) {}

  rpc CreateDetectionExclusionRuleConfig(CreateDetectionExclusionRuleConfigRequest) returns (CreateDetectionExclusionRuleConfigResponse) {}

  rpc UpdateDetectionExclusionRule(UpdateDetectionExclusionRuleRequest) returns (UpdateDetectionExclusionRuleResponse) {}

  rpc DeleteDetectionExclusionRule(DeleteDetectionExclusionRuleRequest) returns (DeleteDetectionExclusionRuleResponse) {}

//  detection exception rules - to be implemented later

//  rpc GetAllDetectionExceptionRules(GetAllDetectionExceptionRulesRequest) returns (GetAllDetectionExceptionRulesResponse) {}

//  rpc CreateDetectionExceptionRuleConfig(CreateDetectionExceptionRuleConfigRequest) returns (CreateDetectionExceptionRuleConfigResponse) {}

//  rpc UpdateDetectionExceptionRule(UpdateDetectionExceptionRuleRequest) returns (UpdateDetectionExceptionRuleResponse) {}

//  rpc DeleteDetectionExceptionRule(DeleteDetectionExceptionRuleRequest) returns (DeleteDetectionExceptionRuleResponse) {}

}
