syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.override;

import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";

option java_multiple_files = true;

message DetectionOverrideScopeConfig {
  repeated DetectionOverrideScope scopes = 1;
}

message DetectionOverrideScope {
  oneof scope {
    DetectionOverrideEntityScope api_scope = 1;
    DetectionOverrideEntityScope service_scope = 2;
  }
}

message DetectionOverrideEntityScope {
  oneof ids {
    StringList entity_ids = 1;
    StringList label_ids = 2;
  }
}
