syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.override;

import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";

option java_multiple_files = true;

message DetectionOverrideTargetEventsConfig {
  repeated DetectionOverrideEventConfig event_configs = 1;
  DetectionOverrideAnomalousAttributesConfig anomalous_attributes = 2;
}

message DetectionOverrideAnomalousAttributesConfig {
  repeated string attribute_names = 1;
  repeated string attribute_regexes = 2;
}

message DetectionOverrideEventConfig {
  oneof config {
    DetectionOverrideConfidence confidence = 1;
    DetectionOverrideThreatType threat_type = 2;
    DetectionOverrideAnomalousBehaviour anomalous_behaviour = 3;
  }
}

message DetectionOverrideConfidence{
  AnomalyConfidenceLevel confidence_level = 1;
}

message DetectionOverrideThreatType {
  AnomalyEventFamily event_family = 1;
  string threat_type = 2;
}

message DetectionOverrideAnomalousBehaviour {
  DetectionOverrideThreatType threat_type = 1;
  string behaviour_id = 2;
}
