syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.override;

import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";
import "ai/traceable/anomaly/config/service/v1/override/common_detection_override_configs.proto";
import "ai/traceable/anomaly/config/service/v1/override/detection_override_actor_config.proto";
import "ai/traceable/anomaly/config/service/v1/override/detection_override_conditions_config.proto";
import "ai/traceable/anomaly/config/service/v1/override/detection_override_event_config.proto";
import "ai/traceable/anomaly/config/service/v1/override/detection_override_scope_config.proto";

option java_multiple_files = true;


message DetectionExclusionRule {
  string id = 1;
  string description = 2;
  DetectionOverrideRuleScope rule_scope = 3;
  DetectionExclusionRuleConfig config = 4;
}

message DetectionExclusionRuleConfig {
  DetectionExclusionConfigCriteria criteria = 1;
  DetectionOverrideRuleStatus rule_status = 2;
}

message DetectionExclusionConfigCriteria {
  DetectionOverrideAssetConfig target_asset_config = 1;
  DetectionOverrideAssetConfig source_asset_config = 2; // optional, applicable in few cases like bola
  DetectionOverrideTargetEventsConfig target_events_config = 3;
  DetectionOverrideActorsConfig actors_config = 4;
}

message GetAllDetectionExclusionRulesRequest {
}

message GetAllDetectionExclusionRulesResponse {
  repeated DetectionExclusionRule rules = 1;
}

message CreateDetectionExclusionRuleConfigRequest {
  string description = 1;
  DetectionExclusionRuleConfig config = 2;
}

message CreateDetectionExclusionRuleConfigResponse {
  DetectionExclusionRule rule = 1;
}

message UpdateDetectionExclusionRuleRequest {
  DetectionExclusionRule rule = 1;
}

message UpdateDetectionExclusionRuleResponse {
  DetectionExclusionRule rule = 1;
}

message DeleteDetectionExclusionRuleRequest {
  string rule_id = 1;
}

message DeleteDetectionExclusionRuleResponse {
}
