ipResolutionStrategyConfigs = [
  {
    "id": "154ea670-6b46-4dae-a4bd-a43d6887d0a7",
    "data": {
      "name": "Default: IP Resolution Strategy",
      "disabled": false,
      "scope": {
        "environmentScope": {
          "environmentNames": []
        },
        "serviceScope": {
          "serviceNames": []
        }
      },
      "strategy": {
        "evaluateAllIpsForBlocking": true,
        "sources": [
          {
            "sourceAttributeName": "http.request.header.x-real-ip",
            "parsingStrategy": {
              "rawIp": {}
            }
          },
          {
            "sourceAttributeName": "rpc.request.metadata.x-real-ip",
            "parsingStrategy": {
              "rawIp": {}
            }
          },
          {
            "sourceAttributeName": "rpc.request.metadata.x-forwarded-for",
            "parsingStrategy": {
              "splitDelimiter": ",",
              "removeInternalIps": false,
              "preferredIndex": 0,
              "rawIp": {}
            }
          },
          {
            "sourceAttributeName": "http.request.header.x-forwarded-for",
            "parsingStrategy": {
              "splitDelimiter": ",",
              "removeInternalIps": false,
              "preferredIndex": 0,
              "rawIp": {}
            }
          },
          {
            "sourceAttributeName": "http.request.header.forwarded",
            "parsingStrategy": {
              "splitDelimiter": ",",
              "keywordBased": {
                "prefix": "for=\"",
                "suffix": "\""
              }
            }
          },
          {
            "sourceAttributeName": "http.request.header.forwarded",
            "parsingStrategy": {
              "splitDelimiter": ",",
              "keywordBased": {
                "prefix": "for=",
                "suffix": ";"
              }
            }
          },
          {
            "sourceAttributeName": "http.request.header.forwarded",
            "parsingStrategy": {
              "splitDelimiter": ",",
              "keywordBased": {
                "prefix": "for=",
                "suffix": ""
              }
            }
          },
          {
            "sourceAttributeName": "rpc.request.metadata.forwarded",
            "parsingStrategy": {
              "splitDelimiter": ",",
              "keywordBased": {
                "prefix": "for=\"",
                "suffix": "\""
              }
            }
          },
          {
            "sourceAttributeName": "rpc.request.metadata.forwarded",
            "parsingStrategy": {
              "splitDelimiter": ",",
              "keywordBased": {
                "prefix": "for=",
                "suffix": ";"
              }
            }
          },
          {
            "sourceAttributeName": "rpc.request.metadata.forwarded",
            "parsingStrategy": {
              "splitDelimiter": ",",
              "keywordBased": {
                "prefix": "for=",
                "suffix": ""
              }
            }
          },
          {
            "sourceAttributeName": "http.request.header.x-proxyuser-ip",
            "parsingStrategy": {
              "rawIp": {}
            }
          },
          {
            "sourceAttributeName": "rpc.request.metadata.x-proxyuser-ip",
            "parsingStrategy": {
              "rawIp": {}
            }
          },
          {
            "sourceAttributeName": "proxy.client.addr",
            "parsingStrategy": {
              "rawIp": {}
            }
          },
          {
            "sourceAttributeName": "net.sock.peer.addr",
            "parsingStrategy": {
              "rawIp": {}
            }
          },
          {
            "sourceAttributeName": "net.peer.ip",
            "parsingStrategy": {
              "rawIp": {}
            }
          }
        ]
      }
    }
  }
]
