syntax = "proto3";

package ai.traceable.inclusion.rules.config.service.v1;
import "ai/traceable/inclusion/rules/config/service/v1/dataset/data_exfiltration_inclusion_rule.proto";

option java_multiple_files = true;

message GetInclusionRulesRequest {
}

message GetInclusionRulesResponse {
  repeated InclusionRuleConfig configs = 1;
}

message CreateInclusionRuleRequest {
  InclusionRuleData rule_data = 1;
}

message CreateInclusionRuleResponse {
  InclusionRuleConfig config = 1;
}

message UpdateInclusionRuleRequest {
  InclusionRuleConfig rule_config = 1;
}

message UpdateInclusionRuleResponse {
  InclusionRuleConfig config = 1;
}

message DeleteInclusionRuleRequest {
  string rule_id = 1;
}


message DeleteInclusionRuleResponse {

}

message InclusionRuleConfig {
  string id = 1;
  InclusionRuleData rule_data = 2;
  InclusionConfigStatus config_status = 3;

}
message InclusionRuleData {
  string name = 1;
  repeated EnvironmentScope environment_scopes = 2;
  repeated string label_ids = 3; // TODO
  oneof inclusion_rule_type {
    ai.traceable.inclusion.rules.config.service.v1.dataset.DataExfiltrationInclusionRule data_exfiltration_rule = 4;
  }
}

message InclusionConfigStatus {
  bool disabled = 1;
}

message EnvironmentScope {
  bool enabled = 1; // true means all services
  repeated ServiceScope service_scopes = 2;
  string id = 3;
}

message ServiceScope {
  bool enabled = 1; // true means all apis
  repeated ApiScope api_scopes = 2;
  string id = 3;
}

message ApiScope {
  string id = 1;
}
