syntax = "proto3";


package ai.traceable.inclusion.rules.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/inclusion/rules/config/service/v1/inclusion_rules_config.proto";

service InclusionRulesConfigService {

  rpc GetInclusionRules (GetInclusionRulesRequest) returns (GetInclusionRulesResponse) {
  }

  rpc CreateInclusionRule (CreateInclusionRuleRequest) returns (CreateInclusionRuleResponse) {
  }

  rpc UpdateInclusionRule (UpdateInclusionRuleRequest) returns (UpdateInclusionRuleResponse) {
  }

  rpc DeleteInclusionRule (DeleteInclusionRuleRequest) returns (DeleteInclusionRuleResponse) {
  }
}
