syntax = "proto3";

package ai.traceable.auth.detection.config.service.v1;

import "ai/traceable/auth/detection/config/service/v1/auth_detection_rule.proto";

option java_multiple_files = true;

service AuthDetectionConfigService {
  rpc GetAuthDetectionRules(GetAuthDetectionRulesRequest) returns (GetAuthDetectionRulesResponse) {}
  rpc UpdateAuthDetectionRule(UpdateAuthDetectionRuleRequest) returns (UpdateAuthDetectionRuleResponse) {}
  rpc CreateAuthDetectionRule(CreateAuthDetectionRuleRequest) returns (CreateAuthDetectionRuleResponse) {}
  rpc DeleteAuthDetectionRule(DeleteAuthDetectionRuleRequest) returns (DeleteAuthDetectionRuleResponse) {}
}
