syntax = "proto3";

package ai.traceable.auth.detection.config.service.v1;

option java_multiple_files = true;

message GetAuthDetectionRulesRequest {
  AuthDetectionRuleFilter filter = 1;
}

message AuthDetectionRuleFilter {
  AuthDetectionRuleScope scope = 1;
}

message AuthDetectionRuleScope {
  repeated string environment_names = 1;
}

message GetAuthDetectionRulesResponse {
  repeated AuthDetectionRule rules = 1;
}

message AuthDetectionRule {
  string id = 1;
  optional string auth_type = 2;
  AuthDetectionRuleScope scope = 3;
  Predicate predicate = 4;
  bool default = 5;
}

message Predicate {
  oneof predicate {
    CompositePredicate composite_predicate = 1;
    KeyValuePredicate header_predicate = 2;
    KeyValuePredicate cookie_predicate = 3;
    KeyValuePredicate query_parameter_predicate = 4;
    KeyValuePredicate form_body_predicate = 5;
    PathValuePredicate json_body_predicate = 6;
  }

  message CompositePredicate {
    LogicalOperator operator = 1;
    repeated Predicate children = 2;

    enum LogicalOperator {
      LOGICAL_OPERATOR_UNSPECIFIED = 0;
      LOGICAL_OPERATOR_AND = 1;
      LOGICAL_OPERATOR_OR = 2;
    }
  }

  message KeyValuePredicate {
    StringPredicate key_predicate = 1;
    StringPredicate value_predicate = 2;
  }

  message PathValuePredicate {
    PathPredicate path_predicate = 1;
    StringPredicate value_predicate = 2;
  }

  message PathPredicate {
    // Currently this is just a fancy string predicate, but with room for nested expressions in future
    oneof path {
      StringPredicate key_predicate = 1; // Single level match
    }
  }

  message StringPredicate {
    RelationalOperator operator = 1;
    string value = 2;

    enum RelationalOperator {
      RELATIONAL_OPERATOR_UNSPECIFIED = 0;
      RELATIONAL_OPERATOR_EQUALS = 1;
      RELATIONAL_OPERATOR_NOT_EQUALS = 2;
      RELATIONAL_OPERATOR_MATCHES_REGEX = 3;
      RELATIONAL_OPERATOR_NOT_MATCHES_REGEX = 4;
    }
  }
}

message CreateAuthDetectionRuleRequest {
  string auth_type = 1;
  AuthDetectionRuleScope scope = 2;
  Predicate predicate = 3;
}
message CreateAuthDetectionRuleResponse {
  AuthDetectionRule rule = 1;
}
message UpdateAuthDetectionRuleRequest {
  string id = 1;
  string auth_type = 2;
  AuthDetectionRuleScope scope = 3;
  Predicate predicate = 4;
}
message UpdateAuthDetectionRuleResponse {
  AuthDetectionRule rule = 1;
}
message DeleteAuthDetectionRuleRequest {
  string id = 1;
}
message DeleteAuthDetectionRuleResponse {}
