syntax = "proto3";

package ai.traceable.risk.config.service.v2;

import "ai/traceable/risk/config/service/v2/risk_scope.proto";

option java_multiple_files = true;

message RiskScoringGridConfig {
  RiskScoringGridConfigValues risk_scoring_grid_config_values = 1;
  bool is_default = 2;
}

message RiskScoringGridConfigValues {
  repeated RiskScoringGridCell risk_scoring_grid_cells = 1;
  RiskConfigScope risk_config_scope = 2;
}

message RiskScoringGridCell {
  RiskScoreCategory likelihood_score_category = 1;
  RiskScoreCategory impact_score_category = 2;
  int32 score = 3;
}

message RiskLevelConfigValues {
  int32 medium_level_min_score = 1;
  int32 high_level_min_score = 2;
  int32 critical_level_min_score = 3;
}

enum RiskScoreCategory {
  RISK_SCORE_CATEGORY_UNSPECIFIED = 0;
  RISK_SCORE_CATEGORY_LOW = 1;
  RISK_SCORE_CATEGORY_MEDIUM = 2;
  RISK_SCORE_CATEGORY_HIGH = 3;
  RISK_SCORE_CATEGORY_CRITICAL = 4;
}
