syntax = "proto3";

package ai.traceable.risk.config.service.v2;

option java_multiple_files = true;

message RiskElementConfig {
  string id = 1;
  RiskElementPredicate risk_element_predicate = 2;
  RiskElementScoring risk_element_scoring = 3;
  bool disabled = 4;
}

message RiskElementPredicate {
  oneof type {
    AuthCategoryPredicate external_unencrypted_auth_category = 1;
    AuthCategoryPredicate external_encrypted_auth_category = 2;
    AuthCategoryPredicate internal_unencrypted_auth_category = 3;
    AuthCategoryPredicate internal_encrypted_auth_category = 4;
    PathParamTypePredicate path_param_type = 5;
    VulnerabilitySeverityPredicate vulnerability_severity = 6;
    ResponseSensitivityPredicate response_sensitivity = 7;
    IntPredicate dependent_apis = 8;
    IntPredicate third_party_apis = 9;
    StringPredicate label_id = 10;
  }
}

message RiskElementScoring {
  int32 score = 1;
}

message AuthCategoryPredicate {
  EnumOperator operator = 1;
  AuthCategoryValue value = 2;
}

message PathParamTypePredicate {
  EnumOperator operator = 1;
  PathParamTypeValue value = 2;
}

message VulnerabilitySeverityPredicate {
  EnumOperator operator = 1;
  VulnerabilitySeverityValue value = 2;
}

message ResponseSensitivityPredicate {
  EnumOperator operator = 1;
  ResponseSensitivityValue value = 2;
}

message IntPredicate {
  IntOperator operator = 1;
  int64 value = 2;
}

message StringPredicate {
  StringOperator operator = 1;
  string value = 2;
}

enum AuthCategoryValue {
  AUTH_CATEGORY_VALUE_UNSPECIFIED = 0;
  AUTH_CATEGORY_VALUE_NONE = 1;
  AUTH_CATEGORY_VALUE_WEAK = 2;
  AUTH_CATEGORY_VALUE_STRONG = 3;
}

enum PathParamTypeValue {
  PATH_PARAM_TYPE_VALUE_UNSPECIFIED = 0;
  PATH_PARAM_TYPE_VALUE_NONE = 1;
  PATH_PARAM_TYPE_VALUE_DIGIT = 2;
  PATH_PARAM_TYPE_VALUE_STRING = 3;
}

enum VulnerabilitySeverityValue {
  VULNERABILITY_SEVERITY_VALUE_UNSPECIFIED = 0;
  VULNERABILITY_SEVERITY_VALUE_CRITICAL = 1;
  VULNERABILITY_SEVERITY_VALUE_HIGH = 2;
  VULNERABILITY_SEVERITY_VALUE_MEDIUM = 3;
  VULNERABILITY_SEVERITY_VALUE_LOW = 4;
}

enum ResponseSensitivityValue {
  RESPONSE_SENSITIVITY_VALUE_UNSPECIFIED = 0;
  RESPONSE_SENSITIVITY_VALUE_CRITICAL = 1;
  RESPONSE_SENSITIVITY_VALUE_HIGH = 2;
  RESPONSE_SENSITIVITY_VALUE_MEDIUM = 3;
  RESPONSE_SENSITIVITY_VALUE_LOW = 4;
}

enum EnumOperator {
  ENUM_OPERATOR_UNSPECIFIED = 0;
  ENUM_OPERATOR_EQUALS = 1;
}

enum IntOperator {
  INT_OPERATOR_UNSPECIFIED = 0;
  INT_OPERATOR_EQUALS = 1;
  INT_OPERATOR_NOT_EQUALS = 2;
  INT_OPERATOR_LESS_THAN = 3;
  INT_OPERATOR_LESS_THAN_EQUALS = 4;
  INT_OPERATOR_GREATER_THAN = 5;
  INT_OPERATOR_GREATER_THAN_EQUALS = 6;
}

enum StringOperator {
  STRING_OPERATOR_UNSPECIFIED = 0;
  STRING_OPERATOR_EQUALS = 1;
  STRING_OPERATOR_NOT_EQUALS = 2;
  STRING_OPERATOR_CONTAINS = 3;
  STRING_OPERATOR_NOT_CONTAINS = 4;
}
