syntax = "proto3";

package ai.traceable.data.protection.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/data/protection/config/service/v1/data_protection_config.proto";

service DataProtectionConfigService {

  rpc GetResolvedScopedDataProtectionConfig(GetResolvedScopedDataProtectionConfigRequest) returns (GetResolvedScopedDataProtectionConfigResponse) {}

  rpc UpsertScopedDataProtectionConfig(UpsertScopedDataProtectionConfigRequest) returns (UpsertScopedDataProtectionConfigResponse) {}

  rpc DeleteScopedDataProtectionConfig(DeleteScopedDataProtectionConfigRequest) returns (DeleteScopedDataProtectionConfigResponse) {}
}

message GetResolvedScopedDataProtectionConfigRequest {
  DataProtectionScope scope = 1;
}

message GetResolvedScopedDataProtectionConfigResponse {
  ScopedDataProtectionConfig config = 1;
}

message DeleteScopedDataProtectionConfigRequest {
  DataProtectionScope scope = 1;
}

message DeleteScopedDataProtectionConfigResponse {
}

message UpsertScopedDataProtectionConfigRequest {
  DataProtectionScope scope = 1;
  DataProtectionConfig config = 2;
  optional bool disable_data_protection = 3;
}

message UpsertScopedDataProtectionConfigResponse {
  ScopedDataProtectionConfig config = 1;
}
