syntax = "proto3";

package ai.traceable.anomaly.config.service.v1;

import "ai/traceable/anomaly/config/service/v1/enum_extension.proto";

option java_multiple_files = true;

message AnomalyConfigStatusChange {
  optional bool disabled = 1;
  optional bool internal = 2;
}

message AnomalyConfigStatus {
  bool disabled = 1;
  bool internal = 2; // used only when disabled = true
}

message AnomalyConfigScope {
  AnomalyConfigScopeType scope_type = 1 [deprecated = true];
  oneof scope {
    AnomalyServiceScope service_scope = 2;
    AnomalyApiScope api_scope = 3;
    AnomalyParamScope param_scope = 4 [deprecated = true];
    AnomalyCustomerScope customer_scope = 5;
    AnomalyEnvironmentScope environment_scope = 6;
    AnomalyBackendScope backend_scope = 7;
    AnomalyBackendApiScope backend_api_scope = 8;
    SavedFilterScope saved_filter_scope = 11;
  }
}

message SavedFilterScope {
  string saved_filter_id = 1;
}

message AnomalyCustomerScope {}

message AnomalyEnvironmentScope {
  string environment_id = 1;
}

// deprecated
message AnomalyParamScope {
  option deprecated = true;
  string param_name = 1 [deprecated = true];
  AnomalyApiScope api_scope = 2 [deprecated = true];
  AnomalyParamInfoScope scope = 3;
  AnomalyParamInfo param_info = 4;
}

// deprecated
message AnomalyParamInfoScope {
  option deprecated = true;
  oneof scope {
    AnomalyApiScope api_scope = 1;
    AnomalyServiceScope service_scope = 2;
    AnomalyCustomerScope customer_scope = 3;
  }
}

// deprecated
message AnomalyParamInfo {
  option deprecated = true;
  oneof param_details {
    string param_name = 1;
    string param_regex = 2;
  }
}

message AnomalyApiScope {
  string id = 1;
  AnomalyServiceScope service_scope = 2;
}

message AnomalyServiceScope {
  string id = 1;
  AnomalyEnvironmentScope environment_scope = 2; //optional
}

message AnomalyBackendApiScope {
  string id = 1;
  AnomalyBackendScope backend_scope = 2;
}

message AnomalyBackendScope {
  string id = 1;
  AnomalyEnvironmentScope environment_scope = 2; //optional
}

enum DemoApplicationType {
  DEMO_APPLICATION_TYPE_UNSPECIFIED = 0;
  DEMO_APPLICATION_TYPE_CRAPI = 1;
  DEMO_APPLICATION_TYPE_VAPI = 2;
  DEMO_APPLICATION_TYPE_VAMPI = 3;
}

enum AnomalyConfigScopeType {
  ANOMALY_CONFIG_SCOPE_TYPE_UNSPECIFIED = 0;
  ANOMALY_CONFIG_SCOPE_TYPE_CUSTOMER = 1;
  ANOMALY_CONFIG_SCOPE_TYPE_SERVICE = 2;
  ANOMALY_CONFIG_SCOPE_TYPE_API = 3;
}

message AnomalyRuleTypeVersion {
  AnomalyEventFamily anomaly_event_family = 1;
  RuleVersion rule_version = 2;
}

enum AnomalyEventFamily {
  ANOMALY_EVENT_FAMILY_UNSPECIFIED = 0;
  ANOMALY_EVENT_FAMILY_API_DEF = 1;
  ANOMALY_EVENT_FAMILY_MODSEC = 2;
  ANOMALY_EVENT_FAMILY_SESSION = 3;
  ANOMALY_EVENT_FAMILY_RATE_LIMIT = 4;
  ANOMALY_EVENT_FAMILY_CUSTOM_SIGNATURE = 5;
  ANOMALY_EVENT_FAMILY_VOLUMETRIC = 6;
  ANOMALY_EVENT_FAMILY_CREDENTIAL_STUFFING = 7;
  ANOMALY_EVENT_FAMILY_MALICIOUS_SOURCES = 8;
  ANOMALY_EVENT_FAMILY_GEN_AI = 9;
  ANOMALY_EVENT_FAMILY_THREAT_ACTOR = 10;
}

message AnomalyRuleInfo {
  string rule_id = 1;
  string rule_name = 2;
  string rule_category = 3 [deprecated = true];
  AnomalyEventFamily event_family = 4;
  repeated AnomalySubRuleInfo sub_rule_infos = 5;
  AnomalyRuleCategory anomaly_rule_category = 6 [deprecated = true];
  map<string, string> event_labels = 7;
  AnomalyEventDetails event_details = 8;
  AnomalySeverityLevel severity_level = 9 [deprecated = true];
}

message AnomalySubRuleInfo {
  string rule_id = 1;
  string rule_name = 2;
  repeated AnomalySubRuleType sub_rule_types = 3;
  map<string, string> event_labels = 4;
  AnomalySeverityLevel severity_level = 5;
  AnomalyEventDetails event_details = 6;
}

message AnomalyEventDetails {
  string description = 1;
  string mitigation = 2;
  string impact = 3;
  string references = 4;
}

enum AnomalySubRuleType {
  ANOMALY_SUB_RULE_TYPE_UNSPECIFIED = 0;
  ANOMALY_SUB_RULE_TYPE_REGULAR = 1;
  ANOMALY_SUB_RULE_TYPE_SAFE = 2;
  ANOMALY_SUB_RULE_TYPE_BLOCK = 3;
  ANOMALY_SUB_RULE_TYPE_UNSAFE = 4 [deprecated = true];
}

enum AnomalyRuleCategory {
  ANOMALY_RULE_CATEGORY_UNSPECIFIED = 0 [(string_value) = "Unspecified"];
  ANOMALY_RULE_CATEGORY_PARAMETER_ANOMALIES = 1 [(string_value) = "Parameter Anomalies"];
  ANOMALY_RULE_CATEGORY_REQUEST_RESPONSE_METADATA_ANOMALIES = 2 [(string_value) = "Request and Response Metadata Anomalies"];
  ANOMALY_RULE_CATEGORY_INJECTIONS = 3 [(string_value) = "Injections"];
  ANOMALY_RULE_CATEGORY_SSRF = 4 [(string_value) = "Server-Side Request Forgery (SSRF)"];
  ANOMALY_RULE_CATEGORY_DOS = 5 [(string_value) = "Denial of Service (DOS) attack"];
  ANOMALY_RULE_CATEGORY_SCANNER_DETECTED = 6 [(string_value) = "Scanner Detection"];
  ANOMALY_RULE_CATEGORY_XSS = 7 [(string_value) = "Cross Site Scripting (XSS)"];
  ANOMALY_RULE_CATEGORY_SESSION_FIXATION = 8 [(string_value) = "Session Fixation"];
  ANOMALY_RULE_CATEGORY_PATH_MANIPULATION = 9 [(string_value) = "Path Manipulation"];
  ANOMALY_RULE_CATEGORY_KNOWN_VULNERABILITIES = 10 [(string_value) = "Known Vulnerabilities"];
  ANOMALY_RULE_CATEGORY_AUTHORIZATION_VIOLATIONS = 11 [(string_value) = "Authorization Violations"];
  ANOMALY_RULE_CATEGORY_CUSTOM_RULES = 12 [(string_value) = "Custom Rules"];
  ANOMALY_RULE_CATEGORY_RATE_LIMIT = 13 [(string_value) = "Rate Limit"];
  ANOMALY_RULE_CATEGORY_ATTACKER = 14 [(string_value) = "Attacker"];
  ANOMALY_RULE_CATEGORY_TOKEN_VIOLATIONS = 15 [
    (string_value) = "Token Violations and Anomalies",
    deprecated = true
  ];
  ANOMALY_RULE_CATEGORY_AUTHENTICATION_AND_TOKEN_VIOLATIONS = 16 [(string_value) = "Authentication and Token Violations"];
  ANOMALY_RULE_CATEGORY_GRAPHQL_ATTACKS = 17 [(string_value) = "GraphQL Attacks"];
  ANOMALY_RULE_CATEGORY_VOLUMETRIC = 18 [(string_value) = "Volumetric Anomalies"];
  ANOMALY_RULE_CATEGORY_CREDENTIAL_STUFFING = 19 [
    (string_value) = "Credential Stuffing Attacks",
    deprecated = true
  ];
  ANOMALY_RULE_CATEGORY_ACCOUNT_TAKEOVER = 20 [(string_value) = "Account Takeover"];
}

enum AnomalyConfidenceLevel {
  ANOMALY_CONFIDENCE_LEVEL_UNSPECIFIED = 0;
  ANOMALY_CONFIDENCE_LEVEL_LOW = 1;
  ANOMALY_CONFIDENCE_LEVEL_MEDIUM = 2;
  ANOMALY_CONFIDENCE_LEVEL_HIGH = 3;
}

enum AnomalyCustomType {
  ANOMALY_CUSTOM_TYPE_UNSPECIFIED = 0 [(string_value) = "Unspecified"];
  ANOMALY_CUSTOM_TYPE_CUSTOM_SIGNATURE = 1 [(string_value) = "Custom Signature"];
  ANOMALY_CUSTOM_TYPE_RATE_LIMITING = 2 [(string_value) = "Rate Limiting"];
  ANOMALY_CUSTOM_TYPE_DATA_ACCESS = 3 [
    (string_value) = "Data Access",
    deprecated = true
  ];
  ANOMALY_CUSTOM_TYPE_ENUMERATION = 4 [(string_value) = "Enumeration"];
  ANOMALY_CUSTOM_TYPE_MALICIOUS_SOURCES_IP_RANGE = 5 [(string_value) = "IP Range Malicious Sources"];
  ANOMALY_CUSTOM_TYPE_MALICIOUS_SOURCES_IP_TYPE = 6 [(string_value) = "IP Type Malicious Sources"];
  ANOMALY_CUSTOM_TYPE_MALICIOUS_SOURCES_REGION = 7 [(string_value) = "Region Malicious Sources"];
  ANOMALY_CUSTOM_TYPE_MALICIOUS_SOURCES_EMAIL = 8 [(string_value) = "Email Domain Malicious Sources"];
  ANOMALY_CUSTOM_TYPE_THREAT_ACTOR = 9 [(string_value) = "Threat Actor"];
  ANOMALY_CUSTOM_TYPE_IN_AGENT_VULNERABLE_LIBRARY = 10 [(string_value) = "In-Agent Vulnerable Library"];
  ANOMALY_CUSTOM_TYPE_DATA_LOSS_PREVENTION = 11 [(string_value) = "Data Loss Prevention"];
}

enum AnomalySeverityLevel {
  ANOMALY_SEVERITY_LEVEL_UNSPECIFIED = 0;
  ANOMALY_SEVERITY_LEVEL_LOW = 1;
  ANOMALY_SEVERITY_LEVEL_MEDIUM = 2;
  ANOMALY_SEVERITY_LEVEL_HIGH = 3;
  ANOMALY_SEVERITY_LEVEL_CRITICAL = 4;
}

enum AnomalyRuleAction {
  ANOMALY_RULE_ACTION_UNSPECIFIED = 0;
  ANOMALY_RULE_ACTION_DISABLE = 1;
  ANOMALY_RULE_ACTION_MONITOR = 2;
  ANOMALY_RULE_ACTION_BLOCK = 3;
  ANOMALY_RULE_ACTION_TESTING = 4;
}

message RuleVersionDataChange {
  RuleVersion stable_version = 1;
  RuleVersion override_version = 2;
  RuleTestingMode rule_testing_mode = 3;
  RuleVersion experimental_version = 4 [deprecated = true];
  NotificationConfig notification_config = 5;
}

message RuleVersionData {
  RuleVersion current_version = 1;
  RuleVersion previous_version = 2;
  RuleTestingMode rule_testing_mode = 3;
  RuleVersion experimental_version = 4 [deprecated = true];
}

message RuleVersion {
  string version = 1;
  RuleVersionType version_type = 2;
  string published_date = 3;
}

message NotificationConfig {
  optional bool release_notified = 1;
  optional bool expiry_warning_notified = 2;
  optional bool expiry_notified = 3;
}

message ChangeLog {
  RuleType rule_type = 1;
  RuleVersion current_version = 2;
  RuleVersion previous_version = 3;
  StringList highlights = 4;
  ChangeLogTable added_rules_table = 5;
  ChangeLogTable updated_rules_table = 6;
  ChangeLogTable removed_rules_table = 7;
  ChangeLogTable added_threat_types_table = 8;
  ChangeLogTable removed_threat_types_table = 9;
}

message ChangeLogTable {
  repeated string column_names = 1;
  repeated ChangeLogRow rows = 2;
}

message ChangeLogRow {
  map<string, string> values = 1;
}

enum RuleType {
  RULE_TYPE_UNSPECIFIED = 0;
  RULE_TYPE_WEB_APPLICATION = 1;
  RULE_TYPE_API_PROTECTION = 2;
}

enum RuleVersionType {
  RULE_VERSION_TYPE_UNSPECIFIED = 0;
  RULE_VERSION_TYPE_STABLE = 1;
  RULE_VERSION_TYPE_BETA = 2;
  RULE_VERSION_TYPE_EXPERIMENTAL = 3;
  RULE_VERSION_TYPE_DEPRECATED = 4;
}

enum RuleTestingMode {
  RULE_TESTING_MODE_UNSPECIFIED = 0;
  RULE_TESTING_MODE_DISABLED = 1;
  RULE_TESTING_MODE_ENABLED_FOR_NEW_RULES = 2;
  RULE_TESTING_MODE_ENABLED_FOR_UPDATED_RULES = 3;
  RULE_TESTING_MODE_ENABLED_FOR_NEW_AND_UPDATED_RULES = 4;
  RULE_TESTING_MODE_INHERIT_FROM_ALL_ENVIRONMENTS = 5;
}

enum RuleVersionConfigType {
  RULE_VERSION_CONFIG_TYPE_UNSPECIFIED = 0;
  RULE_VERSION_CONFIG_TYPE_STABLE = 1;
  RULE_VERSION_CONFIG_TYPE_OVERRIDE = 2;
  RULE_VERSION_CONFIG_TYPE_EXPERIMENTAL = 3;
}

enum RuleEvaluationPoint {
  RULE_EVALUATION_POINT_UNSPECIFIED = 0;
  RULE_EVALUATION_POINT_EDGE = 1;
  RULE_EVALUATION_POINT_PLATFORM = 2;
}

message StringList {
  repeated string values = 1;
}

message IntList {
  repeated int32 values = 1;
}
