syntax = "proto3";

package ai.traceable.anomaly.config.service.v1;

option java_multiple_files = true;

message AnomalyConfigStatusChange {
  optional bool disabled = 1;
  optional bool internal = 2;
}

message AnomalyConfigStatus {
  bool disabled = 1;
  bool internal = 2; // used only when disabled = true
}

message AnomalyConfigScope {
  AnomalyConfigScopeType scope_type = 1 [deprecated = true];
  oneof scope { // empty if scope_type = ANOMALY_CONFIG_SCOPE_TYPE_CUSTOMER
    AnomalyServiceScope service_scope = 2; // set if scope_type = ANOMALY_CONFIG_SCOPE_TYPE_SERVICE
    AnomalyApiScope api_scope = 3; // set if scope_type = ANOMALY_CONFIG_SCOPE_TYPE_API
    AnomalyParamScope param_scope = 4; // set if scope_type = ANOMALY_CONFIG_SCOPE_TYPE_PARAM
    AnomalyCustomerScope customer_scope = 5;
  }
}

message AnomalyParamScope {
  string param_name = 1;
  AnomalyApiScope api_scope = 2;
}

message AnomalyApiScope {
  string id = 1;
  AnomalyServiceScope service_scope = 2;
}

message AnomalyServiceScope {
  string id = 1;
}

message AnomalyCustomerScope {
}

enum AnomalyConfigScopeType {
  ANOMALY_CONFIG_SCOPE_TYPE_UNSPECIFIED = 0;
  ANOMALY_CONFIG_SCOPE_TYPE_CUSTOMER = 1;
  ANOMALY_CONFIG_SCOPE_TYPE_SERVICE = 2;
  ANOMALY_CONFIG_SCOPE_TYPE_API = 3;
}

enum AnomalyEventFamily {
  ANOMALY_EVENT_FAMILY_UNSPECIFIED = 0;
  ANOMALY_EVENT_FAMILY_API_DEF = 1;
  ANOMALY_EVENT_FAMILY_MODSEC = 2;
  ANOMALY_EVENT_FAMILY_SESSION = 3;
  ANOMALY_EVENT_FAMILY_RATE_LIMIT = 4;
  ANOMALY_EVENT_FAMILY_CUSTOM_SIGNATURE = 5;
}

message AnomalyRuleInfo {
  string rule_id = 1;
  string rule_name = 2;
  string rule_category = 3;
  AnomalyEventFamily event_family = 4;
  repeated AnomalySubRuleInfo sub_rule_infos = 5;
}

message AnomalySubRuleInfo {
  string rule_id = 1;
  string rule_name = 2;
  repeated AnomalySubRuleType sub_rule_types = 3;
}

enum AnomalySubRuleType {
  ANOMALY_SUB_RULE_TYPE_UNSPECIFIED = 0;
  ANOMALY_SUB_RULE_TYPE_REGULAR = 1;
  ANOMALY_SUB_RULE_TYPE_SAFE = 2;
  ANOMALY_SUB_RULE_TYPE_BLOCK = 3;
}
