[versions]
protoc = "3.21.4"
grpc = "1.48.0"
lombok = "1.18.22"
jackson = "2.13.2"
hypertrace-grpcutils = "0.7.7"
hypertrace-framework = "0.1.43"
hypertrace-entityService = "0.8.41"
traceable-platform = "0.1.99"
traceable-platformGateway = "0.6.57"
kafka = "6.0.1"

junit = "5.8.2"
mockito = "4.4.0"

[libraries]
traceable-actorService-api = { module = "ai.traceable.platform:actor-service-api", version = "0.2.81" }
traceable-opaDistributor-api = { module = "ai.traceable.platform:opa-aggregator-api", version = "0.2.15" }
traceable-insights-api = { module = "ai.traceable.platform:insights-service-api", version = "0.49.14" }
traceable-activityevent-api = { module = "ai.traceable.activity.event.service:activity-event-api", version = "0.4.17" }
traceable-licensemetering-api = { module = "ai.traceable.license.metering.service:license-metering-service-api", version = "0.1.40" }
traceable-platform-jnimodsecurity = { module = "ai.traceable.platform:jni-modsecurity", version.ref = "traceable-platform" }
traceable-apiNamingModel = { module = "ai.traceable.platform:api-naming-model", version = "0.11.35" }
traceable-platformGateway-deepDataStore = { module = "ai.traceable.platform-gateway:deep-data-store", version.ref = "traceable-platformGateway" }
traceable-platformGateway-trainingEvaluationFramework = { module = "ai.traceable.platform-gateway:training-evaluation-framework", version.ref = "traceable-platformGateway" }
traceable-platformGateway-validators = { module = "ai.traceable.platform-gateway:validators", version.ref = "traceable-platformGateway" }
traceable-featureFlag-api = { module = "ai.traceable.featureflag:feature-flag-service-api", version = "0.5.6" }

hypertrace-grpcutils-client = { module = "org.hypertrace.core.grpcutils:grpc-client-utils", version.ref = "hypertrace-grpcutils" }
hypertrace-grpcutils-server = { module = "org.hypertrace.core.grpcutils:grpc-server-utils", version.ref = "hypertrace-grpcutils" }
hypertrace-grpcutils-context = { module = "org.hypertrace.core.grpcutils:grpc-context-utils", version.ref = "hypertrace-grpcutils" }
hypertrace-eventstore = { module = "org.hypertrace.core.eventstore:event-store", version = "0.1.2" }
hypertrace-configservice-server = { module = "org.hypertrace.config.service:config-service" }
hypertrace-configservice-impl = { module = "org.hypertrace.config.service:config-service-impl" }
hypertrace-configservice-api = { module = "org.hypertrace.config.service:config-service-api" }
hypertrace-configservice-alerting-api = { module = "org.hypertrace.config.service:alerting-config-service-api" }
hypertrace-configservice-notification-rule-impl = { module = "org.hypertrace.config.service:notification-rule-config-service-impl" }
hypertrace-configservice-notification-channel-impl = { module = "org.hypertrace.config.service:notification-channel-config-service-impl" }
hypertrace-configservice-span-processing-api = { module = "org.hypertrace.config.service:span-processing-config-service-api" }
hypertrace-configservice-protoconverter = { module = "org.hypertrace.config.service:config-proto-converter" }
hypertrace-configservice-objectstore = { module = "org.hypertrace.config.service:object-store" }
hypertrace-configservice-validation = { module = "org.hypertrace.config.service:validation-utils" }
hypertrace-configservice-spanProcessingUtils = { module = "org.hypertrace.config.service:span-processing-utils" }
hypertrace-configservice-changeeventgenerator = { module = "org.hypertrace.config.service:config-service-change-event-generator" }
hypertrace-configservice-factory = { module = "org.hypertrace.config.service:config-service-factory" }
hypertrace-grpc-framework = { module = "org.hypertrace.core.serviceframework:platform-grpc-service-framework", version.ref = "hypertrace-framework" }
hypertrace-framework-metrics = { module = "org.hypertrace.core.serviceframework:platform-metrics", version.ref = "hypertrace-framework" }
hypertrace-framework-integrationtest = { module = "org.hypertrace.core.serviceframework:integrationtest-service-framework", version.ref = "hypertrace-framework" }
hypertrace-documentstore = { module = "org.hypertrace.core.documentstore:document-store", version = "0.7.5" }

# https://traceableai.atlassian.net/wiki/spaces/Engineering/pages/1746337898/Config+Service+-+Dependency+Hell
# We would ideally want to segregate config service into 2 services - agent-configuration-service, and config-service and not have config-service depend on entity-service
hypertrace-entityservice-api = { module = "org.hypertrace.entity.service:entity-service-api", version.ref = "hypertrace-entityService" }
hypertrace-entityservice-client = { module = "org.hypertrace.entity.service:entity-service-client", version.ref = "hypertrace-entityService" }

guava = { module = "com.google.guava:guava", version = "31.1-jre" }
guice = { module = "com.google.inject:guice", version = "5.0.1" }
javax-annotation = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }
typesafe-config = { module = "com.typesafe:config", version = "1.4.2" }
re2j = { module = "com.google.re2j:re2j", version = "1.6" }
uuidCreator = { module = "com.github.f4b6a3:uuid-creator", version = "2.7.11" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
commons-csv = { module = "org.apache.commons:commons-csv", version = "1.8" }
commons-lang = { module = "org.apache.commons:commons-lang3", version = "3.11" }
commons-net = { module = "commons-net:commons-net", version = "3.8.0" }
commons-validator = { module = "commons-validator:commons-validator", version = "1.7" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
kafka-avro-serializer = { module = "io.confluent:kafka-avro-serializer", version.ref = "kafka" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-api = { module = "io.grpc:grpc-api", version.ref = "grpc" }
grpc-core = { module = "io.grpc:grpc-core", version.ref = "grpc" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
protobuf-javautil = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protoc" }
jersey-common = { module = "org.glassfish.jersey.core:jersey-common", version = "2.36" }

slf4j-log4jimpl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version = "2.17.2" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "1.7.36" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }

[bundles]
grpc-api = ["grpc-stub", "grpc-protobuf", "javax-annotation"]
