[libraries]
hypertrace-configservice-server = { module = "org.hypertrace.config.service:config-service" }
hypertrace-configservice-impl = { module = "org.hypertrace.config.service:config-service-impl" }
hypertrace-configservice-api = { module = "org.hypertrace.config.service:config-service-api" }
hypertrace-configservice-labelsConfigServiceApi = { module = "org.hypertrace.config.service:labels-config-service-api" }
hypertrace-configservice-alerting-api = { module = "org.hypertrace.config.service:alerting-config-service-api" }
hypertrace-configservice-notification-rule-impl = { module = "org.hypertrace.config.service:notification-rule-config-service-impl" }
hypertrace-configservice-notification-channel-impl = { module = "org.hypertrace.config.service:notification-channel-config-service-impl" }
hypertrace-configservice-span-processing-api = { module = "org.hypertrace.config.service:span-processing-config-service-api" }
hypertrace-configservice-protoconverter = { module = "org.hypertrace.config.service:config-proto-converter" }
hypertrace-configservice-objectstore = { module = "org.hypertrace.config.service:object-store" }
hypertrace-configservice-validation = { module = "org.hypertrace.config.service:validation-utils" }
hypertrace-configservice-spanProcessingUtils = { module = "org.hypertrace.config.service:span-processing-utils" }
hypertrace-configservice-changeeventgenerator = { module = "org.hypertrace.config.service:config-service-change-event-generator" }
hypertrace-configservice-changeeventapi = { module = "org.hypertrace.config.service:config-service-change-event-api" }
hypertrace-configservice-factory = { module = "org.hypertrace.config.service:config-service-factory" }
hypertrace-configservice-partitioner-config-impl = { module = "org.hypertrace.config.service:partitioner-config-service-impl" }

automaton = { module = "dk.brics.automaton:automaton", version = "1.11-8"}