syntax = "proto3";

package ai.traceable.threatscoring.config.service.v1;

option java_multiple_files = true;

message ScopedThreatScoringConfigs {
  ThreatScoringConfigScope config_scope = 1;
  ThreatScoringConfigs configs = 2;
}

message ThreatScoringConfigs {
  EventConfidenceScoringConfig event_confidence_scoring_config = 1;
  ThreatActivityConfidenceScoringConfig threat_activity_confidence_scoring_config = 2;
}

message EventConfidenceScoringConfig {
  EventConfidenceMatrixConfig event_confidence_matrix_config = 1;
  MaliciousSpanConfidenceScoring malicious_span_confidence_scoring = 2;
  AnomalousEventConfidenceConfig anomalous_event_confidence_config = 3;
  ResponseConfidenceConfig response_confidence_config = 4;
  ApiTrendConfidenceConfig api_trend_confidence_config = 5;
  ActorMaliciousConfidenceConfig actor_malicious_confidence_config = 6;
}

message ThreatActivityConfidenceScoringConfig {
  ThreatActivityConfidenceMatrixConfig threat_activity_confidence_matrix_config = 1;
  ScoringLevelConfig previous_activity_event_count_level_config = 2;
  ScoringLevelConfig previous_unique_params_count_level_config = 3;
  ScoringLevelConfig response_variation_count_level_config = 4;
}

//to be added later
message EventConfidenceMatrixConfig {
  repeated EventConfidenceMapping event_confidence_mapping = 1;
}

message ThreatActivityConfidenceMatrixConfig {
  repeated ThreatActivityConfidenceMapping threat_activity_confidence_mapping = 1;
}

message EventConfidenceMapping {
  ScoringLevel actor_confidence = 1;
  ScoringLevel malicious_span_confidence = 2;
  ScoringLevel anomalous_confidence = 3;
  ScoringLevel trend_confidence = 4;
  ScoringLevel response_confidence = 5;
  ScoringLevel event_confidence = 6;
}

message ThreatActivityConfidenceMapping {
  ScoringLevel current_event_confidence = 1;
  ScoringLevel previous_activity_confidence = 2;
  ScoringLevel previous_activity_event_count = 3;
  ScoringLevel previous_unique_params_count = 4;
  ScoringLevel new_activity_confidence = 5;
  ScoringLevel response_variation_count = 6;
}

message MaliciousSpanConfidenceScoring {
  ScoringLevelConfig level_config = 1;
}

message AnomalousEventConfidenceConfig {
  ScoringLevelConfig level_config = 1;
  int32 min_number_of_unlearnt_params_in_api = 3;
  int32 min_number_of_unique_unexpected_characters = 4;
}

message ResponseConfidenceConfig {
  ScoringLevelConfig level_config = 1;
}

message ApiTrendConfidenceConfig {
  ScoringLevelConfig level_config = 1;
}

message ActorMaliciousConfidenceConfig {
  IpReputationFactorMapping ip_reputation_factor_mapping = 1;
  int32 actor_trend_factor = 2;
  ScoringLevelConfig level_config = 3;
}

message ScoringLevelConfig {
  int32 medium_level_min_score = 1; // score is between 0-100
  int32 high_level_min_score = 2; // score is between 0-100
  int32 max_normalized_score = 3;
}

message ThreatScoringConfigScope {
  oneof scope {
    EnvironmentScope environment_scope = 1;
  }
}

message EnvironmentScope {
  string environment_id = 1;
}

enum ScoringLevel {
  SCORING_LEVEL_UNSPECIFIED = 0;
  SCORING_LEVEL_LOW = 1;
  SCORING_LEVEL_MEDIUM = 2;
  SCORING_LEVEL_HIGH = 3;
}

message IpReputationFactorMapping {
  double low_ip_reputation_factor = 1;
  double medium_ip_reputation_factor = 2;
  double high_ip_reputation_factor = 3;
  double critical_ip_reputation_factor = 4;
}
