syntax = "proto3";

package ai.traceable.threatscoring.config.service.v1;

option java_multiple_files = true;

message ScopedThreatScoringConfigs {
  ThreatScoringConfigScope config_scope = 1;
  ThreatScoringConfigs configs = 2;
}

message ThreatScoringConfigs {
  EventConfidenceScoringConfig event_confidence_scoring_config = 1;
}

message EventConfidenceScoringConfig {
  EventConfidenceMatrixConfig event_confidence_matrix_config = 1;
  MaliciousSpanConfidenceScoring malicious_span_confidence_scoring = 2;
  AnomalousEventConfidenceConfig anomalous_event_confidence_config = 3;
}

//to be added later
message EventConfidenceMatrixConfig {
  repeated EventConfidenceMapping event_confidence_mapping = 1;
}

message EventConfidenceMapping {
  ScoringLevel actor_confidence = 1;
  ScoringLevel malicious_span_confidence = 2;
  ScoringLevel anomalous_confidence = 3;
  ScoringLevel trend_confidence = 4;
  ScoringLevel response_confidence = 5;
  ScoringLevel event_confidence = 6;
}

message MaliciousSpanConfidenceScoring {
  ScoringLevelConfig level_config = 1;
}

message AnomalousEventConfidenceConfig {
  ScoringLevelConfig level_config = 1;
  int32 min_number_of_unlearnt_params_in_api = 3;
  int32 min_number_of_unique_unexpected_characters = 4;
}

message ScoringLevelConfig {
  int32 medium_level_min_score = 1;
  int32 high_level_min_score = 2;
}

message ThreatScoringConfigScope {
  oneof scope {
    EnvironmentScope environment_scope = 1;
  }
}

message EnvironmentScope {
  string environment_id = 1;
}

enum ScoringLevel {
  SCORING_LEVEL_UNSPECIFIED = 0;
  SCORING_LEVEL_LOW = 1;
  SCORING_LEVEL_MEDIUM = 2;
  SCORING_LEVEL_HIGH = 3;
}
