syntax = "proto3";

package ai.traceable.sessionattribution.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/sessionattribution/config/service/v1/session_attribution_rule.proto";

service SessionAttributionConfigService {
  rpc GetSessionAttributionRules (GetSessionAttributionRulesRequest) returns (GetSessionAttributionRulesResponse) {}
  rpc CreateSessionAttributionRule (CreateSessionAttributionRuleRequest) returns (CreateSessionAttributionRuleResponse) {}
  rpc UpdateSessionAttributionRule (UpdateSessionAttributionRuleRequest) returns (UpdateSessionAttributionRuleResponse) {}
  rpc DeleteSessionAttributionRule (DeleteSessionAttributionRuleRequest) returns (DeleteSessionAttributionRuleResponse) {}
}

message GetSessionAttributionRulesRequest {
  GetSessionAttributionRulesFilter filter = 1;

  message GetSessionAttributionRulesFilter {
    optional bool disabled = 1;
    EnvironmentFilter environment_filter = 2;

    message EnvironmentFilter {
      repeated string environment_names = 1;
    }
  }
}

message GetSessionAttributionRulesResponse {
  repeated SessionAttributionRule rules = 1;
}

message CreateSessionAttributionRuleRequest {
  string name = 1;
  optional string description = 2;
  SessionAttributionRuleScope scope = 3;
  repeated SessionTokenRule token_rules = 4;
}

message CreateSessionAttributionRuleResponse {
  SessionAttributionRule rule = 1;
}

message UpdateSessionAttributionRuleRequest {
  string id = 1;
  string name = 2;
  optional string description = 3;
  SessionAttributionRuleScope scope = 4;
  repeated SessionTokenRule token_rules = 5;
  SessionAttributionRuleStatus status = 6;
}

message UpdateSessionAttributionRuleResponse {
  SessionAttributionRule rule = 1;
}

message DeleteSessionAttributionRuleRequest {
  string id = 1;
}

message DeleteSessionAttributionRuleResponse {
}
