syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.modsec;

import "ai/traceable/anomaly/config/service/v1/modsec/anomaly_modsec_config.proto";

option java_multiple_files = true;

service AnomalyModsecConfigService {
  // tenant-specific
  rpc GetModsecCrsRules(GetModsecCrsRulesRequest) returns (GetModsecCrsRulesResponse) {}

  // tenant-agnostic
  rpc GetDefaultModsecCrsRules(GetDefaultModsecCrsRulesRequest) returns (GetDefaultModsecCrsRulesResponse) {}

  rpc GetWebAppEvaluationConfigContext(GetWebAppEvaluationConfigContextRequest) returns (GetWebAppEvaluationConfigContextResponse) {}
}
