syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.modsec;

option java_multiple_files = true;

import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";

message GetModsecCrsRulesRequest {
  repeated AnomalySubRuleType sub_rule_types = 1;
  bool remove_disabled_rules = 2;
  ModsecRuleVersion rule_version = 3;
  AnomalyConfigScope config_scope = 4;
}

message GetModsecCrsRulesResponse {
  repeated ModsecCrsRulesData modsec_crs_rules = 1;
}

message ModsecCrsRulesData {
  AnomalySubRuleType sub_rule_type = 1;
  string modsec_crs_rules_blob = 2;
}

enum ModsecRuleVersion {
  MODSEC_RULE_VERSION_UNSPECIFIED = 0;
  MODSEC_RULE_VERSION_V3 = 1;
  MODSEC_RULE_VERSION_V3_SECARG_LIMITS = 2;
  MODSEC_RULE_VERSION_CORAZA_V3 = 3;
  MODSEC_RULE_VERSION_V3_SECARG_LIMITS_DETECTION_ONLY_MODE = 4;
  MODSEC_RULE_VERSION_CORAZA_V3_DETECTION_ONLY_MODE = 5;
  MODSEC_RULE_VERSION_TEST_CORAZA_V3 = 6;
  MODSEC_RULE_VERSION_TEST_CORAZA_V3_DETECTION_ONLY_MODE = 7;
}
