syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.modsec;

import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";

option java_multiple_files = true;

message GetModsecCrsRulesRequest {
  repeated AnomalySubRuleType sub_rule_types = 1;
  bool remove_disabled_rules = 2;
  ModsecRuleVersion rule_version = 3;
  AnomalyConfigScope config_scope = 4;
  ModsecCrsRulesTarget target = 5;
}

message GetModsecCrsRulesResponse {
  repeated ModsecCrsRulesData modsec_crs_rules = 1;
  string aggregated_modsec_crs_rules_blob = 2;
}

message GetDefaultModsecCrsRulesRequest {
  repeated AnomalySubRuleType sub_rule_types = 1;
  ModsecRuleVersion rule_version = 2;
  bool use_test_modsec_rules = 3 [deprecated = true];
  RuleVersion version = 4;
}

message GetDefaultModsecCrsRulesResponse {
  repeated ModsecCrsRulesData modsec_crs_rules = 1;
  string aggregated_modsec_crs_rules_blob = 2;
}

message GetWebAppEvaluationConfigContextRequest {
  RuleEvaluationPoint rule_evaluation_point = 1;
  repeated AnomalySubRuleType sub_rule_types = 2;
}

message GetWebAppEvaluationConfigContextResponse {
  bytes web_app_evaluation_config_context = 1;
}

message GetImpactScoringRulesRequest {}

message GetImpactScoringRulesResponse {
  ImpactScoringRules impact_scoring_rules = 1;
}

message ImpactScoringRules {
  string impact_scoring_blob = 1;
}

enum ModsecCrsRulesTarget {
  MODSEC_CRS_RULES_TARGET_UNSPECIFIED = 0;
  MODSEC_CRS_RULES_TARGET_PLATFORM_DETECTION = 1;
  MODSEC_CRS_RULES_TARGET_TPA_DETECTION = 2;
  MODSEC_CRS_RULES_TARGET_TA_BLOCKING = 3;
}

message ModsecCrsRulesData {
  AnomalySubRuleType sub_rule_type = 1;
  string modsec_crs_rules_blob = 2;
}

enum ModsecRuleVersion {
  MODSEC_RULE_VERSION_UNSPECIFIED = 0;
  MODSEC_RULE_VERSION_V3 = 1;
  MODSEC_RULE_VERSION_V3_SECARG_LIMITS = 2 [deprecated = true];
  MODSEC_RULE_VERSION_CORAZA_V3 = 3;
  MODSEC_RULE_VERSION_V3_SECARG_LIMITS_DETECTION_ONLY_MODE = 4;
  MODSEC_RULE_VERSION_CORAZA_V3_DETECTION_ONLY_MODE = 5;
  MODSEC_RULE_VERSION_TEST_CORAZA_V3 = 6 [deprecated = true];
  MODSEC_RULE_VERSION_TEST_CORAZA_V3_DETECTION_ONLY_MODE = 7 [deprecated = true];
  MODSEC_RULE_VERSION_SENSITIVE_AGENT_CORAZA_V3 = 8;
  MODSEC_RULE_VERSION_SENSITIVE_AGENT_V3 = 9;
  MODSEC_RULE_VERSION_TEST_V3 = 10 [deprecated = true];
  MODSEC_RULE_VERSION_TEST_V3_SECARG_LIMITS = 11 [deprecated = true];
  MODSEC_RULE_VERSION_TEST_V3_SECARG_LIMITS_DETECTION_ONLY_MODE = 12 [deprecated = true];
}
