syntax = "proto3";

package ai.traceable.edge.config.service.v1;

import "google/protobuf/duration.proto";

option go_package = "github.com/Traceableai/config-service/gen/go/ai/traceable/edge/config/service/v1";
option java_multiple_files = true;

// this service is intentionally loosely typed.
// at the edge, different components can use the AgentManager as a proxy to pull their own configs
// and since AgentManager and the server channel are proxying other configs - they don't need to be
// aware of the payload.
service TraceableEdgeConfigService {
  rpc GetConfigs(GetConfigsRequest) returns (GetConfigsResponse) {}
}

message AgentCapabilities {
  repeated Component components = 1;
  map<string, string> additional_fields = 100;
}

message Component {
  oneof value {
    string traceable_platform_agent_version = 1;
    string traceable_edge_bot_service_version = 2;
    string traceable_edge_decision_engine_version = 3;
  }
}

message ConfigPayloads {
  // for ex: the blob of the config
  repeated bytes config_bytes = 1;
}

message ConfigRequestElement {
  // for ex: ClientBotFingerprintPolicy
  string config_type = 1;
  // config type level filter.
  string previous_hash = 2;
  // the client specifies it's capabilities
  AgentCapabilities agent_capabilities = 3;
}

// ConfigResponseElement would be a one of based on config_type
message ConfigResponseElement {
  // what is the hash of the config_payloads
  string hash = 1;
  // edgeDecisionConfig
  string config_type = 2;
  // edgeDecisionConfigs
  ConfigPayloads config_payloads = 3;
  google.protobuf.Duration refresh_after_duration = 4;
  bool enabled = 5;
  // specifies who can process the given payloads
  repeated AgentCapabilities supported_agent_capabilities = 6;
}

message GetConfigsRequest {
  // scope. only environment scope is supported.
  string environment = 1;
  // what does the client currently have
  string previous_hash = 2;
  // request for refreshing the configs
  repeated ConfigRequestElement config_requests = 3;
}

message GetConfigsResponse {
  // hash of all response elements together.
  string hash = 1;
  repeated ConfigResponseElement config_responses = 2;
}
