syntax = "proto3";

package ai.traceable.api.gateway.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/api/gateway/config/service/v1/api_route.proto";
import "ai/traceable/api/gateway/config/service/v1/api_gateway.proto";

service ApiGatewayConfigService {
  rpc CreateRoutes (CreateRoutesRequest) returns (CreateRoutesResponse) {
  }

  rpc GetRoutes (GetRoutesRequest) returns (GetRoutesResponse) {
  }

  rpc DeleteRoutes (DeleteRoutesRequest) returns (DeleteRoutesResponse) {
  }

  rpc CreateMetadata (CreateMetadataRequest) returns (CreateMetadataResponse) {
  }

  rpc GetMetadata (GetMetadataRequest) returns (GetMetadataResponse) {
  }

  rpc DeleteMetadata (DeleteMetadataRequest) returns (DeleteMetadataResponse) {
  }
}

message GetRoutesRequest {
  ApiRouteFilter filter = 1;
}

message GetRoutesResponse {
  repeated ApiRoute routes = 1;
}

message CreateRoutesRequest {
  repeated NewApiRoute routes = 1;
}

message CreateRoutesResponse {
  repeated ApiRoute routes = 1;
}

message DeleteRoutesRequest {
  ApiRouteFilter filter = 1;
}

message DeleteRoutesResponse {

}

message ApiRouteFilter {
  oneof type {
    OrgIds org_ids = 1;
    ApiInfo api_info = 2;
  }
}

message OrgIds {
  repeated string org_id = 1;
}

message ApiInfo {
  optional string http_method = 1;
  optional string path = 2;
  optional string service_name = 3;
}

message CreateMetadataRequest {
  ConfigMetadata config_metadata = 1;
}

message CreateMetadataResponse {

}

message GetMetadataRequest {
  MetadataFilter metadata_filter = 1;
}

message GetMetadataResponse {
  repeated ConfigMetadata config_metadata = 1;
}

message DeleteMetadataRequest {
  MetadataFilter metadata_filter = 1;
}

message DeleteMetadataResponse {

}

message MetadataFilter {
  oneof type {
    OrgIds org_ids = 1;
  }
}
