syntax = "proto3";

package ai.traceable.api.gateway.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/api/gateway/config/service/v1/api_route.proto";

service ApiGatewayConfigService {
  rpc CreateRoutes (CreateRoutesRequest) returns (CreateRoutesResponse) {
  }

  rpc GetRoutes (GetRoutesRequest) returns (GetRoutesResponse) {
  }

  rpc DeleteRoutes (DeleteRoutesRequest) returns (DeleteRoutesResponse) {
  }
}

message GetRoutesRequest {
  ApiRouteFilter filter = 1;
}

message GetRoutesResponse {
  repeated ApiRoute routes = 1;
}

message CreateRoutesRequest {
  repeated NewApiRoute routes = 1;
}

message CreateRoutesResponse {
  repeated ApiRoute routes = 1;
}

message DeleteRoutesRequest {
  ApiRouteFilter filter = 1;
}

message DeleteRoutesResponse {

}

message ApiRouteFilter {
  oneof type {
    OrgIds org_ids = 1;
  }
}

message OrgIds {
  repeated string org_id = 1;
}
