syntax = "proto3";

package ai.traceable.api.gateway.config.service.v1;

option java_multiple_files = true;

enum GatewayType {
  GATEWAY_TYPE_UNSPECIFIED = 0;
  GATEWAY_TYPE_MULESOFT = 1;
  GATEWAY_TYPE_APIGEE = 2;
}

message ConfigMetadata {
  string org_id = 1;
  repeated SourceInfo source_info = 2;
}

message SourceInfo {
  RequestInfo request_info = 1;
  StorageInfo storage_info = 2;
}

message RequestInfo {
  string url = 1;
  map<string, string> headers = 2;
}

message StorageInfo {
  string dir_name = 1;
}
