syntax = "proto3";

package ai.traceable.api.gateway.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/api/gateway/config/service/v1/api_gateway.proto";

message ApiRoute {
  string id = 1;
  RouteInfo info = 2;
  Metadata metadata = 3;
}

message NewApiRoute {
  RouteInfo info = 1;
  Metadata metadata = 2;
}

message RouteInfo {
  optional string service_name = 3;
  optional string http_method = 4;
  string path = 1;
  optional bool is_deprecated = 2;
  repeated Policy policies = 5;
}

message Metadata {
  string org_id = 1;
  GatewayType gateway_type = 2;
}

message Policy {
  string type = 1;
  optional string name = 2;
}
