syntax = "proto3";

package ai.traceable.localprocessing.config.service.v1;

option java_multiple_files = true;
option go_package = "github.com/Traceableai/config-service/localprocessing/v1";

message GetApiNamingModelRequest {
  repeated ServiceRequest service_requests = 1;
  optional string environment = 2;
}

message ServiceRequest {
  string service_name = 1;
  optional string trie_token = 2;
  optional string config_hash = 3;
}

message GetApiNamingModelResponse {
  repeated ServiceResponse service_responses = 1;
  repeated string fallback_wildcard_regexes = 2;
}

message ServiceResponse {
  Trie trie = 1;
  ApiNamingConfig config = 2;
  string service_name = 3;
}

message Trie {
  oneof trie {
    FullTrie full_trie = 1;
    DiffTrie diff_trie = 2;
  }
  string token = 3;
}

message FullTrie {
  Node root = 1;
}

message Node {
  Value value = 1;
  repeated Node children = 2;
}

message DiffTrie {
  repeated TrieDiffLog trie_diff_logs = 1;
}

message TrieDiffLog {
  oneof change {
    TrieNodePath path_addition = 1;
    TrieNodePath node_removal = 2;
  }
}

message TrieNodePath {
  repeated Value values = 1;
}

message Value {
  oneof segment {
    string name = 1;
    Wildcard wildcard = 2;
  }
}

message Wildcard {
  WildcardType wildcard_type = 1;
  optional string extension = 2;
}

message ApiNamingConfig {
  repeated ApiNamingCustomRule api_naming_custom_rules = 1;
  repeated WildcardConfig wildcard_configs = 2;
  repeated string url_reject_regexes = 3;
  repeated string extensions = 4;
  repeated string segment_whitelist_regexes = 5;
  optional string hash = 6;
}

message ApiNamingCustomRule {
  string regex_pattern = 1;
  string url_pattern = 2;
  int32 priority = 3;  //Higher the priority will be denoted by smaller rank
}

message WildcardConfig {
  WildcardType wildcard_type = 1;
  repeated string identification_regexes = 2;
  int32 priority = 3;   //Higher the priority will be denoted by smaller rank
}

enum WildcardType {
  WILDCARD_TYPE_UNSPECIFIED = 0;
  WILDCARD_TYPE_ID = 1;
  WILDCARD_TYPE_LOW_CARDINALITY = 2;
  WILDCARD_TYPE_MEDIUM_CARDINALITY = 3;
  WILDCARD_TYPE_HIGH_CARDINALITY = 4;
}
