syntax = "proto3";

package ai.traceable.localprocessing.config.service.v1;

option java_multiple_files = true;
option go_package = "github.com/Traceableai/config-service/localprocessing/v1";

service LocalProcessingConfigService {
  rpc GetLocalProcessingConfig(GetLocalProcessingConfigRequest) returns (GetLocalProcessingConfigResponse) {}
}

message GetLocalProcessingConfigRequest {}

message GetLocalProcessingConfigResponse {
  ProtectionModeConfig protection_mode_config = 1;
}

message ProtectionModeConfig {
  ProtectionMode default_protection_mode = 1;
  repeated ProtectedEndpoint protected_endpoints = 2;
}

enum ProtectionMode {
  PROTECTION_MODE_UNSPECIFIED = 0;
  PROTECTION_MODE_ADVANCED = 1;
  PROTECTION_MODE_CORE = 2;
}

message ProtectedEndpoint {
  ProtectionMode protection_mode = 1;
  oneof endpoint_specification {
    HttpEndpointSpecification http_endpoint_specification = 2;
    GrpcEndpointSpecification grpc_endpoint_specification = 3;
  }
}

message HttpEndpointSpecification {
  string path_regex = 1;
  string method = 2;
}

message GrpcEndpointSpecification {
  string path_regex = 1;
}
