syntax = "proto3";

package ai.traceable.fraud.datamodel.derivation.config.service.v1;

import "ai/traceable/fraud/datamodel/derivation/config/service/v1/fraud_datamodel_derivation_config.proto";
import "google/protobuf/struct.proto";

option java_multiple_files = true;

service FraudDataModelDerivationConfigService {
  rpc CreateDerivationConfig(CreateDerivationConfigRequest) returns (CreateDerivationConfigResponse) {}
  rpc UpdateDerivationConfig(UpdateDerivationConfigRequest) returns (UpdateDerivationConfigResponse) {}
  rpc UpsertDerivationConfig(UpsertDerivationConfigRequest) returns (UpsertDerivationConfigResponse) {}
  rpc GetDerivationConfigs(GetDerivationConfigsRequest) returns (GetDerivationConfigsResponse) {}
  rpc GetDerivationConfig(GetDerivationConfigRequest) returns (GetDerivationConfigResponse) {}
  rpc DeleteDerivationConfigs(DeleteDerivationConfigsRequest) returns (DeleteDerivationConfigsResponse) {}
  rpc CreateUserAgentMergeMappingConfig(CreateUserAgentMergeMappingConfigRequest) returns (CreateUserAgentMergeMappingConfigResponse) {}
  rpc GetUserAgentMergeMappingConfig(GetUserAgentMergeMappingConfigRequest) returns (GetUserAgentMergeMappingConfigResponse) {}
  rpc GetUserAgentMergeMappingConfigs(GetUserAgentMergeMappingConfigsRequest) returns (GetUserAgentMergeMappingConfigsResponse) {}
  rpc UpdateUserAgentMergeMappingConfig(UpdateUserAgentMergeMappingConfigRequest) returns (UpdateUserAgentMergeMappingConfigResponse) {}
  rpc DeleteUserAgentMergeMappingConfig(DeleteUserAgentMergeMappingConfigRequest) returns (DeleteUserAgentMergeMappingConfigResponse) {}
}

message CreateDerivationConfigRequest {
  DerivationConfigType derivation_config_type = 1;
  string name = 2;
  string derivation_config = 3;
}

message CreateDerivationConfigResponse {
  DerivationConfig derivation_config = 1;
}

message UpdateDerivationConfigRequest {
  DerivationConfig derivation_config = 1;
}

message UpdateDerivationConfigResponse {
  DerivationConfig derivation_config = 1;
}

message UpsertDerivationConfigRequest {
  DerivationConfig derivation_config = 1;
}

message UpsertDerivationConfigResponse {
  DerivationConfig derivation_config = 1;
}

message GetDerivationConfigsRequest {
  DerivationConfigType derivation_config_type = 1;
  repeated string derivation_config_ids = 2;
  bool include_disabled = 3;
}

message GetDerivationConfigsResponse {
  repeated DerivationConfig derivation_configs = 1;
}

message GetDerivationConfigRequest {
  DerivationConfigType derivation_config_type = 1;
  string derivation_config_id = 2;
  bool include_disabled = 3;
}

message GetDerivationConfigResponse {
  DerivationConfig derivation_config = 1;
}

message DeleteDerivationConfigsRequest {
  bool dry_run = 1;
  string derivation_config_id = 2;
}

message DeleteDerivationConfigsResponse {}

message CreateUserAgentMergeMappingConfigRequest {
  map<string, google.protobuf.ListValue> pairs = 2;
  oneof scope {
    ApiScope api_scope = 3;
    TenantScope tenant_scope = 4;
  }
}

message CreateUserAgentMergeMappingConfigResponse {
  UserAgentMergeMappingConfig user_agent_merge_mapping_config = 1;
}

message GetUserAgentMergeMappingConfigsRequest {}

message GetUserAgentMergeMappingConfigsResponse {
  repeated UserAgentMergeMappingConfig user_agent_merge_mapping_config = 1;
}

message GetUserAgentMergeMappingConfigRequest {
  string id = 1;
}

message GetUserAgentMergeMappingConfigResponse {
  UserAgentMergeMappingConfig user_agent_merge_mapping_config = 1;
}

message UpdateUserAgentMergeMappingConfigRequest {
  UserAgentMergeMappingConfig user_agent_merge_mapping_config = 1;
}

message UpdateUserAgentMergeMappingConfigResponse {
  UserAgentMergeMappingConfig user_agent_merge_mapping_config = 1;
}

message DeleteUserAgentMergeMappingConfigRequest {
  string id = 1;
}

message DeleteUserAgentMergeMappingConfigResponse {}
