syntax = "proto3";

package ai.traceable.fraud.datamodel.derivation.config.service.v1;

option java_multiple_files = true;

enum DerivationConfigType {
  DERIVATION_CONFIG_TYPE_UNSPECIFIED = 0;
  DERIVATION_CONFIG_TYPE_ENTITY = 1;
  DERIVATION_CONFIG_TYPE_RELATIONSHIP = 2;
  DERIVATION_CONFIG_TYPE_EVENT = 3;
  DERIVATION_CONFIG_TYPE_METRIC = 4;
  DERIVATION_CONFIG_TYPE_BASELINE = 5;
  DERIVATION_CONFIG_TYPE_FRAUD_DETECTION_EVENT = 6;
  DERIVATION_CONFIG_TYPE_RISK_DECISION = 7;
  DERIVATION_CONFIG_TYPE_RISK_DECISION_FINGERPRINT = 8;
  DERIVATION_CONFIG_TYPE_RISK_DECISION_SIGNATURE = 9;
  DERIVATION_CONFIG_TYPE_RISK_DECISION_RATELIMIT = 10;
}

message DerivationConfig {
  string id = 1;
  DerivationConfigType derivation_config_type = 2;
  string name = 3;
  string derivation_config = 4;
  bool disabled = 5;
}
