syntax = "proto3";

package ai.traceable.policy.fingerprint.dataset.v1;

option java_package = "ai.traceable.policy.fingerprint.dataset.v1";
option java_multiple_files = true;
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "ai/traceable/edge/common/config/v1/common.proto";
import "ai/traceable/datamodel/data/transformation/config/v1/transformation.proto";

message DetectionTypeScope {
  repeated string detection_types = 1;
}

message DetectionSourceScope {
  repeated string detection_sources = 1;
}

// fingerprint data needs to be downloaded separately.

// policy1 ->
//  email - list of emails
//  AND xyz - list of xyzs
// policy2 -> list of email handle patterns
// policy3 -> bloomfilter to be applied on request_cookie['visitor_uuid']

//

// represents the fingerprint data to be downloaded from the server, per policy.
message FingerprintDataset {
  string fingerprint_dataset_id = 1;
  repeated string labels = 2;

  // specify if this data must be used for only specific scope
  FingerprintDatasetScope inclusion_scope = 3;
  FingerprintDatasetScope exclusion_scope = 4;

  // when is it valid?
  ai.traceable.edge.common.config.v1.ConfigTtl ttl = 5;

  // toggle to enable / disable
  bool enabled = 6;
  // logical AND applied
  repeated ai.traceable.edge.common.config.v1.MatchCondition match_conditions = 7;
}

message FingerprintDatasetScope {
  ai.traceable.edge.common.config.v1.EnvironmentScope environment_scope = 1;
  // volumetric or rate limiting, etc
  DetectionTypeScope detection_type_scope = 2;
  // policy names or labels
  DetectionSourceScope detection_source_scope = 3;
  // use the request attributes to specify the scope, typically some pattern on the request params
  DatasetMatchCondition dataset_match_condition = 4;
}

message DatasetMatchCondition {
  // how do we derive this fingerprint keys from the request payload? (LHS)
  ai.traceable.datamodel.data.transformation.config.v1.AttributeDerivationMapping lhs = 1;

  // RHS. what should we match against?
  oneof rhs {
    // allowed operators: IN, NOT_IN
    google.protobuf.ListValue list_value = 2;
    // allowed operators: LIKE, NOT_LIKE
    string regex = 3;
    // allowed operators: NOT_IN (because bloom filter can answer if an element is NOT present)
    bytes bloom_filter = 4;
    // allowed operators: GT, LT, GTE, LTE
    double number_value = 5;
    // allowed operators: EQ, NOT_EQ
    bool bool_value = 6;
    // allowed operators: EQ, NOT_EQ
    google.protobuf.NullValue null_value = 7;
    // allowed operators: EQ, NOT_EQ
    string string_value = 8;
    // allowed operators: BETWEEN
    RangeValue range_value = 9;
    // allowed operators: BETWEEN
    TimeRangeValue time_range_value = 10;
  }

  // validate against "rhs" type
  MatchOperator match_operator = 11;
}

message RangeValue {
  double lower = 1;
  double upper = 2;
}

message TimeRangeValue {
  int64 start = 1;
  int64 end = 2;
}

enum MatchOperator {
  MATCH_OPERATOR_UNSPECIFIED = 0;
  MATCH_OPERATOR_IN = 1;
  MATCH_OPERATOR_NOT_IN = 2;
  MATCH_OPERATOR_LIKE = 3;
  MATCH_OPERATOR_NOT_LIKE = 4;
  MATCH_OPERATOR_EQ = 5;
  MATCH_OPERATOR_NOT_EQ = 6;
  MATCH_OPERATOR_GT = 7;
  MATCH_OPERATOR_LT = 8;
  MATCH_OPERATOR_GTE = 9;
  MATCH_OPERATOR_LTE = 10;
  MATCH_OPERATOR_BETWEEN = 11;
}

message FingerprintDatasetList {
  repeated FingerprintDataset fingerprint_datasets = 1;
}
