syntax = "proto3";

package ai.traceable.ast.config.service.v1;

option java_multiple_files = true;

message Assertion {
  string fixed_assertion_id = 1;
  string lhs = 2;
  string rhs = 3;
  MatchOperator operator = 4;
  map<string, string> data = 5;
  string lhs_value = 6;
  string rhs_value = 7;
  string key = 8;
  bool is_enabled = 9;
  oneof type {
    AssertionTypeImmediateResponse assertion_type_immediate_response = 10;
  }
  string description = 11;
}

message AssertionTypeImmediateResponse {}

enum MatchOperator {
  MATCH_OPERATOR_UNSPECIFIED = 0;
  MATCH_OPERATOR_EQUALS = 1;
  MATCH_OPERATOR_NOT_EQUALS = 2;
  MATCH_OPERATOR_MATCHES_REGEX = 3;
  MATCH_OPERATOR_NOT_MATCHES_REGEX = 4;
  MATCH_OPERATOR_GREATER_THAN = 5;
  MATCH_OPERATOR_GREATER_THAN_EQUALS = 6;
  MATCH_OPERATOR_LESS_THAN = 7;
  MATCH_OPERATOR_LESS_THAN_EQUALS = 8;
  MATCH_OPERATOR_CONTAINS = 9;
  MATCH_OPERATOR_NOT_CONTAINS = 10;
  MATCH_OPERATOR_KEYS_EQUALS = 11;
  MATCH_OPERATOR_KEYS_NOT_EQUALS = 12;
  MATCH_OPERATOR_FUZZY_EQUALS = 13;
  MATCH_OPERATOR_FUZZY_NOT_EQUALS = 14;
  MATCH_OPERATOR_FUZZY_KEYS_EQUALS = 15;
  MATCH_OPERATOR_FUZZY_KEYS_NOT_EQUALS = 16;
  MATCH_OPERATOR_VALUES_DIFFERENCE = 17;
  MATCH_OPERATOR_VALUES_SEARCH = 18;
  MATCH_OPERATOR_VALUES_NOT_SEARCH = 19;
  MATCH_OPERATOR_REGEXLOOKUP_EQUALS = 20;
  MATCH_OPERATOR_REGEXLOOKUP_NOT_EQUALS = 21;
  MATCH_OPERATOR_REGEXLOOKUP_MATCHES_REGEX = 22;
  MATCH_OPERATOR_REGEXLOOKUP_NOT_MATCHES_REGEX = 23;
  MATCH_OPERATOR_ALWAYS_TRUE = 24;
  MATCH_OPERATOR_ALWAYS_FALSE = 25;
  MATCH_OPERATOR_RAW = 26;
  MATCH_OPERATOR_COLLABORATOR_LOOKUP_CONTAINS = 27;
  MATCH_OPERATOR_IN = 28;
  MATCH_OPERATOR_NOT_IN = 29;
  MATCH_OPERATOR_ATTRIBUTE_EXISTS = 30;
  MATCH_OPERATOR_ATTRIBUTE_NOT_EXISTS = 31;
}
