syntax = "proto3";

package ai.traceable.ast.config.service.v1;

import "google/protobuf/duration.proto";

option java_multiple_files = true;

message AstFeatureConfig {
  string environment_id = 1;
  oneof status {
    AstDisabledConfig disabled_config = 2;
    AstEnabledConfig enabled_config = 3;
  }
}
message AstDisabledConfig {}
message AstEnabledConfig {
  AstReplayConfig replay_config = 1;
}

message AstReplayConfig {
  bool replay_enabled = 1;
  SpanFilters span_filters = 2;
  google.protobuf.Duration api_inactivity_duration = 3;
  optional int32 max_api_limit = 4;
  optional bool skip_non_learnt_apis = 5;
  optional bool skip_under_discovery_apis = 6;
}

message SpanFilters {
  repeated KeyValuePredicateWithLocation conditions = 1;
}

message KeyValuePredicateWithLocation {
  Location location = 1;
  KeyValuePredicate key_value_predicate = 2;
}

message KeyValuePredicate {
  StringPredicate key_predicate = 1;
  StringPredicate value_predicate = 2;
}

message StringPredicate {
  RelationalOperator operator = 1;
  string value = 2;
}

enum RelationalOperator {
  RELATIONAL_OPERATOR_UNSPECIFIED = 0;
  RELATIONAL_OPERATOR_EQUALS = 1;
  RELATIONAL_OPERATOR_MATCHES_REGEX = 2;
  RELATIONAL_OPERATOR_CONTAINS = 3;
  RELATIONAL_OPERATOR_NOT_CONTAINS = 4;
  RELATIONAL_OPERATOR_NOT_MATCHES_REGEX = 5;
}

enum Location {
  LOCATION_UNSPECIFIED = 0;
  LOCATION_REQUEST_HEADER = 1;
  LOCATION_REQUEST_COOKIE = 2;
  LOCATION_ATTRIBUTE = 3;
}

message ScanPurgeConfig {
  google.protobuf.Duration purge_duration = 1;
  optional int64 scan_retention_limit_per_suite = 2;
}

message VulnerabilityMetadataOverrides {
  IdentifyingAttributes identifying_attributes = 1;
  CustomerDefinedTagsMap customer_defined_tags = 2;
  optional double cvss_score = 3;
  optional string cvss_vector_string = 4;
  optional VulnerabilitySeverity severity = 5;
  optional google.protobuf.Duration estimated_fix_time = 6;
}

message CustomerDefinedTagsMap {
  map<string, TagValue> customer_defined_tags = 1;
}

message TagValue {
  repeated string value = 1;
}

// The metadata_id is the context key identifier here. The category and subcategory will be used in scan-manager when a
// config-change event is published to read from plugin template files
message IdentifyingAttributes {
  string metadata_id = 1;
  string category = 2;
  string subcategory = 3;
}

enum VulnerabilitySeverity {
  VULNERABILITY_SEVERITY_UNSPECIFIED = 0;
  VULNERABILITY_SEVERITY_CRITICAL = 1;
  VULNERABILITY_SEVERITY_HIGH = 2;
  VULNERABILITY_SEVERITY_MEDIUM = 3;
  VULNERABILITY_SEVERITY_LOW = 4;
}
