syntax = "proto3";

package ai.traceable.ast.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/ast/config/service/v1/ast.proto";

service AstConfigService {
  // read api
  rpc GetScanPurgeConfig (GetScanPurgeConfigRequest) returns (GetScanPurgeConfigResponse) {}

  // write api
  rpc UpdateScanPurgeConfig (UpdateScanPurgeConfigRequest) returns (UpdateScanPurgeConfigResponse) {}

  // edit plugin fields api.
  rpc EditVulnerabilityMetadataOverrides (EditVulnerabilityMetadataOverridesRequest) returns (EditVulnerabilityMetadataOverridesResponse) {}

  rpc DeleteVulnerabilityMetadataOverridesConfig(DeleteVulnerabilityMetadataOverridesConfigRequest) returns (DeleteVulnerabilityMetadataOverridesConfigResponse) {}

  rpc GetVulnerabilityMetadataOverrides(GetVulnerabilityMetadataOverridesRequest) returns (GetVulnerabilityMetadataOverridesResponse) {}
}

message UpdateScanPurgeConfigRequest {
  ScanPurgeConfig purge_config = 1;
}

message UpdateScanPurgeConfigResponse {
  ScanPurgeConfig purge_config = 1;
}

message GetScanPurgeConfigRequest {}

message GetScanPurgeConfigResponse {
  ScanPurgeConfig purge_config = 1;
}

message EditVulnerabilityMetadataOverridesRequest {
  VulnerabilityMetadataOverrides vulnerability_metadata_overrides = 1;
}

message EditVulnerabilityMetadataOverridesResponse {
  VulnerabilityMetadataOverrides vulnerability_metadata_overrides = 1;
}

message GetVulnerabilityMetadataOverridesRequest {
  string metadata_id = 1;
}

message GetVulnerabilityMetadataOverridesResponse {
  VulnerabilityMetadataOverrides vulnerability_metadata_overrides = 1;
}

message DeleteVulnerabilityMetadataOverridesConfigRequest {
  string metadata_id = 1;
}

message DeleteVulnerabilityMetadataOverridesConfigResponse {}
