syntax = "proto3";

package ai.traceable.ast.config.service.v1;

option java_multiple_files = true;

import "google/protobuf/timestamp.proto";
import "ai/traceable/ast/config/service/v1/mutation_override.proto";
import "ai/traceable/ast/config/service/v1/assertion_override.proto";
import "ai/traceable/ast/config/service/v1/ast_override_scope.proto";

message AstOverride {
  string id = 1;
  string name = 2;
  optional string description = 3;
  string created_by = 4;
  string last_updated_by = 5;
  repeated OverrideScope scopes = 6;
  OverrideConfig config = 7;
  google.protobuf.Timestamp last_updated_timestamp = 8;
}

message OverrideConfig {
  oneof type {
    MutationOverride mutation_override = 1;
    AssertionOverride assertion_override = 2;
  }
}
