syntax = "proto3";

package ai.traceable.ast.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/ast/config/service/v1/ast.proto";
import "ai/traceable/ast/config/service/v1/ast_overrides_request.proto";
import "ai/traceable/ast/config/service/v1/ast_overrides_response.proto";
import "ai/traceable/ast/config/service/v1/ast_custom_test_plugins.proto";
import "ai/traceable/ast/config/service/v1/vulnerability_auto_resolution_config.proto";

service AstConfigService {
  // read api
  rpc GetScanPurgeConfig (GetScanPurgeConfigRequest) returns (GetScanPurgeConfigResponse) {}

  // write api
  rpc UpdateScanPurgeConfig (UpdateScanPurgeConfigRequest) returns (UpdateScanPurgeConfigResponse) {}

  // edit plugin fields api.
  rpc EditVulnerabilityMetadataOverrides (EditVulnerabilityMetadataOverridesRequest) returns (EditVulnerabilityMetadataOverridesResponse) {}

  rpc DeleteVulnerabilityMetadataOverridesConfig(DeleteVulnerabilityMetadataOverridesConfigRequest) returns (DeleteVulnerabilityMetadataOverridesConfigResponse) {}

  rpc GetVulnerabilityMetadataOverrides(GetVulnerabilityMetadataOverridesRequest) returns (GetVulnerabilityMetadataOverridesResponse) {}

  rpc GetAllVulnerabilityMetadataOverrides(GetAllVulnerabilityMetadataOverridesRequest) returns (GetAllVulnerabilityMetadataOverridesResponse) {}

  rpc GetAstFeatureConfigs(GetAstFeatureConfigsRequest) returns (GetAstFeatureConfigsResponse);

  rpc UpdateAstFeatureConfig(UpdateAstFeatureConfigRequest) returns (UpdateAstFeatureConfigResponse);

  rpc GetAllCustomTestPlugins(GetAllCustomTestPluginsRequest) returns (GetAllCustomTestPluginsResponse);

  rpc CreateCustomTestPlugin(CreateCustomTestPluginRequest) returns (CreateCustomTestPluginResponse);

  rpc UpdateCustomTestPlugin(UpdateCustomTestPluginRequest) returns (UpdateCustomTestPluginResponse);

  rpc DeleteCustomTestPlugin(DeleteCustomTestPluginRequest) returns (DeleteCustomTestPluginResponse);

  rpc GetAstOverrides (GetAstOverridesRequest) returns (GetAstOverridesResponse);

  rpc CreateAstOverride (CreateAstOverrideRequest) returns (CreateAstOverrideResponse);

  rpc UpdateAstOverride (UpdateAstOverrideRequest) returns (UpdateAstOverrideResponse);

  rpc DeleteAstOverrides (DeleteAstOverridesRequest) returns (DeleteAstOverridesResponse);

  rpc GetVulnerabilityAutoResolutionConfigs(GetVulnerabilityAutoResolutionConfigsRequest) returns (GetVulnerabilityAutoResolutionConfigsResponse);
}

message UpdateScanPurgeConfigRequest {
  ScanPurgeConfig purge_config = 1;
}

message UpdateScanPurgeConfigResponse {
  ScanPurgeConfig purge_config = 1;
}

message GetScanPurgeConfigRequest {}

message GetScanPurgeConfigResponse {
  ScanPurgeConfig purge_config = 1;
}

message EditVulnerabilityMetadataOverridesRequest {
  VulnerabilityMetadataOverrides vulnerability_metadata_overrides = 1;
}

message EditVulnerabilityMetadataOverridesResponse {
  VulnerabilityMetadataOverrides vulnerability_metadata_overrides = 1;
}

message GetVulnerabilityMetadataOverridesRequest {
  string metadata_id = 1;
}

message GetVulnerabilityMetadataOverridesResponse {
  VulnerabilityMetadataOverrides vulnerability_metadata_overrides = 1;
}

message DeleteVulnerabilityMetadataOverridesConfigRequest {
  string metadata_id = 1;
}

message DeleteVulnerabilityMetadataOverridesConfigResponse {}

message GetAllVulnerabilityMetadataOverridesRequest {}

message GetAllVulnerabilityMetadataOverridesResponse {
  repeated VulnerabilityMetadataOverrides vulnerability_metadata_overrides = 1;
}

message UpdateAstFeatureConfigRequest {
  string environment_id = 1;
  oneof update_status {
    AstDisabledConfig disabled_config = 2;
    AstEnabledConfig enabled_config = 3;
  }
}

message UpdateAstFeatureConfigResponse {
  AstFeatureConfig updated_config = 1;
}

message GetAstFeatureConfigsRequest {
  AstFeatureConfigFilter filter = 1;
}

message AstFeatureConfigFilter {
  oneof filter {
    EnvironmentIdFilter environment_id_filter = 1;
  }

  message EnvironmentIdFilter {
    repeated string environment_ids = 1;
  }
}

message GetAstFeatureConfigsResponse {
  repeated AstFeatureConfig configs = 1;
  oneof default_config {
    AstDisabledConfig default_disabled_config = 2;
    AstEnabledConfig default_enabled_config = 3;
  }
}

message GetVulnerabilityAutoResolutionConfigsRequest {}

message GetVulnerabilityAutoResolutionConfigsResponse {
  repeated VulnerabilityAutoResolutionConfig vulnerability_auto_resolution_configs = 1;
}
