syntax = "proto3";

package ai.traceable.ast.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/ast/config/service/v1/ast.proto";

service AstConfigService {
  // read api
  rpc GetScanPurgeConfig (GetScanPurgeConfigRequest) returns (GetScanPurgeConfigResponse) {}

  // write api
  rpc UpdateScanPurgeConfig (UpdateScanPurgeConfigRequest) returns (UpdateScanPurgeConfigResponse) {}
}

message UpdateScanPurgeConfigRequest {
  ScanPurgeConfig purge_config = 1;
}

message UpdateScanPurgeConfigResponse {
  ScanPurgeConfig purge_config = 1;
}

message GetScanPurgeConfigRequest {}

message GetScanPurgeConfigResponse {
  ScanPurgeConfig purge_config = 1;
}
