syntax = "proto3";

package ai.traceable.ast.config.service.v1;

import "ai/traceable/ast/config/service/v1/ast.proto";

option java_multiple_files = true;

message GetAllCustomTestPluginsRequest {
  CustomTestPluginFilter filter = 1;
}

message CustomTestPluginFilter {
  oneof type {
    StringList id_filter = 1;
  }
}

message StringList {
  repeated string values = 1;
}

message GetAllCustomTestPluginsResponse {
  repeated CustomTestPlugin custom_test_plugins = 1;
}

message CreateCustomTestPluginRequest {
  CreateCustomTestPlugin create_custom_test_plugin = 1;
}

message CreateCustomTestPlugin {
  string name = 1;
  CodeSnippetDetails code_snippet_details = 2;
  string description = 3;
  TestPluginType plugin_type = 4;
  TestPluginSafetyType plugin_safety_type = 5;
  string plugin_details = 6;
  map<string, TagValue> tags = 7;
  repeated string potential_generated_vulnerability_types = 8;
  SampleData sample_data = 9;
  repeated ApiType supported_api_types = 10;
  PluginScope plugin_scope = 12;
}

enum ApiType {
  API_TYPE_UNSPECIFIED = 0;
  API_TYPE_HTTP = 1;
  API_TYPE_GRPC = 2;
  API_TYPE_GRAPHQL = 3;
}

enum TestPluginType {
  TEST_PLUGIN_TYPE_UNSPECIFIED = 0;
  TEST_PLUGIN_TYPE_ACTIVE = 1;
  TEST_PLUGIN_TYPE_PASSIVE = 2;
}

enum TestPluginSafetyType {
  TEST_PLUGIN_SAFETY_TYPE_UNSPECIFIED = 0;
  TEST_PLUGIN_SAFETY_TYPE_SAFE = 1;
  TEST_PLUGIN_SAFETY_TYPE_UNSAFE = 2;
}

message CodeSnippetDetails {
  string code_snippet = 1;
  CodeSnippetType code_snippet_type = 2;
}

message CreateCustomTestPluginResponse {
  CustomTestPlugin custom_test_plugin = 1;
}

message UpdateCustomTestPluginRequest {
  UpdateCustomTestPlugin update_custom_test_plugin = 1;
}

message UpdateCustomTestPlugin {
  string id = 1;
  string name = 2;
  CodeSnippetDetails code_snippet_details = 3;
  string description = 4;
  TestPluginType plugin_type = 5;
  TestPluginSafetyType plugin_safety_type = 6;
  string plugin_details = 7;
  map<string, TagValue> tags = 8;
  repeated string potential_generated_vulnerability_types = 9;
  SampleData sample_data = 10;
  repeated ApiType supported_api_types = 11;
}

message UpdateCustomTestPluginResponse {
  CustomTestPlugin custom_test_plugin = 1;
}

message DeleteCustomTestPluginRequest {
  string id = 1;
}

message DeleteCustomTestPluginResponse {}

message CustomTestPlugin {
  string id = 1;
  string name = 2;
  CodeSnippetDetails code_snippet_details = 3;
  string description = 4;
  TestPluginType plugin_type = 5;
  TestPluginSafetyType plugin_safety_type = 6;
  string plugin_details = 7;
  map<string, TagValue> tags = 8;
  repeated string potential_generated_vulnerability_types = 9;
  SampleData sample_data = 10;
  repeated ApiType supported_api_types = 11;
  PluginScope plugin_scope = 12;
}

message PluginScope {
  oneof scope {
    EnvironmentScope environment_scope = 1;
  }
}

message EnvironmentScope {
  repeated string environment_ids = 1;
}

enum CodeSnippetType {
  CODE_SNIPPET_TYPE_UNSPECIFIED = 0;
  CODE_SNIPPET_TYPE_VULNERABILITY_METADATA_INCLUDED_PYTHON_SCRIPT = 1;
  CODE_SNIPPET_TYPE_YAML = 2;
}

message SampleData {
  oneof sample_data {
    HttpRestApiDetails http_rest_api_details = 1;
  }
}

message HttpRestApiDetails {
  string request_body = 1;
  map<string, string> request_headers = 2;
  string target_url = 3;
  HttpMethod method = 4;
  optional string endpoint_id = 5;
}

enum HttpMethod {
  HTTP_METHOD_UNSPECIFIED = 0;
  HTTP_METHOD_GET = 1;
  HTTP_METHOD_POST = 2;
  HTTP_METHOD_PUT = 3;
  HTTP_METHOD_DELETE = 4;
  HTTP_METHOD_PATCH = 5;
  HTTP_METHOD_OPTIONS = 6;
  HTTP_METHOD_HEAD = 7;
  HTTP_METHOD_TRACE = 8;
}
