syntax = "proto3";

package ai.traceable.ast.config.service.v1;

option java_multiple_files = true;

import "google/protobuf/struct.proto";

message Mutation {
  string fixed_mutation_id = 1;
  MutationAction action = 2;
  string key = 3;
  google.protobuf.Value value = 4;
  map<string, string> data = 5;
  google.protobuf.Value original_value = 6;
  bool is_enabled = 7;
  string description = 8;
}

enum MutationAction {
  MUTATION_ACTION_UNSPECIFIED = 0;
  MUTATION_ACTION_ADD = 1;
  MUTATION_ACTION_SET = 2;
  MUTATION_ACTION_DELETE = 3;
  MUTATION_ACTION_MODIFY = 4;
  MUTATION_ACTION_REPEAT = 5;
  MUTATION_ACTION_REGEX_DELETE = 6;
  MUTATION_ACTION_REGEX_MODIFY = 7;
  MUTATION_ACTION_REGEX_SET = 8;
  MUTATION_ACTION_REGEX_REPEAT = 9;
}
