syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.apidef;
import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";

option java_multiple_files = true;

message GetApiDefinitionTrainerConfigsRequest {
  AnomalyConfigScope config_scope = 1;
}

message GetApiDefinitionTrainerConfigsResponse {
  ApiDefinitionTrainerConfig api_definition_trainer_config = 1;
}

message UpdateApiDefinitionTrainerConfigsRequest {
  repeated ApiDefinitionApplierConfig api_definition_applier_configs = 1;
  AnomalyConfigScope config_scope = 2;
}

message UpdateApiDefinitionTrainerConfigsResponse {
  ApiDefinitionTrainerConfig api_definition_trainer_config = 1;
}

message ApiDefinitionTrainerConfig {
  repeated ApiDefinitionApplierConfig api_definition_applier_configs = 1;
}

message ApiDefinitionApplierConfig {
  bool disabled = 1;
  oneof applier_config {
    TypeMetadataApplierConfig type = 6;
    PiiMetadataApplierConfig pii = 7;
    EnumerationsMetadataApplierConfig enum = 8;
    DigitLengthMetadataApplierConfig digit_length = 9;
    SpecialCharactersMetadataApplierConfig special_chars = 10;
    HttpStatusCodeMetadataApplierConfig http_status = 11;
    DeviceMetadataApplierConfig device = 12;
    ContentSizeMetadataApplierConfig content_size = 13;
    ApiAccessorsMetadataApplierConfig api_accessors = 14;
    ParamAccessorsMetadataApplierConfig param_accessors = 15;
    ParamTypeAccessorsMetadataApplierConfig param_type_accessors = 16;
    SsrfProtocolMetadataApplierConfig ssrf_protocol = 17;
    SsrfDomainMetadataApplierConfig ssrf_domain = 18;
    ThresholdsFamilyMetadataApplierConfig thresholds_family = 19;
    QueryParamContainsSensitiveDataVulnerabilityApplierConfig query_param_contains_sensitive_data = 20;
    JavaSerializedObjectVulnerabilityApplierConfig java_serialized_object = 21;
    LackOfEncryptionVulnerabilityApplierConfig lack_of_encryption = 22;
    PersistentCookieContainsSensitiveDataVulnerabilityApplierConfig persistent_cookie_contains_sensitive_data = 23;
    PiiSensitiveDataApplierConfig pii_sensitive_data = 24;
  }
}

message TypeMetadataApplierConfig {
  optional int32 max_allowed_child_params = 1;
}

message PiiMetadataApplierConfig {
  optional int32 dlp_api_request_batch_size = 1;
  optional int32 max_dlp_api_requests_per_sec = 2;
  optional bool dlp_use_cached_response = 3;
  DlpSchedule dlp_schedule = 4;
}

message EnumerationsMetadataApplierConfig {
  optional int32 max_enumerations = 1;
  optional int32 enum_value_max_length = 2;
  optional int32 min_occurrence_count = 3;
  // Takes value between 0-100
  optional double min_enum_occurrence_percent = 4;
}

message DigitLengthMetadataApplierConfig {
  RequiredIpValues diverse_ip_diverse_user = 1;
  RequiredIpValues diverse_ip_limited_user = 2;
  RequiredIpValues limited_ip = 3;
}

message SpecialCharactersMetadataApplierConfig {
  RequiredIpValues diverse_ip_diverse_user = 1;
  RequiredIpValues diverse_ip_limited_user = 2;
  RequiredIpValues limited_ip = 3;
}

message HttpStatusCodeMetadataApplierConfig {
  RequiredIpValues diverse_ip_diverse_user = 1;
  RequiredIpValues diverse_ip_limited_user = 2;
  RequiredIpValues limited_ip = 3;
}

message DeviceMetadataApplierConfig {
  RequiredIpValues diverse_ip_diverse_user = 1;
  RequiredIpValues diverse_ip_limited_user = 2;
  RequiredIpValues limited_ip = 3;
}

message ContentSizeMetadataApplierConfig {
  optional int32 request_range_size = 1;
  optional int32 response_range_size = 2;
}

message ApiAccessorsMetadataApplierConfig {
  RequiredIpValues diverse_ip_diverse_user = 1;
  RequiredIpValues diverse_ip_limited_user = 2;
  RequiredIpValues limited_ip = 3;
}

message ParamAccessorsMetadataApplierConfig {
  RequiredParamValues diverse_ip_diverse_user = 1;
  RequiredParamValues diverse_ip_limited_user = 2;
  RequiredParamValues limited_ip = 3;
}

message ParamTypeAccessorsMetadataApplierConfig {
  RequiredIpValues diverse_ip_diverse_user = 1;
  RequiredIpValues diverse_ip_limited_user = 2;
  RequiredIpValues limited_ip = 3;
}

message SsrfProtocolMetadataApplierConfig {
  RequiredIpValues diverse_ip_diverse_user = 1;
  RequiredIpValues diverse_ip_limited_user = 2;
  RequiredIpValues limited_ip = 3;
}

message SsrfDomainMetadataApplierConfig {
  optional int32 max_allowed_hosts = 1;
}

message ThresholdsFamilyMetadataApplierConfig {
  optional int64 learning_time_millis = 1;
  optional int32 required_ips_for_diverse_set = 2;
  optional int32 required_user_ids_for_diverse_set = 3;
  repeated int32 bad_status_ip = 4;
  repeated int32 bad_status_user_id = 5;
  optional int32 required_percent_for_authenticated = 6;
  optional int32 thresholds_family_relearn_version = 7;
}

message QueryParamContainsSensitiveDataVulnerabilityApplierConfig {
  optional int32 min_total_pii_type_occurrences = 1;
  optional int32 min_percent_of_pii_type = 2;
}

message JavaSerializedObjectVulnerabilityApplierConfig {
  repeated string base64_serialized_strings = 1;
  optional string raw_serialized_string = 2;
}

message LackOfEncryptionVulnerabilityApplierConfig {
  optional int32 min_percent_of_https_calls = 1;
  optional int32 min_number_of_calls = 2;
}

message PersistentCookieContainsSensitiveDataVulnerabilityApplierConfig {
  optional int32 min_total_pii_type_occurrences = 1;
  optional int32 min_percent_of_pii_type = 2;
}

message PiiSensitiveDataApplierConfig {
  optional int32 dlp_api_request_batch_size = 1;
  optional int32 max_dlp_api_requests_per_sec = 2;
  optional bool dlp_use_cached_response = 3;
  DlpSchedule dlp_schedule = 4;
}

message DlpSchedule {
  optional string param_age_threshold_duration = 1;
  optional string low_age_frequency_duration = 2;
  optional string high_age_frequency_duration = 3;
}

message RequiredIpValues {
  optional int32 required_no_of_appearances = 1;
  optional int32 required_unique_user_ids_count = 2;
  optional int32 required_unique_ips_count = 3;
}

message RequiredParamValues {
  optional int32 required_unique_user_ids_count_query_param = 1;
  optional int32 required_unique_ips_count_query_param = 2;
  optional int32 required_no_of_appearances_query_param = 3;
  optional int32 required_unique_user_ids_count_request_body_param = 4;
  optional int32 required_unique_ips_count_request_body_param = 5;
  optional int32 required_no_of_appearances_request_body_param = 6;
}
