syntax = "proto3";

package ai.traceable.ast.scan.profile.config.service.v1;

import "ai/traceable/ast/scan/profile/config/service/v1/scan_profile.proto";

option java_multiple_files = true;

service ScanProfileConfigService {
  rpc CreateScanProfile(CreateScanProfileRequest) returns (CreateScanProfileResponse) {}

  rpc UpdateScanProfile(UpdateScanProfileRequest) returns (UpdateScanProfileResponse) {}

  rpc GetScanProfiles(GetScanProfilesRequest) returns (GetScanProfilesResponse) {}

  rpc DeleteScanProfiles(DeleteScanProfilesRequest) returns (DeleteScanProfilesResponse) {}
}

// Requests.
message CreateScanProfileRequest {
  string name = 1;
  UpsertScanProfile create_scan_profile = 2;
}

message UpdateScanProfileRequest {
  string name = 1;
  UpsertScanProfile update_scan_profile = 2;
}

message GetScanProfilesRequest {
  ScanProfileFilter filter = 1;
}

message DeleteScanProfilesRequest {
  ScanProfileFilter filter = 1;
}

// Responses.
message CreateScanProfileResponse {
  ScanProfile scan_profile = 1;
}

message UpdateScanProfileResponse {
  ScanProfile scan_profile = 1;
}

message GetScanProfilesResponse {
  repeated ScanProfile scan_profiles = 1;
}

message DeleteScanProfilesResponse {}

message UpsertScanProfile {
  string description = 1;
  ScanProfileConfiguration profile_configuration = 2;
}

message ScanProfileFilter {
  repeated string scan_profile_names = 1;
}
