syntax = "proto3";

package ai.traceable.data.classification.config.service.v1;

option java_multiple_files = true;

message DataType {
  string id = 1;
  DataTypeRule rule = 2;
}

message DataTypeRule {
  string name = 1;
  optional string description = 2;
  repeated ScopedPattern scoped_patterns = 3;
  optional string suppression_pattern = 4;
  optional bool enabled = 5;
  DataSetInfo.DataSuppression data_suppression = 6;
  DataSetInfo.Sensitivity sensitivity = 7;
  reserved 8;
  repeated string data_set_id = 9;

  message ScopedPattern {
    oneof scope {
      GlobalScope global_scope = 1;
      EnvironmentScope environment_scope = 2;
      ApiScope api_scope = 3;
    }
    repeated Location locations = 5;
    oneof pattern {
      StringPattern key_pattern = 6;
      KeyValuePattern key_value_pattern = 7;
      KeyValuePattern leaf_key_value_pattern = 9;
    }
    Action action = 8;
  }

  message GlobalScope {
  }

  message EnvironmentScope {
    repeated string environment_ids = 1;
  }

  message ApiScope {
    repeated string api_ids = 1;
  }

  message StringPattern {
    Operator operator = 1;
    string value = 2;
  }

  message KeyValuePattern {
    StringPattern key_pattern = 1;
    StringPattern value_pattern = 2;
  }

  enum Location {
    LOCATION_UNSPECIFIED = 0;
    LOCATION_PATH = 1;
    LOCATION_QUERY = 2;
    LOCATION_REQUEST_HEADER = 3;
    LOCATION_REQUEST_BODY = 4;
    LOCATION_REQUEST_COOKIE = 5;
    LOCATION_RESPONSE_HEADER = 6;
    LOCATION_RESPONSE_BODY = 7;
    LOCATION_RESPONSE_COOKIE = 8;
    LOCATION_ANY = 9;
  }

  enum Operator {
    OPERATOR_UNSPECIFIED = 0;
    OPERATOR_EQUALS = 1; // operator to check if the key is equal to the provided value
    OPERATOR_MATCHES_REGEX = 2; // operator to check if the key matches the provided regex value
  }

  enum Action {
    ACTION_UNSPECIFIED = 0;
    ACTION_MATCH = 1; // action to apply the data type if match is successful
    ACTION_IGNORE = 2; // action to ignore the data type if match is successful
  }
}

message DataSet {
  string id = 1;
  DataSetInfo info = 2;
}

message DataSetInfo {
  string name = 1;
  optional string description = 2;
  bool enabled = 3 [deprecated = true];
  repeated string data_type_ids = 4 [deprecated = true];
  DataSuppression data_suppression = 5 [deprecated = true];
  Sensitivity sensitivity = 6 [deprecated = true];
  optional string color = 7 [deprecated = true];

  enum DataSuppression {
    DATA_SUPPRESSION_UNSPECIFIED = 0;
    DATA_SUPPRESSION_RAW = 1;
    DATA_SUPPRESSION_REDACT = 2;
    DATA_SUPPRESSION_OBFUSCATE = 3;
  }

  enum Sensitivity {
    SENSITIVITY_UNSPECIFIED = 0;
    SENSITIVITY_LOW = 1;
    SENSITIVITY_MEDIUM = 2;
    SENSITIVITY_HIGH = 3;
    SENSITIVITY_CRITICAL = 4;
    SENSITIVITY_NONE = 5;
  }
}

message DataClassificationOverride {
  string id = 1;
  DataClassificationOverrideRule data_classification_override_rule = 2;
}

message DataClassificationOverrideRule {
  string name = 1;
  optional string description = 2;
  DataClassificationOverrideScope scope = 3;
  SpanFilter span_filter = 5;

  oneof override {
    DataSuppressionOverride data_suppression_override = 4;
  }

  message DataClassificationOverrideScope {
    oneof scope {
      EnvironmentScope environment_scope = 1;
    }
  }

  message EnvironmentScope {
    string environment_id = 1;
  }

  message DataSuppressionOverride {
    DataSetInfo.DataSuppression data_suppression = 1;
  }
}

message DataClassificationOverrideFilter {
  oneof filter {
    IdFilter id_filter = 1;
    ScopeFilter scope_filter = 2;
  }
}

message IdFilter {
  repeated string ids = 1;
}

message ScopeFilter {
  repeated DataClassificationOverrideRule.DataClassificationOverrideScope scopes = 1;
}

message SpanFilter {
  oneof filter {
    SpanLogicalFilter logical_filter = 1;
    SpanKeyValueFilter key_value_filter = 2;
    SpanFilter negation_filter = 3;
  }
}

message SpanLogicalFilter {
  LogicalOperator operator = 1;
  repeated SpanFilter children = 2;
}

enum LogicalOperator {
  LOGICAL_OPERATOR_UNSPECIFIED = 0;
  LOGICAL_OPERATOR_AND = 1; // No OR support currently
}

message SpanKeyValueFilter {
  DataTypeRule.StringPattern key_pattern = 1;
  DataTypeRule.StringPattern value_pattern = 2;
}
