entity.service.config = {
  entity-service {
    dataStoreType = mongo
    mongo {
      host = ${?mongo_host}
      port = 27017
    }
  }
  query.aggregation.enabled = false
}

entity.service.attributeMap = [
  {
    "scope": "SERVICE",
    "name": "SERVICE.id",
    "subDocPath": "entityId"
  },
  {
    "scope": "SERVICE",
    "name": "SERVICE.name",
    "subDocPath": "entityName"
  },
  {
    "scope": "SERVICE",
    "name": "SERVICE.environment",
    "subDocPath": "attributes.ENVIRONMENT"
  },
  {
    "scope": "ACTOR",
    "name": "ACTOR.id",
    "subDocPath": "entityId"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.actorId",
     "subDocPath": "attributes.actor_id"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.status",
     "subDocPath": "attributes.status"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.ipAddress",
     "subDocPath": "attributes.ip_address"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.ipAddresses",
     "subDocPath": "attributes.ip_addresses"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.statusExpiration",
     "subDocPath": "attributes.status_expiry_timestamp"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.environment",
     "subDocPath": "attributes.environment"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.statusChangeSource",
     "subDocPath": "attributes.status_change_source"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.statusChangeDetails",
     "subDocPath": "attributes.status_change_details"
   },
   {
     "scope": "ACTOR",
     "name": "ACTOR.blockedEventLabels",
     "subDocPath": "attributes.blocked_event_labels"
   }
]
