entity.service.config = {
  entity-service {
    dataStoreType = mongo
    mongo {
      host = localhost
      host = ${?mongo_host}
      port = 27017
;       port = ${?MONGO_PORT}
    }
  }
  query.aggregation.enabled = false
}

entity.service.attributeMap = [
  {
    "scope": "SERVICE",
    "name": "SERVICE.id",
    "subDocPath": "entityId"
  },
  {
    "scope": "SERVICE",
    "name": "SERVICE.name",
    "subDocPath": "entityName"
  },
  {
    "scope": "SERVICE",
    "name": "SERVICE.environment",
    "subDocPath": "attributes.ENVIRONMENT"
  }
]
