states:
- currentState: DEPLOYMENT_STATUS_INIT
  transitions:
  - ACTION_CREATE:
     nextStates: [DEPLOYMENT_STATUS_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_REQUESTED
  transitions:
  - ACTION_EDIT:
     nextStates: [DEPLOYMENT_STATUS_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_HOLD:
     nextStates: [DEPLOYMENT_STATUS_ON_HOLD]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_UPDATE_STATUS:
     nextStates: [DEPLOYMENT_STATUS_IN_PROGRESS]
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS, CONFIG_ACCESS_TYPE_TRACEABLE]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_IN_PROGRESS
  transitions:
  - ACTION_UPDATE_STATUS:
     nextStates: [DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY, DEPLOYMENT_STATUS_BLOCKED]
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS, CONFIG_ACCESS_TYPE_TRACEABLE]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_BLOCKED
  transitions:
  - ACTION_EDIT:
     nextStates: [DEPLOYMENT_STATUS_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY
  transitions:
  - ACTION_EDIT:
     nextStates: [DEPLOYMENT_STATUS_CHANGE_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_REQUEST_REMOVAL:
     nextStates: [DEPLOYMENT_STATUS_REMOVAL_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_CHANGE_REQUESTED
  transitions:
  - ACTION_EDIT:
     nextStates: [DEPLOYMENT_STATUS_CHANGE_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_CANCEL_CHANGE_REQUEST:
     nextStates: [DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_UPDATE_STATUS:
     nextStates: [DEPLOYMENT_STATUS_CHANGE_IN_PROGRESS]
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS, CONFIG_ACCESS_TYPE_TRACEABLE]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_CHANGE_IN_PROGRESS
  transitions:
  - ACTION_UPDATE_STATUS:
     nextStates: [DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY, DEPLOYMENT_STATUS_CHANGE_BLOCKED]
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS, CONFIG_ACCESS_TYPE_TRACEABLE]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_CHANGE_BLOCKED
  transitions:
  - ACTION_EDIT:
     nextStates: [DEPLOYMENT_STATUS_CHANGE_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_REMOVAL_REQUESTED
  transitions:
  - ACTION_CANCEL_REMOVAL_REQUEST:
     nextStates: [DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_UPDATE_STATUS:
     nextStates: [DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS]
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS, CONFIG_ACCESS_TYPE_TRACEABLE]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS
  transitions:
  - ACTION_UPDATE_STATUS:
     nextStates: [DEPLOYMENT_STATUS_ON_HOLD, DEPLOYMENT_STATUS_REMOVAL_BLOCKED]
     accessTypes: [CONFIG_ACCESS_TYPE_DEVOPS, CONFIG_ACCESS_TYPE_TRACEABLE]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_REMOVAL_BLOCKED
  transitions:
  - ACTION_EDIT:
     nextStates: [DEPLOYMENT_STATUS_REMOVAL_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]

- currentState: DEPLOYMENT_STATUS_ON_HOLD
  transitions:
  - ACTION_EDIT:
     nextStates: [DEPLOYMENT_STATUS_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DEPLOY:
     nextStates: [DEPLOYMENT_STATUS_REQUESTED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DELETE:
     nextStates: [DEPLOYMENT_STATUS_DELETED]
     accessTypes: [CONFIG_ACCESS_TYPE_GLOBAL, CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]
  - ACTION_DOWNLOAD:
     nextStates: []
     accessTypes: [CONFIG_ACCESS_TYPE_TRACEABLE, CONFIG_ACCESS_TYPE_DEVOPS]