- configKey: "maxPendingHttpRequest"
  description: "Max Pending Http Requests for a service"
  displayName: "Max Pending Http Requests"
  constraint:
    intRange:
      min: 1
      max: 10000
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 2048

- configKey: "tcpConnectionTimeout"
  description: "TCP Connection Timeout in seconds"
  displayName: "TCP Connection Timeout(ms)"
  constraint:
    intRange:
      min: 0
      max: 5000
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 200

- configKey: "maxTcpConnections"
  description: "Maximum number of TCP connections allowed for a service"
  displayName: "Max TCP Connections"
  constraint:
    intRange:
      min: 0
      max: 10000
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 1024

- configKey: "tcpIdleTimeout"
  description: "TCP Idle Timeout in seconds"
  displayName: "TCP Idle Timeout(s)"
  constraint:
    intRange:
      min: 1
      max: 86400
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 3600

- configKey: "probeInterval"
  description: "Interval between TCP health probes in seconds"
  displayName: "Probe Interval(s)"
  constraint:
    intRange:
      min: 0
      max: 100
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 30

- configKey: "maxProbes"
  description: "Maximum number of TCP health probes to send"
  displayName: "Max Probes"
  constraint:
    intRange:
      min: 0
      max: 100
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 5

- configKey: "probeTimeout"
  description: "Timeout for TCP health probes in seconds"
  displayName: "Probe Timeout(s)"
  constraint:
    intRange:
      min: 0
      max: 10
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 2

- configKey: "tcpKeepaliveTime"
  description: "TCP keep alive time in seconds"
  displayName: "TCP Keepalive Time(s)"
  constraint:
    intRange:
      min: 1
      max: 3600
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 300

- configKey: "httpMaxRequests"
  description: "Maximum number of active requests to a destination"
  displayName: "HTTP Max Requests"
  constraint:
    intRange:
      min: 1
      max: 25000
  configPermission:
    read: CONFIG_ACCESS_TYPE_GLOBAL
    write: CONFIG_ACCESS_TYPE_GLOBAL
  identifiers:
    - chartName: ""
      chartPath: ""
  default_value: 5000
