syntax = "proto3";

package ai.traceable.sensitivedata.config.service.v1;

option java_multiple_files = true;
option go_package = "github.com/Traceableai/config-service/sensitivedata/v1";

service PiiTypeConfigService {
  rpc CreatePiiType(CreatePiiTypeRequest) returns (CreatePiiTypeResponse) {}
  rpc GetPiiTypes(GetPiiTypesRequest) returns (GetPiiTypesResponse) {}
  rpc DeletePiiType(DeletePiiTypeRequest) returns (DeletePiiTypeResponse) {}
}

message CreatePiiTypeRequest {
  PiiType pii_type = 1;
}

message CreatePiiTypeResponse {
  PiiType pii_type = 1;
}

message GetPiiTypesRequest {}

message GetPiiTypesResponse {
  repeated PiiType pii_types = 1;
}

message DeletePiiTypeRequest {
  string name = 1;
}

message DeletePiiTypeResponse {}

message PiiType {
  string name = 1;
  string display_name = 2;
  PiiSource pii_source = 3;
}

enum PiiSource {
  PII_SOURCE_UNSPECIFIED = 0;
  PII_SOURCE_DLP = 1;
  PII_SOURCE_CUSTOM = 2;
}
