syntax = "proto3";

package ai.traceable.sensitivedata.config.service.v1;

import "ai/traceable/sensitivedata/config/service/v1/pii_filter_config.proto";

option go_package = "github.com/Traceableai/config-service/sensitivedata/v1";
option java_multiple_files = true;

service PiiFilterConfigService {
  rpc GetPiiFilterConfig(GetPiiFilterConfigRequest) returns (GetPiiFilterConfigResponse) {}
}

message GetPiiFilterConfigRequest {
  bool include_conditional_rules = 1;
  string hash = 2;
  bool data_classification_supported = 3;
}

message GetPiiFilterConfigResponse {
  PiiFilterConfig pii_filter_config = 1;
  string hash = 2;
  bool enabled = 3;
}
