syntax = "proto3";

package ai.traceable.sensitivedata.config.service.v1;

option java_multiple_files = true;
option go_package = "github.com/Traceableai/config-service/sensitivedata/v1";

message PiiFilterConfig {
  RedactionStrategy redaction_strategy = 1;
  repeated string prefixes = 2;
  repeated PiiElement key_regexs = 3;
  repeated PiiElement value_regexs = 4;
  repeated ComplexData complex_data = 5;
}

enum RedactionStrategy {
  REDACTION_STRATEGY_UNSPECIFIED = 0;
  REDACTION_STRATEGY_REDACT = 1;
  REDACTION_STRATEGY_HASH = 2;
  REDACTION_STRATEGY_RAW = 3;
}

message PiiElement {
  string regex = 1;
  string category = 2 [deprecated = true];
  RedactionStrategy redaction_strategy = 3;
  bool session_identifier = 4;
  repeated int32 session_indexes = 5;
  string session_separator = 6;
  bool fqn = 7;
  string rule_id = 8;
}

message ComplexData {
  string key = 1;
  string type = 2;
  string type_key = 3;
}
