syntax = "proto3";

option java_multiple_files = true;

package ai.traceable.sensitivedata.config.service.v1;

import "ai/traceable/sensitivedata/config/service/v1/pii_filter_config.proto";

service SensitiveDataConfigService {
  // update the redaction strategy for the specified parameter type
  rpc UpdateRedactionStrategyForType(UpdateRedactionStrategyForTypeRequest) returns (UpdateRedactionStrategyForTypeResponse) {}

  // get the redaction strategy for the specified parameter type
  rpc GetRedactionStrategyForType(GetRedactionStrategyForTypeRequest) returns (GetRedactionStrategyForTypeResponse) {}

  // update automatic secret redaction strategy
  rpc UpdateAutomaticSecretRedactionStrategy(UpdateAutomaticSecretRedactionStrategyRequest) returns (UpdateAutomaticSecretRedactionStrategyResponse) {}

  // get automatic secret redaction strategy
  rpc GetAutomaticSecretRedactionStrategy(GetAutomaticSecretRedactionStrategyRequest) returns (GetAutomaticSecretRedactionStrategyResponse) {}
}

message UpdateRedactionStrategyForTypeRequest {
  ParamType param_type = 1;
  RedactionStrategy redaction_strategy = 2;
}

message UpdateRedactionStrategyForTypeResponse {}

message GetRedactionStrategyForTypeRequest {
  ParamType param_type = 1;
}

message GetRedactionStrategyForTypeResponse {
  RedactionStrategy redaction_strategy = 1;
}

message UpdateAutomaticSecretRedactionStrategyRequest {
  bool enabled = 1;
}

message UpdateAutomaticSecretRedactionStrategyResponse {}

message GetAutomaticSecretRedactionStrategyRequest {}

message GetAutomaticSecretRedactionStrategyResponse {
  bool enabled = 1;
}

message Parameter {
  ParamType param_type = 1;
  string name = 2;
}

enum ParamType {
  PARAM_TYPE_UNSPECIFIED = 0;
  PARAM_TYPE_HEADER = 1;
  PARAM_TYPE_QUERY = 2;
  PARAM_TYPE_BODY = 3;
}