syntax = "proto3";

package ai.traceable.sensitivedata.config.service.v1;

option go_package = "github.com/Traceableai/config-service/sensitivedata/v1";
option java_multiple_files = true;

import "ai/traceable/sensitivedata/config/service/v1/pii_filter_config.proto";
import "ai/traceable/sensitivedata/config/service/v1/redaction_rule.proto";

service SensitiveDataConfigService {
  // update the redaction strategy for the specified parameter type
  rpc UpdateRedactionStrategyForType(UpdateRedactionStrategyForTypeRequest) returns (UpdateRedactionStrategyForTypeResponse) {}

  // get the redaction strategy for the specified parameter type
  rpc GetRedactionStrategyForType(GetRedactionStrategyForTypeRequest) returns (GetRedactionStrategyForTypeResponse) {}

  // update automatic secret redaction strategy
  rpc UpdateAutomaticSecretRedactionStrategy(UpdateAutomaticSecretRedactionStrategyRequest) returns (UpdateAutomaticSecretRedactionStrategyResponse) {}

  // get automatic secret redaction strategy
  rpc GetAutomaticSecretRedactionStrategy(GetAutomaticSecretRedactionStrategyRequest) returns (GetAutomaticSecretRedactionStrategyResponse) {}

  rpc CreateRedactionRule(CreateRedactionRuleRequest) returns (CreateRedactionRuleResponse) {}

  rpc UpdateRedactionRule(UpdateRedactionRuleRequest) returns (UpdateRedactionRuleResponse) {}

  rpc GetAllRedactionRules(GetAllRedactionRulesRequest) returns (GetAllRedactionRulesResponse) {}

  rpc DeleteRedactionRule(DeleteRedactionRuleRequest) returns (DeleteRedactionRuleResponse) {}
}

message UpdateRedactionStrategyForTypeRequest {
  ParamType param_type = 1;
  RedactionStrategy redaction_strategy = 2;
}

message UpdateRedactionStrategyForTypeResponse {}

message GetRedactionStrategyForTypeRequest {
  ParamType param_type = 1;
}

message GetRedactionStrategyForTypeResponse {
  RedactionStrategy redaction_strategy = 1;
}

message UpdateAutomaticSecretRedactionStrategyRequest {
  bool enabled = 1;
}

message UpdateAutomaticSecretRedactionStrategyResponse {}

message GetAutomaticSecretRedactionStrategyRequest {}

message GetAutomaticSecretRedactionStrategyResponse {
  bool enabled = 1;
}

message CreateRedactionRuleRequest {
  NewRedactionRule new_redaction_rule = 1;
}

message CreateRedactionRuleResponse {
  RedactionRule redaction_rule = 1;
}

message UpdateRedactionRuleRequest {
  RedactionRule redaction_rule = 1;
}

message UpdateRedactionRuleResponse {
  RedactionRule redaction_rule = 1;
}

message GetAllRedactionRulesRequest {}

message GetAllRedactionRulesResponse {
  repeated RedactionRule redaction_rules = 1;
}

message DeleteRedactionRuleRequest {
  string redaction_rule_id = 1;
}

message DeleteRedactionRuleResponse {}

message Parameter {
  ParamType param_type = 1;
  string name = 2;
}

enum ParamType {
  PARAM_TYPE_UNSPECIFIED = 0;
  PARAM_TYPE_HEADER = 1;
  PARAM_TYPE_QUERY = 2;
  PARAM_TYPE_BODY = 3;
}
