syntax = "proto3";

package ai.traceable.data.parsing.config.service.v1;

import "ai/traceable/graphql/autogen/schema/annotations/field/v1/graphql_field_options.proto";

option java_multiple_files = true;

message DataParsingConfig {
  string id = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Identifier of the data parsing config"];
  int32 rank = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Rank for ordering data parsing configs"];
  DataParsingRule data_parsing_rule = 3 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "The data parsing rule"];
}

message DataParsingRule {
  bool enabled = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Data parsing rule is enabled or not"];
  oneof scope {
    GlobalScope global_scope = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Data parsing rule has global scope"];
    EnvironmentScope environment_scope = 3 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Data parsing rule is environment scoped"];
  }
  // NOTE: Keep below portion of this proto in sync with
  // the DataParsingRule proto in external-data-classification-config-service-api
  SpanFilter span_filter = 4 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Filter for spans to apply data parsing rule"];
  AttributeFilter attribute_filter = 5 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Filter for attributes to apply data parsing rule"];
  DataParsingMode mode = 6 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Mode of data parsing rule"];
  oneof failure_strategy {
    DropOnFailure drop_on_failure = 7 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Strategy to drop data on failure"];
  }

  enum DataParsingMode {
    DATA_PARSING_MODE_UNSPECIFIED = 0;
    DATA_PARSING_MODE_JSON = 1;
    DATA_PARSING_MODE_COOKIE_STRING = 2;
    DATA_PARSING_MODE_SQL = 3;
    DATA_PARSING_MODE_URL_ENCODED = 4;
    DATA_PARSING_MODE_XML = 5;
    DATA_PARSING_MODE_MULTIPART = 6;
    DATA_PARSING_MODE_CONTENT_TYPE_HEADER = 7;
    DATA_PARSING_MODE_SERVER_SENT_EVENTS = 8;
    DATA_PARSING_MODE_KEY_VALUE = 9;
  }

  message DropOnFailure {}

  message GlobalScope {}

  message EnvironmentScope {
    repeated string environment_ids = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "List of environment IDs"];
  }
}

message SpanFilter {
  // TODO - this could include things like API scoping in the future
  // This supports things like matching a url before checking for a particular param name
  repeated AttributePredicate required_matching_attributes = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Attributes required to match"];
}

message AttributeFilter {
  // This is used to, for example, restrict matches to only headers
  repeated string prefixes = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Prefixes to restrict attribute matching"];
}

message StringPredicate {
  Operator operator = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Operator for string predicate"];
  string value = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Value for string predicate"];
}

message AttributePredicate {
  StringPredicate name_predicate = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Predicate for attribute name"];
  StringPredicate value_predicate = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Predicate for attribute value"];
}

enum Operator {
  OPERATOR_UNSPECIFIED = 0;
  OPERATOR_EQUALS = 1;
  OPERATOR_MATCHES_REGEX = 2;
  OPERATOR_NOT_EQUALS = 3;
  OPERATOR_NOT_MATCHES_REGEX = 4;
}
