genAiConfig = {
  globalConfig = {
    enabled = false
  }
  issuesSummaryFeatureConfig = {
    enabled = false
  }
  threatActivitySummaryFeatureConfig = {
    enabled = false
  }
  chatbotFeatureConfig = {
    enabled = false
  }
  astAuthHookGeneratorAgentFeatureConfig = {
    enabled = false
  }
}
