riskLevelConfigValues = {
    mediumLevelMinScore = 2
    highLevelMinScore = 5
    criticalLevelMinScore = 9
}

riskFactorGridConfigValues = {
    riskFactorGridCells = [
      {
        likelihoodScoreCategory = RISK_SCORE_CATEGORY_LOW
        impactScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
        score = 3
      }
    ]
}