riskLevelConfigValues = {
    mediumLevelMinScore = 2
    highLevelMinScore = 5
    criticalLevelMinScore = 9
}

riskFactorGridConfigValues = {
    riskFactorGridCells = [
      {
        likelihoodScoreCategory = RISK_SCORE_CATEGORY_LOW
        impactScoreCategory = RISK_SCORE_CATEGORY_MEDIUM
        score = 3
      }
    ]
}

riskLikelihoodConfigs = {
    riskFactors = [
      {
        riskFactorInfo = {
          name = "custom-tag"
          riskFactorType = RISK_FACTOR_TYPE_CUSTOM_TAGS
        }
        riskFactorConfig = {
          id = "custom-tag"
          riskElementConfigs = [
            {
              id = "tag-1"
              riskElementInfo = {
                labelId = {
                  operator = STRING_OPERATOR_EQUALS
                  value = "tag1"
                }
              }
              riskElementScoring = {
                score = 3
              }
            },
            {
              id = "tag-2"
              riskElementInfo = {
                labelId = {
                  operator = STRING_OPERATOR_EQUALS
                  value = "tag2"
                }
              }
              riskElementScoring = {
                score = 4
              }
            }
          ]
        }
        customizationOptions = [CUSTOMIZATION_OPTIONS_ELEMENT_ADD_DELETE, CUSTOMIZATION_OPTIONS_FACTOR_SCORE_CONTRIBUTION]
      },
      {
        riskFactorInfo = {
          name = "motive"
          riskFactorType = RISK_FACTOR_TYPE_MOTIVE
        }
        riskFactorConfig = {
          id = "motive"
          riskElementConfigs = [
            {
              id = "response-has-pii"
              riskElementInfo = {
                responsePiiCount = {
                  operator = INT_OPERATOR_GREATER_THAN
                  value = 0
                }
              }
              riskElementScoring = {
                score = 6
              }
            }
          ]
        }
      }
    ]
}

riskImpactConfigs = {
    riskFactors = [
      {
        riskFactorInfo = {
          name = "custom-tag"
          riskFactorType = RISK_FACTOR_TYPE_CUSTOM_TAGS
        }
        riskFactorConfig = {
          id = "custom-tag"
          riskElementConfigs = [
            {
              id = "tag-1"
              riskElementInfo = {
                labelId = {
                  operator = STRING_OPERATOR_EQUALS
                  value = "tag1"
                }
              }
              riskElementScoring = {
                score = 3
              }
            },
            {
              id = "tag-2"
              riskElementInfo = {
                labelId = {
                  operator = STRING_OPERATOR_EQUALS
                  value = "tag2"
                }
              }
              riskElementScoring = {
                score = 4
              }
            }
          ]
        }
        customizationOptions = [CUSTOMIZATION_OPTIONS_ELEMENT_ADD_DELETE, CUSTOMIZATION_OPTIONS_FACTOR_SCORE_CONTRIBUTION]
      },
      {
        riskFactorInfo = {
          name = "sensitiveDataExposure"
          riskFactorType = RISK_FACTOR_TYPE_SENSITIVE_DATA_EXPOSURE
        }
        riskFactorConfig = {
          id = "sensitiveDataExposure"
          riskElementConfigs = [
            {
              id = "request-has-params"
              riskElementInfo = {
                requestParamsCount = {
                  operator = INT_OPERATOR_GREATER_THAN
                  value = 5
                }
              }
              riskElementScoring = {
                score = 7
              }
            }
          ]
        }
      }
    ]
}