default.agent.polling.frequency = 30s
get.configs.thread.pool.size = 5
custom.signature.rule.version = CUSTOM_MODSEC_RULE_VERSION_CORAZA_V3
supplier.configs =
[
  {
    configType = "EdgeDecisionEngineConfig"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.EdgeDecisionEngineConfigSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "CaptchaSiteKeyConfig"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.CaptchaSiteKeyConfigSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "CloudBotDeploymentConfig"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.CloudBotDeploymentConfigSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "ClientBotFingerprintPolicy"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.ClientBotFingerprintPolicySupplier"
    agentPollingFrequency = 30s
  },
  {
     configType = "InvisibleCaptchaPolicy"
     fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.InvisibleCaptchaPolicySupplier"
     agentPollingFrequency = 30s
  },
  {
    configType = "WebAppEvaluationConfigContext"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.WebAppEvaluationConfigContextSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "ApiProtectEvaluationConfigContext"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.ApiProtectEvaluationConfigContextSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "CustomSignatureEvaluationConfigContext"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.CustomSignatureEvaluationConfigContextSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "PreDetectionFilteringConfigContext"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.filtering.config.context.PreDetectionFilteringConfigContextSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "PostDetectionFilteringConfigContext"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.filtering.config.context.PostDetectionFilteringConfigContextSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "ApiIdResolverConfig"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.api.resolution.url.pattern.trie.ApiIdResolverConfigSupplier"
    agentPollingFrequency = 600s
  },
  {
    configType = "SecuritySchemeConfig"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.SecuritySchemeConfigSupplier"
    agentPollingFrequency = 30s
  },
  {
    configType = "AiEndpointMetadataConfig"
    fullyQualifiedClassName = "ai.traceable.edge.config.service.supplier.AiEndpointMetadataConfigSupplier"
    agentPollingFrequency = 600s
  }
]

default.variables.user-attribution =
{
    "3e761879-c77b-4d8f-a075-62ff28e8fa8a" = [
        {
          name = "userId1"
          transformation_config = {
            jexl_expression = {
              jexl_expression = "$s.getHeaders().get('authorization')"
                }
            output_type = "FIELD_TYPE_STR"
            }
        }
    ]
}