syntax = "proto3";

package ai.traceable.anomaly.config.service.detection.v2;

option java_multiple_files = true;

import "ai/traceable/anomaly/config/service/detection/v2/definitions_detection_default_configs.proto";
import "ai/traceable/anomaly/config/service/detection/v2/definitions_detection_rule_configs.proto";
import "ai/traceable/anomaly/config/service/detection/v2/definitions_detection_blocking_rule_configs.proto";


service DetectionConfigService {

  // detection_default_configs

  rpc GetAllDetectionDefaultConfigs(GetAllDetectionDefaultConfigsRequest) returns (GetAllDetectionDefaultConfigsResponse) {}

  rpc CreateDefaultEnvironmentDetectionConfig(CreateDefaultEnvironmentDetectionConfigRequest) returns (CreateDefaultEnvironmentDetectionConfigResponse) {}

  rpc UpdateDetectionDefaultConfig(UpdateDetectionDefaultConfigRequest) returns (UpdateDetectionDefaultConfigResponse) {}

  rpc DeleteDefaultEnvironmentDetectionConfig(DeleteDefaultEnvironmentDetectionConfigRequest) returns (DeleteDefaultEnvironmentDetectionConfigResponse) {}

  // detection_rule_configs

  rpc GetAllOrderedDetectionRules(GetAllOrderedDetectionRulesRequest) returns (GetAllOrderedDetectionRulesResponse) {}

  rpc CreateDetectionRuleConfig(CreateDetectionRuleConfigRequest) returns (CreateDetectionRuleConfigResponse) {}

  rpc UpdateDetectionRule(UpdateDetectionRuleRequest) returns (UpdateDetectionRuleResponse) {}

  rpc DeleteDetectionRule(DeleteDetectionRuleRequest) returns (DeleteDetectionRuleResponse) {}

  // detection_blocking_rule_configs

  rpc GetAllDetectionBlockingRules(GetAllDetectionBlockingRulesRequest) returns (GetAllDetectionBlockingRulesResponse) {}

  rpc CreateDetectionBlockingRuleConfig(CreateDetectionBlockingRuleConfigRequest) returns (CreateDetectionBlockingRuleConfigResponse) {}

  rpc UpdateDetectionBlockingRule(UpdateDetectionBlockingRuleRequest) returns (UpdateDetectionBlockingRuleResponse) {}

  rpc DeleteDetectionBlockingRule(DeleteDetectionBlockingRuleRequest) returns (DeleteDetectionBlockingRuleResponse) {}

}
