syntax = "proto3";

package ai.traceable.anomaly.config.service.detection.v2;

import "ai/traceable/anomaly/config/service/detection/v2/detection_common_configs.proto";
import "ai/traceable/anomaly/config/service/detection/v2/detection_scope_config.proto";
import "ai/traceable/anomaly/config/service/detection/v2/detection_threat_activity_config.proto";
import "ai/traceable/anomaly/config/service/detection/v2/detection_actor_config.proto";

option java_multiple_files = true;

message DetectionDefaultConfig {
  DetectionDefaultScopeConfig scope_config = 1;
  DetectionDefaultConfigDetails config_details = 2;
}

message DetectionDefaultScopeConfig {
  oneof scope {
    DetectionTenantScope tenant_scope = 1;
    DetectionEnvironmentScope environment_scope = 2;
  }
}

message DetectionDefaultConfigDetails {
  DetectionConfigAction action = 1;
  DetectionConfidence confidence = 2;
}


message GetAllDetectionDefaultConfigsRequest {
}

message GetAllDetectionDefaultConfigsResponse {
  repeated DetectionDefaultConfig default_configs = 2;
}

message CreateDefaultEnvironmentDetectionConfigRequest {
  DetectionEnvironmentScope environment_scope = 1;
  DetectionDefaultConfigDetails config_details = 2;
}

message CreateDefaultEnvironmentDetectionConfigResponse {
  DetectionDefaultConfig config = 1;
}

message UpdateDetectionDefaultConfigRequest {
  DetectionDefaultConfig config = 1;
}

message UpdateDetectionDefaultConfigResponse {
  DetectionDefaultConfig config = 1;
}

message DeleteDefaultEnvironmentDetectionConfigRequest {
  DetectionEnvironmentScope environment_scope = 1;
}

message DeleteDefaultEnvironmentDetectionConfigResponse {
}
