syntax = "proto3";

package ai.traceable.anomaly.config.service.detection.v2;

import "ai/traceable/anomaly/config/service/detection/v2/detection_common_configs.proto";
import "ai/traceable/anomaly/config/service/detection/v2/detection_scope_config.proto";
import "ai/traceable/anomaly/config/service/detection/v2/detection_threat_activity_config.proto";
import "ai/traceable/anomaly/config/service/detection/v2/detection_actor_config.proto";
import "ai/traceable/anomaly/config/service/detection/v2/detection_conditions_config.proto";

option java_multiple_files = true;


message DetectionRule {
  string id = 1;
  string description = 2;
  DetectionRuleConfig config = 3;
}

message DetectionRuleConfig {
  int64 priority = 1;
  DetectionConfigCriteria detection_criteria = 2;
  DetectionConfigStatus config_status = 3;
}

message DetectionConfigCriteria {
  DetectionConfigAction action = 1;
  DetectionThreatActivityConfig threat_activity_config = 2;
  DetectionActorConfig actor_config = 3;
  DetectionAssetConfig target_config = 4;
  DetectionAssetConfig source_config = 5; // optional, only applicable for sessions
}

message DetectionAssetConfig {
  DetectionScopeConfig detection_scope = 4;
  DetectionConditionsConfig conditions_config = 6;
}

message DetectionConfigStatus {
  bool rule_disabled = 1;
  bool rule_hidden_from_customer = 2;
}

message GetAllOrderedDetectionRulesRequest {
}

message GetAllOrderedDetectionRulesResponse {
  repeated DetectionRule rules = 1;
}

message CreateDetectionRuleConfigRequest {
  string description = 1;
  DetectionRuleConfig config = 2;
}

message CreateDetectionRuleConfigResponse {
  DetectionRule rule = 1;
}

message UpdateDetectionRuleRequest {
  DetectionRule rule = 1;
}

message UpdateDetectionRuleResponse {
  DetectionRule rule = 1;
}

message DeleteDetectionRuleRequest {
  string rule_id = 1;
}

message DeleteDetectionRuleResponse {
}
