syntax = "proto3";

package ai.traceable.saved.filter.config.service.v1;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option java_multiple_files = true;

message SavedFilter {
  // Unique ID generated for a saved filter
  string id = 1;
  // Name of the saved filter
  string name = 2;
  // Usually the entity to which the saved filter is associated to
  string scope = 3;
  // Visibility of the saved filter
  Visibility visibility = 4;
  // Filtering criteria
  FilterCriteria filter_criteria = 5;
  // ID of the user who created the saved filter
  string created_by_user_id = 6;
  // Creation timestamp of the saved filter
  google.protobuf.Timestamp created_timestamp = 7;
  // Last updated timestamp of the saved filter
  google.protobuf.Timestamp updated_timestamp = 8;

  string category = 9;
}

message Visibility {
  oneof visibility_type {
    // The saved filter will be available only for the user who created it
    PrivateVisibility private = 1;
    // The saved filter will be available across all users
    PublicVisibility public = 2;
  }
}

message PrivateVisibility {}

message PublicVisibility {}

message FilterCriteria {
  oneof filter_condition {
    LogicalFilterCondition logical_filter = 1;
    RelationalFilterCondition relational_filter = 2;
    ArrayFilterCondition array_filter = 3;
    FilterCriteria negated_filter = 4;
  }
}

message LogicalFilterCondition {
  LogicalOperator operator = 1;
  repeated FilterCriteria filter_criteria = 2;
}

message RelationalFilterCondition {
  // Filed name for the filter condition
  string field_name = 1 [deprecated = true];
  Expression lhs_expression = 4;
  // Comparison operator for the condition
  RelationalOperator operator = 2;
  // Value to compare with
  google.protobuf.Value field_value = 3 [deprecated = true];
  Expression rhs_expression = 5;
}

message ArrayFilterCondition {
  ArrayOperator operator = 1;

  oneof type {
    RelationalFilterCondition relational_filter = 2;
  }
}

message Expression {
  oneof type {
    Field field = 1;
    google.protobuf.Value value = 2;
  }
}

message Field {
  // In case a scope is missing, we will consider the scope of the filter itself
  optional string scope = 1;
  string key = 2;
}

enum LogicalOperator {
  LOGICAL_OPERATOR_UNSPECIFIED = 0;
  LOGICAL_OPERATOR_AND = 1;
  LOGICAL_OPERATOR_OR = 2;
}

enum RelationalOperator {
  RELATIONAL_OPERATOR_UNSPECIFIED = 0;
  RELATIONAL_OPERATOR_EQ = 1;
  RELATIONAL_OPERATOR_NEQ = 2;
  RELATIONAL_OPERATOR_IN = 3;
  RELATIONAL_OPERATOR_NOT_IN = 4;
  RELATIONAL_OPERATOR_LESS_THAN = 5;
  RELATIONAL_OPERATOR_LESS_THAN_OR_EQUAL_TO = 6;
  RELATIONAL_OPERATOR_GREATER_THAN = 7;
  RELATIONAL_OPERATOR_GREATER_THAN_OR_EQUAL_TO = 8;
  RELATIONAL_OPERATOR_REGEX_MATCHES = 9;
}

enum ArrayOperator {
  ARRAY_OPERATOR_UNSPECIFIED = 0;
  ARRAY_OPERATOR_ANY = 1;
  ARRAY_OPERATOR_ALL = 2;
}
