riskFactors = [
  {
    riskFactorInfo = {
      name = "Custom Tags"
      riskFactorType = RISK_FACTOR_TYPE_CUSTOM_TAGS
    }
    riskFactorConfig = {
      id = "customTagsLikelihood"
      riskElementConfigs = [
        {
          id = "criticalLikelihood"
          riskElementInfo = {
            name = "Critical"
            labelId = {
              operator = STRING_OPERATOR_EQUALS
              value = "Critical"
            }
          }
          riskElementScoring = {
            score = 0
          }
        },
        {
          id = "sensitiveLikelihood"
          riskElementInfo = {
            name = "Sensitive"
            labelId = {
              operator = STRING_OPERATOR_EQUALS
              value = "Sensitive"
            }
          }
          riskElementScoring = {
            score = 0
          }
        }
      ]
    }
    customizationOptions = [CUSTOMIZATION_OPTIONS_FACTOR_SCORE_CONTRIBUTION, CUSTOMIZATION_OPTIONS_ELEMENT_ADD_DELETE]
  },
  {
    riskFactorInfo = {
      name = "Motive"
      riskFactorType = RISK_FACTOR_TYPE_MOTIVE
    }
    riskFactorConfig = {
      id = "motive"
      riskElementConfigs = [
        {
          id = "responseHasPii"
          riskElementInfo = {
            name = "Response has PII"
            responsePiiCount = {
              operator = INT_OPERATOR_EQUALS
              value = 0
            }
          }
          riskElementScoring = {
            score = 8
          }
        }
      ]
    }
  },
  {
    riskFactorInfo = {
      name = "Ease Of Access"
      riskFactorType = RISK_FACTOR_TYPE_EASE_OF_ACCESS
    }
    riskFactorConfig = {
      id = "easeOfAccess"
      riskElementConfigs = [
        {
          id = "endpointInternalRestricted"
          riskElementInfo = {
            name = "Endpoint is Internal and Restricted"
            endpointInternalRestricted = {
              value = true
            }
          }
          riskElementScoring = {
            score = 1
          }
        },
        {
          id = "endpointInternalPopular"
          riskElementInfo = {
            name = "Endpoint is Internal and Popular"
            endpointInternalPopular = {
              value = true
            }
          }
          riskElementScoring = {
            score = 5
          }
        },
        {
          id = "endpointExternalRestricted"
          riskElementInfo = {
            name = "Endpoint is External and Restricted"
            endpointExternalRestricted = {
              value = true
            }
          }
          riskElementScoring = {
            score = 6
          }
        },
        {
          id = "endpointExternalPopular"
          riskElementInfo = {
            name = "Endpoint is Internal and Popular"
            endpointExternalPopular = {
              value = true
            }
          }
          riskElementScoring = {
            score = 10
          }
        }
      ]
    }
  }
]