syntax = "proto3";

package ai.traceable.integration.config.service.snyk.v1;

import "ai/traceable/integration/config/service/snyk/v1/snyk_integration.proto";

option java_multiple_files = true;

service SnykIntegrationService {
  rpc GetSnykIntegrationSummary(GetSnykIntegrationSummaryRequest) returns (GetSnykIntegrationSummaryResponse) {}
  rpc GetSnykIntegrationDetails(GetSnykIntegrationDetailsRequest) returns (GetSnykIntegrationDetailsResponse) {}
  rpc CreateSnykIntegration(CreateSnykIntegrationRequest) returns (CreateSnykIntegrationResponse) {}
  rpc UpdateSnykIntegration(UpdateSnykIntegrationRequest) returns (UpdateSnykIntegrationResponse) {}
  rpc DeleteSnykIntegration(DeleteSnykIntegrationRequest) returns (DeleteSnykIntegrationResponse) {}
}

message GetSnykIntegrationSummaryRequest {}

message GetSnykIntegrationSummaryResponse {}

message GetSnykIntegrationDetailsRequest {}

message GetSnykIntegrationDetailsResponse {
  SnykIntegration snyk_integration = 1;
}

message CreateSnykIntegrationRequest {
  EncryptedText api_token = 1;
  SnykBaseUrls snyk_base_urls = 2;
}

message CreateSnykIntegrationResponse {}

message UpdateSnykIntegrationRequest {
  EncryptedText api_token = 1;
  SnykBaseUrls snyk_base_urls = 2;
}

message UpdateSnykIntegrationResponse {}

message DeleteSnykIntegrationRequest {}

message DeleteSnykIntegrationResponse {}
