syntax = "proto3";

package ai.traceable.detection.exclusion.config.service.v1;

import "ai/traceable/config/commons/v1/audit.proto";
import "ai/traceable/detection/exclusion/config/service/v1/detection_exclusion_rule.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_config.proto";

option java_multiple_files = true;

message CreateDetectionExclusionRuleRequest {
  DetectionExclusionRuleScope rule_scope = 1;
  DetectionExclusionRuleInfo rule_info = 2;
}

message CreateDetectionExclusionRuleResponse {
  DetectionExclusionRule rule = 1;
}

message UpdateDetectionExclusionRuleRequest {
  DetectionExclusionRule rule = 1;
}

message UpdateDetectionExclusionRuleResponse {
  DetectionExclusionRule rule = 1;
}

message DeleteDetectionExclusionRuleRequest {
  string id = 1;
}

message DeleteDetectionExclusionRuleResponse {}

message GetDetectionExclusionRulesRequest {
  GetRulesFilter filter = 1;
}

message GetDetectionExclusionRulesResponse {
  repeated DetectionExclusionRule rules = 1;
  repeated DetectionExclusionRuleRecord rule_records = 2;
}

message DetectionExclusionRuleRecord {
  DetectionExclusionRule rule = 1;
  ai.traceable.config.commons.v1.AuditDetails audit_details = 2;
}

message GetDetectionExclusionEdgeDecisionRulesRequest {
  GetRulesFilter filter = 1;
}

message GetDetectionExclusionEdgeDecisionRulesResponse {
  ai.traceable.edge.decision.config.service.v1.EdgeDecisionEngineConfig edge_decision_engine_config = 1;
}

message BulkUpsertDetectionExclusionRulesRequest {
  repeated UpsertDetectionExclusionRuleData rules = 1;
}

message BulkUpsertDetectionExclusionRulesResponse {
  repeated DetectionExclusionRule rules = 1;
}

message BulkDeleteDetectionExclusionRulesRequest {
  repeated string ids = 1;
}

message BulkDeleteDetectionExclusionRulesResponse {}

message BulkUpdateDetectionExclusionRulesRequest {
  repeated string ids = 1;
  bool disabled = 2;
  // future extensions: add/remove rule_scope(s)
}

message BulkUpdateDetectionExclusionRulesResponse {}

message GetRulesFilter {
  repeated string rule_ids = 1;
  DetectionExclusionRuleScope rule_scope = 2;
  optional bool disabled = 3;
  optional bool hidden = 4;
  repeated RuleChangeSource rule_change_sources = 5 [deprecated = true];
  repeated RuleSource rule_creation_sources = 6;
  repeated RuleIntent rule_intents = 7;
  repeated ExclusionTarget exclusion_targets = 8;
  repeated RuleEvaluationPoint rule_evaluation_points = 9;
  ai.traceable.config.commons.v1.AuditFilter audit_filter = 10;
}

message DetectionExclusionMigrationConfig {
  bool migration_completed = 1;
  // exclusion target addition
  bool change_log_2_migration_completed = 2;
  // SSTI parent rule fix
  bool change_log_3_migration_completed = 3;
  // marking rules with source conditions as hidden
  bool change_log_4_migration_completed = 4;
  // migration with respect to the addition of rule evaluation points
  bool rule_evaluation_points_migration_completed = 5;
  // migration for revamp of api protection exclusion rules
  bool api_protection_exclusion_rules_migration_completed = 6;
  // migration for removal of PLATFORM rule evaluation point when EXCLUDE_FROM_ALLOW is the only exclusion target
  bool allow_only_platform_removal_migration_completed = 7;
  // re-migration to fix rule evaluation points computed using allMatch for exclusion targets (should be anyMatch)
  bool exclusion_target_any_match_fix_migration_completed = 8;
}

message GetExclusionModsecRulesRequest {
  GetRulesFilter rules_filter = 1;
  repeated string service_names = 2;
}

message GetExclusionModsecRulesResponse {
  string modsec_directives_blob = 1;
  repeated ModsecBlobData modsec_blobs_data = 2;
  repeated DetectionExclusionModsecRule modsec_rules = 3;
}

message ModsecBlobData {
  string modsec_blob = 1;
  repeated string service_names = 2;
  repeated string rule_ids = 3;
}

message UpsertDetectionExclusionRuleData {
  DetectionExclusionRuleScope rule_scope = 1;
  DetectionExclusionRuleInfo rule_info = 2;
  oneof id {
    bool uuid_from_name_and_source = 3;
    bool random_uuid = 4;
    string pre_defined_id = 5;
  }
}
