syntax = "proto3";

package ai.traceable.detection.exclusion.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/detection/exclusion/config/service/v1/detection_exclusion_rule.proto";

message CreateDetectionExclusionRuleRequest {
  DetectionExclusionRuleScope rule_scope = 1;
  DetectionExclusionRuleInfo rule_info = 2;
}

message CreateDetectionExclusionRuleResponse {
  DetectionExclusionRule rule = 1;
}

message UpdateDetectionExclusionRuleRequest {
  DetectionExclusionRule rule = 1;
}

message UpdateDetectionExclusionRuleResponse {
  DetectionExclusionRule rule = 1;
}

message DeleteDetectionExclusionRuleRequest {
  string id = 1;
}

message DeleteDetectionExclusionRuleResponse {
}

message GetDetectionExclusionRulesRequest {
  GetRulesFilter filter = 1;
}

message GetDetectionExclusionRulesResponse {
  repeated DetectionExclusionRule rules = 1;
}

message BulkUpsertDetectionExclusionRulesRequest {
  repeated UpsertDetectionExclusionRuleData rules = 1;
}

message BulkUpsertDetectionExclusionRulesResponse {
  repeated DetectionExclusionRule rules = 1;
}

message BulkDeleteDetectionExclusionRulesRequest {
  repeated string ids = 1;
}

message BulkDeleteDetectionExclusionRulesResponse {
}

message GetRulesFilter {
  repeated string rule_ids = 1;
  DetectionExclusionRuleScope rule_scope = 2;
  optional bool disabled = 3;
  optional bool hidden = 4;
  repeated RuleChangeSource rule_change_sources = 5 [deprecated = true];
  repeated RuleSource rule_creation_sources = 6;
  repeated RuleIntent rule_intents = 7;
  repeated ExclusionTarget exclusion_targets = 8;
}

message DetectionExclusionMigrationConfig {
  bool migration_completed = 1;
  // exclusion target addition
  bool change_log_2_migration_completed = 2;
  // SSTI parent rule fix
  bool change_log_3_migration_completed = 3;
  // marking rules with source conditions as hidden
  bool change_log_4_migration_completed = 4;
}

message GetExclusionModsecRulesRequest{
  GetRulesFilter rules_filter = 1;
  repeated string service_names = 2;
}

message GetExclusionModsecRulesResponse {
  string modsec_directives_blob = 1;
  repeated ModsecBlobData modsec_blobs_data = 2;
  repeated DetectionExclusionModsecRule modsec_rules = 3;
}

message ModsecBlobData {
  string modsec_blob = 1;
  repeated string service_names = 2;
  repeated string rule_ids = 3;
}

message UpsertDetectionExclusionRuleData {
  DetectionExclusionRuleScope rule_scope = 1;
  DetectionExclusionRuleInfo rule_info = 2;
}
