syntax = "proto3";

package ai.traceable.detection.exclusion.config.service.v1;

import "ai/traceable/detection/exclusion/config/service/v1/detection_event_details.proto";
import "ai/traceable/detection/exclusion/config/service/v1/detection_match_condition_details.proto";
import "ai/traceable/detection/exclusion/config/service/v1/detection_scope_details.proto";

option java_multiple_files = true;

message RequestScannerTypeCondition {
  repeated string scanner_types = 1;
  bool exclude = 2;
}

message ScopeCondition {
  oneof scope {
    EntityScope entity_scope = 1;
    LabelScope label_scope = 2;
    UrlScope url_scope = 3;
  }
  bool exclude = 4;
}

message SpanAttributeMatchCondition {
  KeyMetadataMatchCondition key_match_condition = 1;
  MatchCondition value_match_condition = 2;
}

message IpLocationTypeCondition {
  repeated IpLocationType ip_location_types = 1;
  bool exclude = 2;
}

enum IpLocationType {
  IP_LOCATION_TYPE_UNSPECIFIED = 0;
  IP_LOCATION_TYPE_ANONYMOUS_VPN = 1;
  IP_LOCATION_TYPE_HOSTING_PROVIDER = 2;
  IP_LOCATION_TYPE_PUBLIC_PROXY = 3;
  IP_LOCATION_TYPE_TOR_EXIT_NODE = 4;
  IP_LOCATION_TYPE_BOT = 7;
  IP_LOCATION_TYPE_SCANNER = 8;
}

message IpReputationCondition {
  oneof reputation {
    IpReputationSeverity max_ip_reputation_severity = 1;
    int32 max_ip_reputation_score = 2;
  }
}

message UserIdCondition {
  repeated string user_id_regexes = 1;
  repeated string actor_entity_ids = 2; // not supported currently
  repeated string user_ids = 3;
  bool exclude = 4;
}

enum IpReputationSeverity {
  IP_REPUTATION_SEVERITY_UNSPECIFIED = 0;
  IP_REPUTATION_SEVERITY_LOW = 1;
  IP_REPUTATION_SEVERITY_MEDIUM = 2;
  IP_REPUTATION_SEVERITY_HIGH = 3;
  IP_REPUTATION_SEVERITY_CRITICAL = 4;
}

message EventCondition {
  repeated SystemDefinedEvent system_defined_events = 1;
  repeated CustomRuleEvent custom_rule_events = 2;
  repeated ThreatActorEvent threat_actor_events = 3;
}

message AnomalousAttributeCondition {
  MatchCondition key_match_condition = 1;
  MatchCondition value_match_condition = 2;
  repeated AttributeValueType observed_types = 3;
  repeated AttributeValueType learnt_types = 4;
}

message IpAddressCondition {
  repeated string cidr_ip_ranges = 1;
  repeated string ip_addresses = 2;
  repeated string raw_input_ip_data = 3;
  IpAddressConditionType ip_address_condition_type = 4;
  bool exclude = 5;
}

message IpConnectionTypeCondition {
  repeated IpConnectionType ip_connection_types = 1;
  bool exclude = 2;
}

message IpOrganisationCondition {
  repeated string ip_organisation_regexes = 1;
  bool exclude = 2;
}

message IpAsnCondition {
  repeated string ip_asn_regexes = 1;
  bool exclude = 2;
}

message IpAbuseVelocityCondition {
  IpAbuseVelocity max_ip_abuse_velocity = 1;
}

message RegionCondition {
  repeated Region regions = 1;
  bool exclude = 2;

  message Region {
    oneof region {
      string country_iso_code = 1;
    }
  }
}

message EmailDomainCondition {
  repeated string email_domains = 1;
  repeated string email_regexes = 2;
  bool exclude = 3;
}

message UserAgentCondition {
  repeated string user_agents = 1;
  repeated string user_agent_regexes = 2;
  bool exclude = 3;
}

enum IpAbuseVelocity {
  IP_ABUSE_VELOCITY_UNSPECIFIED = 0;
  IP_ABUSE_VELOCITY_LOW = 1;
  IP_ABUSE_VELOCITY_MEDIUM = 2;
  IP_ABUSE_VELOCITY_HIGH = 3;
}

enum IpConnectionType {
  IP_CONNECTION_TYPE_UNSPECIFIED = 0;
  IP_CONNECTION_TYPE_RESIDENTIAL = 1;
  IP_CONNECTION_TYPE_MOBILE = 2;
  IP_CONNECTION_TYPE_CORPORATE = 3;
  IP_CONNECTION_TYPE_DATA_CENTER = 4;
  IP_CONNECTION_TYPE_EDUCATION = 5;
}

enum AttributeValueType {
  ATTRIBUTE_VALUE_TYPE_UNSPECIFIED = 0;
  ATTRIBUTE_VALUE_TYPE_BOOLEAN = 1;
  ATTRIBUTE_VALUE_TYPE_INTEGER = 2;
  ATTRIBUTE_VALUE_TYPE_FLOAT = 3;
  ATTRIBUTE_VALUE_TYPE_CHAR = 4;
  ATTRIBUTE_VALUE_TYPE_STRING = 5;
  ATTRIBUTE_VALUE_TYPE_OBJECT = 6;
  ATTRIBUTE_VALUE_TYPE_URL = 7;
  ATTRIBUTE_VALUE_TYPE_EMAIL = 8;
  ATTRIBUTE_VALUE_TYPE_JSON = 9;
  ATTRIBUTE_VALUE_TYPE_CREDIT_CARD = 10;
  ATTRIBUTE_VALUE_TYPE_DATE = 11;
  ATTRIBUTE_VALUE_TYPE_ARRAY = 12;
  ATTRIBUTE_VALUE_TYPE_HTML = 13;
  ATTRIBUTE_VALUE_TYPE_RICH_TEXT_HTML = 14;
  ATTRIBUTE_VALUE_TYPE_CLOB = 15;
  ATTRIBUTE_VALUE_TYPE_FREE_TEXT = 16;
  ATTRIBUTE_VALUE_TYPE_COMMAND_OR_CODE = 17;
  ATTRIBUTE_VALUE_TYPE_FILTER_QUERY = 18;
}

enum IpAddressConditionType {
  IP_ADDRESS_CONDITION_TYPE_UNSPECIFIED = 0;
  IP_ADDRESS_CONDITION_TYPE_ALL_INTERNAL = 2;
  IP_ADDRESS_CONDITION_TYPE_ALL_EXTERNAL = 3;
}
