syntax = "proto3";

package ai.traceable.detection.exclusion.config.service.v1;

import "google/protobuf/struct.proto";

option java_multiple_files = true;

message KeyMetadataMatchCondition {
  KeyMetadata metadata = 1;
  MatchCondition match_condition = 2; // optional, depending on the metadata
}

enum KeyMetadata {
  KEY_METADATA_UNSPECIFIED = 0;
  KEY_METADATA_URL = 1;
  KEY_METADATA_HOST = 2;
  KEY_METADATA_HTTP_METHOD = 3;
  KEY_METADATA_USER_AGENT = 4;
  KEY_METADATA_STATUS_CODE = 5;
  KEY_METADATA_REQUEST_BODY = 6;
  KEY_METADATA_RESPONSE_BODY = 7;
  KEY_METADATA_REQUEST_HEADER = 8;
  KEY_METADATA_RESPONSE_HEADER = 9;
  KEY_METADATA_REQUEST_COOKIE = 10;
  KEY_METADATA_RESPONSE_COOKIE = 11;
  KEY_METADATA_QUERY_PARAMETER = 12;
  KEY_METADATA_REQUEST_BODY_PARAMETER = 13;
  KEY_METADATA_RESPONSE_BODY_PARAMETER = 14;
  KEY_METADATA_RESPONSE_BODY_SIZE = 15;
  KEY_METADATA_TAG = 16;
  KEY_METADATA_REQUEST_BODY_SIZE = 17;
  KEY_METADATA_QUERY_PARAMS_COUNT = 18;
  KEY_METADATA_REQUEST_HEADERS_COUNT = 19;
  KEY_METADATA_RESPONSE_HEADERS_COUNT = 20;
  KEY_METADATA_REQUEST_COOKIES_COUNT = 21;
  KEY_METADATA_RESPONSE_COOKIES_COUNT = 22;
}

message MatchCondition {
  MatchOperator operator = 1;
  google.protobuf.Value value = 2;
}

enum MatchOperator {
  MATCH_OPERATOR_UNSPECIFIED = 0;
  MATCH_OPERATOR_EQUALS = 1;
  MATCH_OPERATOR_NOT_EQUAL = 2;
  MATCH_OPERATOR_MATCHES_REGEX = 3;
  MATCH_OPERATOR_NOT_MATCH_REGEX = 4;
  MATCH_OPERATOR_GREATER_THAN = 5;
  MATCH_OPERATOR_LESS_THAN = 6;
}
