syntax = "proto3";
package ai.traceable.detection.exclusion.config.service.v1;

import "ai/traceable/detection/exclusion/config/service/v1/detection_match_condition_details.proto";

option java_multiple_files = true;

message SystemDefinedEvent {
  SystemDefinedEventFamily event_family = 1;
  oneof type_id {
    string event_type_id = 2;
    string event_sub_type_id = 3;
  }
  MatchCondition description_match_condition = 4;
}

enum SystemDefinedEventFamily {
  SYSTEM_DEFINED_EVENT_FAMILY_UNSPECIFIED = 0;
  SYSTEM_DEFINED_EVENT_FAMILY_API_DEF = 1;
  SYSTEM_DEFINED_EVENT_FAMILY_MODSEC = 2;
  SYSTEM_DEFINED_EVENT_FAMILY_SESSION = 3;
  SYSTEM_DEFINED_EVENT_FAMILY_VOLUMETRIC = 4;
  SYSTEM_DEFINED_EVENT_FAMILY_CREDENTIAL_STUFFING = 5;
  SYSTEM_DEFINED_EVENT_FAMILY_GEN_AI = 6;
}

message CustomRuleEvent {
  CustomRuleFamily rule_family = 1;
  optional string rule_id = 2;
}

enum CustomRuleFamily {
  CUSTOM_RULE_FAMILY_UNSPECIFIED = 0;
  CUSTOM_RULE_FAMILY_SIGNATURE = 1;
  CUSTOM_RULE_FAMILY_RATE_LIMIT = 2;
  CUSTOM_RULE_FAMILY_MALICIOUS_SOURCES = 3;
  CUSTOM_RULE_FAMILY_DATA_LOSS_PREVENTION = 4;
  CUSTOM_RULE_FAMILY_ENUMERATION = 5;
}

message ThreatActorEvent {
  ThreatActorIdentifier threat_actor_identifier = 1;
  oneof identifier {
    string actor_entity_id = 2;
  }
}

enum ThreatActorIdentifier {
  THREAT_ACTOR_IDENTIFIER_UNSPECIFIED = 0;
  THREAT_ACTOR_IDENTIFIER_ACTOR_ENTITY_ID = 1;
}
