apiProtectThreatRuleIdToConfigMap = [
  {
    configStatus = {
      disabled = true
      internal = true
    }
    apiProtectAnomalyDetectionConfig = {
      apiProtectAnomalyRule = {
        anomalyRuleId = "ssrf"
      }
    }
  },
  {
    apiProtectAnomalyDetectionConfig = {
      apiProtectAnomalyRule = {
        anomalyRuleId = "parameterAnomaly"
        subRuleConfigs = [
          {
            subRuleId = "parameterAnomaly_sct"
            anomalyRuleAction = "ANOMALY_RULE_ACTION_DISABLE"
          }
        ]
      }
    }
  },
  {
    apiProtectAnomalyDetectionConfig = {
      apiProtectAnomalyRule = {
        anomalyRuleId = "schemaValidation"
        subRuleConfigs = [
          {
            subRuleId = "schemaValidation_ureqp"
            anomalyRuleAction = "ANOMALY_RULE_ACTION_DISABLE"
          }
        ]
      }
    }
  },
  {
    apiProtectAnomalyDetectionConfig = {
      apiProtectAnomalyRule = {
        anomalyRuleId = "contentAnomaly"
        subRuleConfigs = [
          {
            subRuleId = "contentAnomaly_reqce"
            anomalyRuleAction = "ANOMALY_RULE_ACTION_DISABLE"
          }
        ]
      }
    }
  },
  {
    apiProtectAnomalyDetectionConfig = {
      apiProtectAnomalyRule = {
        anomalyRuleId = "authzv"
        subRuleConfigs = [
          {
            subRuleId = "authzv_bfla"
            anomalyRuleAction = "ANOMALY_RULE_ACTION_DISABLE"
          }
        ]
      }
    }
  },
  // GraphQL rules
  {
    configStatus = {
      disabled = false
    }
    apiProtectAnomalyDetectionConfig = {
      apiProtectAnomalyRule = {
        anomalyRuleId = "gqla"
        subRuleConfigs = [
          {
            subRuleId = "gqla_iq"
            anomalyRuleAction = "ANOMALY_RULE_ACTION_DISABLE"
          },
          {
            subRuleId = "gqla_fda"
            anomalyRuleAction = "ANOMALY_RULE_ACTION_DISABLE"
            configParams = {
              "max_duplicates" = 10
            }
          },
          {
            subRuleId = "gqla_drq"
            configParams = {
              "max_depth" = 10
            }
          },
          {
            subRuleId = "gqla_aba"
            configParams = {
              "max_aliases" = 10
            }
          },
          {
            subRuleId = "gqla_bqa"
            configParams = {
              "max_batches" = 10
            }
          },
          {
            subRuleId = "gqla_gdlb"
            configParams = {
              "field_deny_list" = ["systemHealth"]
              "operation_deny_list" = ["systemHealth"]
            }
          }
        ]
      }
    }
  },
  // JWT rules
  {
    configStatus = {
      disabled = true
      internal = true
    }
    apiProtectAnomalyDetectionConfig = {
      apiProtectAnomalyRule = {
        anomalyRuleId = "jwt"
        subRuleConfigs = [
          {
            subRuleId = "jwt_iss"
            configParams = {
              "min_percent_seen" = 0.2
            }
          },
          {
            subRuleId = "jwt_aud"
            configParams = {
              "min_percent_seen" = 0.2
            }
          },
          {
            subRuleId = "jwt_alg"
            configParams = {
              "min_percent_seen" = 0.2
            }
          },
          {
            subRuleId = "jwt_sign"
            configParams = {
              "min_percent_seen" = 0.2
            }
          },
          {
            subRuleId = "jwt_albeast"
            configParams = {
              "min_percent_seen" = 0.2
            }
          },
          {
            subRuleId = "jwt_jku"
            configParams = {
              "min_percent_seen" = 0.2
            }
          }
        ]
      }
    }
  }
]