apiProtectThreatRuleIdToConfigMap = [
  // GraphQL rules
  {
    ruleId = "gqla_drq"
    configs = [
      {
        key = "max_depth"
        value = "10"
      }
    ]
  },
  {
    ruleId = "gqla_aba"
    configs = [
      {
        key = "max_aliases"
        value = "10"
      }
    ]
  },
  {
    ruleId = "gqla_fda"
    configs = [
      {
        key = "max_duplicates"
        value = "10"
      }
    ]
  },
  {
    ruleId = "gqla_bqa"
    configs = [
      {
        key = "max_batches"
        value = "10"
      }
    ]
  },
  {
    ruleId = "gqla_gdlb"
    configs = [
      {
        key = "field_deny_list"
        value = ["systemHealth"]
      },
      {
        key = "operation_deny_list"
        value = ["systemHealth"]
      }
    ]
  },
  // JWT rules
  {
    ruleId = "jwt_iss"
    configs = [
      {
        key = "min_percent_seen"
        value = 0.2
      }
    ]
  },
  {
    ruleId = "jwt_aud"
    configs = [
      {
        key = "min_percent_seen"
        value = 0.2
      }
    ]
  },
  {
    ruleId = "jwt_alg"
    configs = [
      {
        key = "min_percent_seen"
        value = 0.2
      }
    ]
  },
  {
    ruleId = "jwt_sign"
    configs = [
      {
        key = "min_percent_seen"
        value = 0.2
      }
    ]
  },
  {
    ruleId = "jwt_albeast"
    configs = [
      {
        key = "min_percent_seen"
        value = 0.2
      }
    ]
  },
  {
    ruleId = "jwt_jku"
    configs = [
      {
        key = "min_percent_seen"
        value = 0.2
      }
    ]
  }
]