syntax = "proto3";

package ai.traceable.threatmanagement.config.service.v1;

option java_multiple_files = true;

message GetAnomalyScoreContributionRequest {
}

message GetAnomalyScoreContributionResponse {
  AnomalyScoreContribution anomaly_score_contribution = 1;
  AnomalyScoreContribution default_anomaly_score_contribution = 2;
}

message UpdateAnomalyScoreContributionRequest {
  AnomalyScoreContribution anomaly_score_contribution = 1;
}

message UpdateAnomalyScoreContributionResponse {
  AnomalyScoreContribution anomaly_score_contribution = 1;
  AnomalyScoreContribution default_anomaly_score_contribution = 2;
}

message AnomalyScoreContribution {
  int32 anomaly_score = 1;
}
