syntax = "proto3";

package ai.traceable.threatmanagement.config.service.v1;

option java_multiple_files = true;

message GetSecurityEventTypeContributionRequest {
}

message GetSecurityEventTypeContributionResponse {
  SecurityEventTypeContribution security_event_type_contribution = 1;
}

message UpdateSecurityEventTypeContributionRequest {
  SecurityEventTypeContribution security_event_type_contribution = 1;
}

message UpdateSecurityEventTypeContributionResponse {
  SecurityEventTypeContribution security_event_type_contribution = 1;
}

message SecurityEventTypeContribution {
  SecurityEventTypeContributionKind security_event_type_contribution_kind = 1;

  enum SecurityEventTypeContributionKind {
    SECURITY_EVENT_TYPE_CONTRIBUTION_KIND_UNSPECIFIED = 0;
    SECURITY_EVENT_TYPE_CONTRIBUTION_KIND_ALL = 1;
    SECURITY_EVENT_TYPE_CONTRIBUTION_KIND_HIGH_RISK_APIS = 2;
  }
}
