syntax = "proto3";

package ai.traceable.threatmanagement.config.service.v1;

import "ai/traceable/threatmanagement/config/service/v1/scope_config.proto";

option java_multiple_files = true;

message GetSecurityEventScoreContributionRequest {
  ScopeConfig scope = 1;
}

message GetSecurityEventScoreContributionResponse {
  SecurityEventScoreContribution security_event_score_contribution = 1;
  SecurityEventScoreContribution default_security_event_score_contribution = 2;
}

message UpdateSecurityEventScoreContributionRequest {
  SecurityEventScoreContribution security_event_score_contribution = 1;
}

message UpdateSecurityEventScoreContributionResponse {
  SecurityEventScoreContribution security_event_score_contribution = 1;
  SecurityEventScoreContribution default_security_event_score_contribution = 2;
}

message SecurityEventScoreContribution {
  int32 medium_score = 1;
  int32 high_score = 2;
  int32 low_score = 3;
  int32 critical_score = 4;
  ScopeConfig scope = 5;
}
