syntax = "proto3";

package ai.traceable.threatmanagement.config.service.v1;

option java_multiple_files = true;

message GetThreatAutoBlockingConfigRequest {}

message GetThreatAutoBlockingConfigResponse {
  ThreatAutoBlockingActionConfig auto_blocking_action_config = 1;
}

message ExcludeAutoBlockingConfig {
  repeated string user_id_regexes = 1;
}

message UpdateThreatAutoBlockingConfigRequest {
  ThreatAutoBlockingActionType action_type = 1;
  ExpirationDetails expiration_details = 2;
  repeated ExcludeAutoBlockingConfig exclude_configs = 3;

  message ExpirationDetails {
    // Duration represented in ISO 8601 duration format.
    optional string duration = 1;
  }
}

message UpdateThreatAutoBlockingConfigResponse {
  ThreatAutoBlockingActionConfig auto_blocking_action_config = 1;
}

message ThreatAutoBlockingActionConfig {
  ThreatAutoBlockingActionType action_type = 1;
  ExpirationDetails expiration_details = 2;
  repeated ExcludeAutoBlockingConfig exclude_configs = 3;

  message ExpirationDetails {
    // Duration represented in ISO 8601 duration format.
    string duration = 1;
    int64 timestamp_millis = 2;
  }
}

enum ThreatAutoBlockingActionType {
  THREAT_AUTO_BLOCKING_ACTION_TYPE_UNSPECIFIED = 0;
  THREAT_AUTO_BLOCKING_ACTION_TYPE_NO_ACTION = 1;
  THREAT_AUTO_BLOCKING_ACTION_TYPE_BLOCK = 2;
}
