syntax = "proto3";

package ai.traceable.threatmanagement.config.service.v1;

option java_multiple_files = true;

message GetThreatScoreBoundRequest {
}

message GetThreatScoreBoundResponse {
  ThreatScoreBound threat_score_bound = 1;
  ThreatScoreBound default_threat_score_bound = 2;
}

message UpdateThreatScoreBoundRequest {
  ThreatScoreBound threat_score_bound = 1;
}

message UpdateThreatScoreBoundResponse {
  ThreatScoreBound threat_score_bound = 1;
  ThreatScoreBound default_threat_score_bound = 2;
}

message ThreatScoreBound {
  int32 medium_score_upper_bound = 1;
  int32 high_score_upper_bound = 2;
  int32 low_score_upper_bound = 3;
}
