syntax = "proto3";

package ai.traceable.threatmanagement.config.service.v1;

import "ai/traceable/threatmanagement/config/service/v1/anomaly_score_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/ip_reputation_score_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/security_event_score_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/security_event_type_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/status_code_score_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/threat_auto_blocking.proto";
import "ai/traceable/threatmanagement/config/service/v1/threat_score_bound.proto";
import "ai/traceable/threatmanagement/config/service/v1/threat_score_config.proto";

option java_multiple_files = true;

service ThreatManagementConfigService {
  rpc GetThreatScoreBound(GetThreatScoreBoundRequest) returns (GetThreatScoreBoundResponse) {}

  rpc UpdateThreatScoreBound(UpdateThreatScoreBoundRequest) returns (UpdateThreatScoreBoundResponse) {}

  rpc GetSecurityEventScoreContribution(GetSecurityEventScoreContributionRequest) returns (GetSecurityEventScoreContributionResponse) {}

  rpc UpdateSecurityEventScoreContribution(UpdateSecurityEventScoreContributionRequest) returns (UpdateSecurityEventScoreContributionResponse) {}

  rpc GetAnomalyScoreContribution(GetAnomalyScoreContributionRequest) returns (GetAnomalyScoreContributionResponse) {}

  rpc UpdateAnomalyScoreContribution(UpdateAnomalyScoreContributionRequest) returns (UpdateAnomalyScoreContributionResponse) {}

  rpc GetSecurityEventTypeContribution(GetSecurityEventTypeContributionRequest) returns (GetSecurityEventTypeContributionResponse) {}

  rpc UpdateSecurityEventTypeContribution(UpdateSecurityEventTypeContributionRequest) returns (UpdateSecurityEventTypeContributionResponse) {}

  rpc GetThreatAutoBlockingConfig(GetThreatAutoBlockingConfigRequest) returns (GetThreatAutoBlockingConfigResponse) {}

  rpc UpdateThreatAutoBlockingConfig(UpdateThreatAutoBlockingConfigRequest) returns (UpdateThreatAutoBlockingConfigResponse) {}

  rpc GetIpReputationThreatScoreConfig(GetIpReputationThreatScoreConfigRequest) returns (GetIpReputationThreatScoreConfigResponse) {}

  rpc UpdateIpReputationThreatScoreConfig(UpdateIpReputationThreatScoreConfigRequest) returns (UpdateIpReputationThreatScoreConfigResponse) {}

  rpc GetStatusCodeThreatScoreConfigs(GetStatusCodeThreatScoreConfigsRequest) returns (GetStatusCodeThreatScoreConfigsResponse) {}

  rpc UpdateStatusCodeThreatScoreConfigs(UpdateStatusCodeThreatScoreConfigsRequest) returns (UpdateStatusCodeThreatScoreConfigsResponse) {}

  rpc GetThreatScoreConfig(GetThreatScoreConfigRequest) returns (GetThreatScoreConfigResponse) {}
}
