syntax = "proto3";

package ai.traceable.threatmanagement.config.service.v1;

import "ai/traceable/threatmanagement/config/service/v1/anomaly_score_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/ip_reputation_score_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/security_event_score_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/security_event_type_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/status_code_score_contribution.proto";
import "ai/traceable/threatmanagement/config/service/v1/threat_score_bound.proto";

option java_multiple_files = true;

message GetThreatScoreConfigRequest {}

message GetThreatScoreConfigResponse {
  ThreatScoreConfig threat_score_config = 1;
}

message ThreatScoreConfig {
  AnomalyScoreContribution anomaly_score_contribution = 1;
  SecurityEventScoreContribution security_event_score_contribution = 2;
  SecurityEventTypeContribution security_event_type_contribution = 3;
  IpReputationThreatScoreConfig ip_reputation_threat_score_config = 4;
  StatusCodeThreatScoreConfigs status_code_threat_score_configs = 5;
  ThreatScoreBound threat_score_bound = 6;
}
