defaultAiAppProtectionRules = [
  {
    id = "b7feb949-f061-48f1-9943-8e0edce3860c"
    name = "Default : Non-Compliant Model Usage"
    description = "Non-Compliant Model Usage"
    disabled = true
    internal = true
    hidden = false
    category = CATEGORY_AI_APP_PROTECTION
    ruleSource = RULE_SOURCE_DEFAULT
    definition = {
      clauseGroup = {
        clauseOperator = CLAUSE_OPERATOR_AND
        clauses = [
          {
            attributeKeyValueExpression = {
              keyCondition = {
                operator = MATCH_OPERATOR_EQUALS
                value = "GENAI_MODELS"
              }
            }
          },
          {
            attributeKeyValueExpression = {
              keyCondition = {
                operator = MATCH_OPERATOR_EQUALS
                value = "GENAI_PROVIDERS"
              }
              valueCondition = {
                operator = MATCH_OPERATOR_NOT_MATCH_REGEX
                value = "OpenAI|Anthropic|Cohere|AzureOpenAI|Google|DeepSeek|Llama|(Mistral AI)|(Stability AI)|(Microsoft Phi\/Copilot)|Grok"
              }
            }
          }
        ]
      }
      labels = {
        "threatTypeId" : "llmModelGovernance"
      }
    }
    effect = {
      eventType = EVENT_TYPE_NORMAL_DETECTION
      eventSeverity = EVENT_SEVERITY_MEDIUM
      ruleEvaluationPoints = [RULE_EVALUATION_POINT_PLATFORM]
    }
  },
  {
    id = "2e208b6a-d2fa-4f19-9620-0d2e64131667"
    name = "Default : AI Input Size Too Large"
    description = "AI Input Size Too Large"
    disabled = true
    internal = false
    hidden = false
    category = CATEGORY_AI_APP_PROTECTION
    ruleSource = RULE_SOURCE_DEFAULT
    definition = {
      clauseGroup = {
        clauseOperator = CLAUSE_OPERATOR_AND
        clauses = [
          {
            attributeKeyValueExpression = {
              keyCondition = {
                operator = MATCH_OPERATOR_EQUALS
                value = "genAiPromptSize"
              }
              valueCondition = {
                operator = MATCH_OPERATOR_GREATER_THAN
                value = "500"
              }
            }
          }
        ]
      }
      labels = {
        "threatTypeId" : "llmInputExplosion"
      }
    }
    effect = {
      eventType = EVENT_TYPE_NORMAL_DETECTION
      eventSeverity = EVENT_SEVERITY_MEDIUM
      ruleEvaluationPoints = [RULE_EVALUATION_POINT_PLATFORM]
    }
  }
]