syntax = "proto3";

package ai.traceable.cloud.edge.deployment.config.service.v1;

import "ai/traceable/cloud/edge/deployment/config/service/v1/cluster_config.proto";
import "ai/traceable/cloud/edge/deployment/config/service/v1/service_config.proto";

option java_multiple_files = true;

message CloudEdgeDeploymentConfig {
  string id = 1;
  CloudEdgeDeploymentInputConfig cloud_edge_deployment_input_config = 2;
  CloudEdgeDeploymentOutputConfig cloud_edge_deployed_output_config = 3;
  CloudEdgeDeploymentInputConfig last_applied_input_config = 4;
}

message CloudEdgeDeploymentInputConfig {
  ClusterConfig cluster_config = 1;
  repeated ServiceConfig service_configs = 2;
}

message CloudEdgeDeploymentOutputConfig {
  string cname = 1;
  string health_check_url = 2;
  repeated string ips_to_be_whitelisted = 3;
  DeploymentStatus status = 4;
  string comment = 5;
}

message CloudEdgeDeploymentConfigWithActions {
  CloudEdgeDeploymentConfig cloud_edge_deployment_config = 1;
  repeated Action allowed_actions = 2;
  repeated DeploymentStatus allowed_statuses = 3;
}

enum DeploymentStatus {
  DEPLOYMENT_STATUS_UNSPECIFIED = 0;
  DEPLOYMENT_STATUS_IN_PROGRESS = 1;
  DEPLOYMENT_STATUS_DEPLOYED_SUCCESSFULLY = 2;
  DEPLOYMENT_STATUS_REQUESTED = 3;
  DEPLOYMENT_STATUS_ON_HOLD = 4;
  DEPLOYMENT_STATUS_BLOCKED = 5;
  DEPLOYMENT_STATUS_CHANGE_REQUESTED = 6;
  DEPLOYMENT_STATUS_CHANGE_BLOCKED = 7;
  DEPLOYMENT_STATUS_CHANGE_IN_PROGRESS = 8;
  DEPLOYMENT_STATUS_REMOVAL_REQUESTED = 9;
  DEPLOYMENT_STATUS_REMOVAL_BLOCKED = 10;
  DEPLOYMENT_STATUS_REMOVAL_IN_PROGRESS = 11;
}

enum Action {
  ACTION_UNSPECIFIED = 0;
  ACTION_VIEW = 1;
  ACTION_EDIT = 2;
  ACTION_DELETE = 3;
  ACTION_HOLD = 4;
  ACTION_UPDATE_STATUS = 5;
  ACTION_REQUEST_REMOVAL = 6;
  ACTION_CANCEL_CHANGE_REQUEST = 7;
  ACTION_CANCEL_REMOVAL_REQUEST = 8;
  ACTION_DEPLOY = 9;
  ACTION_CREATE = 10;
}
