syntax = "proto3";

package ai.traceable.cloud.edge.deployment.config.service.v1;

import "google/protobuf/struct.proto";

option java_multiple_files = true;

enum DeploymentType {
  DEPLOYMENT_TYPE_UNSPECIFIED = 0;
  DEPLOYMENT_TYPE_HOSTED = 1;
  DEPLOYMENT_TYPE_MANAGED = 2;
}

message ClusterConfig {
  string cluster_name = 1;
  string environment_name = 2;
  repeated RegionConfig primary_regions = 3;
  repeated RegionConfig secondary_regions = 4;
  ClusterAdvancedConfig advanced_config = 5;
  bool protection_disabled = 6 [deprecated = true];
  DeploymentType deployment_type = 7;
}

message ClusterAdvancedConfig {
  google.protobuf.Struct generic_config = 1;
}

message RegionConfig {
  oneof region {
    string aws_region = 1;
  }
}
