syntax = "proto3";

package ai.traceable.blocking.config.service.v2;

import "google/protobuf/struct.proto";

option go_package = "github.com/Traceableai/config-service/blocking/v2";
option java_multiple_files = true;

message BlockingPolicyConfigurationRequest {}

message BlockingPolicyConfiguration {
  // in the precedence-order of evaluation
  repeated BlockingDetails blocking_details_list = 1;
  repeated ExclusionRule exclusion_rules = 2;
}

message BlockingDetails {
  BlockingCategory category = 1;
  BlockingRuleType blocking_rule_type = 2;
  string info = 3;
  optional int64 expiration_timestamp = 4;
  BlockingStatus status = 9;
  oneof details {
    IpDetails ip_details = 5;
    ModsecDetails modsec_details = 6;
    CustomSignatureDetails custom_signature_details = 7;
    RegionDetails region_details = 8;
    ActorDetails actor_details = 10;
    IpTypeDetails ip_type_details = 11;
    BlockingDetailsCombination details_combination = 12;
  }
  string rule_id = 13;
  RuleAction action = 14;
}

message ExclusionRule {
  string rule_id = 1;
  string info = 2;
  BlockingDetailsCombination details = 3;
  repeated AnomalousAttributeCondition anomalous_attribute_conditions = 4;
  repeated EventCondition event_conditions = 5;
  repeated ExclusionTarget targets = 6;

  message AnomalousAttributeCondition {
    MatchExpression key_expression = 1;
    MatchExpression value_expression = 2;
  }

  message EventCondition {
    BlockingCategory blocking_category = 1;
    repeated string ids = 2;
    repeated string id_prefixes = 3;
  }

  enum ExclusionTarget {
    EXCLUSION_TARGET_UNSPECIFIED = 0;
    EXCLUSION_TARGET_BLOCK = 1;
    EXCLUSION_TARGET_ALLOW = 2;
  }
}

message BlockingDetailsCombination {
  repeated BlockingDetailsCondition details_conditions = 1;
  ConditionsOperator operator = 2;

  enum ConditionsOperator {
    CONDITIONS_OPERATOR_UNSPECIFIED = 0;
    CONDITIONS_OPERATOR_AND = 1;
    CONDITIONS_OPERATOR_OR = 2;
    CONDITIONS_OPERATOR_NOT = 3;
  }
}

message BlockingDetailsCondition {
  oneof details {
    IpDetails ip_details = 1;
    ModsecDetails modsec_details = 2;
    CustomSignatureDetails custom_signature_details = 3;
    RegionDetails region_details = 4;
    ActorDetails actor_details = 5;
    IpTypeDetails ip_type_details = 6;
    BlockingDetailsCombination details_combination = 7;
  }
}

message ModsecDetails {
  string rule_id = 1;
}

message IpDetails {
  repeated string ip_addresses = 1;
  repeated string ip_ranges = 2;
}

message ActorDetails {
  string user_id = 1;
  repeated string ip_addresses = 2;
}

message CustomSignatureDetails {
  string rule_id = 1;
}

message RegionDetails {
  repeated string regions = 1;
}

message IpTypeDetails {
  repeated IpType ip_types = 1;
}

message RuleAction {
  repeated InlineModification inline_modifications = 1;
}

message InlineModification {
  oneof modification {
    HeaderInjection header_injection = 1;
  }
}

message HeaderInjection {
  AttributeScope scope = 1;
  string header_name = 2;
  FieldValue value = 3;
}

message FieldValue {
  oneof value {
    string static_value = 1;
  }
}

enum AttributeScope {
  ATTRIBUTE_SCOPE_UNSPECIFIED = 0;
  ATTRIBUTE_SCOPE_REQUEST = 1;
  ATTRIBUTE_SCOPE_RESPONSE = 2;
}

// BlockingCategory should be consistent with v1 due to use of ordinal parsing in detector
enum BlockingCategory {
  BLOCKING_CATEGORY_UNSPECIFIED = 0;
  BLOCKING_CATEGORY_THREAT_ACTOR = 1;
  BLOCKING_CATEGORY_RATE_LIMIT = 2;
  BLOCKING_CATEGORY_MODSECURITY = 3;
  BLOCKING_CATEGORY_CUSTOM_IP_RULE = 4 [deprecated = true];
  BLOCKING_CATEGORY_CUSTOM_REGION_RULE = 5 [deprecated = true];
  BLOCKING_CATEGORY_CUSTOM_SIGNATURE_RULE = 6;
  BLOCKING_CATEGORY_MALICIOUS_SOURCES_RULE = 7;
  BLOCKING_CATEGORY_DATA_EXFILTRATION = 8;
  BLOCKING_CATEGORY_ENUMERATION = 9;
  BLOCKING_CATEGORY_TRANSACTION_BASED_DLP = 10;
}

enum BlockingRuleType {
  BLOCKING_RULE_TYPE_UNSPECIFIED = 0;
  BLOCKING_RULE_TYPE_ALLOW = 1;
  BLOCKING_RULE_TYPE_BLOCK = 2;
  BLOCKING_RULE_TYPE_BLOCK_ALL_EXCEPT = 3;
  BLOCKING_RULE_TYPE_ANALYTICS = 4;
}

// BlockingStatus should be consistent with v1 due to use of ordinal parsing in detector
enum BlockingStatus {
  BLOCKING_STATUS_UNSPECIFIED = 0;
  BLOCKING_STATUS_ALLOWED = 1;
  BLOCKING_STATUS_DENIED = 2;
  BLOCKING_STATUS_SUSPENDED = 3;
  BLOCKING_STATUS_SNOOZED = 4;
}

enum IpType {
  IP_TYPE_UNSPECIFIED = 0;
  IP_TYPE_BOT = 1;
  IP_TYPE_VPN = 2;
  IP_TYPE_TOR = 3;
  IP_TYPE_PROXY = 4;
  IP_TYPE_HOSTING_PROVIDER = 5;
}
message MatchExpression {
  MatchOperator operator = 1;
  google.protobuf.Value value = 2;
}

enum MatchOperator {
  MATCH_OPERATOR_UNSPECIFIED = 0;
  MATCH_OPERATOR_EQUALS = 1;
  MATCH_OPERATOR_NOT_EQUALS = 2;
  MATCH_OPERATOR_CONTAINS = 3;
  MATCH_OPERATOR_NOT_CONTAINS = 8;
  MATCH_OPERATOR_STARTS_WITH = 4;
  MATCH_OPERATOR_ENDS_WITH = 5;
  MATCH_OPERATOR_REGEX_MATCH = 6;
  MATCH_OPERATOR_IN = 7;
  MATCH_OPERATOR_GREATER_THAN = 9;
  MATCH_OPERATOR_LESS_THAN = 10;
}
