syntax = "proto3";

package ai.traceable.datamodel.data.transformation.config.v1;

option java_multiple_files = true;

import "google/protobuf/struct.proto";

message DataModelEntity {
  string id = 1;
  string type = 2;
  string name = 3;
  repeated AttributeDerivationMapping metadata_attributes = 4;
}

// we cannot support arbitrary output types on transformation.
enum FieldType {
  FIELD_TYPE_UNSPECIFIED = 0;
  FIELD_TYPE_STR = 1;
  FIELD_TYPE_BOOL = 2;
  FIELD_TYPE_LONG = 3;
  FIELD_TYPE_DOUBLE = 4;
  FIELD_TYPE_LIST = 5;
  FIELD_TYPE_MAP = 6;
  FIELD_TYPE_TIMESTAMP = 7;
  FIELD_TYPE_BINARY = 8;
  FIELD_TYPE_INT = 9;
}

// represents a data transformation that can be applied to extract a value from the given context
message DataTransformationConfig {
  oneof transformation {
    google.protobuf.Value static_value = 1;
    JexlExpressionConfig jexl_expression = 2;
    JexlScriptConfig jexl_script = 3;
    RegexConfig regex = 4;
    ConditionalConfig conditional = 5;
  }
  FieldType output_type = 7;
}

// a script that can be executed within the jexl context
message JexlScriptConfig {
  string jexl_script = 1;
}

// an expression that can be evaluated within the jexl context
message JexlExpressionConfig {
  string jexl_expression = 1;
}

message RegexConfig {
  // expression to generate elements
  oneof expr {
    string regex = 1;
    string split_regex = 2;
  }
  // index of elements to select
  repeated int32 group_indices = 3;
  // delimiter to be used to join the selected elements
  string join_delimiter = 4;
  // optionally, further transform the value.
  DataTransformationConfig value_transformation = 5;
}

message ConditionalConfig {
  string bool_expression = 1; // $s.getPath().contains('/registration')
  DataTransformationConfig true_transformation = 2; // static_value = true
  DataTransformationConfig false_transformation = 3; // static_value = false
}

// represents a single rule that derives a value from the transformation context
message DerivationRule {
  DataTransformationConfig transformation_config = 1;
  // apply the rule only if "condition", must eval to bool. if not, assume False.
  JexlExpressionConfig condition_expression = 3;
}

// represents a single attribute that needs to be extracted from the transformation context
message AttributeDerivationMapping {
  // name of the attribute
  string name = 1;
  // type of the attribute
  FieldType type = 2; // str, bool
  // ordered list of derivation rules, that provide the value for the attribute
  // first non-null rule
  repeated DerivationRule rules = 3;
}

// though similar to AttributeDerivationMapping, these are an indication for storing and ability reference them
// in the same transformation context
message VariableDerivationMapping {
  // name of the attribute
  string name = 1;
  // ordered list of derivation rules, that provide the value for the attribute
  // first non-null rule
  repeated DerivationRule rules = 3;
}
