syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.trainer;

import "ai/traceable/anomaly/config/service/v1/trainer/training_action.proto";
import "ai/traceable/anomaly/config/service/v1/trainer/training_config.proto";

option java_multiple_files = true;

service TrainerConfigService {
  rpc GetScopedTrainingConfig(GetScopedTrainingConfigRequest) returns (GetScopedTrainingConfigResponse) {}

  rpc GetAllScopedTrainingConfigs(GetAllScopedTrainingConfigsRequest) returns (GetAllScopedTrainingConfigsResponse) {}

  rpc GetUnresolvedScopedTrainingConfig(GetUnresolvedScopedTrainingConfigRequest) returns (GetUnresolvedScopedTrainingConfigResponse) {}

  rpc GetAllUnresolvedScopedTrainingConfig(GetAllUnresolvedScopedTrainingConfigRequest) returns (GetAllUnresolvedScopedTrainingConfigResponse) {}

  rpc UpdateScopedTrainingConfig(UpdateScopedTrainingConfigRequest) returns (UpdateScopedTrainingConfigResponse) {}

  rpc UpsertTrainingAction(UpsertTrainingActionRequest) returns (UpsertTrainingActionResponse) {}

  rpc DeleteScopedTrainingConfig(DeleteScopedTrainingConfigRequest) returns (DeleteScopedTrainingConfigResponse) {}

  rpc GetAllTrainingActions(GetAllTrainingActionsRequest) returns (GetAllTrainingActionsResponse) {}

  rpc DeleteTrainingAction(DeleteTrainingActionRequest) returns (DeleteTrainingActionResponse) {}

  rpc GetAllUnresolvedVulnerabilityScopedTrainingConfigs(GetAllUnresolvedVulnerabilityScopedTrainingConfigsRequest) returns (GetAllUnresolvedVulnerabilityScopedTrainingConfigsResponse) {}

  rpc UpdateVulnerabilityScopedTrainingConfig(UpdateVulnerabilityScopedTrainingConfigRequest) returns (UpdateVulnerabilityScopedTrainingConfigResponse) {}

  rpc DeleteScopedVulnerabilityTrainingConfig(DeleteScopedVulnerabilityTrainingConfigRequest) returns (DeleteScopedVulnerabilityTrainingConfigResponse) {}
}
