syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.trainer;
import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";

option java_multiple_files = true;

enum TrainingConfigType {
  TRAINING_CONFIG_TYPE_UNSPECIFIED = 0;
  TRAINING_CONFIG_TYPE_METADATA = 1;
  TRAINING_CONFIG_TYPE_VULNERABILITY = 2;
  TRAINING_CONFIG_TYPE_SESSION = 3;
  TRAINING_CONFIG_TYPE_API_NAMING = 4;
  TRAINING_CONFIG_TYPE_SENSITIVE_DATA = 5;
  TRAINING_CONFIG_TYPE_LOCAL_TRAINING = 6;
}

message GetTrainingConfigsFilter {
  repeated TrainingConfigType training_config_types = 1;
}

enum DeleteAnomalyConfigOption {
  DELETE_ANOMALY_CONFIG_OPTION_UNSPECIFIED = 0;
  DELETE_ANOMALY_CONFIG_OPTION_WHOLE_TRAINING_CONFIG = 1;
}

message GetScopedTrainingConfigRequest {
  AnomalyConfigScope config_scope = 1;
  GetTrainingConfigsFilter filter = 2;
}

message GetScopedTrainingConfigResponse {
  ScopedTrainingConfig scoped_training_config = 1;
}

message GetAllScopedTrainingConfigsRequest {
  GetTrainingConfigsFilter filter = 1;
}

message GetAllScopedTrainingConfigsResponse {
  repeated ScopedTrainingConfig scoped_training_configs = 1;
}

message GetUnresolvedScopedTrainingConfigRequest {
  AnomalyConfigScope config_scope = 1;
  GetTrainingConfigsFilter filter = 2;
}

message GetUnresolvedScopedTrainingConfigResponse {
  ScopedTrainingConfig scoped_training_config = 1;
}

message GetAllUnresolvedScopedTrainingConfigRequest {
  GetTrainingConfigsFilter filter = 1;
}

message GetAllUnresolvedScopedTrainingConfigResponse {
  repeated ScopedTrainingConfig scoped_training_configs = 1;
}

message ScopedTrainingConfig {
  AnomalyConfigScope config_scope = 1;
  repeated TrainingConfig training_configs = 2;
}

message UpdateScopedTrainingConfigRequest {
  ScopedTrainingConfig scoped_training_config = 1;
}

message UpdateScopedTrainingConfigResponse {
  ScopedTrainingConfig scoped_training_config = 1;
}

message DeleteScopedTrainingConfigRequest {
  DeleteAnomalyConfigOption delete_anomaly_config_option = 1;
  ScopedTrainingConfig scoped_training_config = 2;
}

message DeleteScopedTrainingConfigResponse {
  ScopedTrainingConfig deleted_scoped_training_config = 1;
}

message TrainingConfig {
  optional bool disabled = 1;
  oneof training_config {
    MetadataTrainingConfig metadata_training_config = 2;
    VulnerabilityTrainingConfig vulnerability_training_config = 3;
    SessionTrainingConfig session_training_config = 4;
    ApiNamingTrainingConfig api_naming_training_config = 5;
    SensitiveDataTrainingConfig sensitive_data_training_config = 6;
    LocalTrainingConfig local_training_config = 7;
  }
}

message LocalTrainingConfig {
  oneof config {
    ApiNamingConfig api_naming_config = 1;
  }
}

message ApiNamingConfig {}

message ApiNamingTrainingConfig {
  oneof config {
    UrlFilterConfig url_filter_config = 1 [deprecated = true];
    TrieModelTrainingConfig trie_model_training_config = 2;
    CustomRulesListConfig custom_rules_list_config = 3 [deprecated = true];
    RejectFilterConfig reject_filter_config = 4;
  }
}

message MetadataTrainingConfig {
  oneof config {
    TypeTrainingConfig type = 1;
    PiiTrainingConfig pii = 2;
    EnumerationsTrainingConfig enum = 3;
    DigitLengthTrainingConfig digit_length = 4;
    SpecialCharactersTrainingConfig special_chars = 5;
    HttpStatusCodeTrainingConfig http_status = 6;
    DeviceTrainingConfig device = 7;
    ContentSizeTrainingConfig content_size = 8;
    AccessorsTrainingConfig accessors = 9;
    SsrfTrainingConfig ssrf = 10;
    ThresholdsFamilyTrainingConfig thresholds_family = 11;
    DataClassificationTrainingConfig data_classification = 12;
    ContentTypeTrainingConfig content_type = 13;
    CountTrainingConfig count = 14;
    IsExternalApiTrainingConfig is_external_api = 15;
    MessagePartStatsTrainingConfig message_part_stats = 16;
    NoSqlTrainingConfig no_sql = 17;
    RailsOpenTrainingConfig rails_open = 18;
    StartTimeTrainingConfig start_time = 19;
    UserAgentTrainingConfig user_agent = 20;
    UserRoleTrainingConfig user_role = 21;
    HtmlTagsTrainingConfig html_tags = 22;
    HtmlTagAttributesTrainingConfig html_tag_attributes = 23;
    JwtParamsTrainingConfig jwt_params = 24;
    ParamExclusionsConfig param_exclusions = 25;
  }
}

message VulnerabilityTrainingConfig {
  AutoResolutionConfig auto_resolution_config = 12;

  oneof config {
    ParamContainsSensitiveDataTrainingConfig param_contains_sensitive_data = 1;
    LackOfEncryptionTrainingConfig lack_of_encryption = 3;
    ApiParamContainsUrlTrainingConfig api_param_contains_url = 4;
    ContentTypeOptionsSecurityHeaderTrainingConfig content_type_options_security_header = 5;
    HstsSecurityHeaderTrainingConfig hsts_security_header = 6;
    JavaSerializedObjectTrainingConfig java_serialized_object = 7;
    ServiceUsesBasicAuthTrainingConfig service_uses_basic_auth = 8;
    CspSecurityHeaderTrainingConfig csp_security_header = 9;
    DirectoryListingTrainingConfig directory_listing = 10;
    EnumerableParamTrainingConfig enumerable_param = 11;
    DeprecatedApiRouteTrainingConfig deprecated_api_route = 13;
    MultipleApiVersionsTrainingConfig multiple_api_versions = 14;
    ExcessDataExposureTrainingConfig excess_data_exposure = 15;
    OpenRedirectTrainingConfig open_redirect = 16;
    MassParameterAssignmentConfig mass_parameter_assignment = 17;
    SqlInjectionErrorBasedTrainingConfig sql_injection_error_based = 18;
    JwtExpiryIssueAtTrainingConfig jwt_expiry_and_issue_at_not_set = 20;
    JwtAlgoWeaknessTrainingConfig jwt_algo_weakness = 19;
    MissingGatewayPoliciesTrainingConfig missing_gateway_policies = 21;
  }
}

message SessionTrainingConfig {
  oneof config {
    ObjectBolaTrainingConfig object_bola = 1;
    UserIdBolaTrainingConfig user_id_bola = 2;
  }
}

message SensitiveDataTrainingConfig {
  oneof config {
    PiiSensitiveDataTrainingConfig pii_sensitive_data = 1;
  }
}

message TypeTrainingConfig {
  optional int32 max_allowed_child_params = 1;
}

message PiiTrainingConfig {
  optional int32 dlp_api_request_batch_size = 1;
  optional int32 max_dlp_api_requests_per_sec = 2;
  optional string param_age_threshold_duration = 3;
  optional string low_age_frequency_duration = 4;
  optional string high_age_frequency_duration = 5;
}

message DataClassificationTrainingConfig {}

message EnumerationsTrainingConfig {
  optional int32 max_enumerations = 1;
  optional int32 enum_value_max_length = 2;
  optional int32 min_occurrence_count = 3;
  // Takes value between 0-100
  optional double min_enum_occurrence_percent = 4;
}

message ThresholdsFamilyTrainingConfig {
  optional int64 learning_time_millis = 1;
  optional int32 required_ips_for_diverse_set = 2;
  optional int32 required_user_ids_for_diverse_set = 3;
  IntList bad_status_ips = 4;
  IntList bad_status_user_ids = 5;
  optional int32 required_percent_for_authenticated = 6;
  optional int32 thresholds_family_relearn_version = 7;
}

message DigitLengthTrainingConfig {
  ThresholdFamilyConfig threshold_family_config = 1;
}

message SpecialCharactersTrainingConfig {
  ThresholdFamilyConfig threshold_family_config = 1;
}

message HttpStatusCodeTrainingConfig {
  ThresholdFamilyConfig threshold_family_config = 1;
}

message DeviceTrainingConfig {
  ThresholdFamilyConfig threshold_family_config = 1;
}

message ContentSizeTrainingConfig {
  optional int32 request_range_size = 1;
  optional int32 response_range_size = 2;
}

message AccessorsTrainingConfig {
  ThresholdFamilyConfig api_threshold_family_config = 1;
  ThresholdFamilyConfig query_param_threshold_family_config = 2;
  ThresholdFamilyConfig request_body_param_threshold_family_config = 3;
  ThresholdFamilyConfig param_type_threshold_family_config = 4;
  ThresholdFamilyConfig request_header_threshold_family_config = 5;
  ThresholdFamilyConfig request_cookie_threshold_family_config = 6;
}

message SsrfTrainingConfig {
  ThresholdFamilyConfig protocol_threshold_family_config = 1;
  optional int32 max_allowed_hosts = 2;
}

message HtmlTagsTrainingConfig {
  ThresholdFamilyConfig threshold_family_config = 1;
}

message HtmlTagAttributesTrainingConfig {
  ThresholdFamilyConfig threshold_family_config = 1;
}

message ContentTypeTrainingConfig {}

message CountTrainingConfig {}

message IsExternalApiTrainingConfig {}

message MessagePartStatsTrainingConfig {}

message NoSqlTrainingConfig {}

message RailsOpenTrainingConfig {}

message StartTimeTrainingConfig {}

message UserAgentTrainingConfig {}

message UserRoleTrainingConfig {}

message JwtExpiryIssueAtTrainingConfig {};

message JwtAlgoWeaknessTrainingConfig {};

message MassParameterAssignmentConfig {
  MinOccurrenceConfig threshold_parameter_config = 1;
}

message JwtParamsTrainingConfig {
  ThresholdFamilyConfig threshold_family_config = 1;
  StringList include_param_regexes = 2;
}

message MissingGatewayPoliciesTrainingConfig {
  repeated GatewayPolicies recommended_policies = 1;
}

message GatewayPolicies {
  GatewayType gateway_type = 1;
  repeated GatewayPolicy policies = 2;
}

message GatewayPolicy {
  string type = 1;
}

enum GatewayType {
  GATEWAY_TYPE_UNSPECIFIED = 0;
  GATEWAY_TYPE_MULESOFT = 1;
  GATEWAY_TYPE_APIGEE = 2;
}

message ParamExclusionsConfig {
  repeated ParamKeyExclusionConfig param_key_exclusion_configs = 1;
  repeated ParamLevelExclusionConfig param_level_exclusion_configs = 2;
}

message ParamKeyExclusionConfig {
  oneof config {
    ParamKeyConfig query_param_key_config = 1;
    ParamKeyConfig http_request_header_key_config = 2;
    ParamKeyConfig http_response_header_key_config = 3;
    ParamKeyConfig http_request_body_key_config = 4;
    ParamKeyConfig http_response_body_key_config = 5;
    ParamKeyConfig http_request_cookie_key_config = 6;
    ParamKeyConfig http_response_cookie_key_config = 7;
  }
}

message ParamLevelExclusionConfig {
  oneof config {
    ParamLevelConfig http_request_body_level_config = 1;
    ParamLevelConfig http_response_body_level_config = 2;
    ParamLevelConfig rpc_request_body_level_config = 3;
    ParamLevelConfig rpc_response_body_level_config = 4;
  }
}

message ParamKeyConfig {
  oneof config {
    LengthConfig length_config = 1;
    FilterConfig filter_config = 2;
    GibberishConfig gibberish_config = 3;
    FilterConfig exception_config = 4;
  }
  ParamKeyAction action = 5;
}

message LengthConfig {
  bool disabled = 1;
  int32 max_length = 2;
}

message FilterConfig {
  bool disabled = 1;
  Operator operator = 2;
  repeated string values = 3;
}

enum Operator {
  OPERATOR_UNSPECIFIED = 0;
  OPERATOR_CONTAINS = 1;
  OPERATOR_MATCHES_REGEX = 2;
}

enum ParamKeyAction {
  PARAM_KEY_ACTION_UNSPECIFIED = 0;
  PARAM_KEY_ACTION_WILDCARD = 1;
  PARAM_KEY_ACTION_REMOVE = 2;
}

message ParamLevelConfig {
  bool disabled = 1;
  int32 max_level = 2;
}

message ParamContainsSensitiveDataTrainingConfig {
  MinOccurrenceConfig query_param_pii_type_config = 1;
  MinOccurrenceConfig persistent_cookie_pii_type_config = 2;
}

message LackOfEncryptionTrainingConfig {
  MinOccurrenceConfig https_calls_config = 1;
}

message ExcessDataExposureTrainingConfig {
  MinDataTypeOccurrenceConfig data_occurrence_config = 1;
}

message ApiEncryptionTrainingConfig {
  MinOccurrenceConfig https_calls_config = 1;
}

message ApiParamContainsUrlTrainingConfig {}

message ContentTypeOptionsSecurityHeaderTrainingConfig {}

message HstsSecurityHeaderTrainingConfig {}

message CspSecurityHeaderTrainingConfig {}

message DirectoryListingTrainingConfig {}

message JavaSerializedObjectTrainingConfig {}

message MultipleApiVersionsTrainingConfig {}

message ServiceUsesBasicAuthTrainingConfig {}

message DeprecatedApiRouteTrainingConfig {}

message OpenRedirectTrainingConfig {}

message SqlInjectionErrorBasedTrainingConfig {}

message EnumerableParamTrainingConfig {
  optional string include_param_regex = 1;
  optional int32 max_allowed_bucket_occurrence_percent = 2;
  optional int64 min_required_total_occurrence_count = 3;
}

message ObjectBolaTrainingConfig {
  ParamSusceptibilityConfig param_susceptibility_config = 1;
  ThresholdCountConfig required_count_config = 2;
  StringList prefixes_not_allowed_in_response_param_key = 3;
  StringList suffixes_not_allowed_in_response_param_key = 4;
  optional bool enabled_on_same_api = 5;
  MultiValuedStringParamRulesList multi_valued_string_param_rules = 6;
}

message UserIdBolaTrainingConfig {
  UserIdSource user_id_source = 1;
  ThresholdCountConfig required_count_config = 2;
}

message PiiSensitiveDataTrainingConfig {}

message ThresholdCountConfig {
  optional int32 required_calls_count = 1;
  optional int32 required_unique_user_ids_count = 2;
  optional int32 required_unique_ips_count = 3;
}

message ThresholdFamilyConfig {
  ThresholdCountConfig diverse_ip_diverse_user_family_config = 1;
  ThresholdCountConfig diverse_ip_limited_user_family_config = 2;
  ThresholdCountConfig limited_ip_family_config = 3;
}

message MinOccurrenceConfig {
  optional int32 min_total_occurrences = 1;
  optional int32 min_percent = 2;
}

message MinDataTypeOccurrenceConfig {
  optional int32 min_total_occurrences = 1;
  optional int32 min_percent = 2;
  optional int32 min_data_type_occurrences = 3;
}

message AutoResolutionConfig {
  bool disabled = 1;
}

enum UserIdSource {
  USER_ID_SOURCE_UNSPECIFIED = 0;
  USER_ID_SOURCE_ANY = 1;
  USER_ID_SOURCE_JWT = 2;
}

message ParamSusceptibilityConfig {
  StringList prefixes_not_allowed_in_request_param_key = 1;
  StringList suffixes_not_allowed_in_request_param_key = 2;
  optional string request_param_value_regex = 3;
  StringList susceptible_request_param_keys = 4;
  StringList request_param_values_not_allowed = 5;
  StringList regexes_not_allowed_in_request_param_key = 6;
}

message RejectFilterConfig {
  UrlPathFilterConfig url_path_filter_config = 1;
  SegmentFilterConfig segment_filter_config = 2;
  UserAgentFilterConfig user_agent_filter_config = 3;
  StatusCodeFilterConfig status_code_filter_config = 4;
}

message StatusCodeFilterConfig {
  repeated IntRangeFilterConfig range_filter_configs = 1;
}

message IntRangeFilterConfig {
  optional int32 low = 1;
  optional int32 high = 2;
  IntList exclusions = 3;
}

message SegmentFilterConfig {
  optional int32 url_parts_threshold = 1;
  optional int32 segment_length_threshold = 2;
}

message UrlPathFilterConfig  {
  StringList url_path_regex_patterns = 1;
}

message UrlFilterConfig {
  StringList url_reject_regex_patterns = 1;
}

message TrieModelTrainingConfig {
  StringList allow_regex_list = 1;
  ThresholdRegexConfig ids = 2;
  ThresholdRegexConfig low_cardinality = 3;
  ThresholdRegexConfig medium_cardinality = 4;
  ThresholdRegexConfig high_cardinality = 5;
  StringList extensions = 6;
  optional int32 embryonic_threshold = 7;
  optional int32 max_number_of_trie_paths = 8;
  optional int32 non_mergeable_depth = 9;
  GibberishConfig gibberish_config = 10;
  repeated SegmentMergeConfig segment_merge_config = 11;
  StringList id_enums = 12;
}

message GibberishConfig {
  optional int32 threshold = 1;
  bool disabled = 2;
}

message SegmentMergeConfig {
  bool disabled = 1;
  optional string segment_depth = 2;
  repeated LevelThresholdConfig level_threshold_config = 3;
  optional int32 non_mergeable_depth = 4;
}

message LevelThresholdConfig {
  int32 level = 1;
  optional int32 ids_threshold = 2;
  optional int32 low_cardinality_threshold = 3;
  optional int32 high_cardinality_threshold = 4;
  optional int32 medium_cardinality_threshold = 5;
  optional int32 gibberish_threshold = 6;
}

message UserAgentFilterConfig {
  StringList bot_agent_list = 2;
}

message ThresholdRegexConfig {
  optional int32 threshold = 1;
  StringList regex_list = 2;
}

message CustomRulesListConfig{
  repeated CustomRuleConfig custom_rules_config = 1;
}

message CustomRuleConfig{
  string regex = 1;
  string url_pattern = 2;
}

message MultiValuedStringParamRulesList {
  repeated MultiValuedStringParamRule rules = 1;
}

message MultiValuedStringParamRule {
  string key_regex = 1;
  string value_delimiter = 2;
  optional string value_regex = 3;
}
