syntax = "proto3";

package ai.traceable.anomalyscoring.config.service.v1;

import "ai/traceable/anomalyscoring/config/service/v1/anomaly_scoring_config.proto";

option java_multiple_files = true;

service AnomalyScoringConfigService {
  rpc GetAnomalyScoringConfig(GetAnomalyScoringConfigRequest) returns (GetAnomalyScoringConfigResponse) {}

  rpc UpdateImpactScoringConfig(UpdateImpactScoringConfigRequest) returns (UpdateImpactScoringConfigResponse) {}

  rpc UpdateConfidenceScoringConfig(UpdateConfidenceScoringConfigRequest) returns (UpdateConfidenceScoringConfigResponse) {}
}

message GetAnomalyScoringConfigRequest {}

message GetAnomalyScoringConfigResponse {
  AnomalyScoringConfig anomaly_scoring_config = 1;
  AnomalyScoringConfig default_anomaly_scoring_config = 2;
}

message UpdateImpactScoringConfigRequest {
  ImpactScoringConfig impact_scoring_config = 1;
}

message UpdateImpactScoringConfigResponse {
  ImpactScoringConfig impact_scoring_config = 1;
  ImpactScoringConfig default_impact_scoring_config = 2;
}

message UpdateConfidenceScoringConfigRequest {
  ConfidenceScoringConfig confidence_scoring_config = 1;
}

message UpdateConfidenceScoringConfigResponse {
  ConfidenceScoringConfig confidence_scoring_config = 1;
  ConfidenceScoringConfig default_confidence_scoring_config = 2;
}
