syntax = "proto3";

package ai.traceable.risk.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/risk/config/service/v1/risk_config_request_response.proto";


service RiskConfigService {

  rpc GetAllRiskConfigs (GetAllRiskConfigsRequest) returns (GetAllRiskConfigsResponse) {
  }

  rpc GetRiskScoringConfigs (GetRiskScoringConfigsRequest) returns (GetRiskScoringConfigsResponse) {
  }

  rpc GetRiskLikelihoodFactors (GetRiskLikelihoodFactorsRequest) returns (GetRiskLikelihoodFactorsResponse) {
  }

  rpc GetRiskImpactFactors (GetRiskImpactFactorsRequest) returns (GetRiskImpactFactorsResponse) {
  }

  rpc UpdateRiskLevelConfig (UpdateRiskLevelConfigRequest) returns (UpdateRiskLevelConfigResponse) {
  }

  rpc UpdateRiskFactorGridConfig (UpdateRiskFactorGridConfigRequest) returns (UpdateRiskFactorGridConfigResponse) {
  }

  rpc UpdateRiskLikelihoodFactorConfigs (UpdateRiskLikelihoodFactorConfigsRequest) returns (UpdateRiskLikelihoodFactorConfigsResponse) {
  }

  rpc UpdateRiskImpactFactorConfigs (UpdateRiskImpactFactorConfigsRequest) returns (UpdateRiskImpactFactorConfigsResponse) {
  }

  rpc ResetRiskLevelConfig (ResetRiskLevelConfigRequest) returns (ResetRiskLevelConfigResponse) {
  }

  rpc ResetRiskFactorGridConfig (ResetRiskFactorGridConfigRequest) returns (ResetRiskFactorGridConfigResponse) {
  }

  rpc ResetRiskLikelihoodFactorConfigs (ResetRiskLikelihoodFactorConfigsRequest) returns (ResetRiskLikelihoodFactorConfigsResponse) {
  }

  rpc ResetRiskImpactFactorConfigs (ResetRiskImpactFactorConfigsRequest) returns (ResetRiskImpactFactorConfigsResponse) {
  }
}
