syntax = "proto3";

package ai.traceable.risk.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/risk/config/service/v1/risk_scoring_configs.proto";


message GetRiskScoringConfigsRequest {
}

message GetRiskScoringConfigsResponse {
  RiskLevelConfig risk_level_config = 1;
  RiskFactorGridConfig risk_factor_grid_config = 2;
}

message UpdateRiskLevelConfigRequest {
  RiskLevelConfigValues risk_level_config_values = 1;
}

message UpdateRiskLevelConfigResponse {
  RiskLevelConfig risk_level_config = 1;
}

message UpdateRiskFactorGridConfigRequest {
  RiskFactorGridConfigValues risk_factor_grid_config_values = 1;
}

message UpdateRiskFactorGridConfigResponse {
  RiskFactorGridConfig risk_factor_grid_config = 1;
}

message ResetRiskLevelConfigRequest {
}

message ResetRiskLevelConfigResponse {
  RiskLevelConfig risk_level_config = 1;
}

message ResetRiskFactorGridConfigRequest {
}

message ResetRiskFactorGridConfigResponse {
  RiskFactorGridConfig risk_factor_grid_config = 1;
}
