syntax = "proto3";

package ai.traceable.risk.config.service.v1;

import "ai/traceable/risk/config/service/v1/risk_element_configs.proto";

option java_multiple_files = true;

message RiskContributorConfigs {
  repeated RiskFactor risk_factors = 1;
}

message RiskFactor {
  RiskFactorConfig risk_factor_config = 1;
  RiskFactorInfo risk_factor_info = 2;
  repeated CustomizationOptions customization_options = 3;
  bool is_default = 4;
}

message RiskFactorConfig {
  string id = 1;
  RiskFactorScoring risk_factor_scoring = 2;
  repeated RiskElementConfig risk_element_configs = 3;
}

message RiskFactorInfo {
  string name = 1;
  RiskFactorType risk_factor_type = 2;
  string description = 3;
}

enum RiskFactorType {
  RISK_FACTOR_TYPE_UNSPECIFIED = 0;
  RISK_FACTOR_TYPE_CUSTOM_TAGS = 1;
  RISK_FACTOR_TYPE_MOTIVE = 2;
  RISK_FACTOR_TYPE_EASE_OF_ACCESS = 3;
  RISK_FACTOR_TYPE_SENSITIVE_DATA_EXPOSURE = 4;
  RISK_FACTOR_TYPE_EXPOSURE_SURFACE = 5;
  RISK_FACTOR_TYPE_EXPLOIT_SURFACE = 6;
  RISK_FACTOR_TYPE_LOSS_OF_CONFIDENTIALITY = 7;
  RISK_FACTOR_TYPE_EASE_OF_RESOURCE_DISCOVERY = 8;
}

message RiskFactorScoring {
  bool disabled = 1;
  RiskFactorScoreContribution score_contribution = 2;
}

enum RiskFactorScoreContribution {
  RISK_FACTOR_SCORE_CONTRIBUTION_UNSPECIFIED = 0; // default
  RISK_FACTOR_SCORE_CONTRIBUTION_ABSOLUTE = 1; // If present, likelihood/impact must resolve to exactly this value
}

enum CustomizationOptions {
  CUSTOMIZATION_OPTIONS_FACTOR_SCORE_UNSPECIFIED = 0;
  CUSTOMIZATION_OPTIONS_FACTOR_SCORE_CONTRIBUTION = 1;
  CUSTOMIZATION_OPTIONS_ELEMENT_ADD_DELETE = 2;
}
