syntax = "proto3";

package ai.traceable.risk.config.service.v1;

import "ai/traceable/risk/config/service/v1/risk_factor_configs.proto";
import "ai/traceable/risk/config/service/v1/risk_scoring_configs.proto";

option java_multiple_files = true;

message GetRiskScoringConfigsRequest {}

message GetRiskScoringConfigsResponse {
  RiskLevelConfig risk_level_config = 1;
  RiskFactorGridConfig risk_factor_grid_config = 2;
}

message GetRiskLikelihoodConfigsRequest {}

message GetRiskLikelihoodConfigsResponse {
  RiskContributorConfigs risk_likelihood_configs = 1;
}

message GetRiskImpactConfigsRequest {}

message GetRiskImpactConfigsResponse {
  RiskContributorConfigs risk_impact_configs = 1;
}

message UpdateRiskLevelConfigRequest {
  RiskLevelConfigValues risk_level_config_values = 1;
}

message UpdateRiskLevelConfigResponse {
  RiskLevelConfig risk_level_config = 1;
}

message UpdateRiskFactorGridConfigRequest {
  RiskFactorGridConfigValues risk_factor_grid_config_values = 1;
}

message UpdateRiskFactorGridConfigResponse {
  RiskFactorGridConfig risk_factor_grid_config = 1;
}

message UpdateRiskLikelihoodConfigsRequest {
  repeated RiskFactorConfig risk_factor_configs = 1;
}

message UpdateRiskLikelihoodConfigsResponse {
  RiskContributorConfigs risk_likelihood_configs = 1;
}

message UpdateRiskImpactConfigsRequest {
  repeated RiskFactorConfig risk_factor_configs = 1;
}

message UpdateRiskImpactConfigsResponse {
  RiskContributorConfigs risk_impact_configs = 1;
}

message ResetRiskLevelConfigRequest {}

message ResetRiskLevelConfigResponse {
  RiskLevelConfig risk_level_config = 1;
}

message ResetRiskFactorGridConfigRequest {}

message ResetRiskFactorGridConfigResponse {
  RiskFactorGridConfig risk_factor_grid_config = 1;
}

message ResetRiskLikelihoodConfigsRequest {
  RiskContributorConfigsResetFilter filter = 1; // when not set, it means reset all
}

message ResetRiskLikelihoodConfigsResponse {
  RiskContributorConfigs risk_likelihood_configs = 1;
}

message ResetRiskImpactConfigsRequest {
  RiskContributorConfigsResetFilter filter = 1; // when not set, it means reset all
}

message ResetRiskImpactConfigsResponse {
  RiskContributorConfigs risk_impact_configs = 1;
}

message RiskContributorConfigsResetFilter {
  repeated string risk_factor_ids = 1;
}
