syntax = "proto3";

package ai.traceable.edge.decision.config.service.v1;

import "ai/traceable/datamodel/data/transformation/config/v1/transformation.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_common.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/struct.proto";

option java_multiple_files = true;

// represents a single risk decision rule that can be evaluated by risk decision engine
// Given a payload, configure how to determine the risk:
// Check if accepting this payload causes any aggregate threshold to be violated, for example:
// - Has the dim1,dim2..dimN, count(*) crossed a limit -> Rate limit
// - Has the dim1, dim2…dimN, count(distinct dimX) crossed a limit -> Enumeration
// Check if this payload is matching any signatures provided
// Check if this payload matches any known fingerprints, that are provided by different sources
// Check for the occurrence of other events, prior to this event - correlated by certain dimensions
message EdgeDecisionRule {
  string id = 1;
  string name = 2;
  int64 version = 3;
  EdgeDecisionRuleScope rule_scope = 4;
  EdgeDecisionRuleCategory rule_category = 5;
  EdgeDecisionRuleStatus rule_status = 6;
  EdgeDecisionRuleDefinition rule_definition = 7;
  EdgeDecision rule_decision = 8;
  PolicyKind policy_kind = 9;
}

message EdgeDecisionRuleScope {
  // AND
  repeated EdgeDecisionRuleScopeCondition scope_conditions = 1;
}

message EdgeDecisionRuleScopeCondition {
  oneof scope {
    EnvironmentScope environment_scope = 1;
    ServiceScope service_scope = 2;
    UrlScope url_scope = 3;
    UrlRegexScope url_regex_scope = 4;
    HttpMethodScope http_method_scope = 5;
    ai.traceable.datamodel.data.transformation.config.v1.MatchCondition match_condition_scope = 6;
  }

  message ServiceScope {
    // OR
    repeated string service_names = 1;
  }

  message UrlRegexScope {
    // OR
    repeated string url_regexes = 1;
  }

  message UrlScope {
    // OR
    repeated string urls = 1;
  }

  message HttpMethodScope {
    // OR
    // POST / PUT / GET / DELETE, etc
    repeated string http_methods = 1;
  }
}

message EdgeDecisionRuleStatus {
  bool disabled = 1;
  bool internal = 2;
  // specifies the TTL for which the rule is active
  ConfigTtl ttl = 3;
}

message EdgeDecisionRuleDefinition {
  EdgeInputKind edge_input_kind = 1;
  // variables used specifically in this rule
  repeated ai.traceable.datamodel.data.transformation.config.v1.VariableDerivationMapping rule_variables = 2;
  // if the rule matches, what do you want to capture in the result?
  repeated ai.traceable.datamodel.data.transformation.config.v1.AttributeDerivationMapping attribute_projections = 3;
  oneof rule_definition {
    SignatureRule signature_rule = 6;
    EntityRule entity_rule = 7;
    AggregateThresholdRule aggregate_threshold_rule = 8;
    AccessPatternRule access_pattern_rule = 9;
  }
  // each rule must provide a score and weight, that are used to compute the final score.
  //  double risk_score = 6;
  //  double weight = 7;
  // placeholder to allow customization of the rule eval - not all params are known now.
  // this will be a struct containing the following keys: "fingerprintId", "policyId", "target", "targetType"
  google.protobuf.Value custom_fields = 100;
}

// "signature rules" that can be evaluated by risk decision engine
// evaluate a payload to check if it matches the signature
message SignatureRule {
  ai.traceable.datamodel.data.transformation.config.v1.MatchCondition match_condition = 1;
}

// entity rules that can be evaluated by risk decision engine
// this is for any type of entity, like fingerprint, actor/user, etc
message EntityRule {
  repeated EntityRuleData entity_data = 1;
}

// Aggregate threshold rules
// rate limit rules that can be evaluated by risk decision engine
// enumeration rules that can be evaluated by risk decision engine
// <IN FUTURE> evaluate other aggregates, aggregate of attribute values
// evaluate a payload against rate tracker
// in a window of time, count(<>) by (<>)
// evaluate a payload against enumeration
// agg_fn(dimension) by (dim1, dim2..dimN) over [timewindow] , threshold
message AggregateThresholdRule {
  // this should refer to a match criteria that's evaluated in variables so that we don't evaluate again and again
  ai.traceable.datamodel.data.transformation.config.v1.MatchCondition match_condition = 1;

  // group-by to be applied on the payload
  repeated ai.traceable.datamodel.data.transformation.config.v1.AttributeDerivationMapping group_by_dimensions = 2;

  // time window over which aggregate must be computed
  google.protobuf.Duration time_window = 3;

  // The type of aggregation to apply for the threshold
  // Aggregate a value from an event attribute (e.g., sum, avg)
  // equivalent to COUNT(*)
  // - Has the dim1,dim2..dimN, count(*) crossed a limit -> Rate limit

  // Count distinct values for a specific dimension
  // - Has the dim1, dim2…dimN, count(distinct dimX) crossed a limit -> Enumeration
  // - Has the dim1, dim2…dimN, agg_fn(dimX) crossed a limit ->
  ValueAggregateThreshold value_aggregate_threshold = 4;
}

// "api access rules" that can be evaluated by risk decision engine
// evaluate a payload against access pattern
message AccessPatternRule {
  // correlation key to be computed on the request payload(s)
  CorrelationKey correlation_key = 1;
  // common filters that must be applied on all payloads (client_type == '')
  ai.traceable.datamodel.data.transformation.config.v1.MatchCondition filter = 2;
  ai.traceable.datamodel.data.transformation.config.v1.MatchCondition target_request = 3;

  // what other requests do we expect in this window, before the target is invoked
  repeated RequestInvocation pre_requests = 4; // Collection of requests that are expected.
  // what is the time window for grouping
  google.protobuf.Duration time_window = 5;
  // what is the probability of no other api being there in this window?
  // set to "true" to trigger the rule if NO api is seen in this window. Irrespective of pre_requests.
  bool check_for_any_pre_requests = 6;
}

message EntityRuleData {
  ai.traceable.datamodel.data.transformation.config.v1.DataModelEntity entity = 1;
  ai.traceable.datamodel.data.transformation.config.v1.MatchCondition match_condition = 2;
}

message ValueAggregateThreshold {
  // choose the attribute to aggregate
  ai.traceable.datamodel.data.transformation.config.v1.AttributeDerivationMapping dimension = 1;

  enum AggregationType {
    AGGREGATION_TYPE_UNSPECIFIED = 0; // Count the total number of events
    AGGREGATION_TYPE_COUNT = 1; // Count the total number of events
    AGGREGATION_TYPE_DISTINCT_COUNT = 2; // Count distinct values of specified dimensions
    AGGREGATION_TYPE_SUM = 3; // Sum of attribute values
    AGGREGATION_TYPE_AVG = 4; // Average of attribute values
    AGGREGATION_TYPE_MAX = 5; // Maximum attribute value
    AGGREGATION_TYPE_MIN = 6; // Minimum attribute value
  }

  enum ThresholdOperator {
    THRESHOLD_OPERATOR_UNSPECIFIED = 0;
    THRESHOLD_OPERATOR_ABOVE = 1;
    THRESHOLD_OPERATOR_BELOW = 2;
    THRESHOLD_OPERATOR_ABOVE_OR_BELOW = 3;
  }

  AggregationType aggregation_type = 2;
  oneof threshold {
    double static_threshold = 3; // The threshold for the aggregated value, an absolute value.
    RangeThreshold range_threshold = 5; // threshold specified as a range.
    ToleranceThreshold tolerance_threshold = 6; // threshold specified with a tolerance (percent, delta)
  }
  ThresholdOperator threshold_operator = 7; // default: ABOVE.
  // this must be a conscious choice of the consumer - higher resource usage if estimates are disabled for aggregations
  // by default: decision engine may use probabilistic data structures for providing aggregate values
  bool disable_estimated_aggregate = 4;
}

message RangeThreshold {
  double lower_bound = 1; // Explicit lower bound
  double upper_bound = 2; // Explicit upper bound
}

message ToleranceThreshold {
  double reference_value = 1; // base threshold value.
  oneof tolerance_type {
    double percentage_tolerance = 2; // tolerance expressed as a percentage of reference value
    double absolute_tolerance = 3; // tolerance expressed as a fixed offset from reference value
  }
}

message RequestInvocation {
  // required for tracking this invocation.
  string request_invocation_id = 1;
  ai.traceable.datamodel.data.transformation.config.v1.MatchCondition match_condition = 2;
  int32 weight = 3;
  double median_percent = 4;
}

message CorrelationKey {
  // for now, it is the same set of derivation rules applied on all requests in the access pattern config
  // provide derivation of the attributes in the risk config
  repeated ai.traceable.datamodel.data.transformation.config.v1.AttributeDerivationMapping attributes = 1;
}
