syntax = "proto3";

package ai.traceable.edge.decision.config.service.v1;

import "ai/traceable/datamodel/data/transformation/config/v1/transformation.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_custom_response.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_common.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_rule.proto";

option java_multiple_files = true;

message EdgeDecisionSpecScope {
  oneof scope {
    string environment = 1;
  }
}

message EdgeDecisionSpecDirective {
  EdgeDecision edge_decision = 1;
  oneof condition {
    // any rule fires, provide this decision
    bool any_rule = 2;
    // all rules fire, provide this decision
    bool all_rules = 3;
    EdgeDecisionType any_rule_of_type = 4;
    // specific rules fire, provide this decision
    StringList specific_rule_ids = 5;
    // complex expressions with rule names, their weight and scores. and the incoming payload context.
    ai.traceable.datamodel.data.transformation.config.v1.JexlExpressionConfig decision_tree_jexl_expression = 6;
    ai.traceable.datamodel.data.transformation.config.v1.JexlScriptConfig decision_tree_jexl_script = 7;
  }
  EdgeCustomResponse custom_response = 8;
}

message EdgeDecisionSpec {
  string id = 1;
  string name = 2;
  int64 version = 3;
  EdgeInputKind edge_input_kind = 4;
  EdgeDecisionSpecScope scope = 5;
  // ordered list of decision specs.
  // rule_id
  repeated EdgeDecisionSpecDirective decision_spec_directives = 6;
}
