syntax = "proto3";

package ai.traceable.edge.decision.config.service.v1;

import "ai/traceable/edge/decision/config/service/v1/edge_decision_common.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_config.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_rule.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_spec.proto";

option java_multiple_files = true;

service EdgeDecisionConfigService {
  // API to fetch all resolved scoped edge-decision configs for a given tenant
  rpc GetResolvedEdgeDecisionEngineConfigs(GetResolvedEdgeDecisionEngineConfigsRequest) returns (GetResolvedEdgeDecisionEngineConfigsResponse) {}
  // API to fetch the resolved scoped edge-decision config for a given scope
  rpc GetScopedResolvedEdgeDecisionConfig(GetScopedResolvedEdgeDecisionConfigRequest) returns (GetScopedResolvedEdgeDecisionConfigResponse) {}
  // API to manage the edge decision config directly. To keep this atomic, this is the config that's stored for a tenant.
  // caller can get the rules within the config and update them using the same API.
  // we may eventually manage the rules and specs, then generate the engine config.
  // CRUD for overall config - this is optional, we can choose to avoid persisting it and build it runtime
  rpc CreateEdgeDecisionEngineConfig(CreateEdgeDecisionEngineConfigRequest) returns (CreateEdgeDecisionEngineConfigResponse) {}
  rpc UpdateEdgeDecisionEngineConfig(UpdateEdgeDecisionEngineConfigRequest) returns (UpdateEdgeDecisionEngineConfigResponse) {}
  rpc GetEdgeDecisionEngineConfig(GetEdgeDecisionEngineConfigRequest) returns (GetEdgeDecisionEngineConfigResponse) {}
  rpc GetAllEdgeDecisionEngineConfig(GetAllEdgeDecisionEngineConfigRequest) returns (GetAllEdgeDecisionEngineConfigResponse) {}

  // CRUD for rules
  rpc CreateEdgeDecisionRule(CreateEdgeDecisionRuleRequest) returns (CreateEdgeDecisionRuleResponse) {}
  rpc UpdateEdgeDecisionRule(UpdateEdgeDecisionRuleRequest) returns (UpdateEdgeDecisionRuleResponse) {}
  rpc GetAllEdgeDecisionRules(GetAllEdgeDecisionRulesRequest) returns (GetAllEdgeDecisionRulesResponse) {}
  rpc DeleteEdgeDecisionRule(DeleteEdgeDecisionRuleRequest) returns (DeleteEdgeDecisionRuleResponse) {}

  // CRUD for specs
  rpc CreateEdgeDecisionSpec(CreateEdgeDecisionSpecRequest) returns (CreateEdgeDecisionSpecResponse) {}
  rpc UpdateEdgeDecisionSpec(UpdateEdgeDecisionSpecRequest) returns (UpdateEdgeDecisionSpecResponse) {}
  rpc GetAllEdgeDecisionSpecs(GetAllEdgeDecisionSpecsRequest) returns (GetAllEdgeDecisionSpecsResponse) {}
  rpc DeleteEdgeDecisionSpec(DeleteEdgeDecisionSpecRequest) returns (DeleteEdgeDecisionSpecResponse) {}
}

message GetResolvedEdgeDecisionEngineConfigsRequest {
  GetEdgeDecisionConfigsFilter filter = 1;
}

message GetResolvedEdgeDecisionEngineConfigsResponse {
  EdgeDecisionEngineConfig edge_decision_engine_config = 1;
}

message GetScopedResolvedEdgeDecisionConfigRequest {
  EdgeDecisionSpecScope scope = 1;
  GetEdgeDecisionConfigsFilter filter = 2;
}

message GetScopedResolvedEdgeDecisionConfigResponse {
  ScopedEdgeDecisionConfig scoped_edge_decision_config = 1;
}

message GetEdgeDecisionConfigsFilter {
  repeated EdgeDecisionType decision_types = 1;
  repeated EdgeDecisionRuleCategory rule_categories = 2;
  repeated EdgeInputKind edge_input_kinds = 3;
}

message CreateEdgeDecisionEngineConfigRequest {
  EdgeDecisionEngineConfig edge_decision_engine_config = 2;
}

message CreateEdgeDecisionEngineConfigResponse {
  EdgeDecisionEngineConfig edge_decision_engine_config = 1;
}

message UpdateEdgeDecisionEngineConfigRequest {
  int64 current_version = 1;
  EdgeDecisionEngineConfig edge_decision_engine_config = 2;
}

message UpdateEdgeDecisionEngineConfigResponse {
  EdgeDecisionEngineConfig edge_decision_engine_config = 1;
}

message GetEdgeDecisionEngineConfigRequest {
  string id = 1;
}

message GetEdgeDecisionEngineConfigResponse {
  EdgeDecisionEngineConfig edge_decision_engine_config = 1;
}

message GetAllEdgeDecisionEngineConfigRequest {}

message GetAllEdgeDecisionEngineConfigResponse {
  repeated EdgeDecisionEngineConfig edge_decision_engine_configs = 1;
}

message CreateEdgeDecisionRuleRequest {
  EdgeDecisionRule edge_decision_rule = 1;
}

message CreateEdgeDecisionRuleResponse {
  EdgeDecisionRule edge_decision_rule = 1;
}

message UpdateEdgeDecisionRuleRequest {
  int64 current_version = 1;
  EdgeDecisionRule edge_decision_rule = 2;
}

message UpdateEdgeDecisionRuleResponse {
  EdgeDecisionRule edge_decision_rule = 1;
}

message GetAllEdgeDecisionRulesRequest {}

message GetAllEdgeDecisionRulesResponse {
  repeated EdgeDecisionRule edge_decision_rules = 1;
}

message DeleteEdgeDecisionRuleRequest {
  string id = 1;
}

message DeleteEdgeDecisionRuleResponse {
  EdgeDecisionRule deleted_edge_decision_rule = 1;
}

message CreateEdgeDecisionSpecRequest {
  EdgeDecisionSpec edge_decision_spec = 1;
}

message CreateEdgeDecisionSpecResponse {
  EdgeDecisionSpec edge_decision_spec = 1;
}

message UpdateEdgeDecisionSpecRequest {
  int64 current_version = 1;
  EdgeDecisionSpec edge_decision_spec = 2;
}

message UpdateEdgeDecisionSpecResponse {
  EdgeDecisionSpec edge_decision_spec = 1;
}

message GetAllEdgeDecisionSpecsRequest {}

message GetAllEdgeDecisionSpecsResponse {
  repeated EdgeDecisionSpec edge_decision_specs = 1;
}

message DeleteEdgeDecisionSpecRequest {
  string id = 1;
}

message DeleteEdgeDecisionSpecResponse {
  EdgeDecisionSpec deleted_edge_decision_spec = 1;
}
