syntax = "proto3";

package ai.traceable.api.attribute.override.service.v1;

option java_multiple_files = true;

message GetAllApiAttributeOverridesRequest {
  Filter filter = 1;
}

message Filter {
  repeated string api_ids = 1;
}

message GetAllApiAttributeOverridesResponse {
  map<string, ApiAttributeOverrides> api_attribute_overrides = 1;
}

message UpsertApiAttributeOverridesRequest {
  string api_id = 1;
  repeated AttributeOverride attribute_overrides = 2;
}

message UpsertApiAttributeOverridesResponse {
  ApiAttributeOverrides api_attribute_overrides = 1;
}

message RemoveApiAttributeOverridesRequest {
  string api_id = 1;
  repeated AttributeOverrideIdentifier attribute_override_identifiers = 2;
}

message RemoveApiAttributeOverridesResponse {
  ApiAttributeOverrides api_attribute_overrides = 1;
}

message ApiAttributeOverrides {
  string api_id = 1;
  repeated AttributeOverride attribute_overrides = 2;
}

message AttributeOverride {
  oneof attribute_override {
    ParamTypeOverride param_type_override = 1;
    BooleanOverride api_external_override = 2;
  }
}

message BooleanOverride {
  bool value = 1;
}

message ParamTypeOverride {
  string param_name = 1;
  ParamValueType param_value_type = 2;
  ParamTypeAction param_type_action = 3;
}

enum ParamTypeAction {
  PARAM_TYPE_ACTION_UNSPECIFIED = 0;
  PARAM_TYPE_ACTION_EXCLUDE = 1;
  PARAM_TYPE_ACTION_COLLAPSE = 2;
}

enum ParamValueType {
  PARAM_VALUE_TYPE_UNSPECIFIED = 0;
  PARAM_VALUE_TYPE_BOOLEAN = 1;
  PARAM_VALUE_TYPE_INTEGER = 2;
  PARAM_VALUE_TYPE_FLOAT = 3;
  PARAM_VALUE_TYPE_CHAR = 4;
  PARAM_VALUE_TYPE_STRING = 5;
  PARAM_VALUE_TYPE_OBJECT = 6;
  PARAM_VALUE_TYPE_URL = 7;
  PARAM_VALUE_TYPE_EMAIL = 8;
  PARAM_VALUE_TYPE_JSON = 9;
  PARAM_VALUE_TYPE_CREDIT_CARD = 10;
  PARAM_VALUE_TYPE_DATE = 11;
  PARAM_VALUE_TYPE_ARRAY = 12;
  PARAM_VALUE_TYPE_CLOB = 13;
  PARAM_VALUE_TYPE_HTML = 14;
  PARAM_VALUE_TYPE_RICH_TEXT_HTML = 15;
  PARAM_VALUE_TYPE_FREE_TEXT = 16;
  PARAM_VALUE_TYPE_NULL = 17;
}

message AttributeOverrideIdentifier {
  oneof attribute_override_identifier {
    ParamTypeOverrideIdentifier param_type_override_identifier = 1;
    EmptyOverrideIdentifier api_external_override_identifier = 2;
  }
}

message ParamTypeOverrideIdentifier {
  string param_name = 1;
}

message EmptyOverrideIdentifier {}
