syntax = "proto3";

package ai.traceable.api.attribute.override.service.v1;

option java_multiple_files = true;

import "ai/traceable/api/attribute/override/service/v1/api_attributes_override.proto";

service ApiAttributeOverrideService {
  rpc GetAllApiAttributeOverrides (GetAllApiAttributeOverridesRequest) returns (GetAllApiAttributeOverridesResponse) {
  }

  rpc UpsertApiAttributeOverrides (UpsertApiAttributeOverridesRequest) returns (UpsertApiAttributeOverridesResponse) {
  }

  rpc RemoveApiAttributeOverrides (RemoveApiAttributeOverridesRequest) returns (RemoveApiAttributeOverridesResponse) {
  }
}
