syntax = "proto3";
package ai.traceable.jira.integration.config.service.api.v1;

import "ai/traceable/jira/integration/config/service/api/v1/jira_additional_configuration.proto";

option java_multiple_files = true;

service JiraIntegrationConfigService {
  rpc CreateJiraIntegration(CreateJiraIntegrationRequest) returns (CreateJiraIntegrationResponse) {}
  rpc GetJiraIntegrations(GetJiraIntegrationsRequest) returns (GetJiraIntegrationsResponse) {}
  rpc UpdateJiraIntegration(UpdateJiraIntegrationRequest) returns (UpdateJiraIntegrationResponse) {}
  rpc DeleteJiraIntegration(DeleteJiraIntegrationRequest) returns (DeleteJiraIntegrationResponse) {}

  rpc AddJiraTemplate(AddJiraTemplateRequest) returns (AddJiraTemplateResponse) {}
  rpc UpdateJiraTemplate(UpdateJiraTemplateRequest) returns (UpdateJiraTemplateResponse) {}
  rpc DeleteJiraTemplate(DeleteJiraTemplateRequest) returns (DeleteJiraTemplateResponse) {}

  rpc CreateProjectIssueConfiguration(CreateProjectIssueConfigurationRequest) returns (CreateProjectIssueConfigurationResponse) {}
  rpc UpdateProjectIssueConfiguration(UpdateProjectIssueConfigurationRequest) returns (UpdateProjectIssueConfigurationResponse) {}
  rpc DeleteProjectIssueConfiguration(DeleteProjectIssueConfigurationRequest) returns (DeleteProjectIssueConfigurationResponse) {}
  rpc GetProjectIssueConfigurations(GetProjectIssueConfigurationsRequest) returns (GetProjectIssueConfigurationsResponse) {}
}

message CreateJiraIntegrationRequest {
  string name = 1;
  optional string description = 2;
  string consumer_key = 3 [deprecated = true];
  string base_url = 4;
  EncryptedData encrypted_access_token = 5 [deprecated = true];
  Scope scope = 6;
  JiraIntegrationDetails jira_integration_details = 7;
}

message CreateJiraIntegrationResponse {
  JiraIntegration integration = 1;
}

message GetJiraIntegrationsRequest {
  JiraIntegrationFilter jira_integration_filter = 1;
}

message GetJiraIntegrationsResponse {
  repeated JiraIntegration integration = 1;
}

message UpdateJiraIntegrationRequest {
  string jira_integration_id = 1;
  string name = 2;
  string description = 3;
  Scope scope = 4;
}

message UpdateJiraIntegrationResponse {
  JiraIntegration integration = 1;
}

message DeleteJiraIntegrationRequest {
  string jira_integration_id = 1;
}

message DeleteJiraIntegrationResponse {}

message AddJiraTemplateRequest {
  JiraTemplateDetails jira_template_details = 1;
  string integration_id = 2;
  string project_id = 3;
  string issue_type = 4;
  TraceableEntityType supported_entity_type = 5;
}

message AddJiraTemplateResponse {
  JiraTemplate jira_template = 1;
}

message UpdateJiraTemplateRequest {
  string template_id = 1;
  JiraTemplateDetails jira_template_details = 2;
}

message UpdateJiraTemplateResponse {
  JiraTemplate jira_template = 1;
}

message DeleteJiraTemplateRequest {
  string template_id = 1;
}

message DeleteJiraTemplateResponse {}

message GetJiraTemplatesResponse {
  repeated JiraTemplate jira_templates = 1;
}

message CreateProjectIssueConfigurationRequest {
  string integration_id = 1;
  string project_id = 2;
  string issue_type = 3;
  TraceableEntityType traceable_entity_type = 4 [deprecated = true];
  JiraStatusMappingConfiguration jira_status_mapping_configuration = 5;
  repeated JiraFieldConfiguration field_configurations = 6;
  bool jira_bidirectional_sync_is_enabled = 7;
}

message CreateProjectIssueConfigurationResponse {
  JiraProjectIssueConfiguration jira_project_configuration = 1;
}

message UpdateProjectIssueConfigurationRequest {
  string configuration_id = 1;
  JiraStatusMappingConfiguration jira_status_mapping_configuration = 2;
  repeated JiraFieldConfiguration field_configurations = 3;
  bool jira_bidirectional_sync_is_enabled = 4;
}

message UpdateProjectIssueConfigurationResponse {
  JiraProjectIssueConfiguration jira_project_configuration = 1;
}

message DeleteProjectIssueConfigurationRequest {
  string configuration_id = 1 [deprecated = true];
  repeated string configuration_ids = 2;
}

message DeleteProjectIssueConfigurationResponse {}

message GetProjectIssueConfigurationsRequest {
  GetProjectIssueConfigurationsFilter filter = 1;
}

//AND among all fields
message GetProjectIssueConfigurationsFilter {
  optional string integration_id = 1;
  optional string project_id = 2;
  optional string issue_type = 3;
  repeated TraceableEntityType supported_entity_types = 4; // empty means no-matching for this
}

message GetProjectIssueConfigurationsResponse {
  repeated JiraProjectIssueConfiguration jira_project_configurations = 1;
}

message JiraIntegration {
  string id = 1;
  string name = 2;
  string description = 3;
  string consumer_key = 4 [deprecated = true];
  string base_url = 5;
  Scope scope = 6;
  EncryptedData encrypted_access_token = 7 [deprecated = true];
  JiraIntegrationDetails jira_integration_details = 8;
  optional bool jira_bidirectional_sync_is_enabled = 9;
}

message JiraIntegrationDetails {
  oneof integration_details {
    JiraCloudIntegrationDetails jira_cloud_integration_details = 1;
    JiraDataCenterIntegrationDetails jira_data_center_integration_details = 2;
  }
  JiraIntegrationDefaultConfiguration default_project_configuration = 3;
}

message JiraIntegrationDefaultConfiguration {
  string default_project_id = 1;
  optional string default_issue_type = 2;
}

message JiraCloudIntegrationDetails {
  JiraCloudAuthCredentials jira_cloud_auth_credentials = 1;
}

message JiraCloudAuthCredentials {
  string consumer_key = 1;
  EncryptedData encrypted_access_token = 2;
}

message JiraDataCenterIntegrationDetails {
  JiraDataCenterAuthCredentials jira_data_center_auth_credentials = 1;
}

message JiraDataCenterAuthCredentials {
  oneof auth_credentials {
    EncryptedData encrypted_personal_access_token = 1;
  }
  bool is_mtls_enabled = 2;
  optional string ssl_ca_certificate = 3;
  EncryptedData encrypted_ssl_ca_certificate = 4 [deprecated = true];
}

message JiraIntegrationFilter {
  // filtering with scope with environment-ids a,b,c,...
  // will fetch integrations containing at-least one matching environment
  Scope filter_scope = 1;
}

message Scope {
  oneof scope_type {
    StringList environment_ids = 1;
  }
}

message StringList {
  repeated string values = 1;
}

message EncryptedData {
  string base64_encrypted_value = 1;
  string key_id = 2;
}
