global {
  disabled = false
  internal = false
}

detector.config.service {
  modsecDetectionConfigs =
    [
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_912"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_913"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_921"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_930"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_931"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_932"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_934"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_941"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_942"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_943"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_944"
        }
      },
      {
        configStatus = {
          disabled = false
          internal = false
        }
        modsecurityAnomalyDetectionConfig = {
          anomalyRuleId = "crs_951"
        }
      }
    ]
}