global {
  disabled = false
  internal = false
}

detector.config.service {
  modsecDetectionConfigs = []
  apiDefinitionDetectionConfigs =
    [
      {
        configStatus = {
          disabled = true
          internal = true
        }
        apiDefinitionMetadataAnomalyDetectionConfig = {
          anomalyRuleId = "ssrf"
        }
      }
    ]
}