global {
  disabled = false
  internal = false
}

detector.config.service {
  modsecDetectionConfigs = []
  apiDefinitionDetectionConfigs =
    [
      {
        configStatus = {
          disabled = true
          internal = true
        }
        apiDefinitionMetadataAnomalyDetectionConfig = {
          anomalyRuleId = "ssrf"
        }
      }
    ]
  sessionDefinitionDetectionConfigs = []
}

trainer.config.service {
  apiNamingTrainingConfigs = [
    {
      disabled = false
      apiNamingTrainingConfig = {
        urlFilterConfig = {
          urlRejectRegexPatterns = {
            values = [".*\\.css$", ".*\\.jpg$", ".*\\.svg$", ".*\\.js$", ".*\\.pdf$",
              ".*\\.jpeg$", ".*\\.gif$", ".*\\.png$", ".*\\.bmp$", ".*\\.tif$", ".*\\.tiff$",
              ".*\\.mp3$", ".*\\.wma$", ".*\\.wav$", ".*\\.ogg$", ".*\\.mp4$", ".*\\.avi$",
              ".*\\.mkv$", ".*\\.woff$", ".*\\.woff2$", ".*\\.webp$", ".*\\.html$", ".*\\.txt$",
              ".*\\.yml$", ".*\\.yaml$", ".*\\.cgi$", ".*\\.tgz$", ".*\\.rar$", ".*\\.zip$", ".*\\.xml$",
              ".*\\.ico$", ".*\\.htm$", ".*\\.jsp$"]
          }
        }
      }
    },
    {
      disabled = false
      apiNamingTrainingConfig = {
        trieModelTrainingConfig = {
          allowRegexList = {
            values = ["v\\d+"]
          }
          ids = {
            threshold = 1
            regexList = {
            values = ["(\\{){0,1}[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{12}(\\}){0,1}", "\\d+"]
            }
          }
          lowCardinality = {
            threshold = 10
            regexList = {
              values = []
            }
          }
          mediumCardinality = {
            threshold = 25
          }
          highCardinality = {
            threshold = 45
            regexList = {
              values = ["[a-zA-Z]*?([-_+]?[a-zA-Z]+)+[-_+]?"]
            }
          }
          embryonicThreshold = 100
          extensions = {
            values = ["json", "xml"]
          }
        }
      }
    }
  ]
}
