grpc.api.specs = [
  {
    channel = {
      host = inprocess
    },
    grpcClassNames = [
      "ai.traceable.fraud.policy.config.service.v1.FraudPolicyConfigServiceGrpc",
      "ai.traceable.fraud.datamodel.config.service.v1.FraudDataModelConfigServiceGrpc",
      "ai.traceable.fraud.datamodel.derivation.config.service.v1.FraudDataModelDerivationConfigServiceGrpc",
      "ai.traceable.edge.config.service.v1.TraceableEdgeConfigServiceGrpc",
      "ai.traceable.edge.decision.config.service.v1.EdgeDecisionConfigServiceGrpc",
      "ai.traceable.edge.bot.config.service.v1.BotConfigServiceGrpc",
      "ai.traceable.policy.config.service.v1.TraceablePolicyConfigServiceGrpc",
      "ai.traceable.anomaly.config.service.v1.global.AnomalyGlobalConfigServiceGrpc",
      "ai.traceable.customsignature.config.service.v1.CustomSignatureConfigServiceGrpc"
    ]
  }
]