grpc.api.specs = [
  {
    channel = {
      host = inprocess
    },
    grpcClassNames = [
      "ai.traceable.fraud.policy.config.service.v1.FraudPolicyConfigServiceGrpc",
      "ai.traceable.fraud.datamodel.config.service.v1.FraudDataModelConfigServiceGrpc",
      "ai.traceable.fraud.datamodel.derivation.config.service.v1.FraudDataModelDerivationConfigServiceGrpc"
    ]
  },
  {
    channel = {
      host = localhost
      port = 62060
    },
    grpcClassNames = [
      "ai.traceable.risk.decision.service.api.v1.RiskDecisionServiceGrpc"
    ]
  },
  {
    channel = {
      host = localhost
      port = 62056
    },
    grpcClassNames = [
      "ai.traceable.fraud.engine.ml.FraudEngineMLServiceGrpc"
    ]
  },
]