# durations must be specified in seconds only
sampling.config {
  rate.limit.config = {
  # persisting with commented config for example format
    #tenantId = {
    #  traceLimitPerEndpoint = {
    #    fixedWindowLimit = {
    #      quantityAllowed = 10
    #      windowDuration = 60s
    #    }
    #  },
    #  traceLimitGlobal = {
    #    fixedWindowLimit = {
    #      quantityAllowed = 10000
    #      windowDuration = 60s
    #    }
    #  }
    #  apiEndpointCacheDuration = 604800s
    #}
  }
}