syntax = "proto3";

package ai.traceable.bot.categorized.config.service.v1;

import "ai/traceable/bot/categorized/config/service/v1/categorized_bot_config.proto";
import "ai/traceable/datamodel/data/transformation/config/v1/transformation.proto";

option java_multiple_files = true;

service CategorizedBotConfigService {
  rpc GetCategorizedBotConfigs(GetCategorizedBotConfigsRequest) returns (GetCategorizedBotConfigsResponse) {}
  rpc GetCategorizedBotCategoryDetails(GetCategorizedBotCategoryDetailsRequest) returns (GetCategorizedBotCategoryDetailsResponse) {}
  rpc GetCategorizedBotConfigEdgeDecisionVariables(GetCategorizedBotConfigEdgeDecisionVariablesRequest) returns (GetCategorizedBotConfigEdgeDecisionVariablesResponse) {}
}

message GetCategorizedBotCategoryDetailsRequest {
  repeated string bot_category_ids = 1;
}

message GetCategorizedBotCategoryDetailsResponse {
  repeated BotCategory bot_categories = 1;
}

message GetCategorizedBotConfigsRequest {
  optional CategorizedBotRequestFilter bot_request_filter = 1;
}
message GetCategorizedBotConfigsResponse {
  repeated CategorizedBotConfig bot_configs = 1;
}

message CategorizedBotRequestFilter {
  // if none specified all traceable-categorized (pre defined) bots to be sent
  repeated string bot_ids = 1;
  repeated string bot_category_ids = 2;
  repeated string bot_sub_category_ids = 3;
}

message GetCategorizedBotConfigEdgeDecisionVariablesRequest {}

message GetCategorizedBotConfigEdgeDecisionVariablesResponse {
  repeated ai.traceable.datamodel.data.transformation.config.v1.VariableDerivationMapping variable_derivation_mappings = 1;
}
