syntax = "proto3";

package ai.traceable.alerting.config.service.v2;

import "ai/traceable/alerting/config/service/v2/actor_severity_state_change_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/api_fraud_incident_change_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/api_naming_rule_config_change_condition.proto";
import "ai/traceable/alerting/config/service/v2/api_spec_config_change_condition.proto";
import "ai/traceable/alerting/config/service/v2/blocked_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/data_collection_change_condition.proto";
import "ai/traceable/alerting/config/service/v2/detected_security_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/exclude_span_rule_config_change_condition.proto";
import "ai/traceable/alerting/config/service/v2/fraud_detection_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/integration_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/label_config_change_condition.proto";
import "ai/traceable/alerting/config/service/v2/notification_config_change_condition.proto";
import "ai/traceable/alerting/config/service/v2/posture_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/risk_scoring_config_change_condition.proto";
import "ai/traceable/alerting/config/service/v2/security_config_change_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/sensitive_data_configuration_change_condition.proto";
import "ai/traceable/alerting/config/service/v2/threat_actor_state_change_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/threat_scoring_config_change_event_condition.proto";
import "ai/traceable/alerting/config/service/v2/user_change_event_condition.proto";
import "org/hypertrace/alerting/config/service/v1/metric_anomaly_event_condition.proto";

option java_multiple_files = true;

message EventCondition {
  string id = 1;
  EventConditionMutableData event_condition_mutable_data = 2;
}

message EventConditionMutableData {
  oneof condition {
    DetectedSecurityEventCondition detected_security_event_condition = 1;
    ThreatActorStateChangeEventCondition threat_actor_state_change_event_condition = 2;
    BlockedEventCondition blocked_event_condition = 3;
    org.hypertrace.alerting.config.service.v1.MetricAnomalyEventCondition metric_anomaly_event_condition = 4;
    ActorSeverityStateChangeEventCondition actor_severity_state_change_event_condition = 6;
    SecurityConfigChangeEventCondition security_config_change_event_condition = 7;
    UserChangeEventCondition user_change_event_condition = 8;
    NotificationConfigChangeCondition notification_config_change_condition = 10;
    DataCollectionChangeCondition data_collection_change_condition = 11;
    SensitiveDataConfigurationChangeCondition sensitive_data_configuration_change_condition = 12;
    ApiFraudIncidentChangeEventCondition api_fraud_incident_change_event_condition = 13;
    PostureEventCondition posture_event_condition = 14;
    ApiNamingRuleConfigChangeCondition api_naming_rule_config_change_condition = 15;
    ExcludeSpanRuleConfigChangeCondition exclude_span_rule_config_change_condition = 16;
    ApiSpecConfigChangeCondition api_spec_config_change_condition = 17;
    LabelConfigChangeCondition label_config_change_condition = 18;
    RiskScoringConfigChangeCondition risk_scoring_config_change_condition = 19;
    IntegrationEventCondition integration_event_condition = 20;
    ThreatScoringConfigChangeEventCondition threat_scoring_config_change_event_condition = 21;
    FraudDetectionEventCondition fraud_detection_event_condition = 22;
  }
  optional string environment = 5 [deprecated = true]; // use the EventConditionScope moving forward
  EventConditionScope scope = 9;
}

message EventConditionScope {
  oneof scope {
    EnvironmentScope environment_scope = 1;
  }

  message EnvironmentScope {
    repeated string environment_names = 1;
  }
}
