syntax = "proto3";

package ai.traceable.alerting.config.service.v2;

option java_multiple_files = true;

enum SecurityConfigurationType {
  SECURITY_CONFIGURATION_TYPE_UNSPECIFIED = 0;
  SECURITY_CONFIGURATION_TYPE_SIGNATURE_BASED_BLOCKING_RULE = 1;
  SECURITY_CONFIGURATION_TYPE_RATE_LIMITING_RULE = 2;
  SECURITY_CONFIGURATION_TYPE_IP_RANGE_RULE = 3 [deprecated = true];
  SECURITY_CONFIGURATION_TYPE_LOCATION_RULE = 4 [deprecated = true];
  SECURITY_CONFIGURATION_TYPE_CUSTOM_SIGNATURE_RULE = 5;
  SECURITY_CONFIGURATION_TYPE_THREAT_AUTO_BLOCKING = 6 [deprecated = true];
  SECURITY_CONFIGURATION_TYPE_DETECTION_RULE = 7;
  SECURITY_CONFIGURATION_TYPE_EXCLUSIONS = 8;
  SECURITY_CONFIGURATION_TYPE_MALICIOUS_SOURCES_RULE = 9;
  SECURITY_CONFIGURATION_TYPE_DATA_ACCESS_RULE = 10;
  SECURITY_CONFIGURATION_TYPE_ENUMERATION_RULE = 11;
  SECURITY_CONFIGURATION_TYPE_GLOBAL_DETECTION_CONFIG = 12;
  SECURITY_CONFIGURATION_TYPE_MALICIOUS_SOURCES_IP_RANGE_RULE = 13;
  SECURITY_CONFIGURATION_TYPE_MALICIOUS_SOURCES_REGION_RULE = 14;
  SECURITY_CONFIGURATION_TYPE_MALICIOUS_SOURCES_EMAIL_DOMAIN_RULE = 15;
  SECURITY_CONFIGURATION_TYPE_MALICIOUS_SOURCES_IP_TYPE_RULE = 16;
  SECURITY_CONFIGURATION_TYPE_AI_APP_PROTECTION_RULE = 17;
}

message SecurityConfigChangeEventCondition {
  repeated SecurityConfigurationType security_configuration_types = 1;
}
