syntax = "proto3";

package ai.traceable.alerting.config.service.v2;

option java_multiple_files = true;

enum ThreatScoringConfigType {
  THREAT_SCORING_CONFIG_TYPE_UNSPECIFIED = 0;
  THREAT_SCORING_CONFIG_TYPE_ANOMALY_SCORE_CONTRIBUTION = 1;
  THREAT_SCORING_CONFIG_TYPE_SECURITY_EVENT_SCORE_CONTRIBUTION = 2;
  THREAT_SCORING_CONFIG_TYPE_THREAT_SCORE_BOUND = 3;
  THREAT_SCORING_CONFIG_TYPE_SECURITY_EVENT_TYPE_CONTRIBUTION = 4;
  THREAT_SCORING_CONFIG_TYPE_IP_REPUTATION_SCORE_CONTRIBUTION = 5;
  THREAT_SCORING_CONFIG_TYPE_STATUS_CODE_SCORE_CONTRIBUTION = 6;
  THREAT_SCORING_CONFIG_TYPE_THREAT_AUTO_BLOCKING = 7;
}

message ThreatScoringConfigChangeEventCondition {
  repeated ThreatScoringConfigType threat_scoring_config_types = 1;
}
