syntax = "proto3";

package ai.traceable.alerting.config.service.v2;

option java_multiple_files = true;

enum UserChangeType {
  USER_CHANGE_TYPE_UNSPECIFIED = 0;
  USER_CHANGE_TYPE_CREATE = 1;
  USER_CHANGE_TYPE_UPDATE = 2;
  USER_CHANGE_TYPE_DELETE = 3;
  USER_CHANGE_TYPE_INVITE = 4 [deprecated = true];
  USER_CHANGE_TYPE_ACCEPT_INVITE = 5 [deprecated = true];
  USER_CHANGE_TYPE_LOGIN = 6;
  USER_CHANGE_TYPE_LOGOUT = 7;
}

message UserChangeEventCondition {
  repeated UserChangeType user_change_types = 1;
}
