/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.traceable.example.impl;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class MyServiceImplementationIntegrationTest {
    @Test
    public void testSomeMethod() {
        MyServiceImplementation classUnderTest = new MyServiceImplementation();
        assertEquals("implementation", classUnderTest.getText());
    }
}
