genAiRuleIdToConfigMap =
  [
    {
      genAiAnomalyDetectionConfig = {
        anomalyRuleId = "promptTextEvasionAndMisdirection"
        promptTextEvasionAndMisdirection = {}
      }
    },
    {
      genAiAnomalyDetectionConfig = {
        anomalyRuleId = "promptInjection"
        promptInjection = {}
      }
    },
    {
      genAiAnomalyDetectionConfig = {
        anomalyRuleId = "llmRateLimiting"
        llmRateLimiting = {}
      }
    },
    {
      genAiAnomalyDetectionConfig = {
        anomalyRuleId = "piiDetectedInPrompt"
        piiDetectedInPrompt = {}
      }
    },
    {
      genAiAnomalyDetectionConfig = {
        anomalyRuleId = "llmInputExplosion"
        llmInputExplosion = {}
      }
    },
    {
      genAiAnomalyDetectionConfig = {
        anomalyRuleId = "llmModelGovernance"
        llmModelGovernance = {}
      }
    },
    {
      genAiAnomalyDetectionConfig = {
       anomalyRuleId = "codeDetectedInPrompt"
       codeDetectedInPrompt = {}
      }
    },
    {
      genAiAnomalyDetectionConfig = {
        anomalyRuleId = "toxicUnsafeContent"
        toxicUnsafeContent = {}
      }
    }
  ]
