syntax = "proto3";

package ai.traceable.span.processing.config.service.v1;

import "google/protobuf/timestamp.proto";

option java_multiple_files = true;

message KeyValueRetentionRuleSet {
  // Basically like a network ACL - apply first matching rule or use default if no match
  repeated KeyValueRetentionRule rules = 1;
  RetentionAction default = 2;
}

message KeyValueRetentionRuleScope {
  oneof scope {
    EnvironmentScope environment_scope = 1;
  }
  message EnvironmentScope {
    repeated string environment_ids = 1;
  }
}

message KeyValueRetentionRuleData {
  RetentionAction action = 1;
  Predicate predicate = 2;
  google.protobuf.Timestamp expiration = 3;
  KeyValueRetentionRuleScope scope = 4;
}

message KeyValueRetentionRule {
  string id = 1;
  KeyValueRetentionRuleData data = 2;
}

message RetentionAction {
  // Using oneof over simple enum to support configuration in future (e.g. retain but truncate to X chars, sample, etc.)
  oneof action {
    RetainAction retain = 5;
    DiscardAction discard = 6;
    DiscardValueAction discard_value = 7;
  }

  message RetainAction {}
  message DiscardAction {}
  // To retain only the key and discard the value
  message DiscardValueAction {}
}

message Predicate {
  oneof predicate {
    StringPredicate target_key_predicate = 1;
  }
}

message StringPredicate {
  Operator operator = 1;
  oneof rhs  {
    string value = 2;
    StringList any_of_values = 3;
  }

  message StringList {
    repeated string values = 4;
  }

  enum Operator {
    OPERATOR_UNSPECIFIED = 0;
    OPERATOR_EQUALS = 1;
    OPERATOR_MATCHES_REGEX = 2;
    OPERATOR_STARTS_WITH = 3;
    OPERATOR_ENDS_WITH = 4;
    OPERATOR_CONTAINS = 5;
  }
}

enum DataLocation {
  DATA_LOCATION_UNSPECIFIED = 0;
  DATA_LOCATION_REQUEST_HEADER = 1;
  DATA_LOCATION_RESPONSE_HEADER = 2;
  DATA_LOCATION_ATTRIBUTE = 3;
}

enum IngestionStage {
  INGESTION_STAGE_UNSPECIFIED = 0;
  INGESTION_STAGE_QUERY_STORE_PERSISTENCE = 1;
}
