syntax = "proto3";

package ai.traceable.span.processing.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/span/processing/config/service/v1/sampling_configs.proto";
import "ai/traceable/span/processing/config/service/v1/span_filter.proto";
import "ai/traceable/span/processing/config/service/v1/ingestion.proto";
import "google/protobuf/timestamp.proto";

service SpanProcessingConfigService {
  rpc CreateProtectionSpanRule(CreateProtectionSpanRuleRequest) returns (CreateProtectionSpanRuleResponse) {}

  rpc UpdateProtectionSpanRule(UpdateProtectionSpanRuleRequest) returns (UpdateProtectionSpanRuleResponse) {}

  rpc GetAllProtectionSpanRules(GetAllProtectionSpanRulesRequest) returns (GetAllProtectionSpanRulesResponse) {}

  rpc DeleteProtectionSpanRule(DeleteProtectionSpanRuleRequest) returns (DeleteProtectionSpanRuleResponse) {}

  rpc GetAllResolvedProtectionSpanRules(GetAllResolvedProtectionSpanRulesRequest) returns (GetAllResolvedProtectionSpanRulesResponse) {}

  rpc CreateSamplingConfig(CreateSamplingConfigRequest) returns (CreateSamplingConfigResponse) {}

  rpc UpdateSamplingConfig(UpdateSamplingConfigRequest) returns (UpdateSamplingConfigResponse) {}

  rpc GetAllSamplingConfigs(GetAllSamplingConfigsRequest) returns (GetAllSamplingConfigsResponse) {}

  rpc DeleteSamplingConfig(DeleteSamplingConfigRequest) returns (DeleteSamplingConfigResponse) {}

  rpc GetAllResolvedSamplingConfigs(GetAllResolvedSamplingConfigsRequest) returns (GetAllResolvedSamplingConfigsResponse) {}

  rpc GetDefaultProtectionSpanRuleEvaluationStatus(GetDefaultProtectionSpanRuleEvaluationStatusRequest) returns (GetDefaultProtectionSpanRuleEvaluationStatusResponse) {}

  rpc UpdateDefaultProtectionSpanRuleEvaluationStatus(UpdateDefaultProtectionSpanRuleEvaluationStatusRequest) returns (UpdateDefaultProtectionSpanRuleEvaluationStatusResponse) {}

  rpc CreateApiNamingRule (CreateApiNamingRuleRequest) returns (CreateApiNamingRuleResponse) {}

  rpc CreateApiNamingRules (CreateApiNamingRulesRequest) returns (CreateApiNamingRulesResponse) {}

  rpc UpdateApiNamingRule (UpdateApiNamingRuleRequest) returns (UpdateApiNamingRuleResponse) {}

  rpc UpdateApiNamingRules (UpdateApiNamingRulesRequest) returns (UpdateApiNamingRulesResponse) {}

  rpc GetAllApiNamingRules (GetAllApiNamingRulesRequest) returns (GetAllApiNamingRulesResponse) {}

  rpc DeleteApiNamingRule (DeleteApiNamingRuleRequest) returns (DeleteApiNamingRuleResponse) {}

  rpc DeleteApiNamingRules (DeleteApiNamingRulesRequest) returns (DeleteApiNamingRulesResponse) {}

  rpc GetServiceNamingRules (GetServiceNamingRulesRequest) returns (GetServiceNamingRulesResponse) {}
  rpc CreateServiceNamingRule (CreateServiceNamingRuleRequest) returns (CreateServiceNamingRuleResponse) {}
  rpc UpdateServiceNamingRule (UpdateServiceNamingRuleRequest) returns (UpdateServiceNamingRuleResponse) {}
  rpc DeleteServiceNamingRule (DeleteServiceNamingRuleRequest) returns (DeleteServiceNamingRuleResponse) {}

  rpc GetSpanIngestionConfig(GetSpanIngestionConfigRequest) returns (GetSpanIngestionConfigResponse) {}
  rpc CreateSpanIngestionRule(CreateSpanIngestionRuleRequest) returns (CreateSpanIngestionRuleResponse) {}
  rpc UpdateSpanIngestionRule(UpdateSpanIngestionRuleRequest) returns (UpdateSpanIngestionRuleResponse) {}
  rpc DeleteSpanIngestionRule(DeleteSpanIngestionRuleRequest) returns (DeleteSpanIngestionRuleResponse) {}
  rpc RankSpanIngestionRule(RankSpanIngestionRuleRequest) returns (RankSpanIngestionRuleResponse) {}
}

message GetAllResolvedSamplingConfigsRequest {}

message GetAllResolvedSamplingConfigsResponse {
  repeated SamplingConfig sampling_configs = 1;
}

message GetAllResolvedProtectionSpanRulesRequest {}

message GetAllResolvedProtectionSpanRulesResponse {
  repeated ProtectionSpanRule rules = 1;
}

message CreateProtectionSpanRuleRequest {
  ProtectionSpanRuleInfo rule_info = 1;
}

message CreateProtectionSpanRuleResponse {
  ProtectionSpanRuleDetails rule_details = 1;
}

message GetAllProtectionSpanRulesRequest {}

message GetAllProtectionSpanRulesResponse {
  repeated ProtectionSpanRuleDetails rule_details = 1;
}

message UpdateProtectionSpanRuleRequest {
  UpdateProtectionSpanRule rule = 1;
}

message UpdateProtectionSpanRuleResponse {
  ProtectionSpanRuleDetails rule_details = 1;
}

message DeleteProtectionSpanRuleRequest {
  string id = 1;
}

message DeleteProtectionSpanRuleResponse {}

message ProtectionSpanRule {
  string id = 1;
  ProtectionSpanRuleInfo rule_info = 2;
}

message ProtectionSpanRuleDetails {
  ProtectionSpanRule rule = 1;
  ProtectionSpanRuleMetadata metadata = 2;
}

message ProtectionSpanRuleInfo {
  string name = 1;
  SpanFilter filter = 2;
  bool disabled = 3;
}

message ProtectionSpanRuleMetadata {
  google.protobuf.Timestamp creation_timestamp = 1;
  google.protobuf.Timestamp last_updated_timestamp = 2;
}

message UpdateProtectionSpanRule {
  string id = 1;
  string name = 2;
  SpanFilter filter = 3;
  bool disabled = 4;
}

message GetAllSamplingConfigsRequest {}

message GetAllSamplingConfigsResponse {
  repeated SamplingConfigDetails sampling_config_details = 1;
}

message CreateSamplingConfigRequest {
  SamplingConfigInfo sampling_config_info = 1;
}

message CreateSamplingConfigResponse {
  SamplingConfigDetails sampling_config_details = 1;
}

message UpdateSamplingConfigRequest {
  UpdateSamplingConfig sampling_config = 1;
}

message UpdateSamplingConfigResponse {
  SamplingConfigDetails sampling_config_details = 1;
}

message UpdateSamplingConfig {
  string id = 1;
  RateLimitConfig rate_limit_config = 2;
  SpanFilter filter = 3;
}

message DeleteSamplingConfigRequest {
  string id = 1;
}

message DeleteSamplingConfigResponse {}

message GetDefaultProtectionSpanRuleEvaluationStatusRequest {}

message GetDefaultProtectionSpanRuleEvaluationStatusResponse {
  DefaultProtectionSpanRuleEvaluationStatus status = 1;
}

message UpdateDefaultProtectionSpanRuleEvaluationStatusRequest {
  DefaultProtectionSpanRuleEvaluationStatus status = 1;
}

message UpdateDefaultProtectionSpanRuleEvaluationStatusResponse {
  DefaultProtectionSpanRuleEvaluationStatus status = 1;
}

message DefaultProtectionSpanRuleEvaluationStatus {
  bool enabled = 1;
}

message CreateApiNamingRuleRequest {
  ApiNamingRuleInfo rule_info = 1;
}

message CreateApiNamingRuleResponse {
  ApiNamingRuleDetails rule_details = 1;
}

message CreateApiNamingRulesRequest {
  repeated ApiNamingRuleInfo rules_info = 1;
}

message CreateApiNamingRulesResponse {
  repeated ApiNamingRuleDetails rules_details = 1;
}

message GetAllApiNamingRulesRequest {}

message GetAllApiNamingRulesResponse {
  repeated ApiNamingRuleDetails rule_details = 1;
}

message UpdateApiNamingRuleRequest {
  UpdateApiNamingRule rule = 1;
}

message UpdateApiNamingRuleResponse {
  ApiNamingRuleDetails rule_details = 1;
}

message UpdateApiNamingRulesRequest {
  repeated UpdateApiNamingRule rules = 1;
}

message UpdateApiNamingRulesResponse {
  repeated ApiNamingRuleDetails rules_details = 1;
}

message DeleteApiNamingRuleRequest {
  string id = 1;
}

message DeleteApiNamingRuleResponse {}

message DeleteApiNamingRulesRequest {
  repeated string ids = 1;
}

message DeleteApiNamingRulesResponse {}

message ApiNamingRule {
  string id = 1;
  ApiNamingRuleInfo rule_info = 2;
}

message ApiNamingRuleDetails {
  ApiNamingRule rule = 1;
  ApiNamingRuleMetadata metadata = 2;
}

message ApiNamingRuleInfo {
  string name = 1;
  SpanFilter filter = 2;
  ApiNamingRuleConfig rule_config = 3;
  bool disabled = 4;
}

message UpdateApiNamingRule {
  string id = 1;
  string name = 2;
  SpanFilter filter = 3;
  ApiNamingRuleConfig rule_config = 4;
  bool disabled = 5;
}

message ApiNamingRuleConfig {
  oneof rule_config {
    SegmentMatchingBasedConfig segment_matching_based_config = 1;
    ApiSpecBasedConfig api_spec_based_config = 2;
    AstScanBasedConfig ast_scan_based_config = 3;
  }
}

message SegmentMatchingBasedConfig {
  repeated string regexes = 1;
  repeated string values = 2;
}

message ApiSpecBasedConfig {
  string api_spec_id = 1[deprecated = true];
  repeated string api_spec_ids = 4;
  repeated string regexes = 2;
  repeated string values = 3;
}

message AstScanBasedConfig {
  string scan_id = 1;
  string api_spec_id = 2;
  repeated string regexes = 3;
  repeated string values = 4;
}

message ApiNamingRuleMetadata {
  google.protobuf.Timestamp creation_timestamp = 1;
  google.protobuf.Timestamp last_updated_timestamp = 2;
}

message GetServiceNamingRulesRequest {
  ServiceNamingRuleFilter filter = 1;
}

message GetServiceNamingRulesResponse {
  repeated ServiceNamingRule rules = 1;
}

message CreateServiceNamingRuleRequest {
  string name = 1;
  optional string description = 2;
  bool enabled = 3;
  ServiceNamingRuleScope scope = 4;
  repeated ServiceNamingRuleCondition conditions = 5;
  ServiceNamingRuleAction action = 6;
}

message CreateServiceNamingRuleResponse {
  ServiceNamingRule rule = 1;
}

message UpdateServiceNamingRuleRequest {
  string id = 1;
  string name = 2;
  optional string description = 3;
  bool enabled = 4;
  ServiceNamingRuleScope scope = 5;
  repeated ServiceNamingRuleCondition conditions = 6;
  ServiceNamingRuleAction action = 7;
}

message UpdateServiceNamingRuleResponse {
  ServiceNamingRule rule = 1;
}

message DeleteServiceNamingRuleRequest {
  string id = 1;
}

message DeleteServiceNamingRuleResponse {
}

message ServiceNamingRule {
  string id = 1;
  string name = 2;
  int32 rank = 3;
  optional string description = 4;
  bool enabled = 5;
  ServiceNamingRuleScope scope = 6;
  google.protobuf.Timestamp creation_timestamp = 7;
  google.protobuf.Timestamp last_updated_timestamp = 8;
  repeated ServiceNamingRuleCondition conditions = 9;
  ServiceNamingRuleAction action = 10;
}

message ServiceNamingRuleCondition {
  oneof condition {
    AttributeCondition attribute_condition = 1;
  }

  message AttributeCondition {
    string attribute_key = 1;
    ConditionMatchOperator operator = 2;
    string value = 3;
  }

  enum ConditionMatchOperator {
    CONDITION_MATCH_OPERATOR_UNSPECIFIED = 0;
    CONDITION_MATCH_OPERATOR_EQUALS = 1;
    CONDITION_MATCH_OPERATOR_MATCHES_REGEX = 2;
  }
}

message ServiceNamingRuleScope {
  oneof scope {
    EnvironmentScope environment_scope = 1;
  }

  message EnvironmentScope {
    repeated string environment_names = 1;
  }
}

message ServiceNamingRuleAction {
  oneof action {
    StaticNameAssignment static_name_assignment = 1;
    RegexCaptureGroupNameAssignment regex_capture_group_name_assignment = 2;
  }

  message StaticNameAssignment {
    string service_name = 1;
  }

  message RegexCaptureGroupNameAssignment {
    string attribute_key = 1;
    string regex_capture_group = 2;
  }

}
message ServiceNamingRuleFilter {
  ServiceNamingRuleScope scope = 1;
}


message GetSpanIngestionConfigRequest {
  IngestionStage stage = 1;
  SpanIngestionConfigFilter filter = 2;
}

message SpanIngestionConfigFilter {
  optional bool is_rule_expired = 1;
}

message GetSpanIngestionConfigResponse {
  KeyValueRetentionRuleSet request_header_ruleset = 1;
  KeyValueRetentionRuleSet response_header_ruleset = 2;
  KeyValueRetentionRuleSet attribute_ruleset = 3;
  // More could be added later like req body truncation limits etc.
}

message CreateSpanIngestionRuleRequest {
  IngestionStage stage = 1;
  oneof rule {
    KeyValueRetentionRuleData request_header_rule = 2;
    KeyValueRetentionRuleData response_header_rule = 3;
    KeyValueRetentionRuleData attribute_rule = 4;
  }
}

message CreateSpanIngestionRuleResponse {
  KeyValueRetentionRule rule = 1;
}

message UpdateSpanIngestionRuleRequest {
  string id = 1;
  oneof rule {
    KeyValueRetentionRuleData key_value_retention_rule_data = 2;
  }
}

message UpdateSpanIngestionRuleResponse {
  KeyValueRetentionRule rule = 1;
}

message DeleteSpanIngestionRuleRequest {
  string id = 1;
}

message DeleteSpanIngestionRuleResponse {
}

message RankSpanIngestionRuleRequest {
  string id_to_update = 1;
  // The id of the rule that should immediately precede the target id. Omit if we're updating to highest rank.
  optional string preceding_rule_id = 2;
}

message RankSpanIngestionRuleResponse {
}
