syntax = "proto3";

package ai.traceable.span.processing.config.service.v1;

option java_multiple_files = true;

import "ai/traceable/span/processing/config/service/v1/sampling_configs.proto";
import "ai/traceable/span/processing/config/service/v1/span_filter.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

service SpanProcessingConfigService {
  rpc CreateProtectionSpanRule(CreateProtectionSpanRuleRequest) returns (CreateProtectionSpanRuleResponse) {}

  rpc UpdateProtectionSpanRule(UpdateProtectionSpanRuleRequest) returns (UpdateProtectionSpanRuleResponse) {}

  rpc GetAllProtectionSpanRules(GetAllProtectionSpanRulesRequest) returns (GetAllProtectionSpanRulesResponse) {}

  rpc DeleteProtectionSpanRule(DeleteProtectionSpanRuleRequest) returns (DeleteProtectionSpanRuleResponse) {}

  rpc GetAllResolvedProtectionSpanRules(GetAllResolvedProtectionSpanRulesRequest) returns (GetAllResolvedProtectionSpanRulesResponse) {}

  rpc CreateSamplingConfig(CreateSamplingConfigRequest) returns (CreateSamplingConfigResponse) {}

  rpc UpdateSamplingConfig(UpdateSamplingConfigRequest) returns (UpdateSamplingConfigResponse) {}

  rpc GetAllSamplingConfigs(GetAllSamplingConfigsRequest) returns (GetAllSamplingConfigsResponse) {}

  rpc DeleteSamplingConfig(DeleteSamplingConfigRequest) returns (DeleteSamplingConfigResponse) {}

  rpc GetAllResolvedSamplingConfigs(GetAllResolvedSamplingConfigsRequest) returns (GetAllResolvedSamplingConfigsResponse) {}

  rpc GetDefaultProtectionSpanRuleEvaluationStatus(GetDefaultProtectionSpanRuleEvaluationStatusRequest) returns (GetDefaultProtectionSpanRuleEvaluationStatusResponse) {}

  rpc UpdateDefaultProtectionSpanRuleEvaluationStatus(UpdateDefaultProtectionSpanRuleEvaluationStatusRequest) returns (UpdateDefaultProtectionSpanRuleEvaluationStatusResponse) {}

  rpc CreateApiNamingRule (CreateApiNamingRuleRequest) returns (CreateApiNamingRuleResponse) {}

  rpc CreateApiNamingRules (CreateApiNamingRulesRequest) returns (CreateApiNamingRulesResponse) {}

  rpc UpdateApiNamingRule (UpdateApiNamingRuleRequest) returns (UpdateApiNamingRuleResponse) {}

  rpc UpdateApiNamingRules (UpdateApiNamingRulesRequest) returns (UpdateApiNamingRulesResponse) {}

  rpc GetAllApiNamingRules (GetAllApiNamingRulesRequest) returns (GetAllApiNamingRulesResponse) {}

  rpc DeleteApiNamingRule (DeleteApiNamingRuleRequest) returns (DeleteApiNamingRuleResponse) {}

  rpc DeleteApiNamingRules (DeleteApiNamingRulesRequest) returns (DeleteApiNamingRulesResponse) {}
}

message GetAllResolvedSamplingConfigsRequest {}

message GetAllResolvedSamplingConfigsResponse {
  repeated SamplingConfig sampling_configs = 1;
}

message GetAllResolvedProtectionSpanRulesRequest {}

message GetAllResolvedProtectionSpanRulesResponse {
  repeated ProtectionSpanRule rules = 1;
}

message CreateProtectionSpanRuleRequest {
  ProtectionSpanRuleInfo rule_info = 1;
}

message CreateProtectionSpanRuleResponse {
  ProtectionSpanRuleDetails rule_details = 1;
}

message GetAllProtectionSpanRulesRequest {}

message GetAllProtectionSpanRulesResponse {
  repeated ProtectionSpanRuleDetails rule_details = 1;
}

message UpdateProtectionSpanRuleRequest {
  UpdateProtectionSpanRule rule = 1;
}

message UpdateProtectionSpanRuleResponse {
  ProtectionSpanRuleDetails rule_details = 1;
}

message DeleteProtectionSpanRuleRequest {
  string id = 1;
}

message DeleteProtectionSpanRuleResponse {}

message ProtectionSpanRule {
  string id = 1;
  ProtectionSpanRuleInfo rule_info = 2;
}

message ProtectionSpanRuleDetails {
  ProtectionSpanRule rule = 1;
  ProtectionSpanRuleMetadata metadata = 2;
}

message ProtectionSpanRuleInfo {
  string name = 1;
  SpanFilter filter = 2;
  bool disabled = 3;
}

message ProtectionSpanRuleMetadata {
  google.protobuf.Timestamp creation_timestamp = 1;
  google.protobuf.Timestamp last_updated_timestamp = 2;
}

message UpdateProtectionSpanRule {
  string id = 1;
  string name = 2;
  SpanFilter filter = 3;
  bool disabled = 4;
}

message GetAllSamplingConfigsRequest {}

message GetAllSamplingConfigsResponse {
  repeated SamplingConfigDetails sampling_config_details = 1;
}

message CreateSamplingConfigRequest {
  SamplingConfigInfo sampling_config_info = 1;
}

message CreateSamplingConfigResponse {
  SamplingConfigDetails sampling_config_details = 1;
}

message UpdateSamplingConfigRequest {
  UpdateSamplingConfig sampling_config = 1;
}

message UpdateSamplingConfigResponse {
  SamplingConfigDetails sampling_config_details = 1;
}

message UpdateSamplingConfig {
  string id = 1;
  RateLimitConfig rate_limit_config = 2;
  SpanFilter filter = 3;
}

message DeleteSamplingConfigRequest {
  string id = 1;
}

message DeleteSamplingConfigResponse {}

message GetDefaultProtectionSpanRuleEvaluationStatusRequest {}

message GetDefaultProtectionSpanRuleEvaluationStatusResponse {
  DefaultProtectionSpanRuleEvaluationStatus status = 1;
}

message UpdateDefaultProtectionSpanRuleEvaluationStatusRequest {
  DefaultProtectionSpanRuleEvaluationStatus status = 1;
}

message UpdateDefaultProtectionSpanRuleEvaluationStatusResponse {
  DefaultProtectionSpanRuleEvaluationStatus status = 1;
}

message DefaultProtectionSpanRuleEvaluationStatus {
  bool enabled = 1;
}

message CreateApiNamingRuleRequest {
  ApiNamingRuleInfo rule_info = 1;
}

message CreateApiNamingRuleResponse {
  ApiNamingRuleDetails rule_details = 1;
}

message CreateApiNamingRulesRequest {
  repeated ApiNamingRuleInfo rules_info = 1;
}

message CreateApiNamingRulesResponse {
  repeated ApiNamingRuleDetails rules_details = 1;
}

message GetAllApiNamingRulesRequest {}

message GetAllApiNamingRulesResponse {
  repeated ApiNamingRuleDetails rule_details = 1;
}

message UpdateApiNamingRuleRequest {
  UpdateApiNamingRule rule = 1;
}

message UpdateApiNamingRuleResponse {
  ApiNamingRuleDetails rule_details = 1;
}

message UpdateApiNamingRulesRequest {
  repeated UpdateApiNamingRule rules = 1;
}

message UpdateApiNamingRulesResponse {
  repeated ApiNamingRuleDetails rules_details = 1;
}

message DeleteApiNamingRuleRequest {
  string id = 1;
}

message DeleteApiNamingRuleResponse {}

message DeleteApiNamingRulesRequest {
  repeated string ids = 1;
}

message DeleteApiNamingRulesResponse {}

message ApiNamingRule {
  string id = 1;
  ApiNamingRuleInfo rule_info = 2;
}

message ApiNamingRuleDetails {
  ApiNamingRule rule = 1;
  ApiNamingRuleMetadata metadata = 2;
}

message ApiNamingRuleInfo {
  string name = 1;
  SpanFilter filter = 2;
  ApiNamingRuleConfig rule_config = 3;
  bool disabled = 4;
}

message UpdateApiNamingRule {
  string id = 1;
  string name = 2;
  SpanFilter filter = 3;
  ApiNamingRuleConfig rule_config = 4;
  bool disabled = 5;
}

message ApiNamingRuleConfig {
  oneof rule_config {
    SegmentMatchingBasedConfig segment_matching_based_config = 1;
    ApiSpecBasedConfig api_spec_based_config = 2;
    AstScanBasedConfig ast_scan_based_config = 3;
  }
}

message SegmentMatchingBasedConfig {
  repeated string regexes = 1;
  repeated string values = 2;
}

message ApiSpecBasedConfig {
  string api_spec_id = 1[deprecated = true];
  repeated string api_spec_ids = 4;
  repeated string regexes = 2;
  repeated string values = 3;
}

message AstScanBasedConfig {
  string scan_id = 1;
  string api_spec_id = 2;
  repeated string regexes = 3;
  repeated string values = 4;
}

message ApiNamingRuleMetadata {
  google.protobuf.Timestamp creation_timestamp = 1;
  google.protobuf.Timestamp last_updated_timestamp = 2;
}
