# Default values for the helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# Note about Namespace
# --------------------
# It is deliberately left out here and using the helm -n or --namespace flag you can deploy your resources to the same
# namespace as the release. If you leave it out, your resources will be deployed to the default namespace.
# Also, note that the namespace you are deploying to should already exist otherwise the helm command will fail.
# You can always specify a different namespace for a resource by setting it directly in it's yaml file or
# making it configurable by defining it in this file.

###########
# Deployment and Service
###########
replicaCount: 1
maxUnavailable: 0

image:
  repository: traceableai-docker.jfrog.io/traceable/traceable-config-service
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

internalContainerPort: 50101
externalContainerPort: 50102
containerAdminPort: 50103
internalContainerPortName: grpc-int-port
externalContainerPortName: grpc-ext-port

service:
  type: ClusterIP
  internalPort: 50101
  externalPort: 50102

nodeLabels: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=60.0 -XX:MaxDirectMemorySize=128M -XX:+ExitOnOutOfMemoryError"

livenessProbe:
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 3
startupProbe:
  periodSeconds: 5
  failureThreshold: 24
  timeoutSeconds: 3

resources:
  requests:
    cpu: 0.1
    memory: 1.25Gi
  limits:
    cpu: 0.5
    memory: 1.25Gi

deploymentLabels:
  app: traceable-config-service

podLabels:
  app: traceable-config-service

podAnnotations: {}

# The Deployment Selector match labels are different from the pod labels. Note that they should be a subset of the pod
# labels. You append new labels to them but cannot remove labels. If you remove or modify the labels you will need to
# delete the existing deployment bearing the same name and then redeploy. This is the reason why they are separated from
# the pod labels. You can add and remove pod labels without having an effect on the deployment.
# Also, please use "apiVersion: apps/v1" instead of the deprecated "apiVersion: extensions/v1beta1" for the deployment
# apiVersion in the yaml file.
deploymentSelectorMatchLabels:
  app: traceable-config-service

serviceSelectorLabels:
  app: traceable-config-service

serviceAccount:
  create: false
  name: traceable-config-service
  annotations: {}

modelStoreNFSMountPath: "/var/data/models"
modelStoreNFSClaimName: "traceable-nfs-model-store"
deepStoreFilePath: "/var/data/customers/"
deepStoreFsScheme: "gs"
deepStoreMountPath: "/var/data"
deepStoreClaimName: "traceable-nfs-deep-store"
s3BucketName: ""
bucketPrefix: traceable-saas
s3.config:
  - fs.s3a.endpoint: "s3-us-west-2.amazonaws.com"

iamServiceAccountSecret: gcs-iam-secret

trieModels:
  modelStores:
    - deepStoreScheme: "file"
      readEnabled: true
      readPriority: 1
      writeDisabled: false
  cache:
    refreshAfterWriteDuration: 150s
    expireAfterWriteDuration: 300s
    maximumSize: 100

trieDiffLog:
  modelStore:
    deepStoreScheme: "file"
  trieDiffLogsRetentionPeriod: 1h
  cache:
    refreshAfterWriteDuration: 150s
    expireAfterWriteDuration: 300s
    maximumSize: 100

entityFetcher:
  cache:
    refreshAfterWriteDuration: 12h
    expireAfterWriteDuration: 24h
    maximumSize: 1000
    delegate:
      refreshAfterWriteDuration: 600s
      expireAfterWriteDuration: 1200s
      maximumSize: 1000

apiNamingCustomRules:
  cache:
    refreshAfterWriteDuration: 150s
    expireAfterWriteDuration: 300s
    maximumSize: 100

apiNamingConfigs:
  cache:
    refreshAfterWriteDuration: 12h
    expireAfterWriteDuration: 24h
    maximumSize: 100

###########
# Config Maps
###########
traceableConfigServiceConfig:
  name: traceable-config-service-config
  publishChangeEvents: false
  dataStoreType: "mongo"
  mongo:
    host: mongo
    url: ""
  actorServiceConfig:
    host: actor-service
    port: 50888
    request:
      timeout: 10s
    cache:
      maxCacheSize: 10000
      expireAfterWriteDuration: 10m
      refreshAfterWriteDuration: 30s

  insightsServiceConfig:
    host: insights-service
    port: 50098
    request:
      timeout: 10s
  entityServiceConfig:
    host: entity-service
    port: 50061
    cache:
      maxCacheSize: 10000
      refreshAfterWriteDuration: 10m
      expireAfterWriteDuration: 12h
  licenseMeteringServiceConfig:
    host: license-metering-service
    port: 51018
    cacheExpiryDuration: 5m
  featureFlagServiceConfig:
    host: feature-flag-service
    port: 51001
    request:
      timeout: 10s
    cache:
      refresh:
        duration: 5m
      expiration:
        duration: 15m
      thread:
        pool:
          size: 2
  labelApplicationRuleConfigServiceConfig:
    maxDynamicLabelApplicationRulesPerTenant: 100

localApiNamingConfig:
  fullTrieReloadConfig:
    #commented config for reference
    #    tenant1:
    #      disabled: true
    #      timestamp: 2022-03-09T13:36:33Z #in ISO-8601 format
    default:
      disabled: true
      version: "1.2.4"

logConfig:
  name: traceable-config-service-log-config
  monitorInterval: 30
  rootLogger:
    level: INFO
  appender:
    rolling:
      enabled: false

anomalyConfigServiceConfig:
  name: anomaly-config-service-config
  global:
    disabled: false
    internal: false
    licenseTiers: |-
      [
        {
          tier = TIER_TEAM_TRIAL
          disabled = false
        }
      ]

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

cleanupJob:
  enabled: false
  schedule: "0 * * * *"
  startingDeadlineSeconds: 18000
  activeDeadlineSeconds: 18000
  ttlSecondsAfterFinished: 900
  concurrencyPolicy: Forbid
  image:
    repository: "hypertrace/mongo-curl"
    tag: "0.1.4"
    pullPolicy: IfNotPresent
  mongodb:
    uri: "mongodb://mongo-primary-0.mongo-headless:27017,mongo-secondary-0.mongo-headless:27017/default_db?replicaSet=rs0"
  podAnnotations: {}
  imagePullSecrets: []
  affinity: []
  nodeSelector: {}
  securityContext: {}
  tolerations: []

kafka-topic-creator:
  enabled: true
  jobName: traceable-config-service-kafka-topics-creator
  helmHook: pre-install,pre-upgrade
  kafka:
    topics:
      config-change-events:
        replicationFactor: 3
        partitions: 8
        configs:
          retention.bytes: 1073741824 # default = -1
          retention.ms: 86400000 # default = 604800000 (7 days)
  zookeeper:
    address: zookeeper:2181
  imagePullSecrets: []
  podAnnotations: {}
