syntax = "proto3";

package ai.traceable.aiapp.protection.config.service.v1;

import "ai/traceable/aiapp/protection/config/service/v1/common.proto";
import "ai/traceable/graphql/autogen/schema/annotations/field/v1/graphql_field_options.proto";
import "google/protobuf/struct.proto";

option java_multiple_files = true;

message AiAppCustomRule {
  string rule_id = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "ID of the custom rule"];
  AiAppCustomRuleData rule_data = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Details of the custom rule"];
}

message AiAppCustomRuleData {
  string rule_name = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Name of the rule"];
  string description = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Description of the rule"];
  RuleStatusDetails rule_status_details = 3 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Status details of the rule"];
  bool enabled = 4 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "If the rule is enabled"];
  RuleScope rule_scope = 5 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Scope of the rule"];
  Action action = 6 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Action of the rule"];
  map<string, string> event_labels = 7 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Event labels of the rule"];
  oneof rule_data {
    PiiDetectedInPromptRuleData pii_detected_in_prompt_rule_data = 8 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "PII detected in prompt custom rule details"];
    AiRateLimitingRuleData ai_rate_limiting_rule_data = 9 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "AI rate limiting custom rule details"];
    ModelGovernanceRuleData model_governance_rule_data = 10 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Model governance custom rule details"];
    AiInputExplosionRuleData ai_input_explosion_rule_data = 11 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "AI input explosion custom rule details"];
  }
}

message PiiDetectedInPromptRuleData {
  DatatypeCondition datatype_condition = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Datatype condition of the rule"];
  ScopeCondition scope_condition = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Scope condition of the rule"];
}

message AiRateLimitingRuleData {
  MatchOperatorCondition ai_model_types_condition = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "AI model types condition of the rule"];
  MatchOperatorCondition ai_vendors_condition = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "AI vendors condition of the rule"];
  ResourceAccessThresholdConfig threshold_config = 3 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Threshold config of the rule"];
  ScopeCondition scope_condition = 4 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Scope condition of the rule"];
}

message ModelGovernanceRuleData {
  MatchOperatorCondition ai_model_types_condition = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "AI model types condition of the rule"];
  MatchOperatorCondition ai_vendors_condition = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "AI vendors condition of the rule"];
  ScopeCondition scope_condition = 3 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Scope condition of the rule"];
}

message AiInputExplosionRuleData {
  int32 input_character_limit = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Input character limit of the rule"];
  ScopeCondition scope_condition = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Scope condition of the rule"];
}

message RuleStatusDetails {
  bool hidden = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "If the rule is hidden"];
  bool internal = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "If the rule is marked for generating internal events"];
  RuleSource rule_creation_source = 3 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Creation source for the rule"];

  enum RuleSource {
    RULE_SOURCE_UNSPECIFIED = 0;
    RULE_SOURCE_DEFAULT = 1;
    RULE_SOURCE_CUSTOMER = 2;
    RULE_SOURCE_TRACEABLE = 3;
  }
}

message DatatypeCondition {
  repeated string dataset_ids = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Dataset IDs of the condition"];
  repeated string datatype_ids = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Datatype IDs of the condition"];
  MatchOperatorCondition request_body_custom_location_condition = 3 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Custom request body location condition for datatype matching"];
}

message ScopeCondition {
  oneof scope {
    EntityScope entity_scope = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Entity scope condition of the rule"];
    UrlScope url_scope = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "URL scope condition of the rule"];
  }

  message EntityScope {
    EntityType entity_type = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Entity type for the scope"];
    repeated string entity_ids = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Entity IDs for the scope"];
  }

  message UrlScope {
    repeated string url_regexes = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "URL regexes for the scope"];
  }

  enum EntityType {
    ENTITY_TYPE_UNSPECIFIED = 0;
    ENTITY_TYPE_API = 1;
  }
}

message MatchOperatorCondition {
  MatchOperator operator = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Match operator for the condition"];
  google.protobuf.Value value = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Value to be matched for the condition"];
}

enum MatchOperator {
  MATCH_OPERATOR_UNSPECIFIED = 0;
  MATCH_OPERATOR_EQUALS = 1;
  MATCH_OPERATOR_NOT_EQUAL = 2;
  MATCH_OPERATOR_MATCHES_REGEX = 3;
  MATCH_OPERATOR_NOT_MATCH_REGEX = 4;
  MATCH_OPERATOR_CONTAINS = 5;
  MATCH_OPERATOR_NOT_CONTAIN = 6;
  MATCH_OPERATOR_GREATER_THAN = 7;
  MATCH_OPERATOR_LESS_THAN = 8;
}

message Action {
  oneof action {
    Alert alert = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Alert action for the rule"];
    MarkForTesting mark_for_testing = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Mark for testing action for the rule"];
  }

  message Alert {
    SeverityLevel severity_level = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Severity level for the alert action"];
  }

  message MarkForTesting {}
}

message ResourceAccessThresholdConfig {
  UserAggregateType user_aggregate_type = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "User aggregate type for the threshold config"];
  ApiAggregateType api_aggregate_type = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "API aggregate type for the threshold config"];
  oneof threshold_config {
    RollingWindowThresholdConfig rolling_window_threshold_config = 3 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Static threshold config"]; // static threshold
  }

  message RollingWindowThresholdConfig {
    int64 count_allowed = 1 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Count allowed for the static threshold config"];
    string duration_iso = 2 [(ai.traceable.graphql.autogen.schema.annotations.field.v1.graphql_description) = "Duration for the threshold config"];
  }
}

enum UserAggregateType {
  USER_AGGREGATE_TYPE_UNSPECIFIED = 0;
  USER_AGGREGATE_TYPE_PER_USER = 1;
  USER_AGGREGATE_TYPE_ACROSS_USERS = 2;
}

enum ApiAggregateType {
  API_AGGREGATE_TYPE_UNSPECIFIED = 0;
  API_AGGREGATE_TYPE_PER_ENDPOINT = 1;
  API_AGGREGATE_TYPE_ACROSS_ENDPOINTS = 2;
}

enum AiAppCustomRuleType {
  AI_APP_CUSTOM_RULE_TYPE_UNSPECIFIED = 0;
  AI_APP_CUSTOM_RULE_TYPE_PII_DETECTED_IN_PROMPT = 1;
  AI_APP_CUSTOM_RULE_TYPE_RATE_LIMITING = 2;
  AI_APP_CUSTOM_RULE_TYPE_MODEL_GOVERNANCE = 3;
  AI_APP_CUSTOM_RULE_TYPE_INPUT_EXPLOSION = 4;
}
