default.jwt.extraction.rules = [
  {
    "id": "default-jwt-auth-header-extraction",
    "predicate": {},
    "locations": [
      {
        "regexCaptureGroup": "^(?i)Bearer\\s*:?\\s*(.*)$",
        "requestHeader": {
          "operator": "RELATIONAL_OPERATOR_EQUALS",
          "value": "authorization"
        }
      }
    ],
    "instructions": [
      {
        "valueExtraction": {
          "payloadClaimName": "iss"
        },
        "action": {
          "addNewAttribute": "iss"
        }
      },
      {
        "valueExtraction": {
          "payloadClaimName": "aud"
        },
        "action": {
          "addNewAttribute": "aud"
        }
      },
      {
        "valueExtraction": {
          "payloadClaimName": "exp"
        },
        "action": {
          "addNewAttribute": "exp"
        }
      },
      {
        "valueExtraction": {
          "headerKey": "alg"
        },
        "action": {
          "addNewAttribute": "alg"
        }
      }
    ],
    "default": true
  }
]