syntax = "proto3";

option java_multiple_files = true;

package ai.traceable.alerting.config.service.v2;

message DetectedSecurityEventCondition {
  repeated SecurityEventType event_types = 1;
  repeated SecurityEventSeverity severities = 2;
}

enum SecurityEventSeverity {
  SECURITY_EVENT_SEVERITY_UNSPECIFIED = 0;
  SECURITY_EVENT_SEVERITY_LOW = 1;
  SECURITY_EVENT_SEVERITY_MEDIUM = 2;
  SECURITY_EVENT_SEVERITY_HIGH = 3;
  SECURITY_EVENT_SEVERITY_CRITICAL = 4;
}

enum SecurityEventType {
    SECURITY_EVENT_TYPE_UNSPECIFIED = 0;
    SECURITY_EVENT_TYPE_XSS = 1;
    SECURITY_EVENT_TYPE_SCANNER_DETECTED = 2;
    SECURITY_EVENT_TYPE_SESSION_FIXATION = 3;
    SECURITY_EVENT_TYPE_PATH_MANIPULATION = 4;
    SECURITY_EVENT_TYPE_KNOWN_VULNERABILITIES = 5;
    SECURITY_EVENT_TYPE_REQUEST_RESPONSE_METADATA_ANOMALIES = 6;
    SECURITY_EVENT_TYPE_INJECTIONS = 7;
    SECURITY_EVENT_TYPE_PARAMETER_ANOMALIES =8;
    SECURITY_EVENT_TYPE_AUTHORIZATION_VIOLATIONS = 9;
    SECURITY_EVENT_TYPE_RATE_LIMITING = 10;
    SECURITY_EVENT_TYPE_SSRF = 11;
    SECURITY_EVENT_TYPE_CUSTOM_SIGNATURE_RULES = 12;
}
