volumetricRuleIdToConfigMap =
  [
    {
      volumetricAnomalyDetectionConfig {
        anomalyRuleId = "volumetricApiCallSpike"
        apiCallSpike = {}
      }
    },
    {
      volumetricAnomalyDetectionConfig {
        anomalyRuleId = "volumetric"
        apiCallSpike = {}
      }
    }
  ]