modsecRules = [
  {
    ruleId = "crs_913"
    ruleName = "Scanner Detection"
  },
  {
    ruleId = "crs_941"
    ruleName = "Cross Site Scripting"
  },
  {
    ruleId = "crs_943"
    ruleName = "Session Fixation"
  },
  {
    ruleId = "crs_921"
    ruleName = "HTTP Protocol Attacks"
    ruleCategory = "Injections"
  },
  {
    ruleId = "crs_934"
    ruleName = "NodeJS Injection"
    ruleCategory = "Injections"
  },
  {
    ruleId = "crs_942"
    ruleName = "SQL Injection"
    ruleCategory = "Injections"
  },
  {
    ruleId = "crs_930"
    ruleName = "Local File Inclusion"
    ruleCategory = "Path Manipulation"
  },
  {
    ruleId = "crs_931"
    ruleName = "Remote File Inclusion"
    ruleCategory = "Path Manipulation"
  },
  {
    ruleId = "crs_932"
    ruleName = "Remote Code Execution"
    ruleCategory = "Known Vulnerabilities"
  },
  {
    ruleId = "crs_944"
    ruleName = "Java Apache Struts Attacks"
    ruleCategory = "Known Vulnerabilities"
  }
]