modsecRules = [
  {
    ruleId = "crs_101"
    ruleName = "Server Side Request Forgery (SSRF) Signatures"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_SSRF
  },
  {
    ruleId = "crs_913"
    ruleName = "Scanner Detection"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_SCANNER_DETECTED
  },
  {
    ruleId = "crs_941"
    ruleName = "Cross Site Scripting (XSS)"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_XSS
  },
  {
    ruleId = "crs_943"
    ruleName = "Session Fixation"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_SESSION_FIXATION
  },
  {
    ruleId = "crs_921"
    ruleName = "HTTP Protocol Attacks"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_INJECTIONS
  },
  {
    ruleId = "crs_102"
    ruleName = "XML External Entity Injection (XXE)"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_INJECTIONS
  },
  {
    ruleId = "crs_934"
    ruleName = "NodeJS Injection"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_INJECTIONS
  },
  {
    ruleId = "crs_942"
    ruleName = "SQL Injection"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_INJECTIONS
  },
  {
    ruleId = "crs_930"
    ruleName = "Local File Inclusion"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PATH_MANIPULATION
  },
  {
    ruleId = "crs_931"
    ruleName = "Remote File Inclusion"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_PATH_MANIPULATION
  },
  {
    ruleId = "crs_932"
    ruleName = "Remote Code Execution"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_KNOWN_VULNERABILITIES
  },
  {
    ruleId = "crs_944"
    ruleName = "Java Application Attacks"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_KNOWN_VULNERABILITIES
  },
  {
    ruleId = "crs_103"
    ruleName = "Basic Authentication Violation"
    anomalyRuleCategory = ANOMALY_RULE_CATEGORY_AUTHENTICATION_AND_TOKEN_VIOLATIONS
  } 
]
