syntax = "proto3";

package ai.traceable.api.spec.config.service.v1;

option java_multiple_files = true;

import "google/protobuf/timestamp.proto";

// get
message GetApiSpecsRequest {
  ApiSpecFilter api_spec_filter = 1;
}

message ApiSpecFilter {
  oneof filter {
    FileContentSha256Filter file_content_sha_256 = 1;
    StringList ids = 2;
    StringList spec_paths = 3;
  }
  SpecTypeFilter spec_type_filter = 4;
  optional bool api_inspector_disabled = 5;
  ReferenceApiSpecFilter reference_api_spec = 6;
  ReferenceTypeFilter reference_type = 7;
}

message ReferenceApiSpecFilter {
  repeated ReferenceApiSpec reference_api_specs = 1;
}

message ReferenceTypeFilter {
  repeated ReferenceType reference_types = 1;
}

message ReferenceApiSpec {
  oneof reference_type {
    string spec_id = 1;
    string spec_path = 2;
  }
}

message StringList {
  repeated string values = 1;
}

message FileContentSha256Filter {
  repeated string file_content_sha256 = 1;
}

message SpecTypeFilter {
  repeated SpecType spec_types = 1;
}

message GetApiSpecsResponse {
  repeated ApiSpec api_specs = 1;
}

message GetApiSpecRequest {
  string id = 1;
}

message GetApiSpecResponse {
  ApiSpec api_spec = 1;
}

// create
message CreateApiSpecRequest {
  CreateApiSpec create_api_spec = 1;
}

message CreateApiSpecResponse {
  ApiSpec api_spec = 1;
}

message CreateApiSpec {
  string name = 1;
  bool api_naming_enabled = 2;
  ApiSpecStatus status = 3;
  optional string file_content_sha256 = 4;
  optional string spec_path = 5;
  bool api_discovery_enabled = 6;
  SpecType spec_type = 7;
  bool api_inspector_disabled = 8;
}

// update
message UpdateApiSpecRequest {
  UpdateApiSpec api_spec = 1;
}

message UpdateApiSpecResponse {
  ApiSpec api_spec = 1;
}

message UpdateApiSpecsRequest {
  repeated UpdateApiSpec api_specs = 1;
}

message UpdateApiSpecsResponse {
  repeated ApiSpec api_specs = 1;
}

message UpdateApiSpec {
  string spec_id = 1;
  string name = 2;
  bool api_naming_enabled = 3;
  ApiSpecStatus status = 4;
  bool api_discovery_enabled = 5;
  bool api_inspector_disabled = 6;
}

// delete
message DeleteApiSpecRequest {
  string spec_id = 1;
}

message DeleteApiSpecResponse {
}

message DeleteApiSpecsRequest {
  repeated string spec_ids = 1;
}

message DeleteApiSpecsResponse {
}

message ApiSpec {
  string spec_id = 1;
  string name = 2;
  bool api_naming_enabled = 3;
  ApiSpecStatus status = 4;
  google.protobuf.Timestamp creation_timestamp = 5;
  google.protobuf.Timestamp last_updated_timestamp = 6;
  optional string file_content_sha256 = 7;
  optional string spec_path = 8;
  bool api_discovery_enabled = 9;
  SpecType spec_type = 10;
  bool api_inspector_disabled = 11;
  ReferenceType reference_type = 12;
  ApiSpecMetadata api_spec_metadata = 13;
}

enum ReferenceType {
  REFERENCE_TYPE_UNSPECIFIED = 0;
  REFERENCE_TYPE_MAIN = 1;
  REFERENCE_TYPE_REFERENCE = 2;
}

message ApiSpecMetadata {
  oneof spec_metadata_type {
    OpenApiSpecMetadata open_api_spec_metadata = 1;
    PostmanCollectionMetadata postman_collection_metadata = 2;
    PostmanEnvironmentMetadata postman_environment_metadata = 3;
    GraphqlSchemaMetadata graphql_schema_metadata = 4;
  }
}

message OpenApiSpecMetadata {
  repeated OpenApiSpecReference open_api_spec_references = 1;
  OpenApiSpecResolutionState open_api_spec_resolution_state = 2;
}

enum OpenApiSpecResolutionState {
  OPEN_API_SPEC_RESOLUTION_STATE_UNSPECIFIED = 0;
  OPEN_API_SPEC_RESOLUTION_STATE_INCOMPLETE = 1;
  OPEN_API_SPEC_RESOLUTION_STATE_COMPLETE = 2;
}

message PostmanCollectionMetadata {
}

message PostmanEnvironmentMetadata {
}

message GraphqlSchemaMetadata {
}

message OpenApiSpecReference {
  string resolved_spec_path = 1;
  oneof resolution_result {
    MissingOpenApiSpecReference missing_open_api_spec_reference = 2;
    IncompleteOpenApiSpecReference incomplete_open_api_spec_reference = 3;
    CompleteOpenApiSpecReference complete_open_api_spec_reference = 4;
  }
}

message MissingOpenApiSpecReference {
}

message IncompleteOpenApiSpecReference {
  string spec_id = 1;
}

message CompleteOpenApiSpecReference {
  string spec_id = 1;
}

enum SpecType {
  SPEC_TYPE_UNSPECIFIED = 0;
  SPEC_TYPE_OPEN_API_SPEC = 1;
  SPEC_TYPE_POSTMAN_COLLECTION = 2;
  SPEC_TYPE_POSTMAN_ENVIRONMENT = 3;
  SPEC_TYPE_GRAPHQL_SCHEMA = 4;
}

enum ApiSpecStatus {
  API_SPEC_STATUS_UNSPECIFIED = 0;
  API_SPEC_STATUS_IN_PROGRESS = 1;
  API_SPEC_STATUS_COMPLETED = 2;
  API_SPEC_STATUS_INVALID_FORMAT = 3;
  API_SPEC_STATUS_SIZE_LIMIT_EXCEEDED = 4;
  API_SPEC_STATUS_FILE_LIMIT_EXCEEDED = 5;
  API_SPEC_STATUS_NO_FILES_FOUND = 6;
  API_SPEC_STATUS_INVALID_JOB_ID = 7;
  API_SPEC_STATUS_RESOLUTION_IN_PROGRESS = 8;
  API_SPEC_STATUS_RESOLUTION_COMPLETED = 9;
}
