syntax = "proto3";

package ai.traceable.waf.integration.service.api.v1;

option java_multiple_files = true;

import "ai/traceable/waf/integration/service/api/v1/aws_waf_provider.proto";

message WafIntegration {
  string id = 1;
  WafIntegrationDetails waf_integration_details = 2;
}

message WafIntegrationDetails {
  string name = 1;
  optional string description = 2;
  oneof integration_params {
    CloudflareIntegrationParams cloudflare_integration_params = 3;
    AwsIntegrationParams aws_integration_params = 4;
  }
}

message CloudflareIntegrationParams {
  string zone = 1;
  string email = 2;
  string api_token = 3;
}

message UpdatedWafIntegrationDetails {
  string name = 1;
  optional string description = 2;
  oneof integration_params {
    UpdatedCloudflareIntegrationParams updated_cloudflare_integration_params = 3;
    AwsIntegrationUpdateParams updated_aws_integration_params = 4;
  }
}

message UpdatedCloudflareIntegrationParams {
  string zone = 1;
  string email = 2;
  optional string api_token = 3;
}
