syntax = "proto3";

package ai.traceable.waf.integration.service.api.v1;

import "ai/traceable/waf/integration/service/api/v1/akamai_waf_provider.proto";
import "ai/traceable/waf/integration/service/api/v1/aws_waf_provider.proto";
import "ai/traceable/waf/integration/service/api/v1/azure_waf_provider.proto";
import "ai/traceable/waf/integration/service/api/v1/barracuda_waf_provider.proto";
import "ai/traceable/waf/integration/service/api/v1/f5_waf_provider.proto";
import "ai/traceable/waf/integration/service/api/v1/fortinet_waf_provider.proto";
import "ai/traceable/waf/integration/service/api/v1/gcp_waf_provider.proto";
import "ai/traceable/waf/integration/service/api/v1/imperva_waf_provider.proto";

option java_multiple_files = true;

message WafIntegration {
  string id = 1;
  WafIntegrationDetails waf_integration_details = 2;
}

message WafIntegrationDetails {
  string name = 1;
  optional string description = 2;
  oneof integration_params {
    CloudflareIntegrationParams cloudflare_integration_params = 3;
    AwsIntegrationParams aws_integration_params = 4;
    ImpervaIntegrationParams imperva_integration_params = 5;
    AzureIntegrationParams azure_integration_params = 6;
    GcpIntegrationParams gcp_integration_params = 8;
    F5IntegrationParams f5_integration_params = 9;
    AkamaiIntegrationParams akamai_integration_params = 10;
    FortinetIntegrationParams fortinet_integration_params = 11;
    BarracudaIntegrationParams barracuda_integration_params = 12;
  }
  WafIntegrationScope waf_integration_scope = 7;
  repeated WafIntegrationTarget integration_targets = 20; //leaving numbers for oneof
  optional bool enabled = 21;
}

message WafIntegrationTarget {
  oneof type {
    RuleType rule_target = 1;
  }
}

message CloudflareIntegrationParams {
  string zone = 1;
  string email = 2;
  string api_token = 3 [deprecated = true];
  EncryptedData encrypted_api_token = 4;
  string ruleset_id = 5;
  optional CustomListDetail custom_list_detail = 6;
}

message CustomListDetail {
  string block_list_name = 1;
  string allow_list_name = 2;
}

message UpdatedWafIntegrationDetails {
  string name = 1;
  optional string description = 2;
  oneof integration_params {
    UpdatedCloudflareIntegrationParams updated_cloudflare_integration_params = 3;
    AwsIntegrationUpdateParams updated_aws_integration_params = 4;
    ImpervaIntegrationUpdateParams updated_imperva_integration_params = 5;
    AzureIntegrationUpdateParams updated_azure_integration_params = 6;
    GcpIntegrationUpdateParams updated_gcp_integration_params = 8;
    F5IntegrationUpdateParams updated_f5_integration_params = 9;
    AkamaiIntegrationUpdateParams updated_akamai_integration_params = 10;
    FortinetIntegrationUpdateParams updated_fortinet_integration_params = 11;
    BarracudaIntegrationUpdateParams updated_barracuda_integration_params = 12;
  }
  WafIntegrationScope waf_integration_scope = 7;
  repeated WafIntegrationTarget integration_targets = 20;
  optional bool enabled = 21;
}

message UpdatedCloudflareIntegrationParams {
  string zone = 1;
  string email = 2;
  optional string api_token = 3 [deprecated = true];
  optional EncryptedData encrypted_api_token = 4;
  string ruleset_id = 5;
}

message WafIntegrationScope {
  oneof scope { // if no option selected, default is customer scope (all environments)
    EnvironmentScope environment_scope = 1;
  }
}

enum RuleType {
  RULE_TYPE_UNSPECIFIED = 0;
  RULE_TYPE_CUSTOM_SIGNATURE = 1;
  RULE_TYPE_THREAT_ACTORS = 2;
  RULE_TYPE_IP_RANGE = 3;
  RULE_TYPE_REGION = 4;
}

message EnvironmentScope {
  repeated string environment_ids = 1;
}

message EncryptedData {
  string base64_encrypted_data = 1;
  string key_id = 2;
}
