syntax = "proto3";
option java_multiple_files = true;
package ai.traceable.jira.integration.config.service.api.v1;


message JiraTemplate {
  string template_id = 1;
  string integration_id = 2;
  string project_id = 3;
  string issue_type = 4;
  TraceableEntityType entity_type = 5;
  JiraTemplateDetails jira_template_details = 6;
}

message JiraTemplateDetails {
  string name = 1;
  string adf_format_value = 2;
  string markdown_format_value = 3;
}

message JiraProjectIssueConfiguration {
  string configuration_id = 1;
  JiraProjectIssueConfigurationDetails jira_project_issue_configuration_details = 2;
}

message JiraProjectIssueConfigurationDetails {
  string integration_id = 1;
  string project_id = 2;
  string issue_type = 3;
  TraceableEntityType valid_traceable_entity_type = 4 [deprecated = true];
  JiraStatusMappingConfiguration jira_status_mapping_configuration = 5;
  repeated JiraTemplate jira_template = 6;
  repeated JiraFieldConfiguration field_configurations = 7;
  bool jira_bidirectional_sync_is_enabled = 8;
}

message JiraFieldConfiguration {
  string field_key = 1;
  optional string overridden_default_value_json_string = 2;
  optional DynamicField overridden_dynamic_value = 3;
  TraceableEntityType valid_traceable_entity_type = 4;
}

enum DynamicField {
  DYNAMIC_FIELD_UNSPECIFIED = 0;
  DYNAMIC_FIELD_LOGGED_IN_USER = 1;
}

message JiraStatusMappingConfiguration {
  repeated JiraStatusMapping status_mappings = 1;
}

message JiraStatusMapping {
  TraceableEntityStatus traceable_entity_status = 1;
  string jira_status = 2;
}

enum TraceableEntityStatus {
  TRACEABLE_ENTITY_STATUS_UNSPECIFIED = 0;
  TRACEABLE_ENTITY_STATUS_ISSUES_COMMON_OPEN = 1;
  TRACEABLE_ENTITY_STATUS_ISSUES_COMMON_REOPENED = 2;
  TRACEABLE_ENTITY_STATUS_ISSUES_COMMON_ACCEPTED_RISK = 3;
  TRACEABLE_ENTITY_STATUS_ISSUES_COMMON_NOT_AN_ISSUE = 4;
  TRACEABLE_ENTITY_STATUS_ISSUES_COMMON_UNDER_REVIEW = 5;
  TRACEABLE_ENTITY_STATUS_ISSUES_COMMON_FIXED = 6;

  TRACEABLE_ENTITY_STATUS_THREAT_ACTIVITY_OPEN = 9;
  TRACEABLE_ENTITY_STATUS_THREAT_ACTIVITY_FALSE_THREAT = 10;
  TRACEABLE_ENTITY_STATUS_THREAT_ACTIVITY_ACCEPTED_THREAT = 11;
  TRACEABLE_ENTITY_STATUS_THREAT_ACTIVITY_ACTIONABLE_THREAT = 12;
  TRACEABLE_ENTITY_STATUS_THREAT_ACTIVITY_UNDER_REVIEW = 13;

  TRACEABLE_ENTITY_STATUS_AST_VULNERABILITY_OPEN = 15;
  TRACEABLE_ENTITY_STATUS_AST_VULNERABILITY_REOPENED = 16;
  TRACEABLE_ENTITY_STATUS_AST_VULNERABILITY_ACCEPTED_RISK = 17;
  TRACEABLE_ENTITY_STATUS_AST_VULNERABILITY_NOT_AN_ISSUE = 18;
  TRACEABLE_ENTITY_STATUS_AST_VULNERABILITY_UNDER_REVIEW = 19;
  TRACEABLE_ENTITY_STATUS_AST_VULNERABILITY_FIXED = 20;

  TRACEABLE_ENTITY_STATUS_VULNERABILITY_OPEN = 23;
  TRACEABLE_ENTITY_STATUS_VULNERABILITY_REOPENED = 24;
  TRACEABLE_ENTITY_STATUS_VULNERABILITY_ACCEPTED_RISK = 25;
  TRACEABLE_ENTITY_STATUS_VULNERABILITY_NOT_AN_ISSUE = 26;
  TRACEABLE_ENTITY_STATUS_VULNERABILITY_UNDER_REVIEW = 27;
  TRACEABLE_ENTITY_STATUS_VULNERABILITY_FIXED = 28;
}

enum TraceableEntityType {
  TRACEABLE_ENTITY_TYPE_UNSPECIFIED = 0;
  TRACEABLE_ENTITY_TYPE_VULNERABILITY = 1;
  TRACEABLE_ENTITY_TYPE_AST_VULNERABILITY = 2;
  TRACEABLE_ENTITY_TYPE_THREAT_ACTIVITY = 3;
}
