syntax = "proto3";
option java_multiple_files = true;
package ai.traceable.servicenow.itsm.integration.config.service.api.v1;

import "google/protobuf/struct.proto";

// this message is intended for apis where we don't want to expose the credentials
message ServiceNowItsmIntegration {
  string id = 1;
  ServiceNowIntegrationDetails integration_details = 2;
}

// this message is intended for apis where we do want to return the credentials
message ServiceNowItsmIntegrationWithAuthCredentials {
  string id = 1;
  ServiceNowIntegrationDetails integration_details = 2;
  ServiceNowItsmAuthCredentials auth_credentials = 3;
}

message ServiceNowIntegrationDetails {
  string name = 1;
  string description = 2;
  string server_url = 3;
  ServiceNowItsmIntegrationScope scope = 4;
  repeated ServiceNowItsmIntegrationTablesConfiguration table_configurations = 5;
}

message ServiceNowItsmIntegrationTablesConfiguration {
  string table_name = 1;
  repeated ServiceNowItsmIntegrationFieldsConfiguration fields_configurations = 2;
  string table_configuration_id = 3;
}

message ServiceNowItsmIntegrationFieldsConfiguration {
  string column_name = 1;
  string display_name = 2;
  ServiceNowItsmIntegrationFieldType field_type = 3;
  optional string reference_table_name = 4; // only present when field type is SERVICE_NOW_REFERENCE and the values are expected to be fetched by a secondary query
  repeated google.protobuf.Value values = 5;
  optional google.protobuf.Value default_value = 6;
}

enum ServiceNowItsmIntegrationFieldType {
  SERVICE_NOW_ITSM_INTEGRATION_FIELD_TYPE_UNSPECIFIED = 0;
  SERVICE_NOW_ITSM_INTEGRATION_FIELD_TYPE_CALLER_REFERENCE = 1;
  SERVICE_NOW_ITSM_INTEGRATION_FIELD_TYPE_ASSIGNEE_REFERENCE = 2;
  SERVICE_NOW_ITSM_INTEGRATION_FIELD_TYPE_ASSIGNEE_GROUP_REFERENCE = 3;
  SERVICE_NOW_ITSM_INTEGRATION_FIELD_TYPE_SERVICE_NOW_REFERENCE = 4;
  SERVICE_NOW_ITSM_INTEGRATION_FIELD_TYPE_STRING = 5;
  SERVICE_NOW_ITSM_INTEGRATION_FIELD_TYPE_ENUMERATED_CHOICE = 6;
}

message ServiceNowItsmAuthCredentials {
  string client_id = 1;
  string user_name = 2;
  string encryption_key_id = 3;
  string encrypted_user_password = 4;
  string encrypted_client_secret = 5;
}

message ServiceNowItsmIntegrationFilter {
  // filtering with scope with environment-ids a,b,c,...
  // will fetch integrations containing at-least one matching environment
  ServiceNowItsmIntegrationScope scope = 1;
}

message ServiceNowItsmIntegrationScope {
  oneof scope {
    StringList environment_ids = 1;
  }
}

message StringList {
  repeated string values = 1;
}
