syntax = "proto3";
option java_multiple_files = true;
package ai.traceable.servicenow.itsm.integration.config.service.api.v1;

import "ai/traceable/servicenow/itsm/integration/config/service/api/v1/service_now_itsm_integration.proto";

service ServiceNowItsmIntegrationConfigService {
  rpc CreateServiceNowItsmIntegration(CreateServiceNowItsmIntegrationRequest) returns (CreateServiceNowItsmIntegrationResponse) {}
  rpc UpdateServiceNowItsmIntegration(UpdateServiceNowItsmIntegrationRequest) returns (UpdateServiceNowItsmIntegrationResponse) {}
  rpc DeleteServiceNowItsmIntegration(DeleteServiceNowItsmIntegrationRequest) returns (DeleteServiceNowItsmIntegrationResponse) {}

  // this get API will return integration details without the credentials - perfect for Graphql
  rpc GetServiceNowItsmIntegration(GetServiceNowItsmIntegrationRequest) returns (GetServiceNowItsmIntegrationResponse) {}

  // and this get API is intended to be used with services that require the credentials
  rpc GetServiceNowItsmIntegrationWithAuthCredentials(GetServiceNowItsmIntegrationWithAuthCredentialsRequest) returns (GetServiceNowItsmIntegrationWithAuthCredentialsResponse) {}
}

message CreateServiceNowItsmIntegrationRequest {
  string name = 1;
  optional string description = 2;
  ServiceNowItsmIntegrationScope scope = 3;
  string server_url = 4;
  ServiceNowItsmAuthCredentials auth_credentials = 5;
}

message CreateServiceNowItsmIntegrationResponse {
  ServiceNowItsmIntegration service_now_itsm_integration = 1;
}

message UpdateServiceNowItsmIntegrationRequest {
  string integration_id = 1;
  string name = 2;
  string description = 3;
  ServiceNowItsmIntegrationScope scope = 4;
  string server_url = 5;
  ServiceNowItsmAuthCredentials auth_credentials = 6;
}

message UpdateServiceNowItsmIntegrationResponse {
  ServiceNowItsmIntegration service_now_itsm_integration = 1;
}

message DeleteServiceNowItsmIntegrationRequest {
  string integration_id = 1;
}

message DeleteServiceNowItsmIntegrationResponse {}

message GetServiceNowItsmIntegrationRequest {
  ServiceNowItsmIntegrationFilter filter = 1;
}

message GetServiceNowItsmIntegrationResponse {
  repeated ServiceNowItsmIntegration service_now_itsm_integration = 1;
}

message GetServiceNowItsmIntegrationWithAuthCredentialsRequest {
  ServiceNowItsmIntegrationFilter filter = 1;
}

message GetServiceNowItsmIntegrationWithAuthCredentialsResponse {
  repeated ServiceNowItsmIntegrationWithAuthCredentials service_now_itsm_integration_with_auth_credentials = 1;
}
