syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.detector;
import "ai/traceable/anomaly/config/service/v1/anomaly_config.proto";
import "ai/traceable/anomaly/config/service/v1/modsec/anomaly_modsec_config.proto";
import "google/protobuf/duration.proto";

option java_multiple_files = true;

enum AnomalyDetectionConfigType {
  ANOMALY_DETECTION_CONFIG_TYPE_UNSPECIFIED = 0;
  ANOMALY_DETECTION_CONFIG_TYPE_MODSECURITY = 1;
  ANOMALY_DETECTION_CONFIG_TYPE_API_DEFINITION = 2;
  ANOMALY_DETECTION_CONFIG_TYPE_API_STATE_BASED = 3;
  ANOMALY_DETECTION_CONFIG_TYPE_SESSION_DEFINITION = 4;
  ANOMALY_DETECTION_CONFIG_TYPE_BLOCKING_METADATA = 5;
  ANOMALY_DETECTION_CONFIG_TYPE_CUSTOM_RULES = 6;
  ANOMALY_DETECTION_CONFIG_TYPE_VOLUMETRIC = 7;
  ANOMALY_DETECTION_CONFIG_TYPE_CREDENTIAL_STUFFING = 8;
}

message AnomalyCategoryConfig {
  AnomalyEventScoreCategory event_score_category = 1;
  AnomalyEventCategory event_category = 2;
}

enum AnomalyEventScoreCategory {
  ANOMALY_EVENT_SCORE_CATEGORY_UNSPECIFIED = 0;
  ANOMALY_EVENT_SCORE_CATEGORY_LOW = 1;
  ANOMALY_EVENT_SCORE_CATEGORY_MEDIUM = 2;
  ANOMALY_EVENT_SCORE_CATEGORY_HIGH = 3;
  ANOMALY_EVENT_SCORE_CATEGORY_CRITICAL = 4;
}

enum AnomalyEventCategory {
  ANOMALY_EVENT_CATEGORY_UNSPECIFIED = 0;
  ANOMALY_EVENT_CATEGORY_LATENT = 1;
  ANOMALY_EVENT_CATEGORY_MALICIOUS = 2;
}

enum DeleteAnomalyConfigOption {
  DELETE_ANOMALY_CONFIG_OPTION_UNSPECIFIED = 0;
  DELETE_ANOMALY_CONFIG_OPTION_WHOLE_DETECTION_CONFIG = 1;
}

message GetAnomalyDetectionConfigsFilter {
  repeated AnomalyDetectionConfigType anomaly_detection_config_types = 1;
}

message GetScopedAnomalyDetectionConfigRequest {
  AnomalyConfigScope config_scope = 1;
  GetAnomalyDetectionConfigsFilter filter = 2;
}

message GetScopedAnomalyDetectionConfigResponse {
  ScopedAnomalyDetectionConfig scoped_anomaly_detection_config = 1;
}

message GetGlobalResolvedScopedAnomalyDetectionConfigRequest {
  AnomalyConfigScope config_scope = 1;
  GetAnomalyDetectionConfigsFilter filter = 2;
}

message GetGlobalResolvedScopedAnomalyDetectionConfigResponse {
  ScopedAnomalyDetectionConfig scoped_anomaly_detection_config = 1;
}

message GetAllScopedAnomalyDetectionConfigsRequest {
  GetAnomalyDetectionConfigsFilter filter = 1;
}

message GetAllScopedAnomalyDetectionConfigsResponse {
  repeated ScopedAnomalyDetectionConfig scoped_anomaly_detection_configs = 1;
}

message GetUnresolvedScopedAnomalyDetectionConfigRequest {
  AnomalyConfigScope config_scope = 1;
  GetAnomalyDetectionConfigsFilter filter = 2;
}

message GetUnresolvedScopedAnomalyDetectionConfigResponse {
  ScopedAnomalyDetectionConfig scoped_anomaly_detection_config = 1;
}

message GetAllUnresolvedScopedAnomalyDetectionConfigsRequest {
  GetAnomalyDetectionConfigsFilter filter = 1;
}

message GetAllUnresolvedScopedAnomalyDetectionConfigsResponse {
  repeated ScopedAnomalyDetectionConfig scoped_anomaly_detection_configs = 1;
}

message GetAllGlobalResolvedScopedAnomalyDetectionConfigsRequest {
  GetAnomalyDetectionConfigsFilter filter = 1;
}

message GetAllGlobalResolvedScopedAnomalyDetectionConfigsResponse {
  repeated ScopedAnomalyDetectionConfig scoped_anomaly_detection_configs = 1;
}

message DeleteScopedAnomalyDetectionConfigRequest {
  DeleteAnomalyConfigOption delete_anomaly_config_option = 1;
  ScopedAnomalyDetectionConfig scoped_anomaly_detection_config = 2;
}

message DeleteScopedAnomalyDetectionConfigResponse {
  ScopedAnomalyDetectionConfig deleted_scoped_anomaly_detection_config = 1;
}

message UpdateScopedAnomalyDetectionConfigRequest {
  ScopedAnomalyDetectionConfig scoped_anomaly_detection_config = 1;
}

message UpdateScopedAnomalyDetectionConfigResponse {
  ScopedAnomalyDetectionConfig scoped_anomaly_detection_config = 1;
}

message ScopedAnomalyDetectionConfig {
  AnomalyConfigScope config_scope = 1;
  repeated AnomalyDetectionConfig anomaly_detection_configs = 2;
}

message AnomalyDetectionConfig {
  AnomalyConfigStatusChange config_status = 1;
  AnomalyCategoryConfig category_config = 2;
  oneof anomaly_detection_config {
    ModsecurityAnomalyDetectionConfig modsecurity_anomaly_detection_config = 5;
    ApiDefinitionMetadataAnomalyDetectionConfig api_definition_metadata_anomaly_detection_config = 6;
    ApiStateBasedAnomalyDetectionConfig api_state_based_anomaly_detection_config = 7;
    SessionDefinitionMetadataAnomalyDetectionConfig session_definition_metadata_anomaly_detection_config = 8;
    BlockingMetadataAnomalyDetectionConfig blocking_metadata_anomaly_detection_config = 9;
    CustomRulesAnomalyDetectionConfig custom_rules_anomaly_detection_config = 10;
    VolumetricAnomalyDetectionConfig volumetric_anomaly_detection_config = 11;
    CredentialStuffingAnomalyDetectionConfig credential_anomaly_detection_config = 12;
  }
}

message ModsecurityAnomalyDetectionConfig {
  oneof config {
    ModsecurityAllDetectionConfig modsec_all_detection = 1;
    ModsecurityAnomalyRuleConfig modsec_anomaly_rule = 2;
  }
}

message ApiDefinitionMetadataAnomalyDetectionConfig {
  string anomaly_rule_id = 1;
  oneof config {
    MissingParamAnomalyConfig missing_param = 2;
    EnumerationsAnomalyConfig enum = 3;
    IntegerAnomalyConfig integer = 4;
    TypeAnomalyConfig type = 5;
    DeviceAnomalyConfig device = 6;
    HttpStatusAnomalyConfig http_status = 7;
    ContentTypeAnomalyConfig content_type = 8;
    ContentSizeAnomalyConfig content_size = 9;
    PayloadAnomalyConfig payload = 10;
    SsrfAnomalyConfig ssrf = 11;
    UnknownParamAnomalyConfig unknown_param = 12;
    BflaAnomalyConfig bfla = 13;
    JwtAnomalyConfig jwt = 14;
    SpecialCharacterAnomalyConfig special_character = 16;
    ContentExplosionAnomalyConfig content_explosion = 17;
  }
  AnomalySubRuleConfigMap sub_rule_configs = 15;
}

message ApiStateBasedAnomalyDetectionConfig {
  oneof config {
    UnknownApiAnomalyConfig unknown_api = 1;
    UnderDiscoveryApiAnomalyConfig under_discovery_api = 2;
    UnderThresholdLearningApiAnomalyConfig under_threshold_learning_api = 3;
    LearntApiAnomalyConfig learnt_api = 4;
  }
}

message SessionDefinitionMetadataAnomalyDetectionConfig {
  string anomaly_rule_id = 1;
  oneof config {
    ObjectBolaAnomalyConfig object_bola = 2;
    UserIdBolaAnomalyConfig user_id_bola = 3;
    SequenceAnomalyConfig sequence_anomaly = 4;
    SessionViolationConfig session_violation = 5;
  }
  AnomalySubRuleConfigMap sub_rule_configs = 6;
}

message BlockingMetadataAnomalyDetectionConfig {
  oneof config {
    CustomIpAnomalyConfig custom_ip = 1;
    CustomRegionAnomalyConfig custom_region = 2;
    CustomSignatureAnomalyConfig custom_signature = 3;
    RateLimitAnomalyConfig rate_limit = 4;
    ThreatActorAnomalyConfig threat_actor = 5;
    SafeCrsAnomalyConfig safe_crs = 6;
    InAgentVulnerableLibraryConfig in_agent_vulnerable_library = 7;
    MaliciousSourcesAnomalyConfig malicious_sources = 8;
  }
}

message CustomRulesAnomalyDetectionConfig {
  oneof config {
    MaliciousSourcesRulesAnomalyConfig malicious_sources = 1;
  }

  message MaliciousSourcesRulesAnomalyConfig {
    EmailDomainAnomalyConfig email_domain = 1;
    IpTypeAnomalyConfig ip_type = 2;
  }

  message EmailDomainAnomalyConfig {
    int32 high_email_fraud_score_min_threshold = 1;
    int32 critical_email_fraud_score_min_threshold = 2;
    optional bool disabled = 3;
  }

  message IpTypeAnomalyConfig {
    AbuseVelocity abuse_velocity_min_threshold = 1;
    int32 ip_reputation_score_min_threshold = 2;
  }
}

message VolumetricAnomalyDetectionConfig {
  oneof config {
    ApiCallSpikeAnomalyConfig api_call_spike = 1;
  }
  string anomaly_rule_id = 2;
}

message ApiCallSpikeAnomalyConfig {
  ApiCallSpikeTuningConfigList api_call_spike_tuning_config_list = 1;
}

message ApiCallSpikeTuningConfigList {
  repeated ApiCallSpikeTuningConfig api_call_spike_tuning_configs = 1;
}

message ApiCallSpikeTuningConfig {
  // the below detection config would be applied on the endpoints identified by this config
  DetectionScopeConfig detection_scope_config = 1;
  // detection specific threshold (int); it specifies the minimum span count
  // for the API to be present during the detection run for the API data to be
  // qualified to be run through the detector
  int64 endpoint_span_count_detection_threshold = 5;
}

message DetectionScopeConfig {
  // there is an implicit OR between the below fields
  // the priority(in case of conflicting scopes) is: endpoint_ids > url_regexes > endpoint_labels
  StringList endpoint_ids = 1;
  StringList url_regexes = 2;
  StringList endpoint_labels = 3;
}

message CredentialStuffingAnomalyDetectionConfig {
  string anomaly_rule_id = 1;
  oneof config {
    CredentialStuffingAnomalyConfig credential_stuffing = 2;
  }
}

message CredentialStuffingAnomalyConfig {
  CredentialStuffingTuningConfigList credential_stuffing_tuning_config_list = 1;
}

message CredentialStuffingTuningConfigList {
  repeated CredentialStuffingTuningConfig credential_stuffing_tuning_configs = 1;
}

message ParameterExtractionConfig {
  oneof parameter_extraction_config {
    // extract the parameter labelled with one of the specified data_type (priority will be given to the data_type_id appearing first in the list), as per the data classification rules
    StringList data_type_ids = 2;
    // example: "get_json_object(request_body, '$.email')".
    // This doesn't have any checks - whether the syntax is correct, the function is supported, etc.
    string extraction_logic = 3;
  }
}

message CredentialStuffingTuningConfig {
  // the below detection config would be applied on the endpoints identified by this config
  DetectionScopeConfig detection_scope_config = 1;
  ParameterExtractionConfig username_extraction_config = 2;
  google.protobuf.Duration look_back_duration = 3;
  int64 unique_users_threshold = 4;
  int64 failed_login_percentage_threshold = 5;
}

message ModsecurityAllDetectionConfig {
  StringList excluded_params = 1;
  optional bool enabled_on_all_entry_spans = 2;
  repeated ParamValueTypeModsecExclude param_value_type_modsec_excludes = 3;
  ai.traceable.anomaly.config.service.v1.modsec.ModsecRuleVersion modsec_rule_version = 4;
}

message ModsecurityAnomalyRuleConfig {
  string anomaly_rule_id = 1;
  repeated AnomalySubRuleConfig sub_rule_configs = 2;
}

message MissingParamAnomalyConfig {
  optional double min_percent_seen = 1;
  StringList severe_names = 2 [deprecated = true];
  optional bool evaluate_request_body_params = 3;
  optional bool enabled_for_internal_ips = 4;
  StringList thresholds_families_excluded = 5;
  StringList severe_regex_strings = 6;
  StringList auth_regex_strings = 7;
}

message UnknownParamAnomalyConfig {
  StringList severe_names = 1 [deprecated = true];
  optional bool modsecurity_enabled = 2;
  optional bool enabled_for_internal_ips = 3;
  StringList thresholds_families_excluded = 4;
  StringList severe_regex_strings = 5;
}

message EnumerationsAnomalyConfig {
  StringList no_anomaly_strings = 1;
  optional bool modsecurity_enabled = 2;
  optional bool enabled_for_internal_ips = 3;
  StringList thresholds_families_excluded = 4;
}

message IntegerAnomalyConfig {
  optional int32 max_length_difference = 1;
  optional double threshold_percent = 2;
}

message TypeAnomalyConfig {
  optional double min_percent_seen = 1;
  StringList no_anomaly_strings = 2;
  optional bool modsecurity_enabled = 3;
  optional bool enabled_for_internal_ips = 4;
}

message DeviceAnomalyConfig {
  optional double min_percent_seen = 1;
}

message HttpStatusAnomalyConfig {
  optional double min_percent_seen = 1;
  StringList valid_http_status_codes = 2;
  StringList valid_grpc_status_codes = 3;
}

message ContentTypeAnomalyConfig {
  optional double min_percent_seen = 1;
  optional bool modsecurity_enabled = 2;
  optional bool enabled_for_internal_ips = 3;
}

message ContentSizeAnomalyConfig {
  optional double min_percent_seen = 1;
  optional double max_difference_ratio = 2;
  optional int32 request_range_size = 3;
  optional int32 response_range_size = 4;
  optional bool enabled_for_internal_ips = 5;
}

message PayloadAnomalyConfig {
  optional bool modsecurity_enabled = 1;
}

message SsrfAnomalyConfig {
  StringList allowed_protocols = 1;
  optional int32 required_occurrences_of_host = 2;
  StringList allowed_domains = 3;
}

message BflaAnomalyConfig {
  optional double min_percent_seen = 1;
  optional bool disabled_for_unknown_roles = 2;
}

message JwtAnomalyConfig {
  optional double time_difference_buffer_millis = 1;
  optional double min_percent_seen = 2;
}

message SpecialCharacterAnomalyConfig {
  optional double min_percent_seen = 1;
  optional double min_total_traffic_seen = 2;
  repeated string exclude_special_characters = 3;
}

message ContentExplosionAnomalyConfig {
  optional double min_percent_seen = 1;
  optional double max_depth_difference_allowed = 2;
}

message LearntApiAnomalyConfig {
  optional bool modsecurity_enabled = 1;
  optional bool evaluate_all_modsecurity_rules = 2;
}

message UnderDiscoveryApiAnomalyConfig {
  optional bool modsecurity_enabled = 1;
  StringList reject_url_regex_strings = 2;
  optional bool evaluate_all_modsecurity_rules = 3;
}

message UnderThresholdLearningApiAnomalyConfig {
  optional bool modsecurity_enabled = 1;
  StringList reject_url_regex_strings = 2;
  optional bool evaluate_all_modsecurity_rules = 3;
}

message UnknownApiAnomalyConfig {
  optional bool modsecurity_enabled = 1;
  optional bool evaluate_all_modsecurity_rules = 2;
}

message ObjectBolaAnomalyConfig {
  optional double min_correlation_probability = 1;
  optional double pairwise_correlation_probability = 2;
  optional double any_source_correlation_probability = 3;
  optional bool disabled_for_missing_preceding_param = 4;
  optional bool enabled_on_same_api = 5;
  optional int64 preceding_event_look_ahead_time_window = 6;
  StringList request_param_values_not_allowed = 7;
  MultiValuedStringParamRulesList multi_valued_string_param_rules = 8;
}

message UserIdBolaAnomalyConfig {
  optional double min_correlation_probability = 1;
  UserIdSource user_id_source = 2;
}

message SequenceAnomalyConfig {
  oneof config {
    PredecessorSuccessorApiSequenceConfig predecessor_successor_api_sequence_config = 1;
  }
}

message PredecessorSuccessorApiSequenceConfig {
  repeated PredecessorSuccessorApiConfig predecessor_successor_api_config = 1;
}

message PredecessorSuccessorApiConfig {
  string successor_api_id = 1;
  StringList predecessor_api_ids = 2;
}

message CustomIpAnomalyConfig {}

message CustomRegionAnomalyConfig {}

message CustomSignatureAnomalyConfig {}

message RateLimitAnomalyConfig {}

message ThreatActorAnomalyConfig {}

message SafeCrsAnomalyConfig {}

message InAgentVulnerableLibraryConfig {}

message MaliciousSourcesAnomalyConfig {}

message AnomalySubRuleConfig {
  string sub_rule_id = 1;
  AnomalyConfigStatusChange config_status = 2;
  AnomalyCategoryConfig category_config = 3;
  optional bool blocking_enabled = 4;
}

message ParamValueTypeModsecExclude {
  ParamValueType param_value_type = 1;
  StringList excluded_modsec_rule_ids = 2;
}

enum IpType {
  IP_TYPE_UNSPECIFIED = 0;
  IP_TYPE_VPN = 1;
  IP_TYPE_PUBLIC_PROXY = 2;
  IP_TYPE_HOSTING_PROVIDER = 3;
  IP_TYPE_TOR = 4;
  IP_TYPE_BOT = 5;
}

enum AbuseVelocity {
  ABUSE_VELOCITY_UNSPECIFIED = 0;
  ABUSE_VELOCITY_LOW = 1;
  ABUSE_VELOCITY_MEDIUM = 2;
  ABUSE_VELOCITY_HIGH = 3;
}

enum ParamValueType {
  PARAM_VALUE_TYPE_UNSPECIFIED = 0;
  PARAM_VALUE_TYPE_HTML = 1;
  PARAM_VALUE_TYPE_RICH_TEXT_HTML = 2;
  PARAM_VALUE_TYPE_FREE_TEXT = 3;
}

enum UserIdSource {
  USER_ID_SOURCE_UNSPECIFIED = 0;
  USER_ID_SOURCE_ANY = 1;
  USER_ID_SOURCE_JWT = 2;
}

message MultiValuedStringParamRulesList {
  repeated MultiValuedStringParamRule rules = 1;
}

message MultiValuedStringParamRule {
  string key_regex = 1;
  string value_delimiter = 2;
  optional string value_regex = 3;
}

message SessionViolationConfig {
  LandSpeedViolationConfig land_speed = 1;
  SessionExpiryConfig session_expiry = 2;
  optional bool disallow_unauthenticated_sessions = 3;
}

message LandSpeedViolationConfig {
  IpTypeList ip_types = 1;
  AbuseVelocity min_ip_abuse_velocity = 2;
  optional int32 min_ip_reputation_score = 3;
  optional int32 unique_user_cities_min_count = 4;
  optional int32 unique_external_ip_addresses_min_count = 5;
}

message SessionExpiryConfig {
  optional int64 time_difference_buffer_millis = 1;
}

message IpTypeList {
  repeated IpType values = 1;
}

message AnomalySubRuleConfigMap {
  map<string, AnomalySubRuleConfig> sub_rule_configs = 1;
}
