syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package ai.traceable.anomaly.config.service.v1.detector;

import "ai/traceable/anomaly/config/service/v1/detector/anomaly_detection_config.proto";

option java_multiple_files = true;

service DetectorConfigService {
  rpc GetScopedAnomalyDetectionConfig(GetScopedAnomalyDetectionConfigRequest) returns (GetScopedAnomalyDetectionConfigResponse) {
    option deprecated = true;
  }

  rpc GetAllScopedAnomalyDetectionConfigs(GetAllScopedAnomalyDetectionConfigsRequest) returns (GetAllScopedAnomalyDetectionConfigsResponse) {
    option deprecated = true;
  }

  rpc GetUnresolvedScopedAnomalyDetectionConfig(GetUnresolvedScopedAnomalyDetectionConfigRequest) returns (GetUnresolvedScopedAnomalyDetectionConfigResponse) {}

  rpc GetAllUnresolvedScopedAnomalyDetectionConfigs(GetAllUnresolvedScopedAnomalyDetectionConfigsRequest) returns (GetAllUnresolvedScopedAnomalyDetectionConfigsResponse) {}

  rpc GetAllGlobalResolvedScopedAnomalyDetectionConfigs(GetAllGlobalResolvedScopedAnomalyDetectionConfigsRequest) returns (GetAllGlobalResolvedScopedAnomalyDetectionConfigsResponse) {}

  rpc GetGlobalResolvedScopedAnomalyDetectionConfig(GetGlobalResolvedScopedAnomalyDetectionConfigRequest) returns (GetGlobalResolvedScopedAnomalyDetectionConfigResponse) {}

  rpc DeleteScopedAnomalyDetectionConfig(DeleteScopedAnomalyDetectionConfigRequest) returns (DeleteScopedAnomalyDetectionConfigResponse) {}

  rpc UpdateScopedAnomalyDetectionConfig(UpdateScopedAnomalyDetectionConfigRequest) returns (UpdateScopedAnomalyDetectionConfigResponse) {}
}
