name: build and validate
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-protos:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Check out main branch code
        uses: actions/checkout@v2
        with:
          ref: main
          path: build/cloned-main
          fetch-depth: 0
          submodules: recursive
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: Setup buf
        uses: Wizhi/setup-buf@f76a0133338dc012333f5a7f883381d466381074
        with:
          version: 0.49.0
      - name: Download protoc go plugins
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1 && go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26.0
      - name: Generate go files for user attribution
        run: buf generate --path external-user-attribution-config-service-api/src/main/proto/ai/traceable/external
      - name: Generate go files for data classification
        run: buf generate --path external-data-classification-config-service-api/src/main/proto/ai/traceable/external
      - name: Verify generated go matches checked in
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"
      - name: verify-protos
        run: |
          buf lint
          buf breaking --against "$GITHUB_WORKSPACE/build/cloned-main"

  validate-helm-charts:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Validate chart
        uses: hypertrace/github-actions/validate-charts@main
        with:
          extra-args: --set global.env=dev
  build:
    runs-on: ubuntu-20.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout Traceable actions
        uses: actions/checkout@v2
        with:
          repository: traceableai/github-actions
          ssh-key: ${{ secrets.GH_ACTION_READ_KEY }}
          path: .github/actions

      - name: Ensure submodules point to commit from main branch
        run: git submodule foreach --recursive "git merge-base --is-ancestor HEAD origin/main"

      - name: Create checksum file
        uses: hypertrace/github-actions/checksum@main

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            !~/.gradle/gradle.properties
          key: gradle-packages-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/checksum.txt') }}
          restore-keys: |
            gradle-packages-${{ runner.os }}-${{ github.job }}
            gradle-packages-${{ runner.os }}

      - name: Setup gradle auth
        uses: ./.github/actions/gradle-setup
        with:
          context-url: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          user: ${{ secrets.ARTIFACTORY_READ_USER }}
          password: ${{ secrets.ARTIFACTORY_READ_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}

      - name: Build with Gradle
        uses: hypertrace/github-actions/gradle@main
        with:
          args: assemble dockerBuildImages
  test:
    runs-on: ubuntu-20.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout Traceable actions
        uses: actions/checkout@v2
        with:
          repository: traceableai/github-actions
          ssh-key: ${{ secrets.GH_ACTION_READ_KEY }}
          path: .github/actions

      - name: Create checksum file
        uses: hypertrace/github-actions/checksum@main

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            !~/.gradle/gradle.properties
          key: gradle-packages-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/checksum.txt') }}
          restore-keys: |
            gradle-packages-${{ runner.os }}-${{ github.job }}
            gradle-packages-${{ runner.os }}

      - name: Setup gradle auth
        uses: ./.github/actions/gradle-setup
        with:
          context-url: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          user: ${{ secrets.ARTIFACTORY_READ_USER }}
          password: ${{ secrets.ARTIFACTORY_READ_TOKEN }}

      - name: Unit test and other verification
        uses: hypertrace/github-actions/gradle@main
        with:
          args: check jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: copy test reports
        uses: hypertrace/github-actions/gradle@main
        if: always()
        with:
          args: copyAllReports --output-dir=/tmp/test-reports

      - name: Archive test reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test-reports
          path: /tmp/test-reports

      - name: Publish Unit Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.19
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./**/build/test-results/**/*.xml
  integration-test:
    runs-on: ubuntu-20.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout Traceable actions
        uses: actions/checkout@v2
        with:
          repository: traceableai/github-actions
          ssh-key: ${{ secrets.GH_ACTION_READ_KEY }}
          path: .github/actions

      - name: Create checksum file
        uses: hypertrace/github-actions/checksum@main

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            !~/.gradle/gradle.properties
          key: gradle-packages-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/checksum.txt') }}
          restore-keys: |
            gradle-packages-${{ runner.os }}-${{ github.job }}
            gradle-packages-${{ runner.os }}
      - name: Setup gradle auth
        uses: ./.github/actions/gradle-setup
        with:
          context-url: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          user: ${{ secrets.ARTIFACTORY_READ_USER }}
          password: ${{ secrets.ARTIFACTORY_READ_TOKEN }}

      - name: Integration test
        uses: hypertrace/github-actions/gradle@main
        with:
          args: jacocoIntegrationTestReport

      - name: Upload Integration Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration

      - name: Copy test reports
        uses: hypertrace/github-actions/gradle@main
        with:
          args: copyAllReports --output-dir=/tmp/test-reports
        if: always()

      - name: Archive Integration Test Reports
        uses: actions/upload-artifact@v1
        with:
          name: integration-test-reports
          path: /tmp/test-reports
        if: always()

      - name: Publish Integration Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./**/build/test-results/**/*.xml
          check_name: Integration Test Results
        if: always()