name: Static Analysis
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: self-hosted-x64-small
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Checkout Traceable actions
        uses: actions/checkout@v4
        with:
          repository: traceableai/github-actions
          ssh-key: ${{ secrets.GH_ACTION_READ_KEY }}
          path: .github/actions

      - name: Setup gradle auth
        uses: traceableai/github-actions/gradle-setup@main

      - name: Build and test
        uses: hypertrace/github-actions/gradle@main
        with:
          args: classes jacocoTestReport

      - name: Sonarqube Analysis
        uses: traceableai/github-actions/sonarqube-analysis@main
        with:
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-login: ${{ secrets.SONAR_LOGIN }}

      - name: Secret Scanning
        uses: traceableai/github-actions/secret-scanning@main
