name: Static Analysis
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: self-hosted-x64-small
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Checkout Traceable actions
        uses: actions/checkout@v2
        with:
          repository: traceableai/github-actions
          ssh-key: ${{ secrets.GH_ACTION_READ_KEY }}
          path: .github/actions

      - name: Setup gradle auth
        uses: ./.github/actions/gradle-setup
        with:
          context-url: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          user: ${{ secrets.ARTIFACTORY_READ_USER }}
          password: ${{ secrets.ARTIFACTORY_READ_TOKEN }}

      - name: Compile source
        uses: hypertrace/github-actions/gradle@main
        with:
          args: classes testClasses

      - name: Sonarqube Analysis
        uses: ./.github/actions/sonarqube-analysis
        with:
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-login: ${{ secrets.SONAR_LOGIN }}

      - name: Secret Scanning
        uses: ./.github/actions/secret-scanning
        with:
          auth-token: ${{ secrets.DEFECTDOJO_AUTH_TOKEN }}