syntax = "proto3";

package ai.traceable.dashboard.config.service.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option java_multiple_files = true;

service DashboardConfigService {
  rpc GetDashboards(GetDashboardsRequest) returns (GetDashboardsResponse) {}

  rpc CreateDashboard(CreateDashboardRequest) returns (CreateDashboardResponse) {}

  rpc UpdateDashboard(UpdateDashboardRequest) returns (UpdateDashboardResponse) {}

  rpc DeleteDashboard(DeleteDashboardRequest) returns (DeleteDashboardResponse) {}

  rpc UpdateDashboardRoleAssignments(UpdateDashboardRoleAssignmentsRequest) returns (UpdateDashboardRoleAssignmentsResponse) {}
}

message GetDashboardsRequest {
  DashboardFilter filter = 1;

  message DashboardFilter {
    optional string ui_reference = 1;
    optional string dashboard_id = 2;
  }
}

message GetDashboardsResponse {
  repeated Dashboard dashboards = 1;
}

message CreateDashboardRequest {
  string name = 1;
  optional string description = 2;
  string json = 3;
  optional string ui_reference = 4;
}

message CreateDashboardResponse {
  Dashboard dashboard = 1;
}

message UpdateDashboardRequest {
  string id = 1;
  string name = 2;
  optional string description = 3;
  string json = 4;
  google.protobuf.Timestamp previous_update_timestamp = 7;
}

message UpdateDashboardResponse {
  Dashboard dashboard = 1;
}

message DeleteDashboardRequest {
  string id = 1;
}

message DeleteDashboardResponse {}

message Dashboard {
  string id = 1;
  string name = 2;
  optional string description = 3;
  string author = 4;
  string json = 5;
  google.protobuf.Timestamp creation_timestamp = 6;
  google.protobuf.Timestamp last_updated_timestamp = 7;
  optional string ui_reference = 8;
  DashboardRoleAssignments role_assignments = 9;
}

message DashboardRoleAssignments {
  repeated DashboardPrincipal viewers = 1;
  repeated DashboardPrincipal editors = 2;
  repeated DashboardPrincipal owners = 3;
}

message DashboardPrincipal {
  oneof principal {
    google.protobuf.Empty all_authenticated_users = 1;
    string user_email = 2;
  }
}

message UpdateDashboardRoleAssignmentsRequest {
  string id = 1;
  google.protobuf.Timestamp previous_update_timestamp = 2;
  DashboardRoleAssignments role_assignments = 3;
}

message UpdateDashboardRoleAssignmentsResponse {
  Dashboard dashboard = 1;
}
