syntax = "proto3";

package ai.traceable.bot.categorized.policy.service.v1;

option java_multiple_files = true;

message CategorizedBotConfigPolicy {
  string id = 1;
  CategorizedBotConfigPolicyDetails categorized_bot_policy_details = 2;
}

message CategorizedBotConfigPolicyDetails {
  string name = 1;
  optional string description = 2;
  bool enabled = 3;
  CategorizedBotPolicyScope categorized_bot_policy_scope = 4;
  repeated BotScope bot_scopes = 5;
  CategorizedBotPolicyActionConfig categorized_bot_policy_action_config = 6;
  optional CategorizedBotPolicyTargetScope categorized_bot_policy_target_scope = 7;
}

message CategorizedBotPolicyScope {
  oneof scope {
    // if no option selected, default is customer scope (all environments)
    // Do we need more scopes here? Service scope or Domain scope?
    EnvironmentScope environment_scope = 1;
  }
}

message CategorizedBotPolicyTargetScope {
  oneof scope {
    EntityScope entity_scope = 2;
  }
}

/**
   If a Bot Category and a bot ID in the same category are provided,
   or if a sub-category in the same category are provided,
   the results will merge into a single EDS rule per bot.

   The order of bot IDs or classifications does not matter.
   The hierarchy of bot scope coverage is Category > Sub Category > Bot ID.

   Do not provide additional entries for sub-categories or bot IDs
   if the top-level category is provided.

   Do not provide additional entries for bot IDs
   if the top-level classification (category and subcategory) is provided.

   Provide bot IDs only if a subset of bots is needed for a given classification.
*/
message BotScope {
  oneof bot_scope {
    BotList bot_list = 1;
    BotClassification bot_classification = 2;
  }

  message BotClassification {
    string category = 1;
    repeated string sub_category = 2;
  }

  message BotList {
    repeated string bot_ids = 1;
  }
}

message EnvironmentScope {
  repeated string environment_ids = 1;
}

message EntityScope {
  EntityType entity_type = 1;
  repeated string entity_ids = 2;
}

enum EntityType {
  ENTITY_TYPE_UNSPECIFIED = 0;
  ENTITY_TYPE_API = 1;
  ENTITY_TYPE_SERVICE = 2;
}

message CategorizedBotPolicyActionConfig {
  CategorizedBotAction bot_action = 1;
}

enum CategorizedBotAction {
  CATEGORIZED_BOT_ACTION_UNSPECIFIED = 0;
  CATEGORIZED_BOT_ACTION_BLOCK = 1;
  CATEGORIZED_BOT_ACTION_MONITOR = 2;
  CATEGORIZED_BOT_ACTION_ALLOW = 3;
}
