syntax = "proto3";

package ai.traceable.bot.categorized.policy.service.v1;

import "ai/traceable/bot/categorized/policy/service/v1/categorized_bot_config_policy.proto";
import "ai/traceable/edge/decision/config/service/v1/edge_decision_config.proto";

option java_multiple_files = true;

service CategorizedBotConfigPolicyService {
  rpc CreateCategorizedBotConfigPolicy(CreateCategorizedBotConfigPolicyRequest) returns (CreateCategorizedBotConfigPolicyResponse) {}
  rpc UpdateCategorizedBotConfigPolicy(UpdateCategorizedBotConfigPolicyRequest) returns (UpdateCategorizedBotConfigPolicyResponse) {}
  rpc GetCategorizedBotConfigPolicies(GetCategorizedBotConfigPoliciesRequest) returns (GetCategorizedBotConfigPoliciesResponse) {}
  rpc DeleteCategorizedBotConfigPolicy(DeleteCategorizedBotConfigPolicyRequest) returns (DeleteCategorizedBotConfigPolicyResponse) {}
  rpc GetCategorizedBotConfigPolicyEdgeDecisionRules(GetCategorizedBotConfigPolicyEdgeDecisionRulesRequest) returns (GetCategorizedBotConfigPolicyEdgeDecisionRulesResponse) {}
}

message CreateCategorizedBotConfigPolicyRequest {
  CategorizedBotConfigPolicyDetails categorized_bot_config_policy_details = 1;
}
message CreateCategorizedBotConfigPolicyResponse {
  CategorizedBotConfigPolicy categorized_bot_config_policy = 1;
}

message UpdateCategorizedBotConfigPolicyRequest {
  CategorizedBotConfigPolicy categorized_bot_config_policy = 1;
}
message UpdateCategorizedBotConfigPolicyResponse {
  CategorizedBotConfigPolicy categorized_bot_config_policy = 1;
}

message GetCategorizedBotConfigPoliciesRequest {
  optional CategorizedBotConfigPolicyFilter categorized_bot_config_policy_filter = 1;
}
message GetCategorizedBotConfigPoliciesResponse {
  repeated CategorizedBotConfigPolicy categorized_bot_config_policies = 1;
}

message DeleteCategorizedBotConfigPolicyRequest {
  string categorized_bot_config_policy_id = 1;
}
message DeleteCategorizedBotConfigPolicyResponse {
  CategorizedBotConfigPolicy categorized_bot_config_policy = 1;
}

message CategorizedBotConfigPolicyFilter {
  repeated string categorized_bot_config_policy_ids = 1;
  repeated string environment_ids = 2;
  repeated CategorizedBotAction allowed_actions = 3;
}

message GetCategorizedBotConfigPolicyEdgeDecisionRulesResponse {
  ai.traceable.edge.decision.config.service.v1.EdgeDecisionEngineConfig edge_decision_engine_config = 1;
}

message GetCategorizedBotConfigPolicyEdgeDecisionRulesRequest {
  CategorizedBotConfigPolicyEdgeDecisionRulesFilter categorized_bot_config_policy_edge_decision_rules_filter = 1;
}

message CategorizedBotConfigPolicyEdgeDecisionRulesFilter {
  repeated string categorized_bot_config_policy_ids = 1;
  repeated CategorizedBotAction allowed_actions = 2;
}
