syntax = "proto3";

package ai.traceable.fraud.policy.config.service.v1;

import "ai/traceable/fraud/datamodel/config/service/v1/fraud_datamodel.proto";
import "ai/traceable/fraud/policy/config/service/v1/incident_config.proto";
import "ai/traceable/fraud/policy/config/service/v1/threat_summary_config.proto";
import "ai/traceable/fraud/policy/config/service/v1/time_object.proto";
import "ai/traceable/fraud/policy/config/service/v1/triage_config.proto";
import "ai/traceable/fraud/query/model/v1/fraud_data_query.proto";
import "google/protobuf/struct.proto";

option java_multiple_files = true;

enum FraudPolicyCategory {
  FRAUD_POLICY_CATEGORY_UNSPECIFIED = 0;
  FRAUD_POLICY_CATEGORY_RISK = 1;
  FRAUD_POLICY_CATEGORY_FRAUD = 2;
  FRAUD_POLICY_CATEGORY_BOT = 3;
}

// certain policy types are templatized and dedicated ux is provided, everything else goes into custom.
enum PolicyType {
  POLICY_TYPE_UNSPECIFIED = 0;
  POLICY_TYPE_VOLUMETRIC = 1;
  POLICY_TYPE_API_ACCESS = 2;
  POLICY_TYPE_ACCOUNT_TAKEOVER = 3;
  POLICY_TYPE_CUSTOM = 4;
  POLICY_TYPE_INTERNAL = 5;
}

enum PolicyGroup {
  POLICY_GROUP_UNSPECIFIED = 0;
  POLICY_GROUP_BOT = 1;
  POLICY_GROUP_WAF = 2;
  POLICY_GROUP_MODSEC = 3;
  POLICY_GROUP_CUSTOM = 4;
  POLICY_GROUP_FRAUD = 5;
}

enum FraudRuleLogicalOperator {
  FRAUD_RULE_LOGICAL_OPERATOR_UNSPECIFIED = 0;
  FRAUD_RULE_LOGICAL_OPERATOR_AND = 1;
  FRAUD_RULE_LOGICAL_OPERATOR_OR = 2;
}

message LogicalFraudRule {
  FraudRuleLogicalOperator operator = 1;
  repeated FraudPolicyRule rules = 2;
}

message FraudPolicyRule {
  oneof rule {
    FraudRule fraud_rule = 1;
    LogicalFraudRule logical_fraud_rule = 2;
  }
}

message FraudPolicyList {
  repeated FraudPolicy policies = 1;
}

message TimeWindow {
  oneof time_window {
    TimeObj relative_time = 1;
    ai.traceable.fraud.query.model.v1.TimeFrame time_frame = 2;
  }
}

enum FraudPolicyStage {
  FRAUD_POLICY_STAGE_UNSPECIFIED = 0;

  // policy is actively being used and output must be shown to external customers as well.
  FRAUD_POLICY_STAGE_PRODUCTION = 1;

  // policy is being tested, and produces reasonable output. Output can be seen by external customers ONLY by turning
  // on debug flag.
  FRAUD_POLICY_STAGE_STAGING = 2;

  // policy is being tested, and MUST not be shown to external customers at all.
  FRAUD_POLICY_STAGE_INTERNAL = 3;

  // a policy created as a simulation of another policy.
  FRAUD_POLICY_STAGE_SIMULATION = 4;
}

enum FraudRiskSeverity {
  FRAUD_RISK_SEVERITY_UNSPECIFIED = 0;
  FRAUD_RISK_SEVERITY_LOW = 1;
  FRAUD_RISK_SEVERITY_MEDIUM = 2;
  FRAUD_RISK_SEVERITY_HIGH = 3;
}

message FraudRiskSpec {
  // risk score (a number between 1-10)
  // Low (1-3); Med (4-7); High (7-10)
  int32 score = 1;
  FraudRiskSeverity severity = 2;
}

message FraudPolicyScope {
  oneof scope {
    EnvironmentScope environment_scope = 1;
    TenantScope tenant_scope = 2;
  }
}

message EnvironmentScope {
  repeated string environment_ids = 1;
}

message TenantScope {}

message Schedule {
  oneof type {
    string cron_expression = 1; // e.g. "0 0/10 * * * ?" (every 10 minutes)
    TimeObj interval = 2; // Interval between executions, if applicable
  }
  // applicable for simulations
  optional int64 start_time = 3; // if we need to eval past windows - 15th Dec
  optional int64 end_time = 4; // if we need to stop eval beyond certain time 18th Dec
}

// policy is a set of rules
message FraudPolicy {
  string id = 1;
  string name = 2;

  FraudPolicyRule fraud_policy_rule = 3;

  // categorize the output of the policy to risk or fraud
  FraudPolicyCategory category = 4 [deprecated = true];

  // which entity type's risk or fraud is being assessed by this policy
  string primary_entity_type = 5;

  // what is the time range we should use on the data queries in this policy when evaluating.
  TimeWindow time_window = 6;

  // policy to run on the results of this policy.
  FraudWatcherPolicy watcher_policy = 7;

  // capture the data queries that indicate biz impact. By default, these will use output of policy.
  repeated FraudBizImpactRule biz_impact_rules = 8;

  // set to true if we should not evaluate this policy.
  bool disabled = 9;

  // apply these labels on all fraud detection events emitted by this fraud policy.
  repeated string labels = 10;

  // set the fraud policy stage, it will determine the visibility of the policy's detection output.
  FraudPolicyStage fraud_policy_stage = 11;

  // a static description of the intent of the policy.
  string description = 12;

  // describe the risk associated with this policy detections
  FraudRiskSpec risk_spec = 13;

  // specify the category to which this risk must be associated (usually determined by the endpoints used for detection)
  // threat type
  string fraud_risk_category = 14;

  FraudPolicyScope scope = 15;

  Schedule schedule = 16;

  // track updates, use for optimistic locking.
  int64 version = 17;

  // categorizes the product group (bot, waf, api protection, etc)
  PolicyGroup policy_group = 18;

  // certain policy types are templatized and dedicated ux is provided, everything else goes into custom.
  PolicyType policy_type = 19;

  // if this policy is generated from a template / default rule, store the template id
  optional string template_id = 20;

  repeated Target target = 21;

  // This field holds references to the definitions, entities, and derivations
  // that are used by this policy.
  repeated BackreferencesInfo backreferences_info = 22;

  IncidentConfig incident_config = 100;
  TriageConfig triage_config = 101;
  // store information about the last execution status of the policy.
  google.protobuf.Value execution_status = 102;
  google.protobuf.Value additional_fields = 103;
  // store context information about substitution variables (used in
  // conjunction with template id)
  repeated ai.traceable.fraud.query.model.v1.TypedParam template_overrides = 104;
  ThreatSummaryConfig threat_summary_config = 105;
  ThreatSummaryConfig detection_summary_config = 106;
}

message FraudWatcherPolicy {
  // what is the policy to be evaluated
  FraudPolicy watcher_policy = 1;

  // how long should we watch the entities
  TimeObj ttl = 2;
}

message FraudDataQuery {
  // data query fetches one of these -
  //  - [(entityId)] list of entity ids
  //  - [(entityId, timestamp, metric_value)] time series of entityId and metric_value
  // a fraud rule will combine this with threshold to fetch only entityIds that are "rule hits"
  ai.traceable.fraud.query.model.v1.DataQuery data_query = 1;
  // what should we summarize the results of this query as?
  string message_format = 2;
  // data query should return these parameters.
  map<string, ai.traceable.fraud.datamodel.config.service.v1.FieldType> message_params = 3;
}

message FraudBizImpactRule {
  // default filter for this query will be the accounts identified by the policy.
  FraudDataQuery fraud_data_query = 2;
}

// rule uses entity predicates to select entities.
message EntityGraphBasedFraudRule {
  // in this case, any entity that matches this query is a "rule hit"
  ai.traceable.fraud.query.model.v1.EntityGraphDataQuery entity_graph_data_query = 1;
  ThresholdDefinition threshold_definition = 4;

  // what should we summarize the results of this query as?
  string message_format = 2;
  // data query should return these parameters.
  map<string, ai.traceable.fraud.datamodel.config.service.v1.FieldType> message_params = 3;
}

// rule uses entity aggregations (# of entities, # of rels, etc) against a threshold
message EntityMetricBasedFraudRule {
  // must return [(entityId, timestamp, entity_metric_value)]
  ai.traceable.fraud.query.model.v1.EntityMetricDataQuery entity_metric_data_query = 1;
  ThresholdDefinition threshold_definition = 2;

  // what should we summarize the results of this query as?
  string message_format = 3;
  // data query should return these parameters.
  map<string, ai.traceable.fraud.datamodel.config.service.v1.FieldType> message_params = 4;
}

// rule uses metric (Event aggregations) against a threshold
message MetricBasedFraudRule {
  ai.traceable.fraud.query.model.v1.MetricDataQuery metric_data_query = 1;
  ThresholdDefinition threshold_definition = 2;

  // what should we summarize the results of this query as?
  string message_format = 3;
  // data query should return these parameters.
  map<string, ai.traceable.fraud.datamodel.config.service.v1.FieldType> message_params = 4;
}

message FraudRule {
  string fraud_rule_id = 1;
  oneof fraud_rule_type {
    EntityGraphBasedFraudRule entity_graph_fraud_rule = 2;
    EntityMetricBasedFraudRule entity_metric_fraud_rule = 3;
    MetricBasedFraudRule metric_fraud_rule = 4;
    // currently, fraud detection event derivation config.
    // use a typed derivation config (edge decision rule)
    string inline_detection_config = 5 [deprecated = true];
    // apply transformation on the input or output. for ex: leventhstein distance on an array_agg of usernames
    string transformation_config = 6 [deprecated = true];
    TransformationConfigBasedFraudRule transformation_config_fraud_rule = 7;
  }
}

message TransformationConfigBasedFraudRule {
  string transformation_config = 1;
  ThresholdDefinition threshold_definition = 2;
  // what should we summarize the results of this query as?
  string message_format = 3;
  // data query should return these parameters.
  map<string, ai.traceable.fraud.datamodel.config.service.v1.FieldType> message_params = 4;
}

message ThresholdDefinition {
  string threshold_name = 4;
  enum ThresholdOperator {
    THRESHOLD_OPERATOR_UNSPECIFIED = 0;
    THRESHOLD_OPERATOR_ABOVE = 1;
    THRESHOLD_OPERATOR_BELOW = 2;
    THRESHOLD_OPERATOR_ABOVE_OR_BELOW = 3;
  }
  oneof threshold_type {
    AutoThreshold auto_threshold = 1;
    ManualThreshold manual_threshold = 2;
  }
  ThresholdOperator threshold_operator = 3;
}

message AutoThreshold {
  // nothing to specify? maybe amount of data, etc. use self-determined model.
}

message QueryBasedThreshold {
  oneof query_source {
    bool copy_query_from_rule = 1;
    ai.traceable.fraud.query.model.v1.DataQuery threshold_query = 2;
  }
  ThresholdOperation threshold_operation = 3;
  BaselineConfig baseline_config = 4;
}

message ManualThreshold {
  oneof manual_threshold_provider {
    double static_value = 1;
    QueryBasedThreshold query_based_threshold = 2;
  }
}

message SimpleAggregationBaseline {
  enum SimpleAggregationFunc {
    SIMPLE_AGGREGATION_FUNC_UNSPECIFIED = 0;

    // sum(n points)
    SIMPLE_AGGREGATION_FUNC_SUM = 1;

    // avg(n points)=sum(n points) / n
    SIMPLE_AGGREGATION_FUNC_AVG = 2;

    // n
    SIMPLE_AGGREGATION_FUNC_COUNT = 3;

    // min(n points)
    SIMPLE_AGGREGATION_FUNC_MIN = 4;

    // max(n points)
    SIMPLE_AGGREGATION_FUNC_MAX = 5;

    // last value of n points
    SIMPLE_AGGREGATION_FUNC_LATEST = 6;
  }
  oneof agg {
    SimpleAggregationFunc func = 1;
    QuantileFunc quantile_func = 2;
  }
}

message SMABaseline {
  int32 window_size = 1;
}

message EWMABaseline {
  double alpha = 1;
}

message LinearRegressionBaseline {
  enum Regressor {
    REGRESSOR_UNSPECIFIED = 0;
    REGRESSOR_LINEAR = 1;
    REGRESSOR_THEIL_SEN = 2;
    REGRESSOR_HUBER = 3;
  }
  Regressor regressor = 1;
}

message BaselineDataConfig {
  // how many historical data points are to be considered to build a baseline
  int32 num_periods = 1;

  // what seasonality to consider?
  Seasonality seasonality = 2;

  enum Seasonality {
    // No seasonality. Use last 'n' points
    SEASONALITY_UNSPECIFIED = 0;

    // Valid ONLY if periodicity is <= 1 Hour. Use last 'n' points from 'n' hours corresponding to the eval period
    SEASONALITY_HOURLY = 1;

    // valid ONLY if periodicity is <= 1 Day. Use last 'n' points from 'n' days corresponding to the eval period
    SEASONALITY_DAILY = 2;

    // valid ONLY if periodicity is <= 1 Week. Use last 'n' points from 'n' weeks corresponding to the eval period
    SEASONALITY_WEEKLY = 3;
  }
}

message QuantileFunc {
  double quantile = 1;
}

message BaselineSpec {
  oneof algo {
    SimpleAggregationBaseline simple_aggregation_baseline = 1;
    LinearRegressionBaseline linear_regression_baseline = 2;
    SMABaseline sma_baseline = 3;
    EWMABaseline ewma_baseline = 4;
  }
}

message BaselineConfig {
  BaselineSpec baseline_spec = 1;
  BaselineDataConfig baseline_data_config = 2;
}

message ThresholdDelta {
  // (lhs - rhs) is within delta
  // allowed deviation = delta
  double delta = 1;
}

message ThresholdPercent {
  // (lhs - rhs) is within the certain %
  // allowed deviation = percent %
  double percent = 1;
}

message ThresholdStdDev {
  // lhs is within std_devs of rhs
  // allowed deviation = num_std_devs
  double num_std_devs = 1;
}

message ThresholdAbsolute {
  // no deviation allowed
}

message ThresholdOperation {
  oneof threshold_op_type {
    ThresholdDelta threshold_delta = 1;
    ThresholdPercent threshold_percent = 2;
    ThresholdStdDev threshold_std_dev = 3;
    ThresholdAbsolute threshold_abs = 4;
  }
}

message Target {
  oneof target_type {
    ApiEndpointTarget api_endpoint = 1;
  }

  message ApiEndpointTarget {
    string api_id = 1;
  }
}

message BackreferencesInfo {
  oneof reference_type {
    // Derivation config reference
    DerivationConfigReference derivation_config = 2;
  }

  message DerivationConfigReference {
    string derivation_config_id = 1;
  }
}
