syntax = "proto3";

package ai.traceable.fraud.policy.config.service.v1;

import "ai/traceable/fraud/policy/config/service/v1/api_access_config.proto";
import "ai/traceable/fraud/policy/config/service/v1/fraud_policy.proto";
import "google/protobuf/field_mask.proto";

option java_multiple_files = true;

service FraudPolicyConfigService {
  rpc CreateFraudPolicy(CreateFraudPolicyRequest) returns (CreateFraudPolicyResponse) {}
  rpc UpdateFraudPolicy(UpdateFraudPolicyRequest) returns (UpdateFraudPolicyResponse) {}
  rpc UpsertFraudPolicy(UpsertFraudPolicyRequest) returns (UpsertFraudPolicyResponse) {}
  rpc GetFraudPolicyList(GetFraudPolicyListRequest) returns (GetFraudPolicyListResponse) {}
  rpc GetFraudPolicy(GetFraudPolicyRequest) returns (GetFraudPolicyResponse) {}
  rpc GetApiAccessAnomalyConfigs(GetApiAccessAnomalyConfigsRequest) returns (GetApiAccessAnomalyConfigsResponse) {}
  rpc GetApiAccessAnomalyConfig(GetApiAccessAnomalyConfigRequest) returns (GetApiAccessAnomalyConfigResponse) {}
  rpc CreateApiAccessAnomalyConfig(CreateApiAccessAnomalyConfigRequest) returns (CreateApiAccessAnomalyConfigResponse) {}
  rpc UpdateApiAccessAnomalyConfig(UpdateApiAccessAnomalyConfigRequest) returns (UpdateApiAccessAnomalyConfigResponse) {}
  rpc DeleteApiAccessAnomalyConfig(DeleteApiAccessAnomalyConfigRequest) returns (DeleteApiAccessAnomalyConfigResponse) {}
}

message CreateFraudPolicyRequest {
  FraudPolicy fraud_policy = 1;
}

message UpsertFraudPolicyResponse {
  FraudPolicy fraud_policy = 1;
}

message UpsertFraudPolicyRequest {
  FraudPolicy fraud_policy = 1;
}

message CreateFraudPolicyResponse {
  FraudPolicy fraud_policy = 1;
}

message UpdateFraudPolicyRequest {
  string fraud_policy_id = 1;
  FraudPolicy fraud_policy = 2;
  int64 current_version = 3;
  google.protobuf.FieldMask update_mask = 4;
}

message UpdateFraudPolicyResponse {
  FraudPolicy fraud_policy = 2;
}

message GetFraudPolicyListRequest {
  repeated string fraud_policy_id = 1;
  bool include_disabled = 2;
}

message GetFraudPolicyListResponse {
  repeated FraudPolicy fraud_policy_list = 1;
}

message GetFraudPolicyRequest {
  string fraud_policy_id = 1;
  bool include_disabled = 2;
}

message GetFraudPolicyResponse {
  FraudPolicy fraud_policy = 1;
}

message GetApiAccessAnomalyConfigRequest {
  string id = 1;
}

message GetApiAccessAnomalyConfigResponse {
  ai.traceable.fraud.policy.config.service.v1.ApiAccessAnomalyConfig config = 1;
}

message GetApiAccessAnomalyConfigsRequest {}

message GetApiAccessAnomalyConfigsResponse {
  repeated ai.traceable.fraud.policy.config.service.v1.ApiAccessAnomalyConfig configs = 1;
}

message CreateApiAccessAnomalyConfigRequest {
  repeated ai.traceable.fraud.policy.config.service.v1.GroupedConfig grouped_configs = 1;
}

message CreateApiAccessAnomalyConfigResponse {
  ai.traceable.fraud.policy.config.service.v1.ApiAccessAnomalyConfig config = 1;
}

message UpdateApiAccessAnomalyConfigRequest {
  ai.traceable.fraud.policy.config.service.v1.ApiAccessAnomalyConfig config = 1;
  google.protobuf.FieldMask update_mask = 2;
}

message UpdateApiAccessAnomalyConfigResponse {
  ai.traceable.fraud.policy.config.service.v1.ApiAccessAnomalyConfig config = 1;
}

message DeleteApiAccessAnomalyConfigRequest {
  string id = 1;
}

message DeleteApiAccessAnomalyConfigResponse {}
