syntax = "proto3";

package ai.traceable.fraud.policy.config.service.v1;

import "ai/traceable/fraud/query/model/v1/fraud_data_query.proto";

option java_multiple_files = true;

message Template {
  // generic template definition
  string template_id = 1; // can map to template id for any kind of template
  string template_string = 2; // json string for the template
  TemplateType template_type = 3; // template type
  repeated ai.traceable.fraud.query.model.v1.TypedParam default_template_variables = 4; // default template variables
  // this can be made a reference to other templates but
  // this increases the complexity and scope of changes,
  // strict ordering needs to be imposed in the onboarding service to ensure
  // derivation configs are upserted before fraud policies
  // also the variables must flow from top down to the tree
  repeated string dependency_templates = 5; // reference to other templates
}

enum TemplateType {
  TEMPLATE_TYPE_UNSPECIFIED = 0;
  TEMPLATE_TYPE_FRAUD_POLICY = 1;
  TEMPLATE_TYPE_DERIVATION_CONFIG = 2;
}

//  Example:
//  Template (Fraud Policy): {
//    template_id: "fraud-policy-1"
//    template_string: "{ \"name\": \"fraud-policy-1\" }"
//    template_type: TEMPLATE_TYPE_FRAUD_POLICY
//    default_template_variables: { name: "name", primitive_val: "fraud-policy-1", type: FIELD_TYPE_STR }
//    dependency_templates: ["{
//      template_id: "derivation-config-1"
//      template_string: "{ \"name\": \"fraud-policy-1\" }"
//      template_type: TEMPLATE_TYPE_DERIVATION_CONFIG
//      default_template_variables: { name: "name", primitive_val: "derivation-config-1" , type: FIELD_TYPE_STR }
//      dependency_templates: []
//    }"]
//  }
